<div id="container">
    <h2><?=$this->escape($this->title);?></h2>
    <div id="mid">
        <form name="frmestadocivil" id="frmestadocivil" action="<?= $this->baseUrl."/".$this->modulo ?>/estadocivil/<?= $this->action;?>" method="post">
            <fieldset>
                <div class="fieldLinha2">
                    <?=$this->label('idEstadoCivil',$this->descricaoCampos['idEstadoCivil']);?><br />					                    
					<?=$this->formText('idEstadoCivil', $this->idEstadoCivil, array('class'=>'medTxtArea', 'maxlength'=>''));?>
                </div>
                <div class="fieldLinha2">
                    <?=$this->label('nameEstadoCivil',$this->descricaoCampos['nameEstadoCivil']);?><br />					                    
					<?=$this->formText('nameEstadoCivil', $this->nameEstadoCivil, array('class'=>'medTxtArea', 'maxlength'=>''));?>
                </div>
            </fieldset>
            <div class="fieldBtn">
                <?= $this->acao($this->botao_submit); ?>
            </div>
        </form>
    </div>
</div>