<?php echo $this->render("header.phtml"); ?>
	<?php echo $this->Aba(
		array(
				array(
					'title'         => 'Pessoal',
					'action'        => 'edit',
					'controller'    => 'register',
					'module'        => 'redesocial',
					'params'        => array(
						'chave' => 'valor' 
						),
					),
				array(
					'title'         => 'Físico',
					'action'        => 'fisico',
					'controller'    => 'profile',
					'module'        => 'redesocial',
					'params'        => array(
						'chave' => 'valor' 
						),
					),
				array(
					'title'         => 'Interesses',
					'action'        => 'interesse',
					'controller'    => 'profile',
					'module'        => 'redesocial',
					'params'        => array(
						'chave' => 'valor' 
						),
					),
				array(
					'title'         => 'Fotos',
					'action'        => 'add',
					'controller'    => 'foto',
					'module'        => 'redesocial',
					'params'        => array(
						'chave' => 'valor' 
						),
					)
				)
			); 
	?>
<?php echo $this->render('footer.phtml'); ?>
