<?php echo $this->render('header.phtml'); ?>
	<div class="left">
		<div class="signin-box">
			<h2>Login <strong></strong></h2>
			<form method="post" action="#" id="loginform">
				<label>
					<strong class="email-label">Nome de usuário</strong>
					<input type="text" value="" id="Email" name="Email">
				</label>
				<label>
					<strong class="passwd-label">Senha</strong>
					<input type="password" id="Passwd" name="Passwd">
				</label>
				<input type="submit" value="Login" id="signIn" name="signIn" class="button button-submit">
				<label class="remember">
					<input type="checkbox" value="yes" id="PersistentCookie" name="PersistentCookie">
					<strong class="remember-label">
						Continuar conectado
					</strong>
				</label>
			</form>
			<ul>
				<li>
					<a target="_top" href="#" id="link-forgot-passwd">
						Não consegue acessar sua conta?
					</a>
				</li>
			</ul>
		</div>
	</div>
	<div class="right">
	</div>
<?php echo $this->render('footer.phtml'); ?>
