<div id="container">
    <h2><?=$this->escape($this->title);?></h2>
    <div id="mid">
        <form name="frmmenurole" id="frmmenurole" action="<?= $this->baseUrl."/".$this->modulo ?>/menurole/<?= $this->action;?>" method="post">
            <fieldset>
                <div class="fieldLinha2">
                    <?=$this->label('idRole',$this->descricaoCampos['idRole']);?><br />					                    
					<?=$this->formText('idRole', $this->idRole, array('class'=>'medTxtArea', 'maxlength'=>''));?>
                </div>
                <div class="fieldLinha2">
                    <?=$this->label('idMenu',$this->descricaoCampos['idMenu']);?><br />					                    
					<?=$this->formText('idMenu', $this->idMenu, array('class'=>'medTxtArea', 'maxlength'=>''));?>
                </div>
                <div class="fieldLinha2">
                    <?=$this->label('menuRoleId',$this->descricaoCampos['menuRoleId']);?><br />					                    
					<?=$this->formText('menuRoleId', $this->menuRoleId, array('class'=>'medTxtArea', 'maxlength'=>''));?>
                </div>
            </fieldset>
            <div class="fieldBtn">
                <?= $this->acao($this->botao_submit); ?>
            </div>
        </form>
    </div>
</div>