<form name="frminteresse" id="frminteresse" action="<?= $this->baseUrl."/".$this->modulo ?>/interesse/<?= $this->action;?>" method="post">
    <div class="fieldLinha">
		<?=$this->FormHidden('idInteresse', $this->idInteresse);?>
		<?=$this->FormHidden('Descricao', $this->Descricao);?>
		<?=$this->FormHidden('idPerfil', $this->idPerfil);?>
	</div>
    <div class="fieldLinha">
        <?=$this->label('idTipoInteresse',$this->descricaoCampos['idTipoInteresse']);?><br />					                    
		<?=$this->FormMultiCheckbox('idTipoInteresse', $this->idTipoInteresse, array(),$this->arrayTipoInteresse);?>
    </div>
    <div class="fieldBtn">
		<?= $this->acao($this->botao_submit); ?>
    </div>
</form>