<div id="container">
    <h2><?=$this->escape($this->title);?></h2>
    <div id="mid">
        <form name="frmassociado" id="frmassociado" action="<?= $this->baseUrl."/".$this->modulo ?>/associado/<?= $this->action;?>" method="post">
            <fieldset>
                <div class="fieldLinha2">
                    <?=$this->label('idAssociado',$this->descricaoCampos['idAssociado']);?><br />					                    
					<?=$this->formText('idAssociado', $this->idAssociado, array('class'=>'medTxtArea', 'maxlength'=>''));?>
                </div>
                <div class="fieldLinha2">
                    <?=$this->label('idMembro',$this->descricaoCampos['idMembro']);?><br />					                    
					<?=$this->formText('idMembro', $this->idMembro, array('class'=>'medTxtArea', 'maxlength'=>''));?>
                </div>
                <div class="fieldLinha2">
                    <?=$this->label('idAssociacao',$this->descricaoCampos['idAssociacao']);?><br />					                    
					<?=$this->formText('idAssociacao', $this->idAssociacao, array('class'=>'medTxtArea', 'maxlength'=>''));?>
                </div>
            </fieldset>
            <div class="fieldBtn">
                <?= $this->acao($this->botao_submit); ?>
            </div>
        </form>
    </div>
</div>