<div id="container">
    <h2><?=$this->escape($this->title);?></h2>
    <div id="mid">
        <form name="frmolho" id="frmolho" action="<?= $this->baseUrl."/".$this->modulo ?>/olho/<?= $this->action;?>" method="post">
            <fieldset>
                <div class="fieldLinha2">
                    <?=$this->label('idOlho',$this->descricaoCampos['idOlho']);?><br />					                    
					<?=$this->formText('idOlho', $this->idOlho, array('class'=>'medTxtArea', 'maxlength'=>''));?>
                </div>
                <div class="fieldLinha2">
                    <?=$this->label('nameOlho',$this->descricaoCampos['nameOlho']);?><br />					                    
					<?=$this->formText('nameOlho', $this->nameOlho, array('class'=>'medTxtArea', 'maxlength'=>''));?>
                </div>
            </fieldset>
            <div class="fieldBtn">
                <?= $this->acao($this->botao_submit); ?>
            </div>
        </form>
    </div>
</div>