				</div>
			</div>
			<div class="footer">
                <div class="clean-footer">
					<ul>
						<li>&copy; 2011 </li>
						<li><a target="_blank" href="#">Política de Privacidade</a></li>
						<li><a target="_blank" href="#">Regulamentos do programa</a></li>
						<li><a target="_blank" href="#">Termos de Uso</a></li>
					</ul>
                </div>
            </div>
        </div>
    </body>
	<script language="javascript" type="text/javascript">
		$.ajax({
			ajaxStart: function(){
				alert();
				$('#preload').show();
			},
			complete: function(){
				$('#preload').hide();
			}
			});
	</script>
</html>
