///////////////////////////////////////////////////////////
//  Zend_Db_Adapter_Pdo_Ibm_Ids.cs
//  Implementation of the Class Zend_Db_Adapter_Pdo_Ibm_Ids
//  Generated by Enterprise Architect
//  Created on:      08-jun-2011 22:13:09
//  Original author: alexis
///////////////////////////////////////////////////////////




namespace Zend.Db.Adapter.Pdo.Ibm {
	/// <summary>
	/// @category   Zend
	///            @package    Zend_Db
	///            @subpackage Adapter
	///            @copyright  Copyright (c) 2005-2010 Zend Technologies USA Inc. (http:
	/// //www.zend.com)
	///            @license    http://framework.zend.com/license/new-bsd     New BSD
	/// License
	/// </summary>
	public class Zend_Db_Adapter_Pdo_Ibm_Ids {

		/// <summary>
		/// @var Zend_Db_Adapter_Abstract
		/// </summary>
		protected var _adapter = null;

		public Zend_Db_Adapter_Pdo_Ibm_Ids(){

		}

		~Zend_Db_Adapter_Pdo_Ibm_Ids(){

		}

		public virtual void Dispose(){

		}

		/// <summary>
		/// Construct the data server class.  It will be used to generate non-generic SQL
		/// for a particular data server
		/// </summary>
		/// <param>Zend_Db_Adapter_Abstract $adapter</param>
		/// <param name="adapter"></param>
		public var __construct(var adapter){

			return null;
		}

		/// <summary>
		/// Map number representation of a data type to a string
		/// </summary>
		/// <param>int $typeNo</param>
		/// <param>string</param>
		/// <param name="typeNo"></param>
		protected var _getDataType(var typeNo){

			return null;
		}

		/// <summary>
		/// Helper method to retrieve primary key column and column location
		/// </summary>
		/// <param>int $tabid</param>
		/// <param>array</param>
		/// <param name="tabid"></param>
		protected var _getPrimaryInfo(var tabid){

			return null;
		}

		/// <summary>
		/// IDS catalog lookup for describe table
		/// </summary>
		/// <param>string $tableName</param>
		/// <param>string $schemaName OPTIONAL</param>
		/// <param>array</param>
		/// <param name="tableName"></param>
		/// <param name="schemaName"></param>
		public var describeTable(var tableName, var schemaName){

			return null;
		}

		/// <summary>
		/// IDS-specific last sequence id
		/// </summary>
		/// <param>string $sequenceName</param>
		/// <param>integer</param>
		/// <param name="sequenceName"></param>
		public var lastSequenceId(var sequenceName){

			return null;
		}

		/// <summary>
		/// Adds an IDS-specific LIMIT clause to the SELECT statement.
		/// </summary>
		/// <param>string $sql</param>
		/// <param>integer $count</param>
		/// <param>integer $offset OPTIONAL</param>
		/// <param>string</param>
		/// <param name="sql"></param>
		/// <param name="count"></param>
		/// <param name="offset"></param>
		public var limit(var sql, var count, var offset){

			return null;
		}

		/// <summary>
		/// Returns a list of the tables in the database.
		/// </summary>
		/// array
		public var listTables(){

			return null;
		}

		/// <summary>
		/// IDS-specific sequence id value
		/// </summary>
		/// <param>string $sequenceName</param>
		/// <param>integer</param>
		/// <param name="sequenceName"></param>
		public var nextSequenceId(var sequenceName){

			return null;
		}

	}//end Zend_Db_Adapter_Pdo_Ibm_Ids

}//end namespace Ibm