<div id="container">
    <h2><?=$this->escape($this->title);?></h2>
    <div id="mid">
        <form name="frmtipoassociacao" id="frmtipoassociacao" action="<?= $this->baseUrl."/".$this->modulo ?>/tipoassociacao/<?= $this->action;?>" method="post">
            <fieldset>
                <div class="fieldLinha2">
                    <?=$this->label('idTipoAssociacao',$this->descricaoCampos['idTipoAssociacao']);?><br />					                    
					<?=$this->formText('idTipoAssociacao', $this->idTipoAssociacao, array('class'=>'medTxtArea', 'maxlength'=>''));?>
                </div>
                <div class="fieldLinha2">
                    <?=$this->label('nomeTipoAssociacao',$this->descricaoCampos['nomeTipoAssociacao']);?><br />					                    
					<?=$this->formText('nomeTipoAssociacao', $this->nomeTipoAssociacao, array('class'=>'medTxtArea', 'maxlength'=>''));?>
                </div>
            </fieldset>
            <div class="fieldBtn">
                <?= $this->acao($this->botao_submit); ?>
            </div>
        </form>
    </div>
</div>