///////////////////////////////////////////////////////////
//  Zend_Db_Table.cs
//  Implementation of the Class Zend_Db_Table
//  Generated by Enterprise Architect
//  Created on:      08-jun-2011 22:13:54
//  Original author: alexis
///////////////////////////////////////////////////////////




using Zend.Db.Table;
namespace Zend.Db {
	/// <summary>
	/// Class for SQL table interface.
	///      @category   Zend
	///      @package    Zend_Db
	///      @subpackage Table
	///      @copyright  Copyright (c) 2005-2010 Zend Technologies USA Inc. (http://www.
	/// zend.com)
	///      @license    http://framework.zend.com/license/new-bsd     New BSD License
	/// </summary>
	public class Zend_Db_Table : Zend_Db_Table_Abstract {

		public Zend_Db_Table(){

		}

		~Zend_Db_Table(){

		}

		public override void Dispose(){

		}

		/// <summary>
		/// __construct() - For concrete implementation of Zend_Db_Table
		/// </summary>
		/// <param>string|array $config string can reference a Zend_Registry key for a db
		/// adapter OR it can reference the name of a table</param>
		/// <param>array|Zend_Db_Table_Definition $definition</param>
		/// <param name="config"></param>
		/// <param name="definition"></param>
		public var __construct(var config, var definition){

			return null;
		}

	}//end Zend_Db_Table

}//end namespace Db