<div id="container">
    <h2><?=$this->escape($this->title);?></h2>
    <div id="mid">
        <form name="frmestado" id="frmestado" action="<?= $this->baseUrl."/".$this->modulo ?>/estado/<?= $this->action;?>" method="post">
            <fieldset>
                <div class="fieldLinha2">
                    <?=$this->label('idEstado',$this->descricaoCampos['idEstado']);?><br />					                    
					<?=$this->formText('idEstado', $this->idEstado, array('class'=>'medTxtArea', 'maxlength'=>''));?>
                </div>
                <div class="fieldLinha2">
                    <?=$this->label('nameEstado',$this->descricaoCampos['nameEstado']);?><br />					                    
					<?=$this->formText('nameEstado', $this->nameEstado, array('class'=>'medTxtArea', 'maxlength'=>''));?>
                </div>
                <div class="fieldLinha2">
                    <?=$this->label('SiglaEstado',$this->descricaoCampos['SiglaEstado']);?><br />					                    
					<?=$this->formText('SiglaEstado', $this->SiglaEstado, array('class'=>'medTxtArea', 'maxlength'=>''));?>
                </div>
            </fieldset>
            <div class="fieldBtn">
                <?= $this->acao($this->botao_submit); ?>
            </div>
        </form>
    </div>
</div>