<div id="container">
    <h2><?=$this->escape($this->title);?></h2>
    <div id="mid">
        <form name="frmpermissaorole" id="frmpermissaorole" action="<?= $this->baseUrl."/".$this->modulo ?>/permissaorole/<?= $this->action;?>" method="post">
            <fieldset>
                <div class="fieldLinha2">
                    <?=$this->label('idRole',$this->descricaoCampos['idRole']);?><br />					                    
					<?=$this->formText('idRole', $this->idRole, array('class'=>'medTxtArea', 'maxlength'=>''));?>
                </div>
                <div class="fieldLinha2">
                    <?=$this->label('idPermissao',$this->descricaoCampos['idPermissao']);?><br />					                    
					<?=$this->formText('idPermissao', $this->idPermissao, array('class'=>'medTxtArea', 'maxlength'=>''));?>
                </div>
            </fieldset>
            <div class="fieldBtn">
                <?= $this->acao($this->botao_submit); ?>
            </div>
        </form>
    </div>
</div>