unit uFrmBaseClientTabela;

interface

uses
  Windows, Messages, SysUtils, Classes, Graphics,
  Controls, Forms, Dialogs, StdCtrls
type
  TfrmBaseClientTabela=class(TForm)
    DBNavigator: TDBNavigator;
    pAction: TPanel;
    sbtnIncluir: TSpeedButton;
    sbtnExcluir: TSpeedButton;
    sbtnAlterar: TSpeedButton;
    pOkCancel: TPanel;
    sbtnConfirma: TSpeedButton;
    sbtnCancela: TSpeedButton;
    tbPrincipal: TTable;
    DSPrincipal: TDataSource;
    DBGrid: TDBGrid;
    sbtnLegenda: TSpeedButton;
    procedure sbtnLegendaClick(Sender : TObject);
    procedure FormClose(Sender : TObject);
    procedure sbtnIncluirClick(Sender : TObject);
    procedure sbtnExcluirClick(Sender : TObject);
    procedure sbtnCancelaClick(Sender : TObject);
    procedure sbtnConfirmaClick(Sender : TObject);
    procedure sbtnAlterarClick(Sender : TObject);
    procedure _PROC_005C9154(Sender : TObject);
    procedure _PROC_005C9556(Sender : TObject);
  private
    { Private declarations }
  public
    { Public declarations }
  end ;

var
  frmBaseClientTabela: TfrmBaseClientTabela;

{This file is generated by DeDe Ver 3.50.04 Copyright (c) 1999-2002 DaFixer}

implementation

{$R *.DFM}

procedure TfrmBaseClientTabela.sbtnLegendaClick(Sender : TObject);
begin
(*
005C93F0   55                     push    ebp
005C93F1   8BEC                   mov     ebp, esp
005C93F3   6A00                   push    $00
005C93F5   53                     push    ebx
005C93F6   56                     push    esi
005C93F7   8BD8                   mov     ebx, eax
005C93F9   8B35F0F76300           mov     esi, [$0063F7F0]
005C93FF   33C0                   xor     eax, eax
005C9401   55                     push    ebp

* Possible String Reference to: 'éú»ãÿëð^[Y]Ã'
|
005C9402   6895945C00             push    $005C9495

***** TRY
|
005C9407   64FF30                 push    dword ptr fs:[eax]
005C940A   648920                 mov     fs:[eax], esp
005C940D   833E00                 cmp     dword ptr [esi], +$00
005C9410   7432                   jz      005C9444
005C9412   8D45FC                 lea     eax, [ebp-$04]
005C9415   50                     push    eax
005C9416   8B06                   mov     eax, [esi]
005C9418   8B4008                 mov     eax, [eax+$08]
005C941B   B90A000000             mov     ecx, $0000000A
005C9420   BA01000000             mov     edx, $00000001

|
005C9425   E89EC9E3FF             call    00405DC8
005C942A   8B45FC                 mov     eax, [ebp-$04]

* Possible String Reference to: 'frmLegenda'
|
005C942D   BAAC945C00             mov     edx, $005C94AC

|
005C9432   E87DC8E3FF             call    00405CB4
005C9437   7507                   jnz     005C9440
005C9439   8B06                   mov     eax, [esi]

* Reference to : TApplication._PROC_0047A1C8()
|
005C943B   E8880DEBFF             call    0047A1C8
005C9440   33C0                   xor     eax, eax
005C9442   8906                   mov     [esi], eax
005C9444   8BCB                   mov     ecx, ebx
005C9446   B201                   mov     dl, $01

* Reference to class TfrmLegenda
|
005C9448   A1FC855C00             mov     eax, dword ptr [$005C85FC]

* Reference to : TApplication._PROC_004751E0()
|
005C944D   E88EBDEAFF             call    004751E0
005C9452   8906                   mov     [esi], eax
005C9454   8B06                   mov     eax, [esi]
005C9456   0588030000             add     eax, +$00000388

* Reference to field TfrmBaseClientTabela.OFFS_03B4
|
005C945B   8B93B4030000           mov     edx, [ebx+$03B4]

|
005C9461   E892C4E3FF             call    004058F8
005C9466   8B06                   mov     eax, [esi]
005C9468   058C030000             add     eax, +$0000038C

* Reference to field TfrmBaseClientTabela.OFFS_03B8
|
005C946D   8B93B8030000           mov     edx, [ebx+$03B8]

|
005C9473   E880C4E3FF             call    004058F8
005C9478   8B06                   mov     eax, [esi]

* Reference to : TApplication._PROC_0047A370()
|
005C947A   E8F10EEBFF             call    0047A370
005C947F   33C0                   xor     eax, eax
005C9481   5A                     pop     edx
005C9482   59                     pop     ecx
005C9483   59                     pop     ecx
005C9484   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: '^[Y]Ã'
|
005C9487   689C945C00             push    $005C949C
005C948C   8D45FC                 lea     eax, [ebp-$04]

|
005C948F   E810C4E3FF             call    004058A4
005C9494   C3                     ret


|
005C9495   E9FABBE3FF             jmp     00405094
005C949A   EBF0                   jmp     005C948C

****** END
|
005C949C   5E                     pop     esi
005C949D   5B                     pop     ebx
005C949E   59                     pop     ecx
005C949F   5D                     pop     ebp
005C94A0   C3                     ret

*)
end;

procedure TfrmBaseClientTabela.FormClose(Sender : TObject);
begin
(*
005C9130   53                     push    ebx
005C9131   56                     push    esi
005C9132   57                     push    edi
005C9133   8BF9                   mov     edi, ecx
005C9135   8BF2                   mov     esi, edx
005C9137   8BD8                   mov     ebx, eax

* Reference to control TfrmBaseClientTabela.tbPrincipal : TTable
|
005C9139   8B83A0030000           mov     eax, [ebx+$03A0]

|
005C913F   E8CC53EDFF             call    0049E510
005C9144   8BCF                   mov     ecx, edi
005C9146   8BD6                   mov     edx, esi
005C9148   8BC3                   mov     eax, ebx

* Reference to : TfrmBaseClient.FormClose()
|
005C914A   E8F91BFAFF             call    0056AD48
005C914F   5F                     pop     edi
005C9150   5E                     pop     esi
005C9151   5B                     pop     ebx
005C9152   C3                     ret

*)
end;

procedure TfrmBaseClientTabela.sbtnIncluirClick(Sender : TObject);
begin
(*
005C93C4   53                     push    ebx
005C93C5   8BD8                   mov     ebx, eax

* Reference to control TfrmBaseClientTabela.tbPrincipal : TTable
|
005C93C7   8B83A0030000           mov     eax, [ebx+$03A0]

* Reference to field TTable.OFFS_009D
|
005C93CD   80B89D00000001         cmp     byte ptr [eax+$009D], $01
005C93D4   750C                   jnz     005C93E2
005C93D6   B203                   mov     dl, $03
005C93D8   8BC3                   mov     eax, ebx
005C93DA   8B08                   mov     ecx, [eax]

* Possible reference to virtual method TfrmBaseClientTabela.OFFS_0108
|
005C93DC   FF9108010000           call    dword ptr [ecx+$0108]

* Reference to control TfrmBaseClientTabela.tbPrincipal : TTable
|
005C93E2   8B83A0030000           mov     eax, [ebx+$03A0]

|
005C93E8   E8C37DEDFF             call    004A11B0
005C93ED   5B                     pop     ebx
005C93EE   C3                     ret

*)
end;

procedure TfrmBaseClientTabela.sbtnExcluirClick(Sender : TObject);
begin
(*
005C933C   53                     push    ebx
005C933D   8BD8                   mov     ebx, eax

* Reference to control TfrmBaseClientTabela.tbPrincipal : TTable
|
005C933F   8B83A0030000           mov     eax, [ebx+$03A0]

* Reference to field TTable.OFFS_009D
|
005C9345   80B89D00000001         cmp     byte ptr [eax+$009D], $01
005C934C   7525                   jnz     005C9373
005C934E   6A00                   push    $00
005C9350   0FB70D84935C00         movzx   ecx, word ptr [$005C9384]
005C9357   B203                   mov     dl, $03

* Possible String Reference to: 'Tem certeza que gostaria de excluir
|                                 este registro?'
|
005C9359   B890935C00             mov     eax, $005C9390

|
005C935E   E84578E8FF             call    00450BA8
005C9363   83F806                 cmp     eax, +$06
005C9366   750B                   jnz     005C9373

* Reference to control TfrmBaseClientTabela.tbPrincipal : TTable
|
005C9368   8B83A0030000           mov     eax, [ebx+$03A0]

|
005C936E   E8E180EDFF             call    004A1454
005C9373   B201                   mov     dl, $01
005C9375   8BC3                   mov     eax, ebx
005C9377   8B08                   mov     ecx, [eax]

* Possible reference to virtual method TfrmBaseClientTabela.OFFS_0108
|
005C9379   FF9108010000           call    dword ptr [ecx+$0108]
005C937F   5B                     pop     ebx
005C9380   C3                     ret

*)
end;

procedure TfrmBaseClientTabela.sbtnCancelaClick(Sender : TObject);
begin
(*
005C94B8   53                     push    ebx
005C94B9   56                     push    esi
005C94BA   8BD8                   mov     ebx, eax

* Reference to control TfrmBaseClientTabela.tbPrincipal : TTable
|
005C94BC   8BB3A0030000           mov     esi, [ebx+$03A0]
005C94C2   0FB6869D000000         movzx   eax, byte ptr [esi+$009D]
005C94C9   3C02                   cmp     al, $02
005C94CB   7404                   jz      005C94D1
005C94CD   3C03                   cmp     al, $03
005C94CF   750A                   jnz     005C94DB
005C94D1   8BC6                   mov     eax, esi
005C94D3   8B10                   mov     edx, [eax]

* Possible reference to virtual method TTable.OFFS_022C
|
005C94D5   FF922C020000           call    dword ptr [edx+$022C]
005C94DB   B201                   mov     dl, $01
005C94DD   8BC3                   mov     eax, ebx
005C94DF   8B08                   mov     ecx, [eax]

* Possible reference to virtual method TfrmBaseClientTabela.OFFS_0108
|
005C94E1   FF9108010000           call    dword ptr [ecx+$0108]
005C94E7   5E                     pop     esi
005C94E8   5B                     pop     ebx
005C94E9   C3                     ret

*)
end;

procedure TfrmBaseClientTabela.sbtnConfirmaClick(Sender : TObject);
begin
(*
005C94EC   56                     push    esi
005C94ED   57                     push    edi
005C94EE   8BF0                   mov     esi, eax

* Reference to control TfrmBaseClientTabela.tbPrincipal : TTable
|
005C94F0   8BBEA0030000           mov     edi, [esi+$03A0]
005C94F6   0FB6879D000000         movzx   eax, byte ptr [edi+$009D]
005C94FD   3C02                   cmp     al, $02
005C94FF   7404                   jz      005C9505
005C9501   3C03                   cmp     al, $03
005C9503   750A                   jnz     005C950F
005C9505   8BC7                   mov     eax, edi
005C9507   8B10                   mov     edx, [eax]

* Possible reference to virtual method TTable.OFFS_0270
|
005C9509   FF9270020000           call    dword ptr [edx+$0270]
005C950F   B201                   mov     dl, $01
005C9511   8BC6                   mov     eax, esi
005C9513   8B08                   mov     ecx, [eax]

* Possible reference to virtual method TfrmBaseClientTabela.OFFS_0108
|
005C9515   FF9108010000           call    dword ptr [ecx+$0108]
005C951B   5F                     pop     edi
005C951C   5E                     pop     esi
005C951D   C3                     ret

*)
end;

procedure TfrmBaseClientTabela.sbtnAlterarClick(Sender : TObject);
begin
(*
005C9314   53                     push    ebx
005C9315   8BD8                   mov     ebx, eax

* Reference to control TfrmBaseClientTabela.tbPrincipal : TTable
|
005C9317   8B83A0030000           mov     eax, [ebx+$03A0]

* Reference to field TTable.OFFS_009D
|
005C931D   80B89D00000001         cmp     byte ptr [eax+$009D], $01
005C9324   7505                   jnz     005C932B

|
005C9326   E8F17DEDFF             call    004A111C
005C932B   B202                   mov     dl, $02
005C932D   8BC3                   mov     eax, ebx
005C932F   8B08                   mov     ecx, [eax]

* Possible reference to virtual method TfrmBaseClientTabela.OFFS_0108
|
005C9331   FF9108010000           call    dword ptr [ecx+$0108]
005C9337   5B                     pop     ebx
005C9338   C3                     ret

*)
end;

procedure TfrmBaseClientTabela._PROC_005C9154(Sender : TObject);
begin
(*
005C9154   53                     push    ebx
005C9155   56                     push    esi
005C9156   8BF0                   mov     esi, eax
005C9158   8BC6                   mov     eax, esi
005C915A   8B10                   mov     edx, [eax]

* Possible reference to virtual method TfrmBaseClientTabela.OFFS_010C
|
005C915C   FF920C010000           call    dword ptr [edx+$010C]
005C9162   8BD8                   mov     ebx, eax

* Reference to field TfrmBaseClientTabela.OFFS_0374
|
005C9164   8D8674030000           lea     eax, [esi+$0374]

* Reference to field TfrmBaseClientTabela.OFFS_03B8
|
005C916A   8B8EB8030000           mov     ecx, [esi+$03B8]

* Possible String Reference to: 'Tabela '
|
005C9170   BA9C915C00             mov     edx, $005C919C

|
005C9175   E83ACAE3FF             call    00405BB4
005C917A   B201                   mov     dl, $01
005C917C   8BC6                   mov     eax, esi
005C917E   8B08                   mov     ecx, [eax]

* Possible reference to virtual method TfrmBaseClientTabela.OFFS_0108
|
005C9180   FF9108010000           call    dword ptr [ecx+$0108]
005C9186   8BC6                   mov     eax, esi

|
005C9188   E83B1BFAFF             call    0056ACC8
005C918D   8BC3                   mov     eax, ebx
005C918F   5E                     pop     esi
005C9190   5B                     pop     ebx
005C9191   C3                     ret

*)
end;

procedure TfrmBaseClientTabela._PROC_005C9556(Sender : TObject);
begin
(*
005C9556   47                     inc     edi
005C9557   001C4B                 add     [ebx+ecx*2], bl
005C955A   40                     inc     eax
005C955B   000C8547005848         add     [$48580047+eax*4], cl
005C9562   40                     inc     eax
005C9563   00744840               add     [eax+ecx*2+$40], dh
005C9567   00905547008C           add     [eax+$8C004755], dl
005C956D   844600                 test    [esi+$00], al
005C9570   845B47                 test    [ebx+$47], bl
005C9573   000C31                 add     [ecx+esi], cl
005C9576   42                     inc     edx
005C9577   006C5747               add     [edi+edx*2+$47], ch
005C957B   00B8574700F4           add     [eax+$F4004757], bh
005C9581   58                     pop     eax
005C9582   47                     inc     edi
005C9583   00E8                   add     al, ch
005C9585   F8                     clc
005C9586   45                     inc     ebp
005C9587   0094C542008462         add     [ebp+eax*8+$62840042], dl
005C958E   47                     inc     edi
005C958F   0070C2                 add     [eax-$3E], dh
005C9592   42                     inc     edx
005C9593   0070AB                 add     [eax-$55], dh
005C9596   47                     inc     edi
005C9597   00E0                   add     al, ah
005C9599   51                     push    ecx
005C959A   47                     inc     edi
005C959B   00B07E4600BC           add     [eax+$BC00467E], dh
005C95A1   844600                 test    [esi+$00], al
005C95A4   08844600B0EB45         or      [esi+eax*2+$45EBB000], al
005C95AB   002C79                 add     [ecx+edi*2], ch
005C95AE   46                     inc     esi
005C95AF   00B85E4700B8           add     [eax+$B800475E], bh
005C95B5   7546                   jnz     005C95FD
005C95B7   00F0                   add     al, dh
005C95B9   EA4500F4EA             jmp     $EAF40045
005C95BE   45                     inc     ebp
005C95BF   00AC5F47006C24         add     [edi+ebx*2+$246C0047], ch
005C95C6   46                     inc     esi
005C95C7   003CA8                 add     [eax+ebp*4], bh
005C95CA   47                     inc     edi
005C95CB   00CC                   add     ah, cl
005C95CD   F8                     clc
005C95CE   45                     inc     ebp
005C95CF   002CED450058FA         add     [$FA580045+ebp*8], ch
005C95D6   45                     inc     ebp
005C95D7   00C8                   add     al, cl
005C95D9   61                     popa
005C95DA   47                     inc     edi
005C95DB   008460470094FB         add     [eax+$FB940047], al
005C95E2   45                     inc     ebp
005C95E3   00C4                   add     ah, al
005C95E5   624700                 bound   eax, qword ptr [edi+$00]
005C95E8   F0                     lock
005C95E9   2446                   and     al, $46
005C95EB   000C76                 add     [esi+esi*2], cl
005C95EE   46                     inc     esi
005C95EF   00CC                   add     ah, cl
005C95F1   7646                   jbe     005C9639
005C95F3   00C0                   add     al, al
005C95F5   7146                   jno     005C963D
005C95F7   00B0764600C8           add     [eax+$C8004676], dh
005C95FD   4F                     dec     edi
005C95FE   47                     inc     edi
005C95FF   0008                   add     [eax], cl
005C9601   6A47                   push    $47
005C9603   00A042460034           add     [eax+$34004642], ah
005C9609   7D47                   jnl     005C9652
005C960B   004882                 add     [eax-$7E], cl
005C960E   47                     inc     edi
005C960F   00748047               add     [eax+eax*4+$47], dh
005C9613   0038                   add     [eax], bh
005C9615   43                     inc     ebx
005C9616   46                     inc     esi
005C9617   005C4346               add     [ebx+eax*2+$46], bl
005C961B   00C4                   add     ah, al
005C961D   834700C8               add     dword ptr [edi+$00], -$38
005C9621   844700                 test    [edi+$00], al
005C9624   94                     xchg    eax, esp
005C9625   41                     inc     ecx
005C9626   46                     inc     esi
005C9627   00A08C4600F8           add     [eax+$F800468C], ah
005C962D   7746                   jnbe    005C9675
005C962F   0000                   add     [eax], al

005C9631   8C4700                 mov     word ptr [edi+$00], es
005C9634   148C                   adc     al, $8C
005C9636   46                     inc     esi
005C9637   006874                 add     [eax+$74], ch
005C963A   46                     inc     esi
005C963B   00648D46               add     [ebp+ecx*4+$46], ah
005C963F   0088A34700A8           add     [eax+$A80047A3], cl
005C9645   49                     dec     ecx
005C9646   47                     inc     edi
005C9647   00584C                 add     [eax+$4C], bl
005C964A   47                     inc     edi
005C964B   004093                 add     [eax-$6D], al
005C964E   47                     inc     edi
005C964F   00905647000C           add     [eax+$C004756], dl
005C9655   57                     push    edi
005C9656   47                     inc     edi
005C9657   00D4                   add     ah, dl
005C9659   A7                     cmpsd
005C965A   47                     inc     edi
005C965B   00A45347006CA2         add     [ebx+edx*2+$A26C0047], ah
005C9662   47                     inc     edi
005C9663   009C86470060A4         add     [esi+eax*4+$A4600047], bl
005C966A   47                     inc     edi
005C966B   00C4                   add     ah, al
005C966D   61                     popa
005C966E   47                     inc     edi
005C966F   00C8                   add     al, cl
005C9671   96                     xchg    eax, esi
005C9672   5C                     pop     esp
005C9673   00B8915C00A4           add     [eax+$A4005C91], bh
005C9679   91                     xchg    eax, ecx
005C967A   5C                     pop     esp
005C967B   0012                   add     [edx], dl
005C967D   54                     push    esp
005C967E   66726D                 jb      005C96EE
005C9681   54                     push    esp
005C9682   61                     popa
005C9683   624F63                 bound   ecx, qword ptr [edi+$63]
005C9686   6F                     outsd
005C9687   7272                   jb      005C96FB
005C9689   656E                   outsb
005C968B   636961                 arpl    [ecx+$61], bp
005C968E   7390                   jnb     005C9620
005C9690   94                     xchg    eax, esp
005C9691   96                     xchg    eax, esi
005C9692   5C                     pop     esp
005C9693   0007                   add     [edi], al
005C9695   12546672               adc     dl, byte ptr [esi+$72]
005C9699   6D                     insd
005C969A   54                     push    esp
005C969B   61                     popa
005C969C   624F63                 bound   ecx, qword ptr [edi+$63]
005C969F   6F                     outsd
005C96A0   7272                   jb      005C9714
005C96A2   656E                   outsb
005C96A4   636961                 arpl    [ecx+$61], bp
005C96A7   736C                   jnb     005C9715
005C96A9   95                     xchg    eax, ebp
005C96AA   5C                     pop     esp
005C96AB   005C905C               add     [eax+edx*4+$5C], bl
005C96AF   006F00                 add     [edi+$00], ch
005C96B2   127546                 adc     dh, byte ptr [ebp+$46]
005C96B5   726D                   jb      005C9724
005C96B7   54                     push    esp
005C96B8   61                     popa
005C96B9   624F63                 bound   ecx, qword ptr [edi+$63]
005C96BC   6F                     outsd
005C96BD   7272                   jb      005C9731
005C96BF   656E                   outsb
005C96C1   636961                 arpl    [ecx+$61], bp
005C96C4   7300                   jnb     005C96C6
005C96C6   0090558BEC33           add     [eax+$33EC8B55], dl
005C96CC   C9                     leave
005C96CD   51                     push    ecx
005C96CE   51                     push    ecx
005C96CF   51                     push    ecx
005C96D0   51                     push    ecx
005C96D1   51                     push    ecx
005C96D2   51                     push    ecx
005C96D3   51                     push    ecx
005C96D4   53                     push    ebx
005C96D5   56                     push    esi
005C96D6   57                     push    edi
005C96D7   8BD8                   mov     ebx, eax
005C96D9   33C0                   xor     eax, eax
005C96DB   55                     push    ebp
005C96DC   687D995C00             push    $005C997D

***** TRY
|
005C96E1   64FF30                 push    dword ptr fs:[eax]
005C96E4   648920                 mov     fs:[eax], esp
005C96E7   8D8378030000           lea     eax, [ebx+$0378]

* Possible String Reference to: 'Versão 8.0'
|
005C96ED   BA98995C00             mov     edx, $005C9998

|
005C96F2   E801C2E3FF             call    004058F8
005C96F7   8D83B4030000           lea     eax, [ebx+$03B4]

* Possible String Reference to: 'ocorrencias'
|
005C96FD   BAAC995C00             mov     edx, $005C99AC

|
005C9702   E8F1C1E3FF             call    004058F8
005C9707   8D83B8030000           lea     eax, [ebx+$03B8]

* Possible String Reference to: 'Ocorrências'
|
005C970D   BAC0995C00             mov     edx, $005C99C0

|
005C9712   E8E1C1E3FF             call    004058F8
005C9717   8BC3                   mov     eax, ebx

* Reference to : TfrmBaseClientTabela._PROC_005C9154()
|
005C9719   E836FAFFFF             call    005C9154
005C971E   8B83A8030000           mov     eax, [ebx+$03A8]
005C9724   8B802C030000           mov     eax, [eax+$032C]

|
005C972A   E829A1E5FF             call    00423858
005C972F   8BF8                   mov     edi, eax
005C9731   4F                     dec     edi
005C9732   85FF                   test    edi, edi
005C9734   0F8C26020000           jl      005C9960
005C973A   47                     inc     edi
005C973B   33F6                   xor     esi, esi
005C973D   8B83A8030000           mov     eax, [ebx+$03A8]
005C9743   8B802C030000           mov     eax, [eax+$032C]
005C9749   8BD6                   mov     edx, esi

* Reference to : TDBGridInplaceEdit._PROC_005C2D18()
|
005C974B   E8C895FFFF             call    005C2D18
005C9750   8B401C                 mov     eax, [eax+$1C]
005C9753   8D55FC                 lea     edx, [ebp-$04]

* Reference to : TDBGridInplaceEdit._PROC_005C1838()
|
005C9756   E8DD80FFFF             call    005C1838
005C975B   8B45FC                 mov     eax, [ebp-$04]

* Possible String Reference to: 'oc_grupo'
|
005C975E   BAD4995C00             mov     edx, $005C99D4

|
005C9763   E84CC5E3FF             call    00405CB4
005C9768   7520                   jnz     005C978A
005C976A   8B83A8030000           mov     eax, [ebx+$03A8]
005C9770   8B802C030000           mov     eax, [eax+$032C]
005C9776   8BD6                   mov     edx, esi

* Reference to : TDBGridInplaceEdit._PROC_005C2D18()
|
005C9778   E89B95FFFF             call    005C2D18
005C977D   8B401C                 mov     eax, [eax+$1C]

* Possible String Reference to: 'Grupo'
|
005C9780   BAE8995C00             mov     edx, $005C99E8
005C9785   8B08                   mov     ecx, [eax]
005C9787   FF510C                 call    dword ptr [ecx+$0C]
005C978A   8B83A8030000           mov     eax, [ebx+$03A8]
005C9790   8B802C030000           mov     eax, [eax+$032C]
005C9796   8BD6                   mov     edx, esi

* Reference to : TDBGridInplaceEdit._PROC_005C2D18()
|
005C9798   E87B95FFFF             call    005C2D18
005C979D   8B401C                 mov     eax, [eax+$1C]
005C97A0   8D55F8                 lea     edx, [ebp-$08]

* Reference to : TDBGridInplaceEdit._PROC_005C1838()
|
005C97A3   E89080FFFF             call    005C1838
005C97A8   8B45F8                 mov     eax, [ebp-$08]

* Possible String Reference to: 'oc_referencia'
|
005C97AB   BAF8995C00             mov     edx, $005C99F8

|
005C97B0   E8FFC4E3FF             call    00405CB4
005C97B5   7520                   jnz     005C97D7
005C97B7   8B83A8030000           mov     eax, [ebx+$03A8]
005C97BD   8B802C030000           mov     eax, [eax+$032C]
005C97C3   8BD6                   mov     edx, esi

* Reference to : TDBGridInplaceEdit._PROC_005C2D18()
|
005C97C5   E84E95FFFF             call    005C2D18
005C97CA   8B401C                 mov     eax, [eax+$1C]

* Possible String Reference to: 'Referência'
|
005C97CD   BA109A5C00             mov     edx, $005C9A10
005C97D2   8B08                   mov     ecx, [eax]
005C97D4   FF510C                 call    dword ptr [ecx+$0C]
005C97D7   8B83A8030000           mov     eax, [ebx+$03A8]
005C97DD   8B802C030000           mov     eax, [eax+$032C]
005C97E3   8BD6                   mov     edx, esi

* Reference to : TDBGridInplaceEdit._PROC_005C2D18()
|
005C97E5   E82E95FFFF             call    005C2D18
005C97EA   8B401C                 mov     eax, [eax+$1C]
005C97ED   8D55F4                 lea     edx, [ebp-$0C]

* Reference to : TDBGridInplaceEdit._PROC_005C1838()
|
005C97F0   E84380FFFF             call    005C1838
005C97F5   8B45F4                 mov     eax, [ebp-$0C]

* Possible String Reference to: 'oc_codigo'
|
005C97F8   BA249A5C00             mov     edx, $005C9A24

|
005C97FD   E8B2C4E3FF             call    00405CB4
005C9802   7520                   jnz     005C9824
005C9804   8B83A8030000           mov     eax, [ebx+$03A8]
005C980A   8B802C030000           mov     eax, [eax+$032C]
005C9810   8BD6                   mov     edx, esi

* Reference to : TDBGridInplaceEdit._PROC_005C2D18()
|
005C9812   E80195FFFF             call    005C2D18
005C9817   8B401C                 mov     eax, [eax+$1C]

* Possible String Reference to: 'Código'
|
005C981A   BA389A5C00             mov     edx, $005C9A38
005C981F   8B08                   mov     ecx, [eax]
005C9821   FF510C                 call    dword ptr [ecx+$0C]
005C9824   8B83A8030000           mov     eax, [ebx+$03A8]
005C982A   8B802C030000           mov     eax, [eax+$032C]
005C9830   8BD6                   mov     edx, esi

* Reference to : TDBGridInplaceEdit._PROC_005C2D18()
|
005C9832   E8E194FFFF             call    005C2D18
005C9837   8B401C                 mov     eax, [eax+$1C]
005C983A   8D55F0                 lea     edx, [ebp-$10]

* Reference to : TDBGridInplaceEdit._PROC_005C1838()
|
005C983D   E8F67FFFFF             call    005C1838
005C9842   8B45F0                 mov     eax, [ebp-$10]

* Possible String Reference to: 'oc_descricao'
|
005C9845   BA489A5C00             mov     edx, $005C9A48

|
005C984A   E865C4E3FF             call    00405CB4
005C984F   7520                   jnz     005C9871
005C9851   8B83A8030000           mov     eax, [ebx+$03A8]
005C9857   8B802C030000           mov     eax, [eax+$032C]
005C985D   8BD6                   mov     edx, esi

* Reference to : TDBGridInplaceEdit._PROC_005C2D18()
|
005C985F   E8B494FFFF             call    005C2D18
005C9864   8B401C                 mov     eax, [eax+$1C]

* Possible String Reference to: 'Descrição'
|
005C9867   BA609A5C00             mov     edx, $005C9A60
005C986C   8B08                   mov     ecx, [eax]
005C986E   FF510C                 call    dword ptr [ecx+$0C]
005C9871   8B83A8030000           mov     eax, [ebx+$03A8]
005C9877   8B802C030000           mov     eax, [eax+$032C]
005C987D   8BD6                   mov     edx, esi

* Reference to : TDBGridInplaceEdit._PROC_005C2D18()
|
005C987F   E89494FFFF             call    005C2D18
005C9884   8B401C                 mov     eax, [eax+$1C]
005C9887   8D55EC                 lea     edx, [ebp-$14]

* Reference to : TDBGridInplaceEdit._PROC_005C1838()
|
005C988A   E8A97FFFFF             call    005C1838
005C988F   8B45EC                 mov     eax, [ebp-$14]

* Possible String Reference to: 'oc_calculo'
|
005C9892   BA749A5C00             mov     edx, $005C9A74

|
005C9897   E818C4E3FF             call    00405CB4
005C989C   7520                   jnz     005C98BE
005C989E   8B83A8030000           mov     eax, [ebx+$03A8]
005C98A4   8B802C030000           mov     eax, [eax+$032C]
005C98AA   8BD6                   mov     edx, esi

* Reference to : TDBGridInplaceEdit._PROC_005C2D18()
|
005C98AC   E86794FFFF             call    005C2D18
005C98B1   8B401C                 mov     eax, [eax+$1C]

* Possible String Reference to: 'Forma de Cálculo'
|
005C98B4   BA889A5C00             mov     edx, $005C9A88
005C98B9   8B08                   mov     ecx, [eax]
005C98BB   FF510C                 call    dword ptr [ecx+$0C]
005C98BE   8B83A8030000           mov     eax, [ebx+$03A8]
005C98C4   8B802C030000           mov     eax, [eax+$032C]
005C98CA   8BD6                   mov     edx, esi

* Reference to : TDBGridInplaceEdit._PROC_005C2D18()
|
005C98CC   E84794FFFF             call    005C2D18
005C98D1   8B401C                 mov     eax, [eax+$1C]
005C98D4   8D55E8                 lea     edx, [ebp-$18]

* Reference to : TDBGridInplaceEdit._PROC_005C1838()
|
005C98D7   E85C7FFFFF             call    005C1838
005C98DC   8B45E8                 mov     eax, [ebp-$18]

* Possible String Reference to: 'oc_mensagem'
|
005C98DF   BAA49A5C00             mov     edx, $005C9AA4

|
005C98E4   E8CBC3E3FF             call    00405CB4
005C98E9   7520                   jnz     005C990B
005C98EB   8B83A8030000           mov     eax, [ebx+$03A8]
005C98F1   8B802C030000           mov     eax, [eax+$032C]
005C98F7   8BD6                   mov     edx, esi

* Reference to : TDBGridInplaceEdit._PROC_005C2D18()
|
005C98F9   E81A94FFFF             call    005C2D18
005C98FE   8B401C                 mov     eax, [eax+$1C]

* Possible String Reference to: 'Mensagem na Fatura'
|
005C9901   BAB89A5C00             mov     edx, $005C9AB8
005C9906   8B08                   mov     ecx, [eax]
005C9908   FF510C                 call    dword ptr [ecx+$0C]
005C990B   8B83A8030000           mov     eax, [ebx+$03A8]
005C9911   8B802C030000           mov     eax, [eax+$032C]
005C9917   8BD6                   mov     edx, esi

* Reference to : TDBGridInplaceEdit._PROC_005C2D18()
|
005C9919   E8FA93FFFF             call    005C2D18
005C991E   8B401C                 mov     eax, [eax+$1C]
005C9921   8D55E4                 lea     edx, [ebp-$1C]

* Reference to : TDBGridInplaceEdit._PROC_005C1838()
|
005C9924   E80F7FFFFF             call    005C1838
005C9929   8B45E4                 mov     eax, [ebp-$1C]

* Possible String Reference to: 'oc_acesso'
|
005C992C   BAD49A5C00             mov     edx, $005C9AD4

|
005C9931   E87EC3E3FF             call    00405CB4
005C9936   7520                   jnz     005C9958
005C9938   8B83A8030000           mov     eax, [ebx+$03A8]
005C993E   8B802C030000           mov     eax, [eax+$032C]
005C9944   8BD6                   mov     edx, esi

* Reference to : TDBGridInplaceEdit._PROC_005C2D18()
|
005C9946   E8CD93FFFF             call    005C2D18
005C994B   8B401C                 mov     eax, [eax+$1C]

* Possible String Reference to: 'Acesso'
|
005C994E   BAE89A5C00             mov     edx, $005C9AE8
005C9953   8B08                   mov     ecx, [eax]
005C9955   FF510C                 call    dword ptr [ecx+$0C]
005C9958   46                     inc     esi
005C9959   4F                     dec     edi
005C995A   0F85DDFDFFFF           jnz     005C973D
005C9960   B301                   mov     bl, $01
005C9962   33C0                   xor     eax, eax
005C9964   5A                     pop     edx
005C9965   59                     pop     ecx
005C9966   59                     pop     ecx
005C9967   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: '‹Ã_^[‹å]Ã'
|
005C996A   6884995C00             push    $005C9984
005C996F   8D45E4                 lea     eax, [ebp-$1C]
005C9972   BA07000000             mov     edx, $00000007

|
005C9977   E84CBFE3FF             call    004058C8
005C997C   C3                     ret

*)
end;

end.