unit uFrmTeste;

interface

uses
  Windows, Messages, SysUtils, Classes, Graphics,
  Controls, Forms, Dialogs, StdCtrls
type
  TfrmTeste=class(TForm)
    Label1: TLabel [0];
    Label3: TLabel [1];
    PATH: TLabel [2];
    LStatus: TLabel [3];
    Label2: TLabel [4];
    Egrupo: TEdit;
    ERota: TEdit;
    btnGerar: TButton;
    EPath: TEdit;
    Button1: TButton;
    Button2: TButton;
    ProgressBar: TProgressBar;
    Button3: TButton;
    Button4: TButton;
    Button5: TButton;
    Button6: TButton;
    Button7: TButton;
    Button8: TButton;
    btnStatus: TButton;
    EArquivo: TEdit;
    qryGeral: TQuery;
    Button9: TButton;
    procedure Button9Click(Sender : TObject);
    procedure btnStatusClick(Sender : TObject);
    procedure Button4Click(Sender : TObject);
    procedure Button6Click(Sender : TObject);
    procedure Button7Click(Sender : TObject);
    procedure Button8Click(Sender : TObject);
    procedure Button5Click(Sender : TObject);
    procedure Button3Click(Sender : TObject);
    procedure Button2Click(Sender : TObject);
    procedure Button1Click(Sender : TObject);
    procedure btnGerarClick(Sender : TObject);
    procedure _PROC_0059782D(Sender : TObject);
    procedure _PROC_005979E1(Sender : TObject);
    procedure _PROC_00597C91(Sender : TObject);
    procedure _PROC_00598169(Sender : TObject);
    procedure _PROC_00598346(Sender : TObject);
    procedure _PROC_0059837A(Sender : TObject);
  private
    { Private declarations }
  public
    { Public declarations }
  end ;

var
  frmTeste: TfrmTeste;

{This file is generated by DeDe Ver 3.50.04 Copyright (c) 1999-2002 DaFixer}

implementation

{$R *.DFM}

procedure TfrmTeste.Button9Click(Sender : TObject);
begin
(*
00597C90   55                     push    ebp
00597C91   8BEC                   mov     ebp, esp
00597C93   6A00                   push    $00
00597C95   53                     push    ebx
00597C96   8BD8                   mov     ebx, eax
00597C98   33C0                   xor     eax, eax
00597C9A   55                     push    ebp

* Possible String Reference to: 'ÈØ”ÊˇÎ[Y]√êUãÏ3…QQQQQQQâE¸3¿Uhˇ~Y'
|
00597C9B   68E07C5900             push    $00597CE0

***** TRY
|
00597CA0   64FF30                 push    dword ptr fs:[eax]
00597CA3   648920                 mov     fs:[eax], esp
00597CA6   8D55FC                 lea     edx, [ebp-$04]

* Reference to control TfrmTeste.Egrupo : TEdit
|
00597CA9   8B8394030000           mov     eax, [ebx+$0394]

|
00597CAF   E84C7EECFF             call    0045FB00
00597CB4   8B45FC                 mov     eax, [ebp-$04]

|
00597CB7   E88835E7FF             call    0040B244
00597CBC   8BD0                   mov     edx, eax
00597CBE   A168F76300             mov     eax, dword ptr [$0063F768]
00597CC3   8B00                   mov     eax, [eax]

|
00597CC5   E832A5FEFF             call    005821FC
00597CCA   33C0                   xor     eax, eax
00597CCC   5A                     pop     edx
00597CCD   59                     pop     ecx
00597CCE   59                     pop     ecx
00597CCF   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: '[Y]√êUãÏ3…QQQQQQQâE¸3¿Uhˇ~Y'
|
00597CD2   68E77C5900             push    $00597CE7
00597CD7   8D45FC                 lea     eax, [ebp-$04]

|
00597CDA   E8C5DBE6FF             call    004058A4
00597CDF   C3                     ret


|
00597CE0   E9AFD3E6FF             jmp     00405094
00597CE5   EBF0                   jmp     00597CD7

****** END
|
00597CE7   5B                     pop     ebx
00597CE8   59                     pop     ecx
00597CE9   5D                     pop     ebp
00597CEA   C3                     ret

*)
end;

procedure TfrmTeste.btnStatusClick(Sender : TObject);
begin
(*
00597CEC   55                     push    ebp
00597CED   8BEC                   mov     ebp, esp
00597CEF   33C9                   xor     ecx, ecx
00597CF1   51                     push    ecx
00597CF2   51                     push    ecx
00597CF3   51                     push    ecx
00597CF4   51                     push    ecx
00597CF5   51                     push    ecx
00597CF6   51                     push    ecx
00597CF7   51                     push    ecx
00597CF8   8945FC                 mov     [ebp-$04], eax
00597CFB   33C0                   xor     eax, eax
00597CFD   55                     push    ebp

* Possible String Reference to: 'Èê—ÊˇÎ»ãÂ]√'
|
00597CFE   68FF7E5900             push    $00597EFF

***** TRY
|
00597D03   64FF30                 push    dword ptr fs:[eax]
00597D06   648920                 mov     fs:[eax], esp
00597D09   33C0                   xor     eax, eax
00597D0B   55                     push    ebp
00597D0C   68BA7E5900             push    $00597EBA

***** TRY
|
00597D11   64FF30                 push    dword ptr fs:[eax]
00597D14   648920                 mov     fs:[eax], esp
00597D17   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TfrmTeste.qryGeral : TQuery
|
00597D1A   8B80D0030000           mov     eax, [eax+$03D0]

|
00597D20   E87769F0FF             call    0049E69C
00597D25   84C0                   test    al, al
00597D27   740E                   jz      00597D37
00597D29   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TfrmTeste.qryGeral : TQuery
|
00597D2C   8B80D0030000           mov     eax, [eax+$03D0]

|
00597D32   E8D967F0FF             call    0049E510
00597D37   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TfrmTeste.qryGeral : TQuery
|
00597D3A   8B80D0030000           mov     eax, [eax+$03D0]

* Reference to field TQuery.OFFS_0248
|
00597D40   8B8048020000           mov     eax, [eax+$0248]
00597D46   8B10                   mov     edx, [eax]
00597D48   FF5244                 call    dword ptr [edx+$44]
00597D4B   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TfrmTeste.qryGeral : TQuery
|
00597D4E   8B80D0030000           mov     eax, [eax+$03D0]

* Reference to field TQuery.OFFS_0248
|
00597D54   8B8048020000           mov     eax, [eax+$0248]

* Possible String Reference to: 'select tb_descricao '
|
00597D5A   BA147F5900             mov     edx, $00597F14
00597D5F   8B08                   mov     ecx, [eax]
00597D61   FF5138                 call    dword ptr [ecx+$38]
00597D64   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TfrmTeste.qryGeral : TQuery
|
00597D67   8B80D0030000           mov     eax, [eax+$03D0]

* Reference to field TQuery.OFFS_0248
|
00597D6D   8B8048020000           mov     eax, [eax+$0248]

* Possible String Reference to: 'from tabelas, roteiros'
|
00597D73   BA347F5900             mov     edx, $00597F34
00597D78   8B08                   mov     ecx, [eax]
00597D7A   FF5138                 call    dword ptr [ecx+$38]
00597D7D   8D55F4                 lea     edx, [ebp-$0C]
00597D80   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TfrmTeste.Egrupo : TEdit
|
00597D83   8B8094030000           mov     eax, [eax+$0394]

|
00597D89   E8727DECFF             call    0045FB00
00597D8E   8B4DF4                 mov     ecx, [ebp-$0C]
00597D91   8D45F8                 lea     eax, [ebp-$08]

* Possible String Reference to: 'where rt_grupo = '
|
00597D94   BA547F5900             mov     edx, $00597F54

|
00597D99   E816DEE6FF             call    00405BB4
00597D9E   8B55F8                 mov     edx, [ebp-$08]
00597DA1   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TfrmTeste.qryGeral : TQuery
|
00597DA4   8B80D0030000           mov     eax, [eax+$03D0]

* Reference to field TQuery.OFFS_0248
|
00597DAA   8B8048020000           mov     eax, [eax+$0248]
00597DB0   8B08                   mov     ecx, [eax]
00597DB2   FF5138                 call    dword ptr [ecx+$38]
00597DB5   8D55EC                 lea     edx, [ebp-$14]
00597DB8   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TfrmTeste.ERota : TEdit
|
00597DBB   8B8098030000           mov     eax, [eax+$0398]

|
00597DC1   E83A7DECFF             call    0045FB00
00597DC6   8B4DEC                 mov     ecx, [ebp-$14]
00597DC9   8D45F0                 lea     eax, [ebp-$10]

* Possible String Reference to: 'and rt_rota = '
|
00597DCC   BA707F5900             mov     edx, $00597F70

|
00597DD1   E8DEDDE6FF             call    00405BB4
00597DD6   8B55F0                 mov     edx, [ebp-$10]
00597DD9   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TfrmTeste.qryGeral : TQuery
|
00597DDC   8B80D0030000           mov     eax, [eax+$03D0]

* Reference to field TQuery.OFFS_0248
|
00597DE2   8B8048020000           mov     eax, [eax+$0248]
00597DE8   8B08                   mov     ecx, [eax]
00597DEA   FF5138                 call    dword ptr [ecx+$38]
00597DED   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TfrmTeste.qryGeral : TQuery
|
00597DF0   8B80D0030000           mov     eax, [eax+$03D0]

* Reference to field TQuery.OFFS_0248
|
00597DF6   8B8048020000           mov     eax, [eax+$0248]

* Possible String Reference to: 'and tb_valor = rt_ind_leitura '
|
00597DFC   BA887F5900             mov     edx, $00597F88
00597E01   8B08                   mov     ecx, [eax]
00597E03   FF5138                 call    dword ptr [ecx+$38]
00597E06   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TfrmTeste.qryGeral : TQuery
|
00597E09   8B80D0030000           mov     eax, [eax+$03D0]

* Reference to field TQuery.OFFS_0248
|
00597E0F   8B8048020000           mov     eax, [eax+$0248]

* Possible String Reference to: 'and tb_tabela = 'roteiros' '
|
00597E15   BAB07F5900             mov     edx, $00597FB0
00597E1A   8B08                   mov     ecx, [eax]
00597E1C   FF5138                 call    dword ptr [ecx+$38]
00597E1F   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TfrmTeste.qryGeral : TQuery
|
00597E22   8B80D0030000           mov     eax, [eax+$03D0]

* Reference to field TQuery.OFFS_0248
|
00597E28   8B8048020000           mov     eax, [eax+$0248]

* Possible String Reference to: 'and tb_campo = 'rt_ind_leitura''
|
00597E2E   BAD47F5900             mov     edx, $00597FD4
00597E33   8B08                   mov     ecx, [eax]
00597E35   FF5138                 call    dword ptr [ecx+$38]
00597E38   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TfrmTeste.qryGeral : TQuery
|
00597E3B   8B80D0030000           mov     eax, [eax+$03D0]

|
00597E41   E8B666F0FF             call    0049E4FC
00597E46   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TfrmTeste.qryGeral : TQuery
|
00597E49   8B80D0030000           mov     eax, [eax+$03D0]
00597E4F   BAF87F5900             mov     edx, $00597FF8

|
00597E54   E8DF79F0FF             call    0049F838
00597E59   8D55E8                 lea     edx, [ebp-$18]
00597E5C   8B08                   mov     ecx, [eax]

* Possible reference to virtual method TQuery.OFFS_60
|
00597E5E   FF5160                 call    dword ptr [ecx+$60]
00597E61   8B55E8                 mov     edx, [ebp-$18]
00597E64   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TfrmTeste.LStatus : TLabel [3]
|
00597E67   8B808C030000           mov     eax, [eax+$038C]

|
00597E6D   E8BE7CECFF             call    0045FB30
00597E72   33C0                   xor     eax, eax
00597E74   5A                     pop     edx
00597E75   59                     pop     ecx
00597E76   59                     pop     ecx
00597E77   648910                 mov     fs:[eax], edx

****** FINALLY
|
00597E7A   68C17E5900             push    $00597EC1
00597E7F   8D55E4                 lea     edx, [ebp-$1C]
00597E82   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TfrmTeste.LStatus : TLabel [3]
|
00597E85   8B808C030000           mov     eax, [eax+$038C]

|
00597E8B   E8707CECFF             call    0045FB00
00597E90   837DE400               cmp     dword ptr [ebp-$1C], +$00
00597E94   7513                   jnz     00597EA9
00597E96   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TfrmTeste.LStatus : TLabel [3]
|
00597E99   8B808C030000           mov     eax, [eax+$038C]

* Possible String Reference to: 'Roteiro inexistente ou Aguardando R
|                                ecepÁ„o'
|
00597E9F   BA1C805900             mov     edx, $0059801C

|
00597EA4   E8877CECFF             call    0045FB30
00597EA9   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TfrmTeste.ProgressBar : TProgressBar
|
00597EAC   8B80AC030000           mov     eax, [eax+$03AC]
00597EB2   33D2                   xor     edx, edx

* Reference to : TTabStrings._PROC_004C93E4()
|
00597EB4   E82B15F3FF             call    004C93E4
00597EB9   C3                     ret


|
00597EBA   E9D5D1E6FF             jmp     00405094
00597EBF   EBBE                   jmp     00597E7F

****** END
|
00597EC1   33C0                   xor     eax, eax
00597EC3   5A                     pop     edx
00597EC4   59                     pop     ecx
00597EC5   59                     pop     ecx
00597EC6   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: 'ãÂ]√'
|
00597EC9   68067F5900             push    $00597F06
00597ECE   8D45E4                 lea     eax, [ebp-$1C]

|
00597ED1   E8CED9E6FF             call    004058A4
00597ED6   8D45E8                 lea     eax, [ebp-$18]

|
00597ED9   E8C6D9E6FF             call    004058A4
00597EDE   8D45EC                 lea     eax, [ebp-$14]

|
00597EE1   E8BED9E6FF             call    004058A4
00597EE6   8D45F0                 lea     eax, [ebp-$10]

|
00597EE9   E8B6D9E6FF             call    004058A4
00597EEE   8D45F4                 lea     eax, [ebp-$0C]

|
00597EF1   E8AED9E6FF             call    004058A4
00597EF6   8D45F8                 lea     eax, [ebp-$08]

|
00597EF9   E8A6D9E6FF             call    004058A4
00597EFE   C3                     ret


|
00597EFF   E990D1E6FF             jmp     00405094
00597F04   EBC8                   jmp     00597ECE

****** END
|
00597F06   8BE5                   mov     esp, ebp
00597F08   5D                     pop     ebp
00597F09   C3                     ret

*)
end;

procedure TfrmTeste.Button4Click(Sender : TObject);
begin
(*
00597AC8   55                     push    ebp
00597AC9   8BEC                   mov     ebp, esp
00597ACB   6A00                   push    $00
00597ACD   6A00                   push    $00
00597ACF   53                     push    ebx
00597AD0   56                     push    esi
00597AD1   8BD8                   mov     ebx, eax
00597AD3   33C0                   xor     eax, eax
00597AD5   55                     push    ebp
00597AD6   68637B5900             push    $00597B63

***** TRY
|
00597ADB   64FF30                 push    dword ptr fs:[eax]
00597ADE   648920                 mov     fs:[eax], esp
00597AE1   6A00                   push    $00
00597AE3   8D55FC                 lea     edx, [ebp-$04]

* Reference to control TfrmTeste.ERota : TEdit
|
00597AE6   8B8398030000           mov     eax, [ebx+$0398]

|
00597AEC   E80F80ECFF             call    0045FB00
00597AF1   8B45FC                 mov     eax, [ebp-$04]

|
00597AF4   E84B37E7FF             call    0040B244
00597AF9   50                     push    eax
00597AFA   8D55F8                 lea     edx, [ebp-$08]

* Reference to control TfrmTeste.Egrupo : TEdit
|
00597AFD   8B8394030000           mov     eax, [ebx+$0394]

|
00597B03   E8F87FECFF             call    0045FB00
00597B08   8B45F8                 mov     eax, [ebp-$08]

|
00597B0B   E83437E7FF             call    0040B244
00597B10   8BD0                   mov     edx, eax
00597B12   A194F96300             mov     eax, dword ptr [$0063F994]
00597B17   8B00                   mov     eax, [eax]
00597B19   59                     pop     ecx

|
00597B1A   E899D5FEFF             call    005850B8
00597B1F   84C0                   test    al, al
00597B21   740C                   jz      00597B2F

* Possible String Reference to: 'Pronto!'
|
00597B23   B8787B5900             mov     eax, $00597B78

* Reference to : TMessageForm._PROC_00450CC0()
|
00597B28   E89391EBFF             call    00450CC0
00597B2D   EB0A                   jmp     00597B39

* Possible String Reference to: 'Problemas no Finalizar Roteiro!'
|
00597B2F   B8887B5900             mov     eax, $00597B88

* Reference to : TMessageForm._PROC_00450CC0()
|
00597B34   E88791EBFF             call    00450CC0

* Reference to control TfrmTeste.btnStatus : TButton
|
00597B39   8B83C8030000           mov     eax, [ebx+$03C8]
00597B3F   66BEEBFF               mov     si, $FFEB

|
00597B43   E874CFE6FF             call    00404ABC
00597B48   33C0                   xor     eax, eax
00597B4A   5A                     pop     edx
00597B4B   59                     pop     ecx
00597B4C   59                     pop     ecx
00597B4D   648910                 mov     fs:[eax], edx

****** FINALLY
|
00597B50   686A7B5900             push    $00597B6A
00597B55   8D45F8                 lea     eax, [ebp-$08]
00597B58   BA02000000             mov     edx, $00000002

|
00597B5D   E866DDE6FF             call    004058C8
00597B62   C3                     ret


|
00597B63   E92CD5E6FF             jmp     00405094
00597B68   EBEB                   jmp     00597B55

****** END
|
00597B6A   5E                     pop     esi
00597B6B   5B                     pop     ebx
00597B6C   59                     pop     ecx
00597B6D   59                     pop     ecx
00597B6E   5D                     pop     ebp
00597B6F   C3                     ret

*)
end;

procedure TfrmTeste.Button6Click(Sender : TObject);
begin
(*
00598168   55                     push    ebp
00598169   8BEC                   mov     ebp, esp
0059816B   6A00                   push    $00
0059816D   6A00                   push    $00
0059816F   53                     push    ebx
00598170   56                     push    esi
00598171   8BD8                   mov     ebx, eax
00598173   33C0                   xor     eax, eax
00598175   55                     push    ebp
00598176   680F825900             push    $0059820F

***** TRY
|
0059817B   64FF30                 push    dword ptr fs:[eax]
0059817E   648920                 mov     fs:[eax], esp

* Reference to control TfrmTeste.ProgressBar : TProgressBar
|
00598181   8B83AC030000           mov     eax, [ebx+$03AC]
00598187   50                     push    eax

* Reference to field TfrmTeste.OFFS_03D8
|
00598188   8D83D8030000           lea     eax, [ebx+$03D8]
0059818E   50                     push    eax
0059818F   8D55FC                 lea     edx, [ebp-$04]

* Reference to control TfrmTeste.ERota : TEdit
|
00598192   8B8398030000           mov     eax, [ebx+$0398]

|
00598198   E86379ECFF             call    0045FB00
0059819D   8B45FC                 mov     eax, [ebp-$04]

|
005981A0   E89F30E7FF             call    0040B244
005981A5   50                     push    eax
005981A6   8D55F8                 lea     edx, [ebp-$08]

* Reference to control TfrmTeste.Egrupo : TEdit
|
005981A9   8B8394030000           mov     eax, [ebx+$0394]

|
005981AF   E84C79ECFF             call    0045FB00
005981B4   8B45F8                 mov     eax, [ebp-$08]

|
005981B7   E88830E7FF             call    0040B244
005981BC   8BD0                   mov     edx, eax
005981BE   A1B0FD6300             mov     eax, dword ptr [$0063FDB0]
005981C3   8B00                   mov     eax, [eax]
005981C5   59                     pop     ecx

|
005981C6   E81197FEFF             call    005818DC
005981CB   84C0                   test    al, al
005981CD   740C                   jz      005981DB

* Possible String Reference to: 'Pronto!'
|
005981CF   B824825900             mov     eax, $00598224

* Reference to : TMessageForm._PROC_00450CC0()
|
005981D4   E8E78AEBFF             call    00450CC0
005981D9   EB0A                   jmp     005981E5

* Possible String Reference to: 'Problemas no Desfazer da Transmiss„
|                                o!'
|
005981DB   B834825900             mov     eax, $00598234

* Reference to : TMessageForm._PROC_00450CC0()
|
005981E0   E8DB8AEBFF             call    00450CC0

* Reference to control TfrmTeste.btnStatus : TButton
|
005981E5   8B83C8030000           mov     eax, [ebx+$03C8]
005981EB   66BEEBFF               mov     si, $FFEB

|
005981EF   E8C8C8E6FF             call    00404ABC
005981F4   33C0                   xor     eax, eax
005981F6   5A                     pop     edx
005981F7   59                     pop     ecx
005981F8   59                     pop     ecx
005981F9   648910                 mov     fs:[eax], edx

****** FINALLY
|
005981FC   6816825900             push    $00598216
00598201   8D45F8                 lea     eax, [ebp-$08]
00598204   BA02000000             mov     edx, $00000002

|
00598209   E8BAD6E6FF             call    004058C8
0059820E   C3                     ret


|
0059820F   E980CEE6FF             jmp     00405094
00598214   EBEB                   jmp     00598201

****** END
|
00598216   5E                     pop     esi
00598217   5B                     pop     ebx
00598218   59                     pop     ecx
00598219   59                     pop     ecx
0059821A   5D                     pop     ebp
0059821B   C3                     ret

*)
end;

procedure TfrmTeste.Button7Click(Sender : TObject);
begin
(*
0059825C   55                     push    ebp
0059825D   8BEC                   mov     ebp, esp
0059825F   6A00                   push    $00
00598261   6A00                   push    $00
00598263   53                     push    ebx
00598264   56                     push    esi
00598265   8BD8                   mov     ebx, eax
00598267   33C0                   xor     eax, eax
00598269   55                     push    ebp
0059826A   6803835900             push    $00598303

***** TRY
|
0059826F   64FF30                 push    dword ptr fs:[eax]
00598272   648920                 mov     fs:[eax], esp

* Reference to control TfrmTeste.ProgressBar : TProgressBar
|
00598275   8B83AC030000           mov     eax, [ebx+$03AC]
0059827B   50                     push    eax

* Reference to field TfrmTeste.OFFS_03D8
|
0059827C   8D83D8030000           lea     eax, [ebx+$03D8]
00598282   50                     push    eax
00598283   8D55FC                 lea     edx, [ebp-$04]

* Reference to control TfrmTeste.ERota : TEdit
|
00598286   8B8398030000           mov     eax, [ebx+$0398]

|
0059828C   E86F78ECFF             call    0045FB00
00598291   8B45FC                 mov     eax, [ebp-$04]

|
00598294   E8AB2FE7FF             call    0040B244
00598299   50                     push    eax
0059829A   8D55F8                 lea     edx, [ebp-$08]

* Reference to control TfrmTeste.Egrupo : TEdit
|
0059829D   8B8394030000           mov     eax, [ebx+$0394]

|
005982A3   E85878ECFF             call    0045FB00
005982A8   8B45F8                 mov     eax, [ebp-$08]

|
005982AB   E8942FE7FF             call    0040B244
005982B0   8BD0                   mov     edx, eax
005982B2   A1B0FD6300             mov     eax, dword ptr [$0063FDB0]
005982B7   8B00                   mov     eax, [eax]
005982B9   59                     pop     ecx

|
005982BA   E89187FEFF             call    00580A50
005982BF   84C0                   test    al, al
005982C1   740C                   jz      005982CF

* Possible String Reference to: 'Pronto!'
|
005982C3   B818835900             mov     eax, $00598318

* Reference to : TMessageForm._PROC_00450CC0()
|
005982C8   E8F389EBFF             call    00450CC0
005982CD   EB0A                   jmp     005982D9

* Possible String Reference to: 'Problemas na Transmiss„o!'
|
005982CF   B828835900             mov     eax, $00598328

* Reference to : TMessageForm._PROC_00450CC0()
|
005982D4   E8E789EBFF             call    00450CC0

* Reference to control TfrmTeste.btnStatus : TButton
|
005982D9   8B83C8030000           mov     eax, [ebx+$03C8]
005982DF   66BEEBFF               mov     si, $FFEB

|
005982E3   E8D4C7E6FF             call    00404ABC
005982E8   33C0                   xor     eax, eax
005982EA   5A                     pop     edx
005982EB   59                     pop     ecx
005982EC   59                     pop     ecx
005982ED   648910                 mov     fs:[eax], edx

****** FINALLY
|
005982F0   680A835900             push    $0059830A
005982F5   8D45F8                 lea     eax, [ebp-$08]
005982F8   BA02000000             mov     edx, $00000002

|
005982FD   E8C6D5E6FF             call    004058C8
00598302   C3                     ret


|
00598303   E98CCDE6FF             jmp     00405094
00598308   EBEB                   jmp     005982F5

****** END
|
0059830A   5E                     pop     esi
0059830B   5B                     pop     ebx
0059830C   59                     pop     ecx
0059830D   59                     pop     ecx
0059830E   5D                     pop     ebp
0059830F   C3                     ret

*)
end;

procedure TfrmTeste.Button8Click(Sender : TObject);
begin
(*
00597BA8   55                     push    ebp
00597BA9   8BEC                   mov     ebp, esp
00597BAB   6A00                   push    $00
00597BAD   6A00                   push    $00
00597BAF   53                     push    ebx
00597BB0   56                     push    esi
00597BB1   8BD8                   mov     ebx, eax
00597BB3   33C0                   xor     eax, eax
00597BB5   55                     push    ebp

* Possible String Reference to: 'ÈE‘ÊˇÎÎ^[YY]√'
|
00597BB6   684A7C5900             push    $00597C4A

***** TRY
|
00597BBB   64FF30                 push    dword ptr fs:[eax]
00597BBE   648920                 mov     fs:[eax], esp
00597BC1   6A00                   push    $00

* Reference to field TfrmTeste.OFFS_03D8
|
00597BC3   8D83D8030000           lea     eax, [ebx+$03D8]
00597BC9   50                     push    eax
00597BCA   8D55FC                 lea     edx, [ebp-$04]

* Reference to control TfrmTeste.ERota : TEdit
|
00597BCD   8B8398030000           mov     eax, [ebx+$0398]

|
00597BD3   E8287FECFF             call    0045FB00
00597BD8   8B45FC                 mov     eax, [ebp-$04]

|
00597BDB   E86436E7FF             call    0040B244
00597BE0   50                     push    eax
00597BE1   8D55F8                 lea     edx, [ebp-$08]

* Reference to control TfrmTeste.Egrupo : TEdit
|
00597BE4   8B8394030000           mov     eax, [ebx+$0394]

|
00597BEA   E8117FECFF             call    0045FB00
00597BEF   8B45F8                 mov     eax, [ebp-$08]

|
00597BF2   E84D36E7FF             call    0040B244
00597BF7   8BD0                   mov     edx, eax
00597BF9   A1ACFB6300             mov     eax, dword ptr [$0063FBAC]
00597BFE   8B00                   mov     eax, [eax]
00597C00   59                     pop     ecx

|
00597C01   E812EBFFFF             call    00596718
00597C06   84C0                   test    al, al
00597C08   740C                   jz      00597C16

* Possible String Reference to: 'Pronto!'
|
00597C0A   B8607C5900             mov     eax, $00597C60

* Reference to : TMessageForm._PROC_00450CC0()
|
00597C0F   E8AC90EBFF             call    00450CC0
00597C14   EB0A                   jmp     00597C20

* Possible String Reference to: 'Problemas no Desfazer Descarga!'
|
00597C16   B8707C5900             mov     eax, $00597C70

* Reference to : TMessageForm._PROC_00450CC0()
|
00597C1B   E8A090EBFF             call    00450CC0

* Reference to control TfrmTeste.btnStatus : TButton
|
00597C20   8B83C8030000           mov     eax, [ebx+$03C8]
00597C26   66BEEBFF               mov     si, $FFEB

|
00597C2A   E88DCEE6FF             call    00404ABC
00597C2F   33C0                   xor     eax, eax
00597C31   5A                     pop     edx
00597C32   59                     pop     ecx
00597C33   59                     pop     ecx
00597C34   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: '^[YY]√'
|
00597C37   68517C5900             push    $00597C51
00597C3C   8D45F8                 lea     eax, [ebp-$08]
00597C3F   BA02000000             mov     edx, $00000002

|
00597C44   E87FDCE6FF             call    004058C8
00597C49   C3                     ret


|
00597C4A   E945D4E6FF             jmp     00405094
00597C4F   EBEB                   jmp     00597C3C

****** END
|
00597C51   5E                     pop     esi
00597C52   5B                     pop     ebx
00597C53   59                     pop     ecx
00597C54   59                     pop     ecx
00597C55   5D                     pop     ebp
00597C56   C3                     ret

*)
end;

procedure TfrmTeste.Button5Click(Sender : TObject);
begin
(*
00598048   55                     push    ebp
00598049   8BEC                   mov     ebp, esp
0059804B   33C9                   xor     ecx, ecx
0059804D   51                     push    ecx
0059804E   51                     push    ecx
0059804F   51                     push    ecx
00598050   51                     push    ecx
00598051   51                     push    ecx
00598052   53                     push    ebx
00598053   56                     push    esi
00598054   8BD8                   mov     ebx, eax
00598056   33C0                   xor     eax, eax
00598058   55                     push    ebp
00598059   682B815900             push    $0059812B

***** TRY
|
0059805E   64FF30                 push    dword ptr fs:[eax]
00598061   648920                 mov     fs:[eax], esp
00598064   8D55F8                 lea     edx, [ebp-$08]

* Reference to control TfrmTeste.EPath : TEdit
|
00598067   8B83A0030000           mov     eax, [ebx+$03A0]

|
0059806D   E88E7AECFF             call    0045FB00
00598072   8D45F8                 lea     eax, [ebp-$08]
00598075   50                     push    eax
00598076   8D55F4                 lea     edx, [ebp-$0C]

* Reference to control TfrmTeste.EArquivo : TEdit
|
00598079   8B83CC030000           mov     eax, [ebx+$03CC]

|
0059807F   E87C7AECFF             call    0045FB00
00598084   8B55F4                 mov     edx, [ebp-$0C]
00598087   58                     pop     eax

|
00598088   E8E3DAE6FF             call    00405B70
0059808D   8B45F8                 mov     eax, [ebp-$08]
00598090   50                     push    eax

* Reference to control TfrmTeste.ProgressBar : TProgressBar
|
00598091   8B83AC030000           mov     eax, [ebx+$03AC]
00598097   50                     push    eax

* Reference to field TfrmTeste.OFFS_03D8
|
00598098   8D83D8030000           lea     eax, [ebx+$03D8]
0059809E   50                     push    eax
0059809F   8D45FC                 lea     eax, [ebp-$04]
005980A2   50                     push    eax
005980A3   8D55F0                 lea     edx, [ebp-$10]

* Reference to control TfrmTeste.ERota : TEdit
|
005980A6   8B8398030000           mov     eax, [ebx+$0398]

|
005980AC   E84F7AECFF             call    0045FB00
005980B1   8B45F0                 mov     eax, [ebp-$10]

|
005980B4   E88B31E7FF             call    0040B244
005980B9   50                     push    eax
005980BA   8D55EC                 lea     edx, [ebp-$14]

* Reference to control TfrmTeste.Egrupo : TEdit
|
005980BD   8B8394030000           mov     eax, [ebx+$0394]

|
005980C3   E8387AECFF             call    0045FB00
005980C8   8B45EC                 mov     eax, [ebp-$14]

|
005980CB   E87431E7FF             call    0040B244
005980D0   8BD0                   mov     edx, eax
005980D2   A1ACFB6300             mov     eax, dword ptr [$0063FBAC]
005980D7   8B00                   mov     eax, [eax]
005980D9   59                     pop     ecx

|
005980DA   E889A2FFFF             call    00592368
005980DF   84C0                   test    al, al
005980E1   740C                   jz      005980EF

* Possible String Reference to: 'Pronto!'
|
005980E3   B840815900             mov     eax, $00598140

* Reference to : TMessageForm._PROC_00450CC0()
|
005980E8   E8D38BEBFF             call    00450CC0
005980ED   EB0A                   jmp     005980F9

* Possible String Reference to: 'Problemas na Descarga!'
|
005980EF   B850815900             mov     eax, $00598150

* Reference to : TMessageForm._PROC_00450CC0()
|
005980F4   E8C78BEBFF             call    00450CC0

* Reference to control TfrmTeste.btnStatus : TButton
|
005980F9   8B83C8030000           mov     eax, [ebx+$03C8]
005980FF   66BEEBFF               mov     si, $FFEB

|
00598103   E8B4C9E6FF             call    00404ABC
00598108   33C0                   xor     eax, eax
0059810A   5A                     pop     edx
0059810B   59                     pop     ecx
0059810C   59                     pop     ecx
0059810D   648910                 mov     fs:[eax], edx

****** FINALLY
|
00598110   6832815900             push    $00598132
00598115   8D45EC                 lea     eax, [ebp-$14]
00598118   BA04000000             mov     edx, $00000004

|
0059811D   E8A6D7E6FF             call    004058C8
00598122   8D45FC                 lea     eax, [ebp-$04]

|
00598125   E87AD7E6FF             call    004058A4
0059812A   C3                     ret


|
0059812B   E964CFE6FF             jmp     00405094
00598130   EBE3                   jmp     00598115

****** END
|
00598132   5E                     pop     esi
00598133   5B                     pop     ebx
00598134   8BE5                   mov     esp, ebp
00598136   5D                     pop     ebp
00598137   C3                     ret

*)
end;

procedure TfrmTeste.Button3Click(Sender : TObject);
begin
(*
005979E0   55                     push    ebp
005979E1   8BEC                   mov     ebp, esp
005979E3   6A00                   push    $00
005979E5   6A00                   push    $00
005979E7   53                     push    ebx
005979E8   56                     push    esi
005979E9   8BD8                   mov     ebx, eax
005979EB   33C0                   xor     eax, eax
005979ED   55                     push    ebp

* Possible String Reference to: 'È÷ÊˇÎÎ^[YY]√'
|
005979EE   68827A5900             push    $00597A82

***** TRY
|
005979F3   64FF30                 push    dword ptr fs:[eax]
005979F6   648920                 mov     fs:[eax], esp
005979F9   6A00                   push    $00

* Reference to field TfrmTeste.OFFS_03D8
|
005979FB   8D83D8030000           lea     eax, [ebx+$03D8]
00597A01   50                     push    eax
00597A02   8D55FC                 lea     edx, [ebp-$04]

* Reference to control TfrmTeste.ERota : TEdit
|
00597A05   8B8398030000           mov     eax, [ebx+$0398]

|
00597A0B   E8F080ECFF             call    0045FB00
00597A10   8B45FC                 mov     eax, [ebp-$04]

|
00597A13   E82C38E7FF             call    0040B244
00597A18   50                     push    eax
00597A19   8D55F8                 lea     edx, [ebp-$08]

* Reference to control TfrmTeste.Egrupo : TEdit
|
00597A1C   8B8394030000           mov     eax, [ebx+$0394]

|
00597A22   E8D980ECFF             call    0045FB00
00597A27   8B45F8                 mov     eax, [ebp-$08]

|
00597A2A   E81538E7FF             call    0040B244
00597A2F   8BD0                   mov     edx, eax
00597A31   A130F96300             mov     eax, dword ptr [$0063F930]
00597A36   8B00                   mov     eax, [eax]
00597A38   59                     pop     ecx

|
00597A39   E81675FEFF             call    0057EF54
00597A3E   84C0                   test    al, al
00597A40   740C                   jz      00597A4E

* Possible String Reference to: 'Pronto!'
|
00597A42   B8987A5900             mov     eax, $00597A98

* Reference to : TMessageForm._PROC_00450CC0()
|
00597A47   E87492EBFF             call    00450CC0
00597A4C   EB0A                   jmp     00597A58

* Possible String Reference to: 'Problemas no Desfazer Carga!'
|
00597A4E   B8A87A5900             mov     eax, $00597AA8

* Reference to : TMessageForm._PROC_00450CC0()
|
00597A53   E86892EBFF             call    00450CC0

* Reference to control TfrmTeste.btnStatus : TButton
|
00597A58   8B83C8030000           mov     eax, [ebx+$03C8]
00597A5E   66BEEBFF               mov     si, $FFEB

|
00597A62   E855D0E6FF             call    00404ABC
00597A67   33C0                   xor     eax, eax
00597A69   5A                     pop     edx
00597A6A   59                     pop     ecx
00597A6B   59                     pop     ecx
00597A6C   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: '^[YY]√'
|
00597A6F   68897A5900             push    $00597A89
00597A74   8D45F8                 lea     eax, [ebp-$08]
00597A77   BA02000000             mov     edx, $00000002

|
00597A7C   E847DEE6FF             call    004058C8
00597A81   C3                     ret


|
00597A82   E90DD6E6FF             jmp     00405094
00597A87   EBEB                   jmp     00597A74

****** END
|
00597A89   5E                     pop     esi
00597A8A   5B                     pop     ebx
00597A8B   59                     pop     ecx
00597A8C   59                     pop     ecx
00597A8D   5D                     pop     ebp
00597A8E   C3                     ret

*)
end;

procedure TfrmTeste.Button2Click(Sender : TObject);
begin
(*
00597904   55                     push    ebp
00597905   8BEC                   mov     ebp, esp
00597907   6A00                   push    $00
00597909   53                     push    ebx
0059790A   56                     push    esi
0059790B   8BD8                   mov     ebx, eax
0059790D   33C0                   xor     eax, eax
0059790F   55                     push    ebp
00597910   6898795900             push    $00597998

***** TRY
|
00597915   64FF30                 push    dword ptr fs:[eax]
00597918   648920                 mov     fs:[eax], esp

* Reference to field TfrmTeste.OFFS_03D8
|
0059791B   8D83D8030000           lea     eax, [ebx+$03D8]
00597921   50                     push    eax
00597922   8D55FC                 lea     edx, [ebp-$04]

* Reference to control TfrmTeste.Egrupo : TEdit
|
00597925   8B8394030000           mov     eax, [ebx+$0394]

|
0059792B   E8D081ECFF             call    0045FB00
00597930   8B45FC                 mov     eax, [ebp-$04]

|
00597933   E80C39E7FF             call    0040B244
00597938   8BD0                   mov     edx, eax
0059793A   A168F76300             mov     eax, dword ptr [$0063F768]
0059793F   8B00                   mov     eax, [eax]

* Reference to control TfrmTeste.ProgressBar : TProgressBar
|
00597941   8B8BAC030000           mov     ecx, [ebx+$03AC]

|
00597947   E8FCCCFEFF             call    00584648
0059794C   84C0                   test    al, al
0059794E   740C                   jz      0059795C

* Possible String Reference to: 'Pronto!'
|
00597950   B8AC795900             mov     eax, $005979AC

* Reference to : TMessageForm._PROC_00450CC0()
|
00597955   E86693EBFF             call    00450CC0
0059795A   EB0A                   jmp     00597966

* Possible String Reference to: 'Problemas com Desfazer RecepÁ„o!'
|
0059795C   B8BC795900             mov     eax, $005979BC

* Reference to : TMessageForm._PROC_00450CC0()
|
00597961   E85A93EBFF             call    00450CC0
00597966   33D2                   xor     edx, edx

* Reference to control TfrmTeste.ProgressBar : TProgressBar
|
00597968   8B83AC030000           mov     eax, [ebx+$03AC]

* Reference to : TTabStrings._PROC_004C93E4()
|
0059796E   E8711AF3FF             call    004C93E4

* Reference to control TfrmTeste.btnStatus : TButton
|
00597973   8B83C8030000           mov     eax, [ebx+$03C8]
00597979   66BEEBFF               mov     si, $FFEB

|
0059797D   E83AD1E6FF             call    00404ABC
00597982   33C0                   xor     eax, eax
00597984   5A                     pop     edx
00597985   59                     pop     ecx
00597986   59                     pop     ecx
00597987   648910                 mov     fs:[eax], edx

****** FINALLY
|
0059798A   689F795900             push    $0059799F
0059798F   8D45FC                 lea     eax, [ebp-$04]

|
00597992   E80DDFE6FF             call    004058A4
00597997   C3                     ret


|
00597998   E9F7D6E6FF             jmp     00405094
0059799D   EBF0                   jmp     0059798F

****** END
|
0059799F   5E                     pop     esi
005979A0   5B                     pop     ebx
005979A1   59                     pop     ecx
005979A2   5D                     pop     ebp
005979A3   C3                     ret

*)
end;

procedure TfrmTeste.Button1Click(Sender : TObject);
begin
(*
0059782C   55                     push    ebp
0059782D   8BEC                   mov     ebp, esp
0059782F   6A00                   push    $00
00597831   6A00                   push    $00
00597833   53                     push    ebx
00597834   56                     push    esi
00597835   8BD8                   mov     ebx, eax
00597837   33C0                   xor     eax, eax
00597839   55                     push    ebp
0059783A   68C7785900             push    $005978C7

***** TRY
|
0059783F   64FF30                 push    dword ptr fs:[eax]
00597842   648920                 mov     fs:[eax], esp
00597845   8D45FC                 lea     eax, [ebp-$04]
00597848   50                     push    eax
00597849   8D55F8                 lea     edx, [ebp-$08]

* Reference to control TfrmTeste.Egrupo : TEdit
|
0059784C   8B8394030000           mov     eax, [ebx+$0394]

|
00597852   E8A982ECFF             call    0045FB00
00597857   8B45F8                 mov     eax, [ebp-$08]

|
0059785A   E8E539E7FF             call    0040B244
0059785F   8BD0                   mov     edx, eax
00597861   A168F76300             mov     eax, dword ptr [$0063F768]
00597866   8B00                   mov     eax, [eax]

* Reference to control TfrmTeste.ProgressBar : TProgressBar
|
00597868   8B8BAC030000           mov     ecx, [ebx+$03AC]

|
0059786E   E811BCFEFF             call    00583484
00597873   84C0                   test    al, al
00597875   740C                   jz      00597883

* Possible String Reference to: 'Pronto!'
|
00597877   B8DC785900             mov     eax, $005978DC

* Reference to : TMessageForm._PROC_00450CC0()
|
0059787C   E83F94EBFF             call    00450CC0
00597881   EB0A                   jmp     0059788D

* Possible String Reference to: 'Problemas na RecepÁ„o!'
|
00597883   B8EC785900             mov     eax, $005978EC

* Reference to : TMessageForm._PROC_00450CC0()
|
00597888   E83394EBFF             call    00450CC0
0059788D   33D2                   xor     edx, edx

* Reference to control TfrmTeste.ProgressBar : TProgressBar
|
0059788F   8B83AC030000           mov     eax, [ebx+$03AC]

* Reference to : TTabStrings._PROC_004C93E4()
|
00597895   E84A1BF3FF             call    004C93E4

* Reference to control TfrmTeste.btnStatus : TButton
|
0059789A   8B83C8030000           mov     eax, [ebx+$03C8]
005978A0   66BEEBFF               mov     si, $FFEB

|
005978A4   E813D2E6FF             call    00404ABC
005978A9   33C0                   xor     eax, eax
005978AB   5A                     pop     edx
005978AC   59                     pop     ecx
005978AD   59                     pop     ecx
005978AE   648910                 mov     fs:[eax], edx

****** FINALLY
|
005978B1   68CE785900             push    $005978CE
005978B6   8D45F8                 lea     eax, [ebp-$08]

|
005978B9   E8E6DFE6FF             call    004058A4
005978BE   8D45FC                 lea     eax, [ebp-$04]

|
005978C1   E8DEDFE6FF             call    004058A4
005978C6   C3                     ret


|
005978C7   E9C8D7E6FF             jmp     00405094
005978CC   EBE8                   jmp     005978B6

****** END
|
005978CE   5E                     pop     esi
005978CF   5B                     pop     ebx
005978D0   59                     pop     ecx
005978D1   59                     pop     ecx
005978D2   5D                     pop     ebp
005978D3   C3                     ret

*)
end;

procedure TfrmTeste.btnGerarClick(Sender : TObject);
begin
(*
00597724   55                     push    ebp
00597725   8BEC                   mov     ebp, esp
00597727   33C9                   xor     ecx, ecx
00597729   51                     push    ecx
0059772A   51                     push    ecx
0059772B   51                     push    ecx
0059772C   51                     push    ecx
0059772D   53                     push    ebx
0059772E   56                     push    esi
0059772F   8BD8                   mov     ebx, eax
00597731   33C0                   xor     eax, eax
00597733   55                     push    ebp
00597734   68F3775900             push    $005977F3

***** TRY
|
00597739   64FF30                 push    dword ptr fs:[eax]
0059773C   648920                 mov     fs:[eax], esp
0059773F   6A00                   push    $00
00597741   8D55FC                 lea     edx, [ebp-$04]

* Reference to control TfrmTeste.EPath : TEdit
|
00597744   8B83A0030000           mov     eax, [ebx+$03A0]

|
0059774A   E8B183ECFF             call    0045FB00
0059774F   8B45FC                 mov     eax, [ebp-$04]
00597752   50                     push    eax
00597753   8D55F8                 lea     edx, [ebp-$08]

* Reference to control TfrmTeste.EArquivo : TEdit
|
00597756   8B83CC030000           mov     eax, [ebx+$03CC]

|
0059775C   E89F83ECFF             call    0045FB00
00597761   8B45F8                 mov     eax, [ebp-$08]
00597764   50                     push    eax

* Reference to control TfrmTeste.ProgressBar : TProgressBar
|
00597765   8B83AC030000           mov     eax, [ebx+$03AC]
0059776B   50                     push    eax

* Reference to field TfrmTeste.OFFS_03D8
|
0059776C   8D83D8030000           lea     eax, [ebx+$03D8]
00597772   50                     push    eax
00597773   8D55F4                 lea     edx, [ebp-$0C]

* Reference to control TfrmTeste.ERota : TEdit
|
00597776   8B8398030000           mov     eax, [ebx+$0398]

|
0059777C   E87F83ECFF             call    0045FB00
00597781   8B45F4                 mov     eax, [ebp-$0C]

|
00597784   E8BB3AE7FF             call    0040B244
00597789   50                     push    eax
0059778A   8D55F0                 lea     edx, [ebp-$10]

* Reference to control TfrmTeste.Egrupo : TEdit
|
0059778D   8B8394030000           mov     eax, [ebx+$0394]

|
00597793   E86883ECFF             call    0045FB00
00597798   8B45F0                 mov     eax, [ebp-$10]

|
0059779B   E8A43AE7FF             call    0040B244
005977A0   8BD0                   mov     edx, eax
005977A2   A130F96300             mov     eax, dword ptr [$0063F930]
005977A7   8B00                   mov     eax, [eax]
005977A9   59                     pop     ecx

|
005977AA   E8256AFEFF             call    0057E1D4
005977AF   84C0                   test    al, al
005977B1   740C                   jz      005977BF

* Possible String Reference to: 'Pronto!'
|
005977B3   B808785900             mov     eax, $00597808

* Reference to : TMessageForm._PROC_00450CC0()
|
005977B8   E80395EBFF             call    00450CC0
005977BD   EB0A                   jmp     005977C9

* Possible String Reference to: 'Problemas na Carga!'
|
005977BF   B818785900             mov     eax, $00597818

* Reference to : TMessageForm._PROC_00450CC0()
|
005977C4   E8F794EBFF             call    00450CC0

* Reference to control TfrmTeste.btnStatus : TButton
|
005977C9   8B83C8030000           mov     eax, [ebx+$03C8]
005977CF   66BEEBFF               mov     si, $FFEB

|
005977D3   E8E4D2E6FF             call    00404ABC
005977D8   33C0                   xor     eax, eax
005977DA   5A                     pop     edx
005977DB   59                     pop     ecx
005977DC   59                     pop     ecx
005977DD   648910                 mov     fs:[eax], edx

****** FINALLY
|
005977E0   68FA775900             push    $005977FA
005977E5   8D45F0                 lea     eax, [ebp-$10]
005977E8   BA04000000             mov     edx, $00000004

|
005977ED   E8D6E0E6FF             call    004058C8
005977F2   C3                     ret


|
005977F3   E99CD8E6FF             jmp     00405094
005977F8   EBEB                   jmp     005977E5

****** END
|
005977FA   5E                     pop     esi
005977FB   5B                     pop     ebx
005977FC   8BE5                   mov     esp, ebp
005977FE   5D                     pop     ebp
005977FF   C3                     ret

*)
end;

procedure TfrmTeste._PROC_0059782D(Sender : TObject);
begin
(*
0059782D   8BEC                   mov     ebp, esp
0059782F   6A00                   push    $00
00597831   6A00                   push    $00
00597833   53                     push    ebx
00597834   56                     push    esi
00597835   8BD8                   mov     ebx, eax
00597837   33C0                   xor     eax, eax
00597839   55                     push    ebp
0059783A   68C7785900             push    $005978C7

***** TRY
|
0059783F   64FF30                 push    dword ptr fs:[eax]
00597842   648920                 mov     fs:[eax], esp
00597845   8D45FC                 lea     eax, [ebp-$04]
00597848   50                     push    eax
00597849   8D55F8                 lea     edx, [ebp-$08]

* Reference to control TfrmTeste.Egrupo : TEdit
|
0059784C   8B8394030000           mov     eax, [ebx+$0394]

|
00597852   E8A982ECFF             call    0045FB00
00597857   8B45F8                 mov     eax, [ebp-$08]

|
0059785A   E8E539E7FF             call    0040B244
0059785F   8BD0                   mov     edx, eax
00597861   A168F76300             mov     eax, dword ptr [$0063F768]
00597866   8B00                   mov     eax, [eax]

* Reference to control TfrmTeste.ProgressBar : TProgressBar
|
00597868   8B8BAC030000           mov     ecx, [ebx+$03AC]

|
0059786E   E811BCFEFF             call    00583484
00597873   84C0                   test    al, al
00597875   740C                   jz      00597883

* Possible String Reference to: 'Pronto!'
|
00597877   B8DC785900             mov     eax, $005978DC

* Reference to : TMessageForm._PROC_00450CC0()
|
0059787C   E83F94EBFF             call    00450CC0
00597881   EB0A                   jmp     0059788D

* Possible String Reference to: 'Problemas na RecepÁ„o!'
|
00597883   B8EC785900             mov     eax, $005978EC

* Reference to : TMessageForm._PROC_00450CC0()
|
00597888   E83394EBFF             call    00450CC0
0059788D   33D2                   xor     edx, edx

* Reference to control TfrmTeste.ProgressBar : TProgressBar
|
0059788F   8B83AC030000           mov     eax, [ebx+$03AC]

* Reference to : TTabStrings._PROC_004C93E4()
|
00597895   E84A1BF3FF             call    004C93E4

* Reference to control TfrmTeste.btnStatus : TButton
|
0059789A   8B83C8030000           mov     eax, [ebx+$03C8]
005978A0   66BEEBFF               mov     si, $FFEB

|
005978A4   E813D2E6FF             call    00404ABC
005978A9   33C0                   xor     eax, eax
005978AB   5A                     pop     edx
005978AC   59                     pop     ecx
005978AD   59                     pop     ecx
005978AE   648910                 mov     fs:[eax], edx

****** FINALLY
|
005978B1   68CE785900             push    $005978CE
005978B6   8D45F8                 lea     eax, [ebp-$08]

|
005978B9   E8E6DFE6FF             call    004058A4
005978BE   8D45FC                 lea     eax, [ebp-$04]

|
005978C1   E8DEDFE6FF             call    004058A4
005978C6   C3                     ret


|
005978C7   E9C8D7E6FF             jmp     00405094
005978CC   EBE8                   jmp     005978B6

****** END
|
005978CE   5E                     pop     esi
005978CF   5B                     pop     ebx
005978D0   59                     pop     ecx
005978D1   59                     pop     ecx
005978D2   5D                     pop     ebp
005978D3   C3                     ret

*)
end;

procedure TfrmTeste._PROC_005979E1(Sender : TObject);
begin
(*
005979E1   8BEC                   mov     ebp, esp
005979E3   6A00                   push    $00
005979E5   6A00                   push    $00
005979E7   53                     push    ebx
005979E8   56                     push    esi
005979E9   8BD8                   mov     ebx, eax
005979EB   33C0                   xor     eax, eax
005979ED   55                     push    ebp

* Possible String Reference to: 'È÷ÊˇÎÎ^[YY]√'
|
005979EE   68827A5900             push    $00597A82

***** TRY
|
005979F3   64FF30                 push    dword ptr fs:[eax]
005979F6   648920                 mov     fs:[eax], esp
005979F9   6A00                   push    $00

* Reference to field TfrmTeste.OFFS_03D8
|
005979FB   8D83D8030000           lea     eax, [ebx+$03D8]
00597A01   50                     push    eax
00597A02   8D55FC                 lea     edx, [ebp-$04]

* Reference to control TfrmTeste.ERota : TEdit
|
00597A05   8B8398030000           mov     eax, [ebx+$0398]

|
00597A0B   E8F080ECFF             call    0045FB00
00597A10   8B45FC                 mov     eax, [ebp-$04]

|
00597A13   E82C38E7FF             call    0040B244
00597A18   50                     push    eax
00597A19   8D55F8                 lea     edx, [ebp-$08]

* Reference to control TfrmTeste.Egrupo : TEdit
|
00597A1C   8B8394030000           mov     eax, [ebx+$0394]

|
00597A22   E8D980ECFF             call    0045FB00
00597A27   8B45F8                 mov     eax, [ebp-$08]

|
00597A2A   E81538E7FF             call    0040B244
00597A2F   8BD0                   mov     edx, eax
00597A31   A130F96300             mov     eax, dword ptr [$0063F930]
00597A36   8B00                   mov     eax, [eax]
00597A38   59                     pop     ecx

|
00597A39   E81675FEFF             call    0057EF54
00597A3E   84C0                   test    al, al
00597A40   740C                   jz      00597A4E

* Possible String Reference to: 'Pronto!'
|
00597A42   B8987A5900             mov     eax, $00597A98

* Reference to : TMessageForm._PROC_00450CC0()
|
00597A47   E87492EBFF             call    00450CC0
00597A4C   EB0A                   jmp     00597A58

* Possible String Reference to: 'Problemas no Desfazer Carga!'
|
00597A4E   B8A87A5900             mov     eax, $00597AA8

* Reference to : TMessageForm._PROC_00450CC0()
|
00597A53   E86892EBFF             call    00450CC0

* Reference to control TfrmTeste.btnStatus : TButton
|
00597A58   8B83C8030000           mov     eax, [ebx+$03C8]
00597A5E   66BEEBFF               mov     si, $FFEB

|
00597A62   E855D0E6FF             call    00404ABC
00597A67   33C0                   xor     eax, eax
00597A69   5A                     pop     edx
00597A6A   59                     pop     ecx
00597A6B   59                     pop     ecx
00597A6C   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: '^[YY]√'
|
00597A6F   68897A5900             push    $00597A89
00597A74   8D45F8                 lea     eax, [ebp-$08]
00597A77   BA02000000             mov     edx, $00000002

|
00597A7C   E847DEE6FF             call    004058C8
00597A81   C3                     ret


|
00597A82   E90DD6E6FF             jmp     00405094
00597A87   EBEB                   jmp     00597A74

****** END
|
00597A89   5E                     pop     esi
00597A8A   5B                     pop     ebx
00597A8B   59                     pop     ecx
00597A8C   59                     pop     ecx
00597A8D   5D                     pop     ebp
00597A8E   C3                     ret

*)
end;

procedure TfrmTeste._PROC_00597C91(Sender : TObject);
begin
(*
00597C91   8BEC                   mov     ebp, esp
00597C93   6A00                   push    $00
00597C95   53                     push    ebx
00597C96   8BD8                   mov     ebx, eax
00597C98   33C0                   xor     eax, eax
00597C9A   55                     push    ebp

* Possible String Reference to: 'ÈØ”ÊˇÎ[Y]√êUãÏ3…QQQQQQQâE¸3¿Uhˇ~Y'
|
00597C9B   68E07C5900             push    $00597CE0

***** TRY
|
00597CA0   64FF30                 push    dword ptr fs:[eax]
00597CA3   648920                 mov     fs:[eax], esp
00597CA6   8D55FC                 lea     edx, [ebp-$04]

* Reference to control TfrmTeste.Egrupo : TEdit
|
00597CA9   8B8394030000           mov     eax, [ebx+$0394]

|
00597CAF   E84C7EECFF             call    0045FB00
00597CB4   8B45FC                 mov     eax, [ebp-$04]

|
00597CB7   E88835E7FF             call    0040B244
00597CBC   8BD0                   mov     edx, eax
00597CBE   A168F76300             mov     eax, dword ptr [$0063F768]
00597CC3   8B00                   mov     eax, [eax]

|
00597CC5   E832A5FEFF             call    005821FC
00597CCA   33C0                   xor     eax, eax
00597CCC   5A                     pop     edx
00597CCD   59                     pop     ecx
00597CCE   59                     pop     ecx
00597CCF   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: '[Y]√êUãÏ3…QQQQQQQâE¸3¿Uhˇ~Y'
|
00597CD2   68E77C5900             push    $00597CE7
00597CD7   8D45FC                 lea     eax, [ebp-$04]

|
00597CDA   E8C5DBE6FF             call    004058A4
00597CDF   C3                     ret


|
00597CE0   E9AFD3E6FF             jmp     00405094
00597CE5   EBF0                   jmp     00597CD7

****** END
|
00597CE7   5B                     pop     ebx
00597CE8   59                     pop     ecx
00597CE9   5D                     pop     ebp
00597CEA   C3                     ret

*)
end;

procedure TfrmTeste._PROC_00598169(Sender : TObject);
begin
(*
00598169   8BEC                   mov     ebp, esp
0059816B   6A00                   push    $00
0059816D   6A00                   push    $00
0059816F   53                     push    ebx
00598170   56                     push    esi
00598171   8BD8                   mov     ebx, eax
00598173   33C0                   xor     eax, eax
00598175   55                     push    ebp
00598176   680F825900             push    $0059820F

***** TRY
|
0059817B   64FF30                 push    dword ptr fs:[eax]
0059817E   648920                 mov     fs:[eax], esp

* Reference to control TfrmTeste.ProgressBar : TProgressBar
|
00598181   8B83AC030000           mov     eax, [ebx+$03AC]
00598187   50                     push    eax

* Reference to field TfrmTeste.OFFS_03D8
|
00598188   8D83D8030000           lea     eax, [ebx+$03D8]
0059818E   50                     push    eax
0059818F   8D55FC                 lea     edx, [ebp-$04]

* Reference to control TfrmTeste.ERota : TEdit
|
00598192   8B8398030000           mov     eax, [ebx+$0398]

|
00598198   E86379ECFF             call    0045FB00
0059819D   8B45FC                 mov     eax, [ebp-$04]

|
005981A0   E89F30E7FF             call    0040B244
005981A5   50                     push    eax
005981A6   8D55F8                 lea     edx, [ebp-$08]

* Reference to control TfrmTeste.Egrupo : TEdit
|
005981A9   8B8394030000           mov     eax, [ebx+$0394]

|
005981AF   E84C79ECFF             call    0045FB00
005981B4   8B45F8                 mov     eax, [ebp-$08]

|
005981B7   E88830E7FF             call    0040B244
005981BC   8BD0                   mov     edx, eax
005981BE   A1B0FD6300             mov     eax, dword ptr [$0063FDB0]
005981C3   8B00                   mov     eax, [eax]
005981C5   59                     pop     ecx

|
005981C6   E81197FEFF             call    005818DC
005981CB   84C0                   test    al, al
005981CD   740C                   jz      005981DB

* Possible String Reference to: 'Pronto!'
|
005981CF   B824825900             mov     eax, $00598224

* Reference to : TMessageForm._PROC_00450CC0()
|
005981D4   E8E78AEBFF             call    00450CC0
005981D9   EB0A                   jmp     005981E5

* Possible String Reference to: 'Problemas no Desfazer da Transmiss„
|                                o!'
|
005981DB   B834825900             mov     eax, $00598234

* Reference to : TMessageForm._PROC_00450CC0()
|
005981E0   E8DB8AEBFF             call    00450CC0

* Reference to control TfrmTeste.btnStatus : TButton
|
005981E5   8B83C8030000           mov     eax, [ebx+$03C8]
005981EB   66BEEBFF               mov     si, $FFEB

|
005981EF   E8C8C8E6FF             call    00404ABC
005981F4   33C0                   xor     eax, eax
005981F6   5A                     pop     edx
005981F7   59                     pop     ecx
005981F8   59                     pop     ecx
005981F9   648910                 mov     fs:[eax], edx

****** FINALLY
|
005981FC   6816825900             push    $00598216
00598201   8D45F8                 lea     eax, [ebp-$08]
00598204   BA02000000             mov     edx, $00000002

|
00598209   E8BAD6E6FF             call    004058C8
0059820E   C3                     ret


|
0059820F   E980CEE6FF             jmp     00405094
00598214   EBEB                   jmp     00598201

****** END
|
00598216   5E                     pop     esi
00598217   5B                     pop     ebx
00598218   59                     pop     ecx
00598219   59                     pop     ecx
0059821A   5D                     pop     ebp
0059821B   C3                     ret

*)
end;

procedure TfrmTeste._PROC_00598346(Sender : TObject);
begin
(*
00598346   59                     pop     ecx
00598347   0000                   add     [eax], al

*)
end;

procedure TfrmTeste._PROC_0059837A(Sender : TObject);
begin
(*
0059837A   47                     inc     edi
0059837B   001C4B                 add     [ebx+ecx*2], bl
0059837E   40                     inc     eax
0059837F   000C8547005848         add     [$48580047+eax*4], cl
00598386   40                     inc     eax
00598387   00744840               add     [eax+ecx*2+$40], dh
0059838B   00905547008C           add     [eax+$8C004755], dl
00598391   844600                 test    [esi+$00], al
00598394   845B47                 test    [ebx+$47], bl
00598397   000C31                 add     [ecx+esi], cl
0059839A   42                     inc     edx
0059839B   006C5747               add     [edi+edx*2+$47], ch
0059839F   00B8574700F4           add     [eax+$F4004757], bh
005983A5   58                     pop     eax
005983A6   47                     inc     edi
005983A7   00E8                   add     al, ch
005983A9   F8                     clc
005983AA   45                     inc     ebp
005983AB   0094C542008462         add     [ebp+eax*8+$62840042], dl
005983B2   47                     inc     edi
005983B3   0070C2                 add     [eax-$3E], dh
005983B6   42                     inc     edx
005983B7   0070AB                 add     [eax-$55], dh
005983BA   47                     inc     edi
005983BB   00E0                   add     al, ah
005983BD   51                     push    ecx
005983BE   47                     inc     edi
005983BF   00B07E4600BC           add     [eax+$BC00467E], dh
005983C5   844600                 test    [esi+$00], al
005983C8   08844600B0EB45         or      [esi+eax*2+$45EBB000], al
005983CF   002C79                 add     [ecx+edi*2], ch
005983D2   46                     inc     esi
005983D3   00B85E4700B8           add     [eax+$B800475E], bh
005983D9   7546                   jnz     00598421
005983DB   00F0                   add     al, dh
005983DD   EA4500F4EA             jmp     $EAF40045
005983E2   45                     inc     ebp
005983E3   00AC5F47006C24         add     [edi+ebx*2+$246C0047], ch
005983EA   46                     inc     esi
005983EB   003CA8                 add     [eax+ebp*4], bh
005983EE   47                     inc     edi
005983EF   00CC                   add     ah, cl
005983F1   F8                     clc
005983F2   45                     inc     ebp
005983F3   002CED450058FA         add     [$FA580045+ebp*8], ch
005983FA   45                     inc     ebp
005983FB   00C8                   add     al, cl
005983FD   61                     popa
005983FE   47                     inc     edi
005983FF   008460470094FB         add     [eax+$FB940047], al
00598406   45                     inc     ebp
00598407   00C4                   add     ah, al
00598409   624700                 bound   eax, qword ptr [edi+$00]
0059840C   F0                     lock
0059840D   2446                   and     al, $46
0059840F   000C76                 add     [esi+esi*2], cl
00598412   46                     inc     esi
00598413   00CC                   add     ah, cl
00598415   7646                   jbe     0059845D
00598417   00C0                   add     al, al
00598419   7146                   jno     00598461
0059841B   00B0764600C8           add     [eax+$C8004676], dh
00598421   4F                     dec     edi
00598422   47                     inc     edi
00598423   0008                   add     [eax], cl
00598425   6A47                   push    $47
00598427   00A042460034           add     [eax+$34004642], ah
0059842D   7D47                   jnl     00598476
0059842F   004882                 add     [eax-$7E], cl
00598432   47                     inc     edi
00598433   00748047               add     [eax+eax*4+$47], dh
00598437   0038                   add     [eax], bh
00598439   43                     inc     ebx
0059843A   46                     inc     esi
0059843B   005C4346               add     [ebx+eax*2+$46], bl
0059843F   00C4                   add     ah, al
00598441   834700C8               add     dword ptr [edi+$00], -$38
00598445   844700                 test    [edi+$00], al
00598448   94                     xchg    eax, esp
00598449   41                     inc     ecx
0059844A   46                     inc     esi
0059844B   00A08C4600F8           add     [eax+$F800468C], ah
00598451   7746                   jnbe    00598499
00598453   0000                   add     [eax], al

00598455   8C4700                 mov     word ptr [edi+$00], es
00598458   148C                   adc     al, $8C
0059845A   46                     inc     esi
0059845B   006874                 add     [eax+$74], ch
0059845E   46                     inc     esi
0059845F   00648D46               add     [ebp+ecx*4+$46], ah
00598463   0088A34700A8           add     [eax+$A80047A3], cl
00598469   49                     dec     ecx
0059846A   47                     inc     edi
0059846B   00584C                 add     [eax+$4C], bl
0059846E   47                     inc     edi
0059846F   004093                 add     [eax-$6D], al
00598472   47                     inc     edi
00598473   00905647000C           add     [eax+$C004756], dl
00598479   57                     push    edi
0059847A   47                     inc     edi
0059847B   00D4                   add     ah, dl
0059847D   A7                     cmpsd
0059847E   47                     inc     edi
0059847F   00A45347006CA2         add     [ebx+edx*2+$A26C0047], ah
00598486   47                     inc     edi
00598487   009C86470060A4         add     [esi+eax*4+$A4600047], bl
0059848E   47                     inc     edi
0059848F   00C4                   add     ah, al
00598491   61                     popa
00598492   47                     inc     edi
00598493   00E0                   add     al, ah
00598495   865900                 xchg    [ecx+$00], bl
00598498   0300                   add     eax, [eax]
0059849A   FA                     cli
0059849B   845900                 test    [ecx+$00], bl
0059849E   800300                 add     byte ptr [ebx], $00
005984A1   0000                   add     [eax], al

*)
end;

end.