unit uFrmAlteraMovimento;

interface

uses
  Windows, Messages, SysUtils, Classes, Graphics,
  Controls, Forms, Dialogs, StdCtrls
type
  TfrmAlteraMovimento=class(TForm)
    pTop: TPanel;
    lVersion: TLabel;
    DBGRoteiros: TDBGrid;
    GroupBox2: TGroupBox;
    Label16: TLabel;
    EdVariacao: TEdit;
    GroupBox1: TGroupBox;
    rbtEnviadoPsion: TRadioButton;
    rbtNaoEnviadoPsion: TRadioButton;
    RetornoPsion: TRadioGroup;
    rbtRetornoPsion: TRadioButton;
    rbtNaoRetornoPsion: TRadioButton;
    GroupBox3: TGroupBox;
    rbtValidado: TRadioButton;
    rbtNaoValidado: TRadioButton;
    RadioGroup1: TRadioGroup;
    rbtProcessado: TRadioButton;
    rbtNaoProcessado: TRadioButton;
    pBottom: TPanel;
    sbtnSair: TSpeedButton;
    QrGrupos: TQuery;
    QrGrupoMovimento: TQuery;
    Tabelas: TTable;
    DSGrupoMoviemento: TDataSource;
    DSTabelas: TDataSource;
    grbRoteiro: TGroupBox;
    grbSelecao: TGroupBox;
    CBGrupo: TComboBox;
    Label1: TLabel;
    QrGruposRT_GRUPO: TIntegerField;
    QrGrupoMovimentoseq_roteiro: TFloatField;
    QrGrupoMovimentocod_referencia: TStringField;
    QrGrupoMovimentoind_enviado: TStringField;
    QrGrupoMovimentoind_obtido: TStringField;
    QrGrupoMovimentoind_validado: TStringField;
    QrGrupoMovimentoind_processado: TStringField;
    QrGrupoMovimentoRoteiro: TStringField;
    sbtnAlterar: TSpeedButton;
    sbtnConfirma: TSpeedButton;
    sbtnCancela: TSpeedButton;
    procedure FormShow(Sender : TObject);
    procedure FormClose(Sender : TObject);
    procedure CBGrupoDropDown(Sender : TObject);
    procedure sbtnSairClick(Sender : TObject);
    procedure sbtnCancelaClick(Sender : TObject);
    procedure sbtnConfirmaClick(Sender : TObject);
    procedure sbtnAlterarClick(Sender : TObject);
    procedure _PROC_006294F8(Sender : TObject);
    procedure _PROC_0062952E(Sender : TObject);
  private
    { Private declarations }
  public
    { Public declarations }
  end ;

var
  frmAlteraMovimento: TfrmAlteraMovimento;

{This file is generated by DeDe Ver 3.50.04 Copyright (c) 1999-2002 DaFixer}

implementation

{$R *.DFM}

procedure TfrmAlteraMovimento.FormShow(Sender : TObject);
begin
(*

* Possible String Reference to: 'Versão 8.0.0'
|
00629488   BAA4946200             mov     edx, $006294A4

* Reference to control TfrmAlteraMovimento.lVersion : TLabel
|
0062948D   8B8064030000           mov     eax, [eax+$0364]

|
00629493   E89866E3FF             call    0045FB30
00629498   C3                     ret

*)
end;

procedure TfrmAlteraMovimento.FormClose(Sender : TObject);
begin
(*
00629458   53                     push    ebx
00629459   8BD9                   mov     ebx, ecx
0062945B   8B153CF86300           mov     edx, [$0063F83C]
00629461   8B12                   mov     edx, [edx]
00629463   8B9260030000           mov     edx, [edx+$0360]
00629469   8B5234                 mov     edx, [edx+$34]
0062946C   52                     push    edx
0062946D   8B153CF86300           mov     edx, [$0063F83C]
00629473   8B12                   mov     edx, [edx]
00629475   B101                   mov     cl, $01

* Reference to field TfrmAlteraMovimento.OFFS_0008
|
00629477   8B4008                 mov     eax, [eax+$08]
0062947A   92                     xchg    eax, edx

|
0062947B   E808560000             call    0062EA88
00629480   C60302                 mov     byte ptr [ebx], $02
00629483   5B                     pop     ebx
00629484   C3                     ret

*)
end;

procedure TfrmAlteraMovimento.CBGrupoDropDown(Sender : TObject);
begin
(*
006292CC   55                     push    ebp
006292CD   8BEC                   mov     ebp, esp
006292CF   6A00                   push    $00
006292D1   53                     push    ebx
006292D2   56                     push    esi
006292D3   57                     push    edi
006292D4   8BD8                   mov     ebx, eax
006292D6   33C0                   xor     eax, eax
006292D8   55                     push    ebp
006292D9   68BA936200             push    $006293BA

***** TRY
|
006292DE   64FF30                 push    dword ptr fs:[eax]
006292E1   648920                 mov     fs:[eax], esp

* Reference to control TfrmAlteraMovimento.CBGrupo : TComboBox
|
006292E4   8B83CC030000           mov     eax, [ebx+$03CC]
006292EA   8B10                   mov     edx, [eax]

* Possible reference to virtual method TComboBox.OFFS_00E8
|
006292EC   FF92E8000000           call    dword ptr [edx+$00E8]

* Reference to control TfrmAlteraMovimento.QrGrupoMovimento : TQuery
|
006292F2   8B83B4030000           mov     eax, [ebx+$03B4]

|
006292F8   E81352E7FF             call    0049E510
006292FD   33C0                   xor     eax, eax
006292FF   55                     push    ebp
00629300   6834936200             push    $00629334

***** TRY
|
00629305   64FF30                 push    dword ptr fs:[eax]
00629308   648920                 mov     fs:[eax], esp
0062930B   A1C8FC6300             mov     eax, dword ptr [$0063FCC8]
00629310   8B00                   mov     eax, [eax]
00629312   8B80E8030000           mov     eax, [eax+$03E8]
00629318   B201                   mov     dl, $01
0062931A   8B08                   mov     ecx, [eax]
0062931C   FF5148                 call    dword ptr [ecx+$48]

* Reference to control TfrmAlteraMovimento.QrGrupoMovimento : TQuery
|
0062931F   8B83B4030000           mov     eax, [ebx+$03B4]

|
00629325   E8E651E7FF             call    0049E510
0062932A   33C0                   xor     eax, eax
0062932C   5A                     pop     edx
0062932D   59                     pop     ecx
0062932E   59                     pop     ecx
0062932F   648910                 mov     fs:[eax], edx
00629332   EB11                   jmp     00629345

|
00629334   E9A7BADDFF             jmp     00404DE0

|
00629339   E876BFDDFF             call    004052B4
0062933E   EB64                   jmp     006293A4

|
00629340   E86FBFDDFF             call    004052B4

****** END
|

* Reference to control TfrmAlteraMovimento.QrGrupos : TQuery
|
00629345   8B83B0030000           mov     eax, [ebx+$03B0]

|
0062934B   E8C051E7FF             call    0049E510

* Reference to control TfrmAlteraMovimento.QrGrupos : TQuery
|
00629350   8B83B0030000           mov     eax, [ebx+$03B0]

|
00629356   E8A151E7FF             call    0049E4FC
0062935B   EB2D                   jmp     0062938A
0062935D   8D55FC                 lea     edx, [ebp-$04]

* Reference to control TfrmAlteraMovimento.QrGruposRT_GRUPO : TIntegerField
|
00629360   8B83D4030000           mov     eax, [ebx+$03D4]
00629366   8B08                   mov     ecx, [eax]

* Possible reference to virtual method TIntegerField.OFFS_60
|
00629368   FF5160                 call    dword ptr [ecx+$60]
0062936B   8B55FC                 mov     edx, [ebp-$04]

* Reference to control TfrmAlteraMovimento.CBGrupo : TComboBox
|
0062936E   8B83CC030000           mov     eax, [ebx+$03CC]

* Reference to field TComboBox.OFFS_0284
|
00629374   8B8084020000           mov     eax, [eax+$0284]
0062937A   8B08                   mov     ecx, [eax]
0062937C   FF5138                 call    dword ptr [ecx+$38]

* Reference to control TfrmAlteraMovimento.QrGrupos : TQuery
|
0062937F   8B83B0030000           mov     eax, [ebx+$03B0]

|
00629385   E8967CE7FF             call    004A1020

* Reference to control TfrmAlteraMovimento.QrGrupos : TQuery
|
0062938A   8B83B0030000           mov     eax, [ebx+$03B0]

* Reference to field TQuery.OFFS_00A1
|
00629390   80B8A100000000         cmp     byte ptr [eax+$00A1], $00
00629397   74C4                   jz      0062935D

* Reference to control TfrmAlteraMovimento.QrGrupos : TQuery
|
00629399   8B83B0030000           mov     eax, [ebx+$03B0]

|
0062939F   E86C51E7FF             call    0049E510
006293A4   33C0                   xor     eax, eax
006293A6   5A                     pop     edx
006293A7   59                     pop     ecx
006293A8   59                     pop     ecx
006293A9   648910                 mov     fs:[eax], edx

****** FINALLY
|
006293AC   68C1936200             push    $006293C1
006293B1   8D45FC                 lea     eax, [ebp-$04]

|
006293B4   E8EBC4DDFF             call    004058A4
006293B9   C3                     ret


|
006293BA   E9D5BCDDFF             jmp     00405094
006293BF   EBF0                   jmp     006293B1

****** END
|
006293C1   5F                     pop     edi
006293C2   5E                     pop     esi
006293C3   5B                     pop     ebx
006293C4   59                     pop     ecx
006293C5   5D                     pop     ebp
006293C6   C3                     ret

*)
end;

procedure TfrmAlteraMovimento.sbtnSairClick(Sender : TObject);
begin
(*

* Reference to : TApplication._PROC_0047A1C8()
|
006294F0   E8D30CE5FF             call    0047A1C8
006294F5   C3                     ret

*)
end;

procedure TfrmAlteraMovimento.sbtnCancelaClick(Sender : TObject);
begin
(*
006293C8   56                     push    esi
006293C9   8BF0                   mov     esi, eax

* Reference to control TfrmAlteraMovimento.Tabelas : TTable
|
006293CB   8B86B8030000           mov     eax, [esi+$03B8]
006293D1   0FB6909D000000         movzx   edx, byte ptr [eax+$009D]
006293D8   80C2FE                 add     dl, $FE
006293DB   80EA02                 sub     dl, $02
006293DE   7308                   jnb     006293E8
006293E0   8B10                   mov     edx, [eax]

* Possible reference to virtual method TTable.OFFS_022C
|
006293E2   FF922C020000           call    dword ptr [edx+$022C]
006293E8   B201                   mov     dl, $01

* Reference to control TfrmAlteraMovimento.grbSelecao : TGroupBox
|
006293EA   8B86C8030000           mov     eax, [esi+$03C8]
006293F0   8B08                   mov     ecx, [eax]

* Possible reference to virtual method TGroupBox.OFFS_68
|
006293F2   FF5168                 call    dword ptr [ecx+$68]
006293F5   B201                   mov     dl, $01

* Reference to control TfrmAlteraMovimento.grbRoteiro : TGroupBox
|
006293F7   8B86C4030000           mov     eax, [esi+$03C4]
006293FD   8B08                   mov     ecx, [eax]

* Possible reference to virtual method TGroupBox.OFFS_68
|
006293FF   FF5168                 call    dword ptr [ecx+$68]
00629402   5E                     pop     esi
00629403   C3                     ret

*)
end;

procedure TfrmAlteraMovimento.sbtnConfirmaClick(Sender : TObject);
begin
(*
00629404   56                     push    esi
00629405   8BF0                   mov     esi, eax

* Reference to control TfrmAlteraMovimento.Tabelas : TTable
|
00629407   8B86B8030000           mov     eax, [esi+$03B8]
0062940D   0FB6909D000000         movzx   edx, byte ptr [eax+$009D]
00629414   80C2FE                 add     dl, $FE
00629417   80EA02                 sub     dl, $02
0062941A   731E                   jnb     0062943A
0062941C   8B10                   mov     edx, [eax]

* Possible reference to virtual method TTable.OFFS_0270
|
0062941E   FF9270020000           call    dword ptr [edx+$0270]

* Reference to control TfrmAlteraMovimento.QrGrupoMovimento : TQuery
|
00629424   8B86B4030000           mov     eax, [esi+$03B4]

|
0062942A   E8E150E7FF             call    0049E510

* Reference to control TfrmAlteraMovimento.QrGrupoMovimento : TQuery
|
0062942F   8B86B4030000           mov     eax, [esi+$03B4]

|
00629435   E8C250E7FF             call    0049E4FC
0062943A   B201                   mov     dl, $01

* Reference to control TfrmAlteraMovimento.grbSelecao : TGroupBox
|
0062943C   8B86C8030000           mov     eax, [esi+$03C8]
00629442   8B08                   mov     ecx, [eax]

* Possible reference to virtual method TGroupBox.OFFS_68
|
00629444   FF5168                 call    dword ptr [ecx+$68]
00629447   B201                   mov     dl, $01

* Reference to control TfrmAlteraMovimento.grbRoteiro : TGroupBox
|
00629449   8B86C4030000           mov     eax, [esi+$03C4]
0062944F   8B08                   mov     ecx, [eax]

* Possible reference to virtual method TGroupBox.OFFS_68
|
00629451   FF5168                 call    dword ptr [ecx+$68]
00629454   5E                     pop     esi
00629455   C3                     ret

*)
end;

procedure TfrmAlteraMovimento.sbtnAlterarClick(Sender : TObject);
begin
(*
006294B4   53                     push    ebx
006294B5   8BD8                   mov     ebx, eax
006294B7   33D2                   xor     edx, edx

* Reference to control TfrmAlteraMovimento.grbSelecao : TGroupBox
|
006294B9   8B83C8030000           mov     eax, [ebx+$03C8]
006294BF   8B08                   mov     ecx, [eax]

* Possible reference to virtual method TGroupBox.OFFS_68
|
006294C1   FF5168                 call    dword ptr [ecx+$68]
006294C4   33D2                   xor     edx, edx

* Reference to control TfrmAlteraMovimento.grbRoteiro : TGroupBox
|
006294C6   8B83C4030000           mov     eax, [ebx+$03C4]
006294CC   8B08                   mov     ecx, [eax]

* Possible reference to virtual method TGroupBox.OFFS_68
|
006294CE   FF5168                 call    dword ptr [ecx+$68]

* Reference to control TfrmAlteraMovimento.Tabelas : TTable
|
006294D1   8B83B8030000           mov     eax, [ebx+$03B8]
006294D7   0FB6909D000000         movzx   edx, byte ptr [eax+$009D]
006294DE   80C2FE                 add     dl, $FE
006294E1   80EA02                 sub     dl, $02
006294E4   7205                   jb      006294EB

|
006294E6   E8317CE7FF             call    004A111C
006294EB   5B                     pop     ebx
006294EC   C3                     ret

*)
end;

procedure TfrmAlteraMovimento._PROC_006294F8(Sender : TObject);
begin
(*
006294F8   44                     inc     esp
006294F9   95                     xchg    eax, ebp
006294FA   6200                   bound   eax, qword ptr [eax]
006294FC   0000                   add     [eax], al

*)
end;

procedure TfrmAlteraMovimento._PROC_0062952E(Sender : TObject);
begin
(*
0062952E   47                     inc     edi
0062952F   001C4B                 add     [ebx+ecx*2], bl
00629532   40                     inc     eax
00629533   000C8547005848         add     [$48580047+eax*4], cl
0062953A   40                     inc     eax
0062953B   00744840               add     [eax+ecx*2+$40], dh
0062953F   00905547008C           add     [eax+$8C004755], dl
00629545   844600                 test    [esi+$00], al
00629548   845B47                 test    [ebx+$47], bl
0062954B   000C31                 add     [ecx+esi], cl
0062954E   42                     inc     edx
0062954F   006C5747               add     [edi+edx*2+$47], ch
00629553   00B8574700F4           add     [eax+$F4004757], bh
00629559   58                     pop     eax
0062955A   47                     inc     edi
0062955B   00E8                   add     al, ch
0062955D   F8                     clc
0062955E   45                     inc     ebp
0062955F   0094C542008462         add     [ebp+eax*8+$62840042], dl
00629566   47                     inc     edi
00629567   0070C2                 add     [eax-$3E], dh
0062956A   42                     inc     edx
0062956B   0070AB                 add     [eax-$55], dh
0062956E   47                     inc     edi
0062956F   00E0                   add     al, ah
00629571   51                     push    ecx
00629572   47                     inc     edi
00629573   00B07E4600BC           add     [eax+$BC00467E], dh
00629579   844600                 test    [esi+$00], al
0062957C   08844600B0EB45         or      [esi+eax*2+$45EBB000], al
00629583   002C79                 add     [ecx+edi*2], ch
00629586   46                     inc     esi
00629587   00B85E4700B8           add     [eax+$B800475E], bh
0062958D   7546                   jnz     006295D5
0062958F   00F0                   add     al, dh
00629591   EA4500F4EA             jmp     $EAF40045
00629596   45                     inc     ebp
00629597   00AC5F47006C24         add     [edi+ebx*2+$246C0047], ch
0062959E   46                     inc     esi
0062959F   003CA8                 add     [eax+ebp*4], bh
006295A2   47                     inc     edi
006295A3   00CC                   add     ah, cl
006295A5   F8                     clc
006295A6   45                     inc     ebp
006295A7   002CED450058FA         add     [$FA580045+ebp*8], ch
006295AE   45                     inc     ebp
006295AF   00C8                   add     al, cl
006295B1   61                     popa
006295B2   47                     inc     edi
006295B3   008460470094FB         add     [eax+$FB940047], al
006295BA   45                     inc     ebp
006295BB   00C4                   add     ah, al
006295BD   624700                 bound   eax, qword ptr [edi+$00]
006295C0   F0                     lock
006295C1   2446                   and     al, $46
006295C3   000C76                 add     [esi+esi*2], cl
006295C6   46                     inc     esi
006295C7   00CC                   add     ah, cl
006295C9   7646                   jbe     00629611
006295CB   00C0                   add     al, al
006295CD   7146                   jno     00629615
006295CF   00B0764600C8           add     [eax+$C8004676], dh
006295D5   4F                     dec     edi
006295D6   47                     inc     edi
006295D7   0008                   add     [eax], cl
006295D9   6A47                   push    $47
006295DB   00A042460034           add     [eax+$34004642], ah
006295E1   7D47                   jnl     0062962A
006295E3   004882                 add     [eax-$7E], cl
006295E6   47                     inc     edi
006295E7   00748047               add     [eax+eax*4+$47], dh
006295EB   0038                   add     [eax], bh
006295ED   43                     inc     ebx
006295EE   46                     inc     esi
006295EF   005C4346               add     [ebx+eax*2+$46], bl
006295F3   00C4                   add     ah, al
006295F5   834700C8               add     dword ptr [edi+$00], -$38
006295F9   844700                 test    [edi+$00], al
006295FC   94                     xchg    eax, esp
006295FD   41                     inc     ecx
006295FE   46                     inc     esi
006295FF   00A08C4600F8           add     [eax+$F800468C], ah
00629605   7746                   jnbe    0062964D
00629607   0000                   add     [eax], al

00629609   8C4700                 mov     word ptr [edi+$00], es
0062960C   148C                   adc     al, $8C
0062960E   46                     inc     esi
0062960F   006874                 add     [eax+$74], ch
00629612   46                     inc     esi
00629613   00648D46               add     [ebp+ecx*4+$46], ah
00629617   0088A34700A8           add     [eax+$A80047A3], cl
0062961D   49                     dec     ecx
0062961E   47                     inc     edi
0062961F   00584C                 add     [eax+$4C], bl
00629622   47                     inc     edi
00629623   004093                 add     [eax-$6D], al
00629626   47                     inc     edi
00629627   00905647000C           add     [eax+$C004756], dl
0062962D   57                     push    edi
0062962E   47                     inc     edi
0062962F   00D4                   add     ah, dl
00629631   A7                     cmpsd
00629632   47                     inc     edi
00629633   00A45347006CA2         add     [ebx+edx*2+$A26C0047], ah
0062963A   47                     inc     edi
0062963B   009C86470060A4         add     [esi+eax*4+$A4600047], bl
00629642   47                     inc     edi
00629643   00C4                   add     ah, al
00629645   61                     popa
00629646   47                     inc     edi
00629647   000E                   add     [esi], cl
00629649   0000                   add     [eax], al

0062964B   0000                   add     [eax], al

0062964D   0001                   add     [ecx], al
0062964F   0000                   add     [eax], al

*)
end;

end.