<div id="container">
    <h2><?=$this->escape($this->title);?></h2>
    <div id="mid">
        <form name="frmcontroller" id="frmcontroller" action="<?= $this->baseUrl."/".$this->modulo ?>/controller/<?= $this->action;?>" method="post">
            <fieldset>
                <div class="fieldLinha2">
                    <?=$this->label('idController',$this->descricaoCampos['idController']);?><br />					                    
					<?=$this->formText('idController', $this->idController, array('class'=>'medTxtArea', 'maxlength'=>''));?>
                </div>
                <div class="fieldLinha2">
                    <?=$this->label('nameController',$this->descricaoCampos['nameController']);?><br />					                    
					<?=$this->formText('nameController', $this->nameController, array('class'=>'medTxtArea', 'maxlength'=>''));?>
                </div>
            </fieldset>
            <div class="fieldBtn">
                <?= $this->acao($this->botao_submit); ?>
            </div>
        </form>
    </div>
</div>