<div id="container">
    <h2><?=$this->escape($this->title);?></h2>
    <div id="mid">
        <form name="frmetinia" id="frmetinia" action="<?= $this->baseUrl."/".$this->modulo ?>/etinia/<?= $this->action;?>" method="post">
            <fieldset>
                <div class="fieldLinha2">
                    <?=$this->label('idEtinia',$this->descricaoCampos['idEtinia']);?><br />					                    
					<?=$this->formText('idEtinia', $this->idEtinia, array('class'=>'medTxtArea', 'maxlength'=>''));?>
                </div>
                <div class="fieldLinha2">
                    <?=$this->label('nameEtinia',$this->descricaoCampos['nameEtinia']);?><br />					                    
					<?=$this->formText('nameEtinia', $this->nameEtinia, array('class'=>'medTxtArea', 'maxlength'=>''));?>
                </div>
            </fieldset>
            <div class="fieldBtn">
                <?= $this->acao($this->botao_submit); ?>
            </div>
        </form>
    </div>
</div>