<div id="container">
    <h2><?=$this->escape($this->title);?></h2>
    <div id="mid">
        <form name="frminteresse" id="frminteresse" action="<?= $this->baseUrl."/".$this->modulo ?>/interesse/<?= $this->action;?>" method="post">
            <fieldset>
                <div class="fieldLinha2">
                    <?=$this->label('idInteresse',$this->descricaoCampos['idInteresse']);?><br />					                    
					<?=$this->formText('idInteresse', $this->idInteresse, array('class'=>'medTxtArea', 'maxlength'=>''));?>
                </div>
                <div class="fieldLinha2">
                    <?=$this->label('Descricao',$this->descricaoCampos['Descricao']);?><br />					                    
					<?=$this->formText('Descricao', $this->Descricao, array('class'=>'medTxtArea', 'maxlength'=>''));?>
                </div>
                <div class="fieldLinha2">
                    <?=$this->label('idTipoInteresse',$this->descricaoCampos['idTipoInteresse']);?><br />					                    
					<?=$this->formText('idTipoInteresse', $this->idTipoInteresse, array('class'=>'medTxtArea', 'maxlength'=>''));?>
                </div>
                <div class="fieldLinha2">
                    <?=$this->label('idPerfil',$this->descricaoCampos['idPerfil']);?><br />					                    
					<?=$this->formText('idPerfil', $this->idPerfil, array('class'=>'medTxtArea', 'maxlength'=>''));?>
                </div>
            </fieldset>
            <div class="fieldBtn">
                <?= $this->acao($this->botao_submit); ?>
            </div>
        </form>
    </div>
</div>