<html lang="pt-BR">
    <head>
		<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1" />
		<meta name="description" content="Rede Social" />
		<meta name="author" content="Alexis Moura" />
		<title><?php echo $this->escape($this->title); ?></title>
		<link rel="stylesheet" type="text/css" media="screen" href="<?=$this->baseUrl;?>/zend/public/styles/global.css" title="Estilo global" />
		
		<script type="text/javascript" src="<?php echo $this->baseUrl;?>/zend/public/scripts/comum.js"></script>
		<script type="text/javascript" src="<?php echo $this->baseUrl;?>/zend/public/scripts/funcoesAjax.js"></script>
		<script type="text/javascript" src="<?php echo $this->baseUrl;?>/zend/public/scripts/jquery-1.6.2.min.js"></script>
		<script type="text/javascript" src="<?php echo $this->baseUrl;?>/zend/public/scripts/jquery-ui-1.8.15.custom.min.js"></script>
		<script type="text/javascript" src="<?php echo $this->baseUrl;?>/zend/public/scripts/jquery.tools.min.js"></script>
		<script type="text/javascript" src="<?php echo $this->baseUrl;?>/zend/public/scripts/jquery.lightbox-0.5.min.js"></script>
		<script type="text/javascript" src="<?php echo $this->baseUrl;?>/zend/public/scripts/jquery.ui.datepicker-pt-BR.js"></script>
		<script type="text/javascript" src="<?php echo $this->baseUrl;?>/zend/public/scripts/micoxUpload2.js"></script>
		<!--
			Script para exibir status de alguma chamada feita via ajax, atravs do carregamento de um gif animado
		-->
		<style type="text/css">
		#preload {
			display:none;
			position:fixed;
			_position:absolute;
			z-index:100;
			top:50%;
			left:50%;
		}
		</style>
		<div id="preload">
			<img src="<?php echo $this->baseUrl;?>/zend/public/images/loading.gif" alt="carregando" name="imgcarregando" id="imgcarregando" title="O conte&uacute;do est&aacute; sendo carregado." style/>
		</div>
    </head>
    <body>
		<script type="text/javascript" src="<?php echo $this->baseUrl;?>/zend/public/scripts/wz_tooltip.js"></script>
        <div class="main">
            <div class="header">
                <div class="clean-header">
					<img alt="Site" src="" class="logo">
					<?php if(!Zend_Auth::getInstance()->hasIdentity()){?>
						<span class="signup-button">
							<a href="<?php echo $this->baseUrl;?>/default/auth/login" class="button-red button" id="link-signup">
							Entrar
							</a>
						</span>
						<span class="signup-button">
							É gratuito crie já sua conta
							<a href="<?php echo $this->baseUrl;?>/redesocial/register/register" class="button-red button" id="link-signup">
							Criar uma conta
							</a>
						</span>
            		<? }else{?>
						<span class="signup-button">
							<a href="<?php echo $this->baseUrl;?>/default/auth/logout" class="button-red button" id="link-signup">
							Logout
							</a>
						</span>
					<? }?>
                </div>
            </div>
			<div class="messenger">
				<span id="msg">
					<?php echo $this->mensagem($this->mensagens);?>
				</span>
				<span id="msgErro">
					<?php echo $this->erro($this->errors,$this->descricaoCampos);?>
				</span>
			</div>
            <div class="center">
				<div class="left">
					<? echo $this->action('gerar','menu', null, array());?>
				</div>
				<div class="right">