<!--div id="pesquisaAjax_<?php echo $this->controller.$this->action;?>" class="pesquisaAjax"-->
    <img src="<?php echo $this->baseUrl;?>/zend/public/images/close.png" alt="fechar" title="Fechar" border="0" onClick="$('<?php echo $this->controller.$this->action;?>').style.display = 'none';" class="fechar"/>
    <div id="containerPesquisaAjax_<?php echo $this->controller.$this->action;?>">
        <h2><?php echo  $this->escape($this->title); ?></h2>

        <div id="mid_<?php echo $this->controller.$this->action;?>">
            <table  style="width: 99%;"  border="0" cellpadding="0" cellspacing="0">
                <tr>
                   <th width="20">
                        <span id="botao-abrir-pesquisa<?php echo $this->controller.$this->action;?>" style="display:<?php echo $this->mostraFiltro=='none'?'block':'none'?>">
                             <img src="<?php echo $this->baseUrl?>/zend/public/images/setaDown.gif" class='inputImg' title='Abrir pesquisa' alt='abrirrPesquisa' onClick="document.getElementById('criterio-pesquisa<?php echo $this->controller.$this->action;?>').style.display = 'block';document.getElementById('botao-fechar-pesquisa<?php echo $this->controller.$this->action;?>').style.display = 'block';document.getElementById('botao-abrir-pesquisa<?php echo $this->controller.$this->action;?>').style.display = 'none';">
                        </span>
                        <span id="botao-fechar-pesquisa<?php echo $this->controller.$this->action;?>" style="display:<?php echo $this->mostraFiltro?>" >
                            <img src="<?php echo $this->baseUrl?>/zend/public/images/setaUp.gif" 'class'='inputImg' 'title'='Fechar pesquisa' 'alt'='fecharPesquisa' onClick="document.getElementById('criterio-pesquisa<?php echo $this->controller.$this->action;?>').style.display = 'none';document.getElementById('botao-fechar-pesquisa<?php echo $this->controller.$this->action;?>').style.display = 'none';document.getElementById('botao-abrir-pesquisa<?php echo $this->controller.$this->action;?>').style.display = 'block';">
                        </span>
                    </th>
                    <th>
                        Crit&eacute;rios da Pesquisa
                    </th>
                </tr>
            </table>
            <span id="criterio-pesquisa<?php echo $this->controller.$this->action;?>" style="display:<?php echo $this->mostraFiltro?>">
                <!--Tabela de filtros para pesquisa -->
                <?php echo $this->getHelper('PesquisaAjax')->filtro;?>
            </span>
            <!--Tabela de resultados da pesquisa -->
            <?php echo $this->getHelper('PesquisaAjax')->tabela;?>
            <div class="fieldBtn">
                <?php echo  $this->acao($this->botao_submit); ?>
            </div><!--/fieldBtn -->
        </div><!--/mid -->
    </div><!--/container -->
<!--/div-->
<link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->baseUrl;?>/zend/public/styles/pesquisaajax.css"/>
