<div id="container">
    <h2><?=$this->escape($this->title);?></h2>
    <div id="mid">
        <form name="frmcabelo" id="frmcabelo" action="<?= $this->baseUrl."/".$this->modulo ?>/cabelo/<?= $this->action;?>" method="post">
            <fieldset>
                <div class="fieldLinha2">
                    <?=$this->label('idCabelo',$this->descricaoCampos['idCabelo']);?><br />					                    
					<?=$this->formText('idCabelo', $this->idCabelo, array('class'=>'medTxtArea', 'maxlength'=>''));?>
                </div>
                <div class="fieldLinha2">
                    <?=$this->label('nameCabelo',$this->descricaoCampos['nameCabelo']);?><br />					                    
					<?=$this->formText('nameCabelo', $this->nameCabelo, array('class'=>'medTxtArea', 'maxlength'=>''));?>
                </div>
            </fieldset>
            <div class="fieldBtn">
                <?= $this->acao($this->botao_submit); ?>
            </div>
        </form>
    </div>
</div>