<div id="container">
    <h2><?=$this->escape($this->title);?></h2>
    <div id="mid">
        <form name="frmcidade" id="frmcidade" action="<?= $this->baseUrl."/".$this->modulo ?>/cidade/<?= $this->action;?>" method="post">
            <fieldset>
                <div class="fieldLinha2">
                    <?=$this->label('idCidade',$this->descricaoCampos['idCidade']);?><br />					                    
					<?=$this->formText('idCidade', $this->idCidade, array('class'=>'medTxtArea', 'maxlength'=>''));?>
                </div>
                <div class="fieldLinha2">
                    <?=$this->label('nameCidade',$this->descricaoCampos['nameCidade']);?><br />					                    
					<?=$this->formText('nameCidade', $this->nameCidade, array('class'=>'medTxtArea', 'maxlength'=>''));?>
                </div>
                <div class="fieldLinha2">
                    <?=$this->label('idEstado',$this->descricaoCampos['idEstado']);?><br />					                    
					<?=$this->formText('idEstado', $this->idEstado, array('class'=>'medTxtArea', 'maxlength'=>''));?>
                </div>
            </fieldset>
            <div class="fieldBtn">
                <?= $this->acao($this->botao_submit); ?>
            </div>
        </form>
    </div>
</div>