<div id="container">
    <h2><?=$this->escape($this->title);?></h2>
    <div id="mid">
        <form name="frmbairro" id="frmbairro" action="<?= $this->baseUrl."/".$this->modulo ?>/bairro/<?= $this->action;?>" method="post">
            <fieldset>
                <div class="fieldLinha2">
                    <?=$this->label('idBairro',$this->descricaoCampos['idBairro']);?><br />					                    
					<?=$this->formText('idBairro', $this->idBairro, array('class'=>'medTxtArea', 'maxlength'=>''));?>
                </div>
                <div class="fieldLinha2">
                    <?=$this->label('nomeBairro',$this->descricaoCampos['nomeBairro']);?><br />					                    
					<?=$this->formText('nomeBairro', $this->nomeBairro, array('class'=>'medTxtArea', 'maxlength'=>''));?>
                </div>
            </fieldset>
            <div class="fieldBtn">
                <?= $this->acao($this->botao_submit); ?>
            </div>
        </form>
    </div>
</div>