<?php// echo $this->render('header.phtml'); ?>
<div id="container">
    <h2><?php echo $this->escape($this->title); ?></h2>

    <div id="mid">
		<span id="msg">
            <?php echo $this->mensagem($this->mensagem);?>
		</span>
        <span id="msgErro">
            <?php echo $this->erro($this->errors,$this->descricaoCampos);?>
		</span>

        <form action="<?php echo $this->baseUrl ?>/index/login" method="post">
            <div class="fieldLinha">
            	<?php echo $this->label("nome_ent","Entidade");?>
                <select name="cod_ent">
                <?php foreach($this->entidades as $entidade) {?>
                    <option label="<?echo $this->escape($entidade->EP_DESCRICAO);?>" value="<?echo $this->escape($entidade->EP_ENTIDADE);?>"><?echo $this->escape($entidade->EP_ENTIDADE.' - '.$entidade->EP_DESCRICAO);?></option>
                <?php } ?>
                </select>
            </div><!--/fieldLinha -->

            <div class="fieldLinha">
            	<?php echo $this->label("username","Matr&iacute;cula");?>
                <?php echo $this->formText('username', $this->username, array("class"=>"smallTxtArea","onkeyup"=>"javascritp:this.value=this.value.toUpperCase();","style"=>"text-transform:uppercase;"));?>
                <?php echo $this->label("password","Senha")?>
                <?php echo $this->formPassword('password', $this->password, array("class"=>"smallTxtArea"));?>
            </div><!--/fieldLinha -->

            <div id="fieldBtn">
                <input type="submit" name="login" value="Login" class="btn" />
            </div><!--/fieldBtn -->
        </form>
    </div><!--/mid -->
</div><!--/container -->
<?php// echo $this->render('footer.phtml'); ?>
