///////////////////////////////////////////////////////////
//  Zend_Db_Statement_Pdo_Oci.cs
//  Implementation of the Class Zend_Db_Statement_Pdo_Oci
//  Generated by Enterprise Architect
//  Created on:      08-jun-2011 22:13:31
//  Original author: alexis
///////////////////////////////////////////////////////////




using Zend.Db.Statement;
namespace Zend.Db.Statement.Pdo {
	/// <summary>
	/// Proxy class to wrap a PDOStatement object for IBM Databases. Matches the
	/// interface of PDOStatement.  All methods simply proxy to the matching method in
	/// PDOStatement.  PDOExceptions thrown by PDOStatement are re-thrown as
	/// Zend_Db_Statement_Exception.
	///          @category   Zend
	///          @package    Zend_Db
	///          @subpackage Statement
	///          @copyright  Copyright (c) 2005-2010 Zend Technologies USA Inc. (http:
	/// //www.zend.com)
	///          @license    http://framework.zend.com/license/new-bsd     New BSD
	/// License
	/// </summary>
	public class Zend_Db_Statement_Pdo_Oci : Zend_Db_Statement_Pdo {

		public Zend_Db_Statement_Pdo_Oci(){

		}

		~Zend_Db_Statement_Pdo_Oci(){

		}

		public override void Dispose(){

		}

		/// <summary>
		/// Fetches a row from the result set.
		/// </summary>
		/// <param>int $style  OPTIONAL Fetch mode for this fetch operation.</param>
		/// <param>int $cursor OPTIONAL Absolute, relative, or other.</param>
		/// <param>int $offset OPTIONAL Number for absolute or relative cursors.</param>
		/// <param>mixed Array, object, or scalar depending on fetch mode.</param>
		/// <param name="style"></param>
		/// <param name="cursor"></param>
		/// <param name="offset"></param>
		public var fetch(var style, var cursor, var offset){

			return null;
		}

		/// <summary>
		/// Returns an array containing all of the result set rows.  Behaves like parent,
		/// but if limit() is used, the final result removes the extra column
		/// 'zend_db_rownum'
		/// </summary>
		/// <param>int $style OPTIONAL Fetch mode.</param>
		/// <param>int $col   OPTIONAL Column number, if fetch mode is by column.</param>
		/// <param>array Collection of rows, each in a format by the fetch mode.</param>
		/// <param name="style"></param>
		/// <param name="col"></param>
		public var fetchAll(var style, var col){

			return null;
		}

	}//end Zend_Db_Statement_Pdo_Oci

}//end namespace Pdo