//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.CompactFramework.Design.Data, Version 2.0.50727.4952.
// 
namespace SPCadMobileSync.SPCadServices {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SPCadServicesSoap", Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AuditoriaSuper))]
    public partial class SPCadServices : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public SPCadServices() {
            this.Url = "http://localhost/SPCad_WS/SPCadServices.asmx";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HelloWorld", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginHelloWorld(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("HelloWorld", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public string EndHelloWorld(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getDateDBServer", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.DateTime getDateDBServer(Autenticantion auth) {
            object[] results = this.Invoke("getDateDBServer", new object[] {
                        auth});
            return ((System.DateTime)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetDateDBServer(Autenticantion auth, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getDateDBServer", new object[] {
                        auth}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.DateTime EndgetDateDBServer(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.DateTime)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetListFuncionario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Funcionario[] GetListFuncionario(Autenticantion auth) {
            object[] results = this.Invoke("GetListFuncionario", new object[] {
                        auth});
            return ((Funcionario[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetListFuncionario(Autenticantion auth, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetListFuncionario", new object[] {
                        auth}, callback, asyncState);
        }
        
        /// <remarks/>
        public Funcionario[] EndGetListFuncionario(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((Funcionario[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetListOcorrencia", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Ocorrencia[] GetListOcorrencia(Autenticantion auth) {
            object[] results = this.Invoke("GetListOcorrencia", new object[] {
                        auth});
            return ((Ocorrencia[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetListOcorrencia(Autenticantion auth, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetListOcorrencia", new object[] {
                        auth}, callback, asyncState);
        }
        
        /// <remarks/>
        public Ocorrencia[] EndGetListOcorrencia(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((Ocorrencia[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetListRamoAtividade", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public RamoAtividade[] GetListRamoAtividade(Autenticantion auth) {
            object[] results = this.Invoke("GetListRamoAtividade", new object[] {
                        auth});
            return ((RamoAtividade[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetListRamoAtividade(Autenticantion auth, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetListRamoAtividade", new object[] {
                        auth}, callback, asyncState);
        }
        
        /// <remarks/>
        public RamoAtividade[] EndGetListRamoAtividade(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((RamoAtividade[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetListCondicaoImovel", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CondicaoImovel[] GetListCondicaoImovel(Autenticantion auth) {
            object[] results = this.Invoke("GetListCondicaoImovel", new object[] {
                        auth});
            return ((CondicaoImovel[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetListCondicaoImovel(Autenticantion auth, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetListCondicaoImovel", new object[] {
                        auth}, callback, asyncState);
        }
        
        /// <remarks/>
        public CondicaoImovel[] EndGetListCondicaoImovel(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((CondicaoImovel[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetListTipoComplemento", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TipoComplemento[] GetListTipoComplemento(Autenticantion auth) {
            object[] results = this.Invoke("GetListTipoComplemento", new object[] {
                        auth});
            return ((TipoComplemento[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetListTipoComplemento(Autenticantion auth, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetListTipoComplemento", new object[] {
                        auth}, callback, asyncState);
        }
        
        /// <remarks/>
        public TipoComplemento[] EndGetListTipoComplemento(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((TipoComplemento[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetListLocalizacaoPadrao", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public LocalizacaoPadrao[] GetListLocalizacaoPadrao(Autenticantion auth) {
            object[] results = this.Invoke("GetListLocalizacaoPadrao", new object[] {
                        auth});
            return ((LocalizacaoPadrao[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetListLocalizacaoPadrao(Autenticantion auth, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetListLocalizacaoPadrao", new object[] {
                        auth}, callback, asyncState);
        }
        
        /// <remarks/>
        public LocalizacaoPadrao[] EndGetListLocalizacaoPadrao(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((LocalizacaoPadrao[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetListTipoPadrao", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TipoPadrao[] GetListTipoPadrao(Autenticantion auth) {
            object[] results = this.Invoke("GetListTipoPadrao", new object[] {
                        auth});
            return ((TipoPadrao[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetListTipoPadrao(Autenticantion auth, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetListTipoPadrao", new object[] {
                        auth}, callback, asyncState);
        }
        
        /// <remarks/>
        public TipoPadrao[] EndGetListTipoPadrao(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((TipoPadrao[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetListFonteAlternativa", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public FonteAlternativa[] GetListFonteAlternativa(Autenticantion auth) {
            object[] results = this.Invoke("GetListFonteAlternativa", new object[] {
                        auth});
            return ((FonteAlternativa[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetListFonteAlternativa(Autenticantion auth, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetListFonteAlternativa", new object[] {
                        auth}, callback, asyncState);
        }
        
        /// <remarks/>
        public FonteAlternativa[] EndGetListFonteAlternativa(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((FonteAlternativa[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetListDistrito", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Distrito[] GetListDistrito(Autenticantion auth) {
            object[] results = this.Invoke("GetListDistrito", new object[] {
                        auth});
            return ((Distrito[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetListDistrito(Autenticantion auth, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetListDistrito", new object[] {
                        auth}, callback, asyncState);
        }
        
        /// <remarks/>
        public Distrito[] EndGetListDistrito(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((Distrito[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetListRota", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Rota[] GetListRota(Autenticantion auth) {
            object[] results = this.Invoke("GetListRota", new object[] {
                        auth});
            return ((Rota[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetListRota(Autenticantion auth, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetListRota", new object[] {
                        auth}, callback, asyncState);
        }
        
        /// <remarks/>
        public Rota[] EndGetListRota(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((Rota[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetListRotaLibQtdCad", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Rota[] GetListRotaLibQtdCad(Autenticantion auth) {
            object[] results = this.Invoke("GetListRotaLibQtdCad", new object[] {
                        auth});
            return ((Rota[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetListRotaLibQtdCad(Autenticantion auth, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetListRotaLibQtdCad", new object[] {
                        auth}, callback, asyncState);
        }
        
        /// <remarks/>
        public Rota[] EndGetListRotaLibQtdCad(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((Rota[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetListRotaLiberada", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Rota[] GetListRotaLiberada(Autenticantion auth) {
            object[] results = this.Invoke("GetListRotaLiberada", new object[] {
                        auth});
            return ((Rota[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetListRotaLiberada(Autenticantion auth, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetListRotaLiberada", new object[] {
                        auth}, callback, asyncState);
        }
        
        /// <remarks/>
        public Rota[] EndGetListRotaLiberada(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((Rota[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetListCadastro", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Cadastro[] GetListCadastro(Autenticantion auth, Rota rotLib) {
            object[] results = this.Invoke("GetListCadastro", new object[] {
                        auth,
                        rotLib});
            return ((Cadastro[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetListCadastro(Autenticantion auth, Rota rotLib, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetListCadastro", new object[] {
                        auth,
                        rotLib}, callback, asyncState);
        }
        
        /// <remarks/>
        public Cadastro[] EndGetListCadastro(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((Cadastro[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetListHistoricoConsumo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public HistoricoConsumo[] GetListHistoricoConsumo(Autenticantion auth, Rota rotaLib) {
            object[] results = this.Invoke("GetListHistoricoConsumo", new object[] {
                        auth,
                        rotaLib});
            return ((HistoricoConsumo[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetListHistoricoConsumo(Autenticantion auth, Rota rotaLib, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetListHistoricoConsumo", new object[] {
                        auth,
                        rotaLib}, callback, asyncState);
        }
        
        /// <remarks/>
        public HistoricoConsumo[] EndGetListHistoricoConsumo(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((HistoricoConsumo[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SetListHistoricoConsumo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public RespostaWS[] SetListHistoricoConsumo(Autenticantion auth, HistoricoConsumo[] contrib) {
            object[] results = this.Invoke("SetListHistoricoConsumo", new object[] {
                        auth,
                        contrib});
            return ((RespostaWS[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSetListHistoricoConsumo(Autenticantion auth, HistoricoConsumo[] contrib, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SetListHistoricoConsumo", new object[] {
                        auth,
                        contrib}, callback, asyncState);
        }
        
        /// <remarks/>
        public RespostaWS[] EndSetListHistoricoConsumo(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((RespostaWS[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SetListCadastro", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public RespostaWS[] SetListCadastro(Autenticantion auth, Cadastro[] contrib) {
            object[] results = this.Invoke("SetListCadastro", new object[] {
                        auth,
                        contrib});
            return ((RespostaWS[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSetListCadastro(Autenticantion auth, Cadastro[] contrib, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SetListCadastro", new object[] {
                        auth,
                        contrib}, callback, asyncState);
        }
        
        /// <remarks/>
        public RespostaWS[] EndSetListCadastro(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((RespostaWS[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SetListFoto", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public RespostaWS SetListFoto(Autenticantion auth, Foto foto, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] file) {
            object[] results = this.Invoke("SetListFoto", new object[] {
                        auth,
                        foto,
                        file});
            return ((RespostaWS)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSetListFoto(Autenticantion auth, Foto foto, byte[] file, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SetListFoto", new object[] {
                        auth,
                        foto,
                        file}, callback, asyncState);
        }
        
        /// <remarks/>
        public RespostaWS EndSetListFoto(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((RespostaWS)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SetSituacaoCargaRota", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SetSituacaoCargaRota(Rota rota, Autenticantion auth, string situacao) {
            this.Invoke("SetSituacaoCargaRota", new object[] {
                        rota,
                        auth,
                        situacao});
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSetSituacaoCargaRota(Rota rota, Autenticantion auth, string situacao, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SetSituacaoCargaRota", new object[] {
                        rota,
                        auth,
                        situacao}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndSetSituacaoCargaRota(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetRotasFinalizadas", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Rota[] GetRotasFinalizadas(Rota[] listRota, Autenticantion auth) {
            object[] results = this.Invoke("GetRotasFinalizadas", new object[] {
                        listRota,
                        auth});
            return ((Rota[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetRotasFinalizadas(Rota[] listRota, Autenticantion auth, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetRotasFinalizadas", new object[] {
                        listRota,
                        auth}, callback, asyncState);
        }
        
        /// <remarks/>
        public Rota[] EndGetRotasFinalizadas(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((Rota[])(results[0]));
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Autenticantion {
        
        private int idUserField;
        
        private string userField;
        
        private string passwordField;
        
        private string idPDAField;
        
        private string ipPDAField;
        
        private bool parcialField;
        
        /// <remarks/>
        public int IdUser {
            get {
                return this.idUserField;
            }
            set {
                this.idUserField = value;
            }
        }
        
        /// <remarks/>
        public string User {
            get {
                return this.userField;
            }
            set {
                this.userField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public string IdPDA {
            get {
                return this.idPDAField;
            }
            set {
                this.idPDAField = value;
            }
        }
        
        /// <remarks/>
        public string IpPDA {
            get {
                return this.ipPDAField;
            }
            set {
                this.ipPDAField = value;
            }
        }
        
        /// <remarks/>
        public bool parcial {
            get {
                return this.parcialField;
            }
            set {
                this.parcialField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class RespostaWS {
        
        private int errorCodeField;
        
        private string errorMsgField;
        
        private long idRecordField;
        
        private string auxField;
        
        /// <remarks/>
        public int errorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        public string errorMsg {
            get {
                return this.errorMsgField;
            }
            set {
                this.errorMsgField = value;
            }
        }
        
        /// <remarks/>
        public long idRecord {
            get {
                return this.idRecordField;
            }
            set {
                this.idRecordField = value;
            }
        }
        
        /// <remarks/>
        public string aux {
            get {
                return this.auxField;
            }
            set {
                this.auxField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Foto))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(HistoricoConsumo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Cadastro))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Rota))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Distrito))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FonteAlternativa))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TipoPadrao))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LocalizacaoPadrao))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TipoComplemento))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CondicaoImovel))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RamoAtividade))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Ocorrencia))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Funcionario))]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class AuditoriaSuper {
        
        private System.Nullable<long> versaoField;
        
        private string usuMovimentacaoField;
        
        private System.Nullable<System.DateTime> dtMovimentacaoField;
        
        private string ipMovimentacaoField;
        
        private string qtdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<long> Versao {
            get {
                return this.versaoField;
            }
            set {
                this.versaoField = value;
            }
        }
        
        /// <remarks/>
        public string UsuMovimentacao {
            get {
                return this.usuMovimentacaoField;
            }
            set {
                this.usuMovimentacaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> DtMovimentacao {
            get {
                return this.dtMovimentacaoField;
            }
            set {
                this.dtMovimentacaoField = value;
            }
        }
        
        /// <remarks/>
        public string IpMovimentacao {
            get {
                return this.ipMovimentacaoField;
            }
            set {
                this.ipMovimentacaoField = value;
            }
        }
        
        /// <remarks/>
        public string Qtd {
            get {
                return this.qtdField;
            }
            set {
                this.qtdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Foto : AuditoriaSuper {
        
        private long idCadastField;
        
        private System.Nullable<int> codOcorrcField;
        
        private int sequenciaField;
        
        private string descFotoField;
        
        private string nomFotoField;
        
        private string numPontoServcField;
        
        private System.DateTime dataField;
        
        private string coordenadaXField;
        
        private string coordenadaYField;
        
        private System.Nullable<System.DateTime> dataGPSField;
        
        /// <remarks/>
        public long idCadast {
            get {
                return this.idCadastField;
            }
            set {
                this.idCadastField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> codOcorrc {
            get {
                return this.codOcorrcField;
            }
            set {
                this.codOcorrcField = value;
            }
        }
        
        /// <remarks/>
        public int sequencia {
            get {
                return this.sequenciaField;
            }
            set {
                this.sequenciaField = value;
            }
        }
        
        /// <remarks/>
        public string descFoto {
            get {
                return this.descFotoField;
            }
            set {
                this.descFotoField = value;
            }
        }
        
        /// <remarks/>
        public string nomFoto {
            get {
                return this.nomFotoField;
            }
            set {
                this.nomFotoField = value;
            }
        }
        
        /// <remarks/>
        public string numPontoServc {
            get {
                return this.numPontoServcField;
            }
            set {
                this.numPontoServcField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
            }
        }
        
        /// <remarks/>
        public string CoordenadaX {
            get {
                return this.coordenadaXField;
            }
            set {
                this.coordenadaXField = value;
            }
        }
        
        /// <remarks/>
        public string CoordenadaY {
            get {
                return this.coordenadaYField;
            }
            set {
                this.coordenadaYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> DataGPS {
            get {
                return this.dataGPSField;
            }
            set {
                this.dataGPSField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class HistoricoConsumo : AuditoriaSuper {
        
        private long idField;
        
        private System.Nullable<long> matriculaField;
        
        private System.Nullable<long> cadastroField;
        
        private System.Nullable<System.DateTime> mesReferenciaField;
        
        private System.Nullable<int> ocorrencia1Field;
        
        private System.Nullable<int> ocorrencia2Field;
        
        private string criterioField;
        
        private System.Nullable<int> volumeMedidoField;
        
        private string flgHistconsumoField;
        
        private System.Nullable<long> leituraApuracaoField;
        
        private System.Nullable<System.DateTime> datLeituraFatField;
        
        /// <remarks/>
        public long Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<long> Matricula {
            get {
                return this.matriculaField;
            }
            set {
                this.matriculaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<long> Cadastro {
            get {
                return this.cadastroField;
            }
            set {
                this.cadastroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> MesReferencia {
            get {
                return this.mesReferenciaField;
            }
            set {
                this.mesReferenciaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> Ocorrencia1 {
            get {
                return this.ocorrencia1Field;
            }
            set {
                this.ocorrencia1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> Ocorrencia2 {
            get {
                return this.ocorrencia2Field;
            }
            set {
                this.ocorrencia2Field = value;
            }
        }
        
        /// <remarks/>
        public string Criterio {
            get {
                return this.criterioField;
            }
            set {
                this.criterioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> VolumeMedido {
            get {
                return this.volumeMedidoField;
            }
            set {
                this.volumeMedidoField = value;
            }
        }
        
        /// <remarks/>
        public string FlgHistconsumo {
            get {
                return this.flgHistconsumoField;
            }
            set {
                this.flgHistconsumoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<long> LeituraApuracao {
            get {
                return this.leituraApuracaoField;
            }
            set {
                this.leituraApuracaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> DatLeituraFat {
            get {
                return this.datLeituraFatField;
            }
            set {
                this.datLeituraFatField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Cadastro : AuditoriaSuper {
        
        private long idField;
        
        private int codigoRotaField;
        
        private int codigoDistritoField;
        
        private int setorField;
        
        private long matriculaField;
        
        private string nomeClienteField;
        
        private string tipoLogradouroField;
        
        private string nomeLogradouroField;
        
        private int numeroImovelField;
        
        private System.Nullable<int> numeroImovelAlterField;
        
        private string tipoComplementoField;
        
        private string tipoComplementoAlterField;
        
        private string informacaoComplementarField;
        
        private string informacaoComplementarAlterField;
        
        private string nomeBairroField;
        
        private string nomeCidadeField;
        
        private int condicaoImovelField;
        
        private System.Nullable<int> condicaoImovelAlterField;
        
        private System.Nullable<System.DateTime> previsaoFimObraField;
        
        private int faceField;
        
        private int sequenciaField;
        
        private string observacao_complementarField;
        
        private int qtdeEconomiasResidencialField;
        
        private int qtdeEconomiasComercialField;
        
        private int qtdeEconomiasIndustrialField;
        
        private int qtdeEconomiasPublicaField;
        
        private System.Nullable<int> qtdeEconomiasResidencialAlterField;
        
        private System.Nullable<int> qtdeEconomiasComercialAlterField;
        
        private System.Nullable<int> qtdeEconomiasIndustrialAlterField;
        
        private System.Nullable<int> qtdeEconomiasPublicaAlterField;
        
        private System.Nullable<int> ramoAtividade1Field;
        
        private System.Nullable<int> ramoAtividade2Field;
        
        private System.Nullable<int> ramoAtividade3Field;
        
        private System.Nullable<int> ramoAtividade4Field;
        
        private System.Nullable<int> ramoAtividade1AlterField;
        
        private System.Nullable<int> ramoAtividade2AlterField;
        
        private System.Nullable<int> ramoAtividade3AlterField;
        
        private System.Nullable<int> ramoAtividade4AlterField;
        
        private string tarifaSocialField;
        
        private string tarifaSocialIncompativelField;
        
        private string tarifaSocialIncompativelObsField;
        
        private string fonteAlternativaField;
        
        private string fonteAlternativaAlterField;
        
        private string piscinaField;
        
        private string piscinaAlterField;
        
        private string reservatorioField;
        
        private string reservatorioAlterField;
        
        private string situacaoImovelField;
        
        private string situacaoImovelAlterField;
        
        private string situacaoPontoServicoField;
        
        private string situacaoPontoServicoAlterField;
        
        private string observacaoVisitaField;
        
        private string numeroPontoServicoField;
        
        private int localizacaoPadraoField;
        
        private System.Nullable<int> localizacaoPadraoAlterField;
        
        private int tipoPadraoField;
        
        private System.Nullable<int> tipoPadraoAlterField;
        
        private string padraoLacradoField;
        
        private string eliminadorArField;
        
        private string possuiTorneiraPadraoField;
        
        private string existeMedidorField;
        
        private string numeroMedidorField;
        
        private string numeroMedidorAlterField;
        
        private System.Nullable<long> leituraField;
        
        private int qtdeDigitosMedidorField;
        
        private System.Nullable<int> qtdeDigitosMedidorAlterField;
        
        private string classeMetrologicaField;
        
        private string classeMetrologicaAlterField;
        
        private string medidorLacradoField;
        
        private string segundaLigacaoField;
        
        private string numeroMedidor2Field;
        
        private System.Nullable<long> leitura2Field;
        
        private System.Nullable<int> qtdeDigitosMedidor2Field;
        
        private string classeMetrologica2Field;
        
        private string medidorLacrado2Field;
        
        private System.DateTime dataInstalacaoField;
        
        private string vetorOcorrenciaField;
        
        private string observacaoImpedimentoField;
        
        private string suspeitaFraudeField;
        
        private string suspeitaFraudeObsField;
        
        private string expectativaConsumoField;
        
        private int codigoFuncionarioField;
        
        private string coordenadaXField;
        
        private string coordenadaYField;
        
        private System.Nullable<System.DateTime> dataVisitaField;
        
        private System.Nullable<int> statusExecucaoField;
        
        private System.Nullable<System.DateTime> dataGPSField;
        
        /// <remarks/>
        public long Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public int CodigoRota {
            get {
                return this.codigoRotaField;
            }
            set {
                this.codigoRotaField = value;
            }
        }
        
        /// <remarks/>
        public int CodigoDistrito {
            get {
                return this.codigoDistritoField;
            }
            set {
                this.codigoDistritoField = value;
            }
        }
        
        /// <remarks/>
        public int Setor {
            get {
                return this.setorField;
            }
            set {
                this.setorField = value;
            }
        }
        
        /// <remarks/>
        public long Matricula {
            get {
                return this.matriculaField;
            }
            set {
                this.matriculaField = value;
            }
        }
        
        /// <remarks/>
        public string NomeCliente {
            get {
                return this.nomeClienteField;
            }
            set {
                this.nomeClienteField = value;
            }
        }
        
        /// <remarks/>
        public string TipoLogradouro {
            get {
                return this.tipoLogradouroField;
            }
            set {
                this.tipoLogradouroField = value;
            }
        }
        
        /// <remarks/>
        public string NomeLogradouro {
            get {
                return this.nomeLogradouroField;
            }
            set {
                this.nomeLogradouroField = value;
            }
        }
        
        /// <remarks/>
        public int NumeroImovel {
            get {
                return this.numeroImovelField;
            }
            set {
                this.numeroImovelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> NumeroImovelAlter {
            get {
                return this.numeroImovelAlterField;
            }
            set {
                this.numeroImovelAlterField = value;
            }
        }
        
        /// <remarks/>
        public string TipoComplemento {
            get {
                return this.tipoComplementoField;
            }
            set {
                this.tipoComplementoField = value;
            }
        }
        
        /// <remarks/>
        public string TipoComplementoAlter {
            get {
                return this.tipoComplementoAlterField;
            }
            set {
                this.tipoComplementoAlterField = value;
            }
        }
        
        /// <remarks/>
        public string InformacaoComplementar {
            get {
                return this.informacaoComplementarField;
            }
            set {
                this.informacaoComplementarField = value;
            }
        }
        
        /// <remarks/>
        public string InformacaoComplementarAlter {
            get {
                return this.informacaoComplementarAlterField;
            }
            set {
                this.informacaoComplementarAlterField = value;
            }
        }
        
        /// <remarks/>
        public string NomeBairro {
            get {
                return this.nomeBairroField;
            }
            set {
                this.nomeBairroField = value;
            }
        }
        
        /// <remarks/>
        public string NomeCidade {
            get {
                return this.nomeCidadeField;
            }
            set {
                this.nomeCidadeField = value;
            }
        }
        
        /// <remarks/>
        public int CondicaoImovel {
            get {
                return this.condicaoImovelField;
            }
            set {
                this.condicaoImovelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> CondicaoImovelAlter {
            get {
                return this.condicaoImovelAlterField;
            }
            set {
                this.condicaoImovelAlterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> PrevisaoFimObra {
            get {
                return this.previsaoFimObraField;
            }
            set {
                this.previsaoFimObraField = value;
            }
        }
        
        /// <remarks/>
        public int Face {
            get {
                return this.faceField;
            }
            set {
                this.faceField = value;
            }
        }
        
        /// <remarks/>
        public int Sequencia {
            get {
                return this.sequenciaField;
            }
            set {
                this.sequenciaField = value;
            }
        }
        
        /// <remarks/>
        public string Observacao_complementar {
            get {
                return this.observacao_complementarField;
            }
            set {
                this.observacao_complementarField = value;
            }
        }
        
        /// <remarks/>
        public int QtdeEconomiasResidencial {
            get {
                return this.qtdeEconomiasResidencialField;
            }
            set {
                this.qtdeEconomiasResidencialField = value;
            }
        }
        
        /// <remarks/>
        public int QtdeEconomiasComercial {
            get {
                return this.qtdeEconomiasComercialField;
            }
            set {
                this.qtdeEconomiasComercialField = value;
            }
        }
        
        /// <remarks/>
        public int QtdeEconomiasIndustrial {
            get {
                return this.qtdeEconomiasIndustrialField;
            }
            set {
                this.qtdeEconomiasIndustrialField = value;
            }
        }
        
        /// <remarks/>
        public int QtdeEconomiasPublica {
            get {
                return this.qtdeEconomiasPublicaField;
            }
            set {
                this.qtdeEconomiasPublicaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> QtdeEconomiasResidencialAlter {
            get {
                return this.qtdeEconomiasResidencialAlterField;
            }
            set {
                this.qtdeEconomiasResidencialAlterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> QtdeEconomiasComercialAlter {
            get {
                return this.qtdeEconomiasComercialAlterField;
            }
            set {
                this.qtdeEconomiasComercialAlterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> QtdeEconomiasIndustrialAlter {
            get {
                return this.qtdeEconomiasIndustrialAlterField;
            }
            set {
                this.qtdeEconomiasIndustrialAlterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> QtdeEconomiasPublicaAlter {
            get {
                return this.qtdeEconomiasPublicaAlterField;
            }
            set {
                this.qtdeEconomiasPublicaAlterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> RamoAtividade1 {
            get {
                return this.ramoAtividade1Field;
            }
            set {
                this.ramoAtividade1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> RamoAtividade2 {
            get {
                return this.ramoAtividade2Field;
            }
            set {
                this.ramoAtividade2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> RamoAtividade3 {
            get {
                return this.ramoAtividade3Field;
            }
            set {
                this.ramoAtividade3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> RamoAtividade4 {
            get {
                return this.ramoAtividade4Field;
            }
            set {
                this.ramoAtividade4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> RamoAtividade1Alter {
            get {
                return this.ramoAtividade1AlterField;
            }
            set {
                this.ramoAtividade1AlterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> RamoAtividade2Alter {
            get {
                return this.ramoAtividade2AlterField;
            }
            set {
                this.ramoAtividade2AlterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> RamoAtividade3Alter {
            get {
                return this.ramoAtividade3AlterField;
            }
            set {
                this.ramoAtividade3AlterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> RamoAtividade4Alter {
            get {
                return this.ramoAtividade4AlterField;
            }
            set {
                this.ramoAtividade4AlterField = value;
            }
        }
        
        /// <remarks/>
        public string TarifaSocial {
            get {
                return this.tarifaSocialField;
            }
            set {
                this.tarifaSocialField = value;
            }
        }
        
        /// <remarks/>
        public string TarifaSocialIncompativel {
            get {
                return this.tarifaSocialIncompativelField;
            }
            set {
                this.tarifaSocialIncompativelField = value;
            }
        }
        
        /// <remarks/>
        public string TarifaSocialIncompativelObs {
            get {
                return this.tarifaSocialIncompativelObsField;
            }
            set {
                this.tarifaSocialIncompativelObsField = value;
            }
        }
        
        /// <remarks/>
        public string FonteAlternativa {
            get {
                return this.fonteAlternativaField;
            }
            set {
                this.fonteAlternativaField = value;
            }
        }
        
        /// <remarks/>
        public string FonteAlternativaAlter {
            get {
                return this.fonteAlternativaAlterField;
            }
            set {
                this.fonteAlternativaAlterField = value;
            }
        }
        
        /// <remarks/>
        public string Piscina {
            get {
                return this.piscinaField;
            }
            set {
                this.piscinaField = value;
            }
        }
        
        /// <remarks/>
        public string PiscinaAlter {
            get {
                return this.piscinaAlterField;
            }
            set {
                this.piscinaAlterField = value;
            }
        }
        
        /// <remarks/>
        public string Reservatorio {
            get {
                return this.reservatorioField;
            }
            set {
                this.reservatorioField = value;
            }
        }
        
        /// <remarks/>
        public string ReservatorioAlter {
            get {
                return this.reservatorioAlterField;
            }
            set {
                this.reservatorioAlterField = value;
            }
        }
        
        /// <remarks/>
        public string SituacaoImovel {
            get {
                return this.situacaoImovelField;
            }
            set {
                this.situacaoImovelField = value;
            }
        }
        
        /// <remarks/>
        public string SituacaoImovelAlter {
            get {
                return this.situacaoImovelAlterField;
            }
            set {
                this.situacaoImovelAlterField = value;
            }
        }
        
        /// <remarks/>
        public string SituacaoPontoServico {
            get {
                return this.situacaoPontoServicoField;
            }
            set {
                this.situacaoPontoServicoField = value;
            }
        }
        
        /// <remarks/>
        public string SituacaoPontoServicoAlter {
            get {
                return this.situacaoPontoServicoAlterField;
            }
            set {
                this.situacaoPontoServicoAlterField = value;
            }
        }
        
        /// <remarks/>
        public string ObservacaoVisita {
            get {
                return this.observacaoVisitaField;
            }
            set {
                this.observacaoVisitaField = value;
            }
        }
        
        /// <remarks/>
        public string NumeroPontoServico {
            get {
                return this.numeroPontoServicoField;
            }
            set {
                this.numeroPontoServicoField = value;
            }
        }
        
        /// <remarks/>
        public int LocalizacaoPadrao {
            get {
                return this.localizacaoPadraoField;
            }
            set {
                this.localizacaoPadraoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> LocalizacaoPadraoAlter {
            get {
                return this.localizacaoPadraoAlterField;
            }
            set {
                this.localizacaoPadraoAlterField = value;
            }
        }
        
        /// <remarks/>
        public int TipoPadrao {
            get {
                return this.tipoPadraoField;
            }
            set {
                this.tipoPadraoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> TipoPadraoAlter {
            get {
                return this.tipoPadraoAlterField;
            }
            set {
                this.tipoPadraoAlterField = value;
            }
        }
        
        /// <remarks/>
        public string PadraoLacrado {
            get {
                return this.padraoLacradoField;
            }
            set {
                this.padraoLacradoField = value;
            }
        }
        
        /// <remarks/>
        public string EliminadorAr {
            get {
                return this.eliminadorArField;
            }
            set {
                this.eliminadorArField = value;
            }
        }
        
        /// <remarks/>
        public string PossuiTorneiraPadrao {
            get {
                return this.possuiTorneiraPadraoField;
            }
            set {
                this.possuiTorneiraPadraoField = value;
            }
        }
        
        /// <remarks/>
        public string ExisteMedidor {
            get {
                return this.existeMedidorField;
            }
            set {
                this.existeMedidorField = value;
            }
        }
        
        /// <remarks/>
        public string NumeroMedidor {
            get {
                return this.numeroMedidorField;
            }
            set {
                this.numeroMedidorField = value;
            }
        }
        
        /// <remarks/>
        public string NumeroMedidorAlter {
            get {
                return this.numeroMedidorAlterField;
            }
            set {
                this.numeroMedidorAlterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<long> Leitura {
            get {
                return this.leituraField;
            }
            set {
                this.leituraField = value;
            }
        }
        
        /// <remarks/>
        public int QtdeDigitosMedidor {
            get {
                return this.qtdeDigitosMedidorField;
            }
            set {
                this.qtdeDigitosMedidorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> QtdeDigitosMedidorAlter {
            get {
                return this.qtdeDigitosMedidorAlterField;
            }
            set {
                this.qtdeDigitosMedidorAlterField = value;
            }
        }
        
        /// <remarks/>
        public string ClasseMetrologica {
            get {
                return this.classeMetrologicaField;
            }
            set {
                this.classeMetrologicaField = value;
            }
        }
        
        /// <remarks/>
        public string ClasseMetrologicaAlter {
            get {
                return this.classeMetrologicaAlterField;
            }
            set {
                this.classeMetrologicaAlterField = value;
            }
        }
        
        /// <remarks/>
        public string MedidorLacrado {
            get {
                return this.medidorLacradoField;
            }
            set {
                this.medidorLacradoField = value;
            }
        }
        
        /// <remarks/>
        public string SegundaLigacao {
            get {
                return this.segundaLigacaoField;
            }
            set {
                this.segundaLigacaoField = value;
            }
        }
        
        /// <remarks/>
        public string NumeroMedidor2 {
            get {
                return this.numeroMedidor2Field;
            }
            set {
                this.numeroMedidor2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<long> Leitura2 {
            get {
                return this.leitura2Field;
            }
            set {
                this.leitura2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> QtdeDigitosMedidor2 {
            get {
                return this.qtdeDigitosMedidor2Field;
            }
            set {
                this.qtdeDigitosMedidor2Field = value;
            }
        }
        
        /// <remarks/>
        public string ClasseMetrologica2 {
            get {
                return this.classeMetrologica2Field;
            }
            set {
                this.classeMetrologica2Field = value;
            }
        }
        
        /// <remarks/>
        public string MedidorLacrado2 {
            get {
                return this.medidorLacrado2Field;
            }
            set {
                this.medidorLacrado2Field = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DataInstalacao {
            get {
                return this.dataInstalacaoField;
            }
            set {
                this.dataInstalacaoField = value;
            }
        }
        
        /// <remarks/>
        public string VetorOcorrencia {
            get {
                return this.vetorOcorrenciaField;
            }
            set {
                this.vetorOcorrenciaField = value;
            }
        }
        
        /// <remarks/>
        public string ObservacaoImpedimento {
            get {
                return this.observacaoImpedimentoField;
            }
            set {
                this.observacaoImpedimentoField = value;
            }
        }
        
        /// <remarks/>
        public string SuspeitaFraude {
            get {
                return this.suspeitaFraudeField;
            }
            set {
                this.suspeitaFraudeField = value;
            }
        }
        
        /// <remarks/>
        public string SuspeitaFraudeObs {
            get {
                return this.suspeitaFraudeObsField;
            }
            set {
                this.suspeitaFraudeObsField = value;
            }
        }
        
        /// <remarks/>
        public string ExpectativaConsumo {
            get {
                return this.expectativaConsumoField;
            }
            set {
                this.expectativaConsumoField = value;
            }
        }
        
        /// <remarks/>
        public int CodigoFuncionario {
            get {
                return this.codigoFuncionarioField;
            }
            set {
                this.codigoFuncionarioField = value;
            }
        }
        
        /// <remarks/>
        public string CoordenadaX {
            get {
                return this.coordenadaXField;
            }
            set {
                this.coordenadaXField = value;
            }
        }
        
        /// <remarks/>
        public string CoordenadaY {
            get {
                return this.coordenadaYField;
            }
            set {
                this.coordenadaYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> DataVisita {
            get {
                return this.dataVisitaField;
            }
            set {
                this.dataVisitaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> StatusExecucao {
            get {
                return this.statusExecucaoField;
            }
            set {
                this.statusExecucaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> DataGPS {
            get {
                return this.dataGPSField;
            }
            set {
                this.dataGPSField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Rota : AuditoriaSuper {
        
        private int codigoRotaField;
        
        private int codigoDistritoField;
        
        private int setorField;
        
        private System.Nullable<System.DateTime> dataDistribuicaoField;
        
        private System.Nullable<System.DateTime> dataPrevisaoField;
        
        private System.Nullable<System.DateTime> dataExportacaoField;
        
        private int qtdCadField;
        
        private int qtdHistField;
        
        /// <remarks/>
        public int CodigoRota {
            get {
                return this.codigoRotaField;
            }
            set {
                this.codigoRotaField = value;
            }
        }
        
        /// <remarks/>
        public int CodigoDistrito {
            get {
                return this.codigoDistritoField;
            }
            set {
                this.codigoDistritoField = value;
            }
        }
        
        /// <remarks/>
        public int Setor {
            get {
                return this.setorField;
            }
            set {
                this.setorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> DataDistribuicao {
            get {
                return this.dataDistribuicaoField;
            }
            set {
                this.dataDistribuicaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> DataPrevisao {
            get {
                return this.dataPrevisaoField;
            }
            set {
                this.dataPrevisaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> DataExportacao {
            get {
                return this.dataExportacaoField;
            }
            set {
                this.dataExportacaoField = value;
            }
        }
        
        /// <remarks/>
        public int QtdCad {
            get {
                return this.qtdCadField;
            }
            set {
                this.qtdCadField = value;
            }
        }
        
        /// <remarks/>
        public int QtdHist {
            get {
                return this.qtdHistField;
            }
            set {
                this.qtdHistField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Distrito : AuditoriaSuper {
        
        private int idField;
        
        private string nomeDistritoField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string NomeDistrito {
            get {
                return this.nomeDistritoField;
            }
            set {
                this.nomeDistritoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class FonteAlternativa : AuditoriaSuper {
        
        private string idField;
        
        private string descricaoField;
        
        /// <remarks/>
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Descricao {
            get {
                return this.descricaoField;
            }
            set {
                this.descricaoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TipoPadrao : AuditoriaSuper {
        
        private int idField;
        
        private string descricaoField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Descricao {
            get {
                return this.descricaoField;
            }
            set {
                this.descricaoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class LocalizacaoPadrao : AuditoriaSuper {
        
        private int idField;
        
        private string descricaoField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Descricao {
            get {
                return this.descricaoField;
            }
            set {
                this.descricaoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TipoComplemento : AuditoriaSuper {
        
        private string tipoField;
        
        private string descricaoField;
        
        /// <remarks/>
        public string Tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
            }
        }
        
        /// <remarks/>
        public string Descricao {
            get {
                return this.descricaoField;
            }
            set {
                this.descricaoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CondicaoImovel : AuditoriaSuper {
        
        private int idField;
        
        private string descricaoField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Descricao {
            get {
                return this.descricaoField;
            }
            set {
                this.descricaoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class RamoAtividade : AuditoriaSuper {
        
        private int idField;
        
        private string descricaoField;
        
        private string tipoField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Descricao {
            get {
                return this.descricaoField;
            }
            set {
                this.descricaoField = value;
            }
        }
        
        /// <remarks/>
        public string Tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Ocorrencia : AuditoriaSuper {
        
        private int idField;
        
        private string descricaoField;
        
        private bool impedimentoBoolField;
        
        private bool danificBoolField;
        
        private string flagLeituraField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Descricao {
            get {
                return this.descricaoField;
            }
            set {
                this.descricaoField = value;
            }
        }
        
        /// <remarks/>
        public bool ImpedimentoBool {
            get {
                return this.impedimentoBoolField;
            }
            set {
                this.impedimentoBoolField = value;
            }
        }
        
        /// <remarks/>
        public bool DanificBool {
            get {
                return this.danificBoolField;
            }
            set {
                this.danificBoolField = value;
            }
        }
        
        /// <remarks/>
        public string FlagLeitura {
            get {
                return this.flagLeituraField;
            }
            set {
                this.flagLeituraField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Funcionario : AuditoriaSuper {
        
        private int idField;
        
        private string nomeField;
        
        private string telefoneField;
        
        private string tipoField;
        
        private string loginField;
        
        private string senhaField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
            }
        }
        
        /// <remarks/>
        public string Telefone {
            get {
                return this.telefoneField;
            }
            set {
                this.telefoneField = value;
            }
        }
        
        /// <remarks/>
        public string Tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
            }
        }
        
        /// <remarks/>
        public string Login {
            get {
                return this.loginField;
            }
            set {
                this.loginField = value;
            }
        }
        
        /// <remarks/>
        public string Senha {
            get {
                return this.senhaField;
            }
            set {
                this.senhaField = value;
            }
        }
    }
}
