<?php if($this->dialogo == true){?>
<div class="sombra">
<div id="bgAlpha">
    <div id="msgTr" class="<?php echo $this->tipoMsg?>">
    	<form id="dialogoConfirma" name="dialogoConfirma" method="post" action="<?php echo $this->destino?>">
        	<h3>&nbsp;</h3>
            <div class="boxTxt"><?php echo $this->mensagemDialogo;?></div>
            <div class="btnLine"><?php echo $this->botoes;?></div>
            <div style="display:none"><?php echo $this->form;?></div>
        </form>
    </div><!--/msgTr -->
</div> 
</div> 
<link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->baseUrl;?>/public/styles/dialogo.css"/>
<?php }?>