<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="pt-br" lang="pt-br">
<head>
    <meta http-equiv="Content-Type" content="text/html;charset=iso-8859-1" />
    <meta http-equiv="content-language" content="pt-br" />
    <meta name="keywords" content="sistemas, orgaos publicos, prefeituras," />
    <meta name="robots" content="index,follow" />
    <meta name="description" content="Sistema de Abastecimento de veiculos" />
    <meta name="author" content="Sistema de informacao puc minas" />
    <title><?=$this->escape($this->title); ?></title>
    <link rel="stylesheet" type="text/css" media="screen" href="<?=$this->baseUrl;?>/public/styles/global.css" title="Estilo global" />
    <!--[if lt IE 7]>
	<style type="text/css">
		.fixed {
            position:absolute !important;
        }
		body {
        	height:100% !important;
            position:relative;
            width:100% !important;
        }
	</style>
    <![endif]-->
	<script type="text/javascript" src="<? echo $this->baseUrl;?>/public/scripts/jscalendar/calendar.js"></script>
	<script type="text/javascript" src="<? echo $this->baseUrl;?>/public/scripts/jscalendar/lang/calendar-br.js"></script>
    <script type="text/javascript" src="<? echo $this->baseUrl;?>/public/scripts/jscalendar/calendar-setup.js"></script>
    <script type="text/javascript" src="<? echo $this->baseUrl;?>/public/scripts/prototype.js"></script>
    <script type="text/javascript" src="<? echo $this->baseUrl;?>/public/scripts/comum.js"></script>
    <!--
        Script para exibir status de alguma chamada feita via ajax, atravs do carregamento de um gif animado
    -->
    <style type="text/css">
    #preload {
        display:none;
        position:fixed;
        _position:absolute;
        z-index:100;
        top:50%;
        left:50%;
    }
    </style>
   <script language="javascript" type="text/javascript">
	Ajax.Responders.register({
        onCreate: function() {
            $('preload').style['display']='block';
        },
        onComplete: function() {
            $('preload').style['display']='none';;
        }
	});
	</script>
    <div id="preload">
        <img src="<? echo $this->baseUrl;?>/public/images/loading.gif" alt="carregando" name="imgcarregando" id="imgcarregando" title="O conte&uacute;do est&aacute; sendo carregado." style/>
    </div>
    <!--
        Fim script
    -->
</head>
<body onload="javascript: var menu1 = new MenuTree('my_menu'); menu1.abrirMenu(); $('mostramenu').style.visibility='visible'">
    <div id="content">
	<script type="text/javascript" src="<? echo $this->baseUrl;?>/public/scripts/wz_tooltip.js"></script>
    <div id="top">
    	<div class="data">
    	    <? if(Zend_Auth::getInstance()->hasIdentity()){$ns = Zend_Registry::get('ns');?>
            <span><? echo $this->entidade;?></span>
            <span><strong>usu&aacute;rio: </strong><?=Zend_Auth::getInstance()->getIdentity()->username;?></span>
            <span>
				<a href="<? echo $this->baseUrl; ?>/index.php" id="home">
					HOME
				</a>
			</span>
            <? }?>
        </div><!--/data -->
        <div class="contTop">
			<a href="<?php echo $this->baseUrl ?>/auth/logout"></a>
		    <div class="logo">
		        <a href="<?php echo $this->baseUrl ?>" title="Voltar para p&aacute;gina principal">
		        </a>
			</div><!--/logo -->
        </div><!--/contTop -->
    </div><!--/top -->

	<div id="conteudo">
		<b class="rtop">
			<b class="r1"></b> <b class="r2"></b> <b class="r3"></b> <b class="r4"></b>
		</b>
