<fieldset>
<div class="fieldLinha">
    <label for="salvar"  onmouseover="Tip('Salvar Arquivo')" onmouseout="UnTip()" style="cursor: help;">Salvar Arquivo</label>
</div>
<div class="fieldLinha">
    <?php echo $this->formCheckbox('salvar', $this->salvar, array('class'=>'radio'), array('S','N'));?>
    <?php echo $this->formHidden('formato', 'pdf');?>
</div>
</fieldset>
<div class="fieldBtn">
    <?php echo  $this->acao($this->botao_submit); ?>
</div><!--/fieldBtn -->
<script>
    $('acao').onclick = function(){$('preload').style['display']='block';$('acao').disabled='disabled';};
</script>