<div id="container">
    <h2><?=$this->escape($this->title);?></h2>
    <div id="mid">
        <form name="frmmenu" id="frmmenu" action="<?= $this->baseUrl."/".$this->modulo ?>/menu/<?= $this->action;?>" method="post">
            <fieldset>
                <div class="fieldLinha2">
                    <?=$this->label('idMenu',$this->descricaoCampos['idMenu']);?><br />					                    
					<?=$this->formText('idMenu', $this->idMenu, array('class'=>'medTxtArea', 'maxlength'=>''));?>
                </div>
                <div class="fieldLinha2">
                    <?=$this->label('MenuIdPai',$this->descricaoCampos['MenuIdPai']);?><br />					                    
					<?=$this->formText('MenuIdPai', $this->MenuIdPai, array('class'=>'medTxtArea', 'maxlength'=>''));?>
                </div>
                <div class="fieldLinha2">
                    <?=$this->label('nameMenu',$this->descricaoCampos['nameMenu']);?><br />					                    
					<?=$this->formText('nameMenu', $this->nameMenu, array('class'=>'medTxtArea', 'maxlength'=>''));?>
                </div>
                <div class="fieldLinha2">
                    <?=$this->label('ordemMenu',$this->descricaoCampos['ordemMenu']);?><br />					                    
					<?=$this->formText('ordemMenu', $this->ordemMenu, array('class'=>'medTxtArea', 'maxlength'=>''));?>
                </div>
                <div class="fieldLinha2">
                    <?=$this->label('pathMenu',$this->descricaoCampos['pathMenu']);?><br />					                    
					<?=$this->formText('pathMenu', $this->pathMenu, array('class'=>'medTxtArea', 'maxlength'=>''));?>
                </div>
            </fieldset>
            <div class="fieldBtn">
                <?= $this->acao($this->botao_submit); ?>
            </div>
        </form>
    </div>
</div>