///////////////////////////////////////////////////////////
//  Zend_Db_Exception.cs
//  Implementation of the Class Zend_Db_Exception
//  Generated by Enterprise Architect
//  Created on:      07-jun-2011 20:06:18
//  Original author: alexis
///////////////////////////////////////////////////////////




namespace NZend.Db
{

	/// <summary>
	/// @category   Zend
	///      @package    Zend_Db
	///      @copyright  Copyright (c) 2005-2010 Zend Technologies USA Inc. (http://www.
	/// zend.com)
	///      @license    http://framework.zend.com/license/new-bsd     New BSD License
	/// </summary>
	public class Zend_Db_Exception {

		public Zend_Db_Exception(){

		}

		public virtual void Dispose(){

		}

	}//end Zend_Db_Exception

}//end namespace Db