unit uDMAnalise;

interface

uses
  Windows, Messages, SysUtils, Classes, Graphics,
  Controls, Forms, Dialogs, StdCtrls
type
  TdmAnalise=class(TForm)
    qryGeral: TQuery;
    qryGrupoAnaliste: TQuery;
    qryRotaAnaliste: TQuery;
    qryAnalise: TQuery;
    dsAnalise: TDataSource;
    qryCDCAnalise: TQuery;
    qryHistoricoConsumo: TQuery;
    DSHistoricoConsumo: TDataSource;
    qryAnormalidade: TQuery;
    qryHistoricoConsumohc_ref_historico: TDateTimeField;
    qryHistoricoConsumohc_data_leitura: TDateTimeField;
    qryHistoricoConsumohc_leitura: TIntegerField;
    qryHistoricoConsumohc_consumo: TIntegerField;
    qryHistoricoConsumohc_dias_consumo: TIntegerField;
    qryHistoricoConsumohc_ocorrencia_leitura: TStringField;
    qryHistoricoConsumooc_descricao: TStringField;
    qryHistoricoConsumohc_leitura_real: TIntegerField;
    procedure dsAnaliseDataChange(Sender : TObject);
    procedure _PROC_00585037(Sender : TObject);
    procedure _PROC_005850B9(Sender : TObject);
    procedure _PROC_00585539(Sender : TObject);
    procedure _PROC_00585681(Sender : TObject);
    procedure _PROC_00585C29(Sender : TObject);
    procedure _PROC_00585D35(Sender : TObject);
    procedure _PROC_00585DB8(Sender : TObject);
    procedure _PROC_00585DE8(Sender : TObject);
    procedure _PROC_00585E1E(Sender : TObject);
  private
    { Private declarations }
  public
    { Public declarations }
  end ;

var
  dmAnalise: TdmAnalise;

{This file is generated by DeDe Ver 3.50.04 Copyright (c) 1999-2002 DaFixer}

implementation

{$R *.DFM}

procedure TdmAnalise.dsAnaliseDataChange(Sender : TObject);
begin
(*
00584FB0   53                     push    ebx
00584FB1   8BD8                   mov     ebx, eax

* Reference to control TdmAnalise.qryCDCAnalise : TQuery
|
00584FB3   8B436C                 mov     eax, [ebx+$6C]

|
00584FB6   E85595F1FF             call    0049E510
00584FBB   BA3C505800             mov     edx, $0058503C

* Reference to control TdmAnalise.qryAnalise : TQuery
|
00584FC0   8B4364                 mov     eax, [ebx+$64]

|
00584FC3   E870A8F1FF             call    0049F838
00584FC8   8B10                   mov     edx, [eax]

* Possible reference to virtual method TQuery.OFFS_58
|
00584FCA   FF5258                 call    dword ptr [edx+$58]
00584FCD   50                     push    eax

* Possible String Reference to: 'nGrupo'
|
00584FCE   BA58505800             mov     edx, $00585058

* Reference to control TdmAnalise.qryCDCAnalise : TQuery
|
00584FD3   8B436C                 mov     eax, [ebx+$6C]

|
00584FD6   E8A559F3FF             call    004BA980
00584FDB   5A                     pop     edx

|
00584FDC   E80B87F1FF             call    0049D6EC
00584FE1   BA64505800             mov     edx, $00585064

* Reference to control TdmAnalise.qryAnalise : TQuery
|
00584FE6   8B4364                 mov     eax, [ebx+$64]

|
00584FE9   E84AA8F1FF             call    0049F838
00584FEE   8B10                   mov     edx, [eax]

* Possible reference to virtual method TQuery.OFFS_58
|
00584FF0   FF5258                 call    dword ptr [edx+$58]
00584FF3   50                     push    eax

* Possible String Reference to: 'nRota'
|
00584FF4   BA7C505800             mov     edx, $0058507C

* Reference to control TdmAnalise.qryCDCAnalise : TQuery
|
00584FF9   8B436C                 mov     eax, [ebx+$6C]

|
00584FFC   E87F59F3FF             call    004BA980
00585001   5A                     pop     edx

|
00585002   E8E586F1FF             call    0049D6EC
00585007   BA88505800             mov     edx, $00585088

* Reference to control TdmAnalise.qryAnalise : TQuery
|
0058500C   8B4364                 mov     eax, [ebx+$64]

|
0058500F   E824A8F1FF             call    0049F838
00585014   8B10                   mov     edx, [eax]

* Possible reference to virtual method TQuery.OFFS_58
|
00585016   FF5258                 call    dword ptr [edx+$58]
00585019   50                     push    eax

* Possible String Reference to: 'nMatricula'
|
0058501A   BAAC505800             mov     edx, $005850AC

* Reference to control TdmAnalise.qryCDCAnalise : TQuery
|
0058501F   8B436C                 mov     eax, [ebx+$6C]

|
00585022   E85959F3FF             call    004BA980
00585027   5A                     pop     edx

|
00585028   E8BF86F1FF             call    0049D6EC

* Reference to control TdmAnalise.qryCDCAnalise : TQuery
|
0058502D   8B436C                 mov     eax, [ebx+$6C]

|
00585030   E8C794F1FF             call    0049E4FC
00585035   5B                     pop     ebx
00585036   C3                     ret

*)
end;

procedure TdmAnalise._PROC_00585037(Sender : TObject);
begin
(*
00585037   0010                   add     [eax], dl
00585039   0000                   add     [eax], al

*)
end;

procedure TdmAnalise._PROC_005850B9(Sender : TObject);
begin
(*
005850B9   8BEC                   mov     ebp, esp
005850BB   51                     push    ecx
005850BC   B905000000             mov     ecx, $00000005
005850C1   6A00                   push    $00
005850C3   6A00                   push    $00
005850C5   49                     dec     ecx
005850C6   75F9                   jnz     005850C1
005850C8   51                     push    ecx
005850C9   874DFC                 xchg    [ebp-$04], ecx
005850CC   53                     push    ebx
005850CD   56                     push    esi
005850CE   57                     push    edi
005850CF   8BF9                   mov     edi, ecx
005850D1   8BF2                   mov     esi, edx
005850D3   8BD8                   mov     ebx, eax
005850D5   33C0                   xor     eax, eax
005850D7   55                     push    ebp
005850D8   687F535800             push    $0058537F

***** TRY
|
005850DD   64FF30                 push    dword ptr fs:[eax]
005850E0   648920                 mov     fs:[eax], esp
005850E3   C645FF01               mov     byte ptr [ebp-$01], $01
005850E7   33C0                   xor     eax, eax
005850E9   8945F8                 mov     [ebp-$08], eax
005850EC   33C0                   xor     eax, eax
005850EE   55                     push    ebp

* Possible String Reference to: 'ÈÖ˙Áˇ∆Eˇ'
|
005850EF   6856535800             push    $00585356

***** TRY
|
005850F4   64FF30                 push    dword ptr fs:[eax]
005850F7   648920                 mov     fs:[eax], esp

* Reference to control TdmAnalise.qryGeral : TQuery
|
005850FA   8B4358                 mov     eax, [ebx+$58]

|
005850FD   E89A95F1FF             call    0049E69C
00585102   84C0                   test    al, al
00585104   7408                   jz      0058510E

* Reference to control TdmAnalise.qryGeral : TQuery
|
00585106   8B4358                 mov     eax, [ebx+$58]

|
00585109   E80294F1FF             call    0049E510

* Reference to control TdmAnalise.qryGeral : TQuery
|
0058510E   8B4358                 mov     eax, [ebx+$58]

* Reference to field TQuery.OFFS_0248
|
00585111   8B8048020000           mov     eax, [eax+$0248]
00585117   8B10                   mov     edx, [eax]
00585119   FF5244                 call    dword ptr [edx+$44]

* Reference to control TdmAnalise.qryGeral : TQuery
|
0058511C   8B4358                 mov     eax, [ebx+$58]

* Reference to field TQuery.OFFS_0248
|
0058511F   8B8048020000           mov     eax, [eax+$0248]

* Possible String Reference to: 'select count(*) as total'
|
00585125   BA9C535800             mov     edx, $0058539C
0058512A   8B08                   mov     ecx, [eax]
0058512C   FF5138                 call    dword ptr [ecx+$38]

* Reference to control TdmAnalise.qryGeral : TQuery
|
0058512F   8B4358                 mov     eax, [ebx+$58]

* Reference to field TQuery.OFFS_0248
|
00585132   8B8048020000           mov     eax, [eax+$0248]

* Possible String Reference to: 'from roteiros'
|
00585138   BAC0535800             mov     edx, $005853C0
0058513D   8B08                   mov     ecx, [eax]
0058513F   FF5138                 call    dword ptr [ecx+$38]
00585142   8D55F0                 lea     edx, [ebp-$10]
00585145   8BC6                   mov     eax, esi

|
00585147   E8A85EE8FF             call    0040AFF4
0058514C   8B4DF0                 mov     ecx, [ebp-$10]
0058514F   8D45F4                 lea     eax, [ebp-$0C]

* Possible String Reference to: 'where rt_grupo    = '
|
00585152   BAD8535800             mov     edx, $005853D8

|
00585157   E8580AE8FF             call    00405BB4
0058515C   8B55F4                 mov     edx, [ebp-$0C]

* Reference to control TdmAnalise.qryGeral : TQuery
|
0058515F   8B4358                 mov     eax, [ebx+$58]

* Reference to field TQuery.OFFS_0248
|
00585162   8B8048020000           mov     eax, [eax+$0248]
00585168   8B08                   mov     ecx, [eax]
0058516A   FF5138                 call    dword ptr [ecx+$38]
0058516D   8D55E8                 lea     edx, [ebp-$18]
00585170   8BC7                   mov     eax, edi

|
00585172   E87D5EE8FF             call    0040AFF4
00585177   8B4DE8                 mov     ecx, [ebp-$18]
0058517A   8D45EC                 lea     eax, [ebp-$14]

* Possible String Reference to: 'and rt_rota       = '
|
0058517D   BAF8535800             mov     edx, $005853F8

|
00585182   E82D0AE8FF             call    00405BB4
00585187   8B55EC                 mov     edx, [ebp-$14]

* Reference to control TdmAnalise.qryGeral : TQuery
|
0058518A   8B4358                 mov     eax, [ebx+$58]

* Reference to field TQuery.OFFS_0248
|
0058518D   8B8048020000           mov     eax, [eax+$0248]
00585193   8B08                   mov     ecx, [eax]
00585195   FF5138                 call    dword ptr [ecx+$38]

* Reference to control TdmAnalise.qryGeral : TQuery
|
00585198   8B4358                 mov     eax, [ebx+$58]

* Reference to field TQuery.OFFS_0248
|
0058519B   8B8048020000           mov     eax, [eax+$0248]

* Possible String Reference to: 'and rt_data_descarga is not null '
|
005851A1   BA18545800             mov     edx, $00585418
005851A6   8B08                   mov     ecx, [eax]
005851A8   FF5138                 call    dword ptr [ecx+$38]

* Reference to control TdmAnalise.qryGeral : TQuery
|
005851AB   8B4358                 mov     eax, [ebx+$58]

* Reference to field TQuery.OFFS_0248
|
005851AE   8B8048020000           mov     eax, [eax+$0248]

* Possible String Reference to: 'and rt_data_transmissao is null '
|
005851B4   BA44545800             mov     edx, $00585444
005851B9   8B08                   mov     ecx, [eax]
005851BB   FF5138                 call    dword ptr [ecx+$38]

* Reference to control TdmAnalise.qryGeral : TQuery
|
005851BE   8B4358                 mov     eax, [ebx+$58]

* Reference to field TQuery.OFFS_0248
|
005851C1   8B8048020000           mov     eax, [eax+$0248]

* Possible String Reference to: 'and (rt_ind_leitura = 3 '
|
005851C7   BA70545800             mov     edx, $00585470
005851CC   8B08                   mov     ecx, [eax]
005851CE   FF5138                 call    dword ptr [ecx+$38]

* Reference to control TdmAnalise.qryGeral : TQuery
|
005851D1   8B4358                 mov     eax, [ebx+$58]

* Reference to field TQuery.OFFS_0248
|
005851D4   8B8048020000           mov     eax, [eax+$0248]

* Possible String Reference to: 'or rt_ind_leitura = 4) '
|
005851DA   BA94545800             mov     edx, $00585494
005851DF   8B08                   mov     ecx, [eax]
005851E1   FF5138                 call    dword ptr [ecx+$38]

* Reference to control TdmAnalise.qryGeral : TQuery
|
005851E4   8B4358                 mov     eax, [ebx+$58]

* Reference to field TQuery.OFFS_0248
|
005851E7   8B8048020000           mov     eax, [eax+$0248]

* Possible String Reference to: 'and rt_referencia = ('
|
005851ED   BAB4545800             mov     edx, $005854B4
005851F2   8B08                   mov     ecx, [eax]
005851F4   FF5138                 call    dword ptr [ecx+$38]

* Reference to control TdmAnalise.qryGeral : TQuery
|
005851F7   8B4358                 mov     eax, [ebx+$58]

* Reference to field TQuery.OFFS_0248
|
005851FA   8B8048020000           mov     eax, [eax+$0248]

* Possible String Reference to: '                      select refere
|                                ncia '
|
00585200   BAD4545800             mov     edx, $005854D4
00585205   8B08                   mov     ecx, [eax]
00585207   FF5138                 call    dword ptr [ecx+$38]

* Reference to control TdmAnalise.qryGeral : TQuery
|
0058520A   8B4358                 mov     eax, [ebx+$58]

* Reference to field TQuery.OFFS_0248
|
0058520D   8B8048020000           mov     eax, [eax+$0248]

* Possible String Reference to: '                      from DIADEMA_
|                                IV.dbo.IDA_GRUPOS '
|
00585213   BA08555800             mov     edx, $00585508
00585218   8B08                   mov     ecx, [eax]
0058521A   FF5138                 call    dword ptr [ecx+$38]

* Reference to control TdmAnalise.qryGeral : TQuery
|
0058521D   8B4358                 mov     eax, [ebx+$58]

* Reference to field TQuery.OFFS_0248
|
00585220   8B8048020000           mov     eax, [eax+$0248]

* Possible String Reference to: '                      where data_le
|                                itura is null '
|
00585226   BA48555800             mov     edx, $00585548
0058522B   8B08                   mov     ecx, [eax]
0058522D   FF5138                 call    dword ptr [ecx+$38]
00585230   8D55E0                 lea     edx, [ebp-$20]
00585233   8BC6                   mov     eax, esi

|
00585235   E8BA5DE8FF             call    0040AFF4
0058523A   8B4DE0                 mov     ecx, [ebp-$20]
0058523D   8D45E4                 lea     eax, [ebp-$1C]

* Possible String Reference to: '                      and grupo = '
|
00585240   BA84555800             mov     edx, $00585584

|
00585245   E86A09E8FF             call    00405BB4
0058524A   8B55E4                 mov     edx, [ebp-$1C]

* Reference to control TdmAnalise.qryGeral : TQuery
|
0058524D   8B4358                 mov     eax, [ebx+$58]

* Reference to field TQuery.OFFS_0248
|
00585250   8B8048020000           mov     eax, [eax+$0248]
00585256   8B08                   mov     ecx, [eax]
00585258   FF5138                 call    dword ptr [ecx+$38]

* Reference to control TdmAnalise.qryGeral : TQuery
|
0058525B   8B4358                 mov     eax, [ebx+$58]

* Reference to field TQuery.OFFS_0248
|
0058525E   8B8048020000           mov     eax, [eax+$0248]

* Possible String Reference to: '                     )'
|
00585264   BAB0555800             mov     edx, $005855B0
00585269   8B08                   mov     ecx, [eax]
0058526B   FF5138                 call    dword ptr [ecx+$38]

* Reference to control TdmAnalise.qryGeral : TQuery
|
0058526E   8B4358                 mov     eax, [ebx+$58]

|
00585271   E88692F1FF             call    0049E4FC

* Reference to control TdmAnalise.qryGeral : TQuery
|
00585276   8B4358                 mov     eax, [ebx+$58]
00585279   BACC555800             mov     edx, $005855CC

|
0058527E   E8B5A5F1FF             call    0049F838
00585283   8B10                   mov     edx, [eax]

* Possible reference to virtual method TQuery.OFFS_58
|
00585285   FF5258                 call    dword ptr [edx+$58]
00585288   48                     dec     eax
00585289   741B                   jz      005852A6
0058528B   8D45E0                 lea     eax, [ebp-$20]
0058528E   50                     push    eax
0058528F   6AFF                   push    $FF

* Possible String Reference to: 'Este roteiro n„o est· liberado para
|                                 ser finalizado'
|
00585291   B9E0555800             mov     ecx, $005855E0
00585296   83CAFF                 or      edx, -$01
00585299   8B45F8                 mov     eax, [ebp-$08]

|
0058529C   E817BDE8FF             call    00410FB8

|
005852A1   E892FFE7FF             call    00405238

* Reference to control TdmAnalise.qryGeral : TQuery
|
005852A6   8B4358                 mov     eax, [ebx+$58]

|
005852A9   E8EE93F1FF             call    0049E69C
005852AE   84C0                   test    al, al
005852B0   7408                   jz      005852BA

* Reference to control TdmAnalise.qryGeral : TQuery
|
005852B2   8B4358                 mov     eax, [ebx+$58]

|
005852B5   E85692F1FF             call    0049E510

* Reference to control TdmAnalise.qryGeral : TQuery
|
005852BA   8B4358                 mov     eax, [ebx+$58]

* Reference to field TQuery.OFFS_0248
|
005852BD   8B8048020000           mov     eax, [eax+$0248]
005852C3   8B10                   mov     edx, [eax]
005852C5   FF5244                 call    dword ptr [edx+$44]

* Reference to control TdmAnalise.qryGeral : TQuery
|
005852C8   8B4358                 mov     eax, [ebx+$58]

* Reference to field TQuery.OFFS_0248
|
005852CB   8B8048020000           mov     eax, [eax+$0248]

* Possible String Reference to: 'update roteiros'
|
005852D1   BA1C565800             mov     edx, $0058561C
005852D6   8B08                   mov     ecx, [eax]
005852D8   FF5138                 call    dword ptr [ecx+$38]

* Reference to control TdmAnalise.qryGeral : TQuery
|
005852DB   8B4358                 mov     eax, [ebx+$58]

* Reference to field TQuery.OFFS_0248
|
005852DE   8B8048020000           mov     eax, [eax+$0248]

* Possible String Reference to: 'set rt_ind_leitura = 4'
|
005852E4   BA34565800             mov     edx, $00585634
005852E9   8B08                   mov     ecx, [eax]
005852EB   FF5138                 call    dword ptr [ecx+$38]
005852EE   8D55D8                 lea     edx, [ebp-$28]
005852F1   8BC6                   mov     eax, esi

|
005852F3   E8FC5CE8FF             call    0040AFF4
005852F8   8B4DD8                 mov     ecx, [ebp-$28]
005852FB   8D45DC                 lea     eax, [ebp-$24]

* Possible String Reference to: 'where rt_grupo = '
|
005852FE   BA54565800             mov     edx, $00585654

|
00585303   E8AC08E8FF             call    00405BB4
00585308   8B55DC                 mov     edx, [ebp-$24]

* Reference to control TdmAnalise.qryGeral : TQuery
|
0058530B   8B4358                 mov     eax, [ebx+$58]

* Reference to field TQuery.OFFS_0248
|
0058530E   8B8048020000           mov     eax, [eax+$0248]
00585314   8B08                   mov     ecx, [eax]
00585316   FF5138                 call    dword ptr [ecx+$38]
00585319   8D55D0                 lea     edx, [ebp-$30]
0058531C   8BC7                   mov     eax, edi

|
0058531E   E8D15CE8FF             call    0040AFF4
00585323   8B4DD0                 mov     ecx, [ebp-$30]
00585326   8D45D4                 lea     eax, [ebp-$2C]

* Possible String Reference to: 'and rt_rota = '
|
00585329   BA70565800             mov     edx, $00585670

|
0058532E   E88108E8FF             call    00405BB4
00585333   8B55D4                 mov     edx, [ebp-$2C]

* Reference to control TdmAnalise.qryGeral : TQuery
|
00585336   8B4358                 mov     eax, [ebx+$58]

* Reference to field TQuery.OFFS_0248
|
00585339   8B8048020000           mov     eax, [eax+$0248]
0058533F   8B08                   mov     ecx, [eax]
00585341   FF5138                 call    dword ptr [ecx+$38]

* Reference to control TdmAnalise.qryGeral : TQuery
|
00585344   8B4358                 mov     eax, [ebx+$58]

|
00585347   E84C57F3FF             call    004BAA98
0058534C   33C0                   xor     eax, eax
0058534E   5A                     pop     edx
0058534F   59                     pop     ecx
00585350   59                     pop     ecx
00585351   648910                 mov     fs:[eax], edx
00585354   EB0E                   jmp     00585364

|
00585356   E985FAE7FF             jmp     00404DE0
0058535B   C645FF00               mov     byte ptr [ebp-$01], $00

|
0058535F   E850FFE7FF             call    004052B4

****** END
|
00585364   33C0                   xor     eax, eax
00585366   5A                     pop     edx
00585367   59                     pop     ecx
00585368   59                     pop     ecx
00585369   648910                 mov     fs:[eax], edx

****** FINALLY
|
0058536C   6886535800             push    $00585386
00585371   8D45D0                 lea     eax, [ebp-$30]
00585374   BA0A000000             mov     edx, $0000000A

|
00585379   E84A05E8FF             call    004058C8
0058537E   C3                     ret


|
0058537F   E910FDE7FF             jmp     00405094
00585384   EBEB                   jmp     00585371

****** END
|
00585386   0FB645FF               movzx   eax, byte ptr [ebp-$01]
0058538A   5F                     pop     edi
0058538B   5E                     pop     esi
0058538C   5B                     pop     ebx
0058538D   8BE5                   mov     esp, ebp
0058538F   5D                     pop     ebp
00585390   C20400                 ret     $0004

*)
end;

procedure TdmAnalise._PROC_00585539(Sender : TObject);
begin
(*
00585539   50                     push    eax
0058553A   4F                     dec     edi
0058553B   53                     push    ebx
0058553C   2000                   and     [eax], al
0058553E   0000                   add     [eax], al

*)
end;

procedure TdmAnalise._PROC_00585681(Sender : TObject);
begin
(*
00585681   8BEC                   mov     ebp, esp
00585683   51                     push    ecx
00585684   B907000000             mov     ecx, $00000007
00585689   6A00                   push    $00
0058568B   6A00                   push    $00
0058568D   49                     dec     ecx
0058568E   75F9                   jnz     00585689
00585690   874DFC                 xchg    [ebp-$04], ecx
00585693   53                     push    ebx
00585694   56                     push    esi
00585695   57                     push    edi
00585696   8BF9                   mov     edi, ecx
00585698   8BF2                   mov     esi, edx
0058569A   8BD8                   mov     ebx, eax
0058569C   33C0                   xor     eax, eax
0058569E   55                     push    ebp
0058569F   68DB595800             push    $005859DB

***** TRY
|
005856A4   64FF30                 push    dword ptr fs:[eax]
005856A7   648920                 mov     fs:[eax], esp
005856AA   C645FF00               mov     byte ptr [ebp-$01], $00

* Reference to control TdmAnalise.qryGeral : TQuery
|
005856AE   8B4358                 mov     eax, [ebx+$58]

|
005856B1   E8E68FF1FF             call    0049E69C
005856B6   84C0                   test    al, al
005856B8   7408                   jz      005856C2

* Reference to control TdmAnalise.qryGeral : TQuery
|
005856BA   8B4358                 mov     eax, [ebx+$58]

|
005856BD   E84E8EF1FF             call    0049E510

* Reference to control TdmAnalise.qryGeral : TQuery
|
005856C2   8B4358                 mov     eax, [ebx+$58]

* Reference to field TQuery.OFFS_0248
|
005856C5   8B8048020000           mov     eax, [eax+$0248]
005856CB   8B10                   mov     edx, [eax]
005856CD   FF5244                 call    dword ptr [edx+$44]

* Reference to control TdmAnalise.qryGeral : TQuery
|
005856D0   8B4358                 mov     eax, [ebx+$58]

* Reference to field TQuery.OFFS_0248
|
005856D3   8B8048020000           mov     eax, [eax+$0248]

* Possible String Reference to: 'select distinct dg_status'
|
005856D9   BAF8595800             mov     edx, $005859F8
005856DE   8B08                   mov     ecx, [eax]
005856E0   FF5138                 call    dword ptr [ecx+$38]

* Reference to control TdmAnalise.qryGeral : TQuery
|
005856E3   8B4358                 mov     eax, [ebx+$58]

* Reference to field TQuery.OFFS_0248
|
005856E6   8B8048020000           mov     eax, [eax+$0248]

* Possible String Reference to: 'from descarga'
|
005856EC   BA1C5A5800             mov     edx, $00585A1C
005856F1   8B08                   mov     ecx, [eax]
005856F3   FF5138                 call    dword ptr [ecx+$38]
005856F6   8D55F4                 lea     edx, [ebp-$0C]
005856F9   8BC6                   mov     eax, esi

|
005856FB   E8F458E8FF             call    0040AFF4
00585700   8B4DF4                 mov     ecx, [ebp-$0C]
00585703   8D45F8                 lea     eax, [ebp-$08]

* Possible String Reference to: 'where dg_grupo    = '
|
00585706   BA345A5800             mov     edx, $00585A34

|
0058570B   E8A404E8FF             call    00405BB4
00585710   8B55F8                 mov     edx, [ebp-$08]

* Reference to control TdmAnalise.qryGeral : TQuery
|
00585713   8B4358                 mov     eax, [ebx+$58]

* Reference to field TQuery.OFFS_0248
|
00585716   8B8048020000           mov     eax, [eax+$0248]
0058571C   8B08                   mov     ecx, [eax]
0058571E   FF5138                 call    dword ptr [ecx+$38]
00585721   8D55EC                 lea     edx, [ebp-$14]
00585724   8BC7                   mov     eax, edi

|
00585726   E8C958E8FF             call    0040AFF4
0058572B   8B4DEC                 mov     ecx, [ebp-$14]
0058572E   8D45F0                 lea     eax, [ebp-$10]

* Possible String Reference to: 'and dg_rota       = '
|
00585731   BA545A5800             mov     edx, $00585A54

|
00585736   E87904E8FF             call    00405BB4
0058573B   8B55F0                 mov     edx, [ebp-$10]

* Reference to control TdmAnalise.qryGeral : TQuery
|
0058573E   8B4358                 mov     eax, [ebx+$58]

* Reference to field TQuery.OFFS_0248
|
00585741   8B8048020000           mov     eax, [eax+$0248]
00585747   8B08                   mov     ecx, [eax]
00585749   FF5138                 call    dword ptr [ecx+$38]

* Reference to control TdmAnalise.qryGeral : TQuery
|
0058574C   8B4358                 mov     eax, [ebx+$58]

|
0058574F   E8A88DF1FF             call    0049E4FC

* Reference to control TdmAnalise.qryGeral : TQuery
|
00585754   8B4358                 mov     eax, [ebx+$58]
00585757   8B10                   mov     edx, [eax]

* Possible reference to virtual method TQuery.OFFS_016C
|
00585759   FF926C010000           call    dword ptr [edx+$016C]
0058575F   48                     dec     eax
00585760   0F855A020000           jnz     005859C0
00585766   BA705A5800             mov     edx, $00585A70

* Reference to control TdmAnalise.qryGeral : TQuery
|
0058576B   8B4358                 mov     eax, [ebx+$58]

|
0058576E   E8C5A0F1FF             call    0049F838
00585773   8B10                   mov     edx, [eax]

* Possible reference to virtual method TQuery.OFFS_58
|
00585775   FF5258                 call    dword ptr [edx+$58]
00585778   83F805                 cmp     eax, +$05
0058577B   0F853F020000           jnz     005859C0

* Reference to control TdmAnalise.qryGeral : TQuery
|
00585781   8B4358                 mov     eax, [ebx+$58]

|
00585784   E8138FF1FF             call    0049E69C
00585789   84C0                   test    al, al
0058578B   7408                   jz      00585795

* Reference to control TdmAnalise.qryGeral : TQuery
|
0058578D   8B4358                 mov     eax, [ebx+$58]

|
00585790   E87B8DF1FF             call    0049E510

* Reference to control TdmAnalise.qryGeral : TQuery
|
00585795   8B4358                 mov     eax, [ebx+$58]

* Reference to field TQuery.OFFS_0248
|
00585798   8B8048020000           mov     eax, [eax+$0248]
0058579E   8B10                   mov     edx, [eax]
005857A0   FF5244                 call    dword ptr [edx+$44]

* Reference to control TdmAnalise.qryGeral : TQuery
|
005857A3   8B4358                 mov     eax, [ebx+$58]

* Reference to field TQuery.OFFS_0248
|
005857A6   8B8048020000           mov     eax, [eax+$0248]

* Possible String Reference to: 'select count(*) as total'
|
005857AC   BA8C5A5800             mov     edx, $00585A8C
005857B1   8B08                   mov     ecx, [eax]
005857B3   FF5138                 call    dword ptr [ecx+$38]

* Reference to control TdmAnalise.qryGeral : TQuery
|
005857B6   8B4358                 mov     eax, [ebx+$58]

* Reference to field TQuery.OFFS_0248
|
005857B9   8B8048020000           mov     eax, [eax+$0248]

* Possible String Reference to: 'from roteiros'
|
005857BF   BAB05A5800             mov     edx, $00585AB0
005857C4   8B08                   mov     ecx, [eax]
005857C6   FF5138                 call    dword ptr [ecx+$38]
005857C9   8D55E4                 lea     edx, [ebp-$1C]
005857CC   8BC6                   mov     eax, esi

|
005857CE   E82158E8FF             call    0040AFF4
005857D3   8B4DE4                 mov     ecx, [ebp-$1C]
005857D6   8D45E8                 lea     eax, [ebp-$18]

* Possible String Reference to: 'where rt_grupo    = '
|
005857D9   BAC85A5800             mov     edx, $00585AC8

|
005857DE   E8D103E8FF             call    00405BB4
005857E3   8B55E8                 mov     edx, [ebp-$18]

* Reference to control TdmAnalise.qryGeral : TQuery
|
005857E6   8B4358                 mov     eax, [ebx+$58]

* Reference to field TQuery.OFFS_0248
|
005857E9   8B8048020000           mov     eax, [eax+$0248]
005857EF   8B08                   mov     ecx, [eax]
005857F1   FF5138                 call    dword ptr [ecx+$38]
005857F4   8D55DC                 lea     edx, [ebp-$24]
005857F7   8BC7                   mov     eax, edi

|
005857F9   E8F657E8FF             call    0040AFF4
005857FE   8B4DDC                 mov     ecx, [ebp-$24]
00585801   8D45E0                 lea     eax, [ebp-$20]

* Possible String Reference to: 'and rt_rota       = '
|
00585804   BAE85A5800             mov     edx, $00585AE8

|
00585809   E8A603E8FF             call    00405BB4
0058580E   8B55E0                 mov     edx, [ebp-$20]

* Reference to control TdmAnalise.qryGeral : TQuery
|
00585811   8B4358                 mov     eax, [ebx+$58]

* Reference to field TQuery.OFFS_0248
|
00585814   8B8048020000           mov     eax, [eax+$0248]
0058581A   8B08                   mov     ecx, [eax]
0058581C   FF5138                 call    dword ptr [ecx+$38]

* Reference to control TdmAnalise.qryGeral : TQuery
|
0058581F   8B4358                 mov     eax, [ebx+$58]

* Reference to field TQuery.OFFS_0248
|
00585822   8B8048020000           mov     eax, [eax+$0248]

* Possible String Reference to: 'and rt_data_descarga is not null '
|
00585828   BA085B5800             mov     edx, $00585B08
0058582D   8B08                   mov     ecx, [eax]
0058582F   FF5138                 call    dword ptr [ecx+$38]

* Reference to control TdmAnalise.qryGeral : TQuery
|
00585832   8B4358                 mov     eax, [ebx+$58]

* Reference to field TQuery.OFFS_0248
|
00585835   8B8048020000           mov     eax, [eax+$0248]

* Possible String Reference to: 'and rt_data_transmissao is null '
|
0058583B   BA345B5800             mov     edx, $00585B34
00585840   8B08                   mov     ecx, [eax]
00585842   FF5138                 call    dword ptr [ecx+$38]

* Reference to control TdmAnalise.qryGeral : TQuery
|
00585845   8B4358                 mov     eax, [ebx+$58]

* Reference to field TQuery.OFFS_0248
|
00585848   8B8048020000           mov     eax, [eax+$0248]

* Possible String Reference to: 'and (rt_ind_leitura = 3 '
|
0058584E   BA605B5800             mov     edx, $00585B60
00585853   8B08                   mov     ecx, [eax]
00585855   FF5138                 call    dword ptr [ecx+$38]

* Reference to control TdmAnalise.qryGeral : TQuery
|
00585858   8B4358                 mov     eax, [ebx+$58]

* Reference to field TQuery.OFFS_0248
|
0058585B   8B8048020000           mov     eax, [eax+$0248]

* Possible String Reference to: 'or rt_ind_leitura = 4) '
|
00585861   BA845B5800             mov     edx, $00585B84
00585866   8B08                   mov     ecx, [eax]
00585868   FF5138                 call    dword ptr [ecx+$38]

* Reference to control TdmAnalise.qryGeral : TQuery
|
0058586B   8B4358                 mov     eax, [ebx+$58]

* Reference to field TQuery.OFFS_0248
|
0058586E   8B8048020000           mov     eax, [eax+$0248]

* Possible String Reference to: 'and rt_referencia = ('
|
00585874   BAA45B5800             mov     edx, $00585BA4
00585879   8B08                   mov     ecx, [eax]
0058587B   FF5138                 call    dword ptr [ecx+$38]

* Reference to control TdmAnalise.qryGeral : TQuery
|
0058587E   8B4358                 mov     eax, [ebx+$58]

* Reference to field TQuery.OFFS_0248
|
00585881   8B8048020000           mov     eax, [eax+$0248]

* Possible String Reference to: '                      select refere
|                                ncia '
|
00585887   BAC45B5800             mov     edx, $00585BC4
0058588C   8B08                   mov     ecx, [eax]
0058588E   FF5138                 call    dword ptr [ecx+$38]

* Reference to control TdmAnalise.qryGeral : TQuery
|
00585891   8B4358                 mov     eax, [ebx+$58]

* Reference to field TQuery.OFFS_0248
|
00585894   8B8048020000           mov     eax, [eax+$0248]

* Possible String Reference to: '                      from DIADEMA_
|                                IV.dbo.IDA_GRUPOS '
|
0058589A   BAF85B5800             mov     edx, $00585BF8
0058589F   8B08                   mov     ecx, [eax]
005858A1   FF5138                 call    dword ptr [ecx+$38]

* Reference to control TdmAnalise.qryGeral : TQuery
|
005858A4   8B4358                 mov     eax, [ebx+$58]

* Reference to field TQuery.OFFS_0248
|
005858A7   8B8048020000           mov     eax, [eax+$0248]

* Possible String Reference to: '                      where data_re
|                                torno is null '
|
005858AD   BA385C5800             mov     edx, $00585C38
005858B2   8B08                   mov     ecx, [eax]
005858B4   FF5138                 call    dword ptr [ecx+$38]
005858B7   8D55D4                 lea     edx, [ebp-$2C]
005858BA   8BC6                   mov     eax, esi

|
005858BC   E83357E8FF             call    0040AFF4
005858C1   8B4DD4                 mov     ecx, [ebp-$2C]
005858C4   8D45D8                 lea     eax, [ebp-$28]

* Possible String Reference to: '                      and grupo = '
|
005858C7   BA745C5800             mov     edx, $00585C74

|
005858CC   E8E302E8FF             call    00405BB4
005858D1   8B55D8                 mov     edx, [ebp-$28]

* Reference to control TdmAnalise.qryGeral : TQuery
|
005858D4   8B4358                 mov     eax, [ebx+$58]

* Reference to field TQuery.OFFS_0248
|
005858D7   8B8048020000           mov     eax, [eax+$0248]
005858DD   8B08                   mov     ecx, [eax]
005858DF   FF5138                 call    dword ptr [ecx+$38]

* Reference to control TdmAnalise.qryGeral : TQuery
|
005858E2   8B4358                 mov     eax, [ebx+$58]

* Reference to field TQuery.OFFS_0248
|
005858E5   8B8048020000           mov     eax, [eax+$0248]

* Possible String Reference to: '                     )'
|
005858EB   BAA05C5800             mov     edx, $00585CA0
005858F0   8B08                   mov     ecx, [eax]
005858F2   FF5138                 call    dword ptr [ecx+$38]

* Reference to control TdmAnalise.qryGeral : TQuery
|
005858F5   8B4358                 mov     eax, [ebx+$58]

|
005858F8   E8FF8BF1FF             call    0049E4FC
005858FD   BABC5C5800             mov     edx, $00585CBC

* Reference to control TdmAnalise.qryGeral : TQuery
|
00585902   8B4358                 mov     eax, [ebx+$58]

|
00585905   E82E9FF1FF             call    0049F838
0058590A   8B10                   mov     edx, [eax]

* Possible reference to virtual method TQuery.OFFS_58
|
0058590C   FF5258                 call    dword ptr [edx+$58]
0058590F   48                     dec     eax
00585910   0F85AA000000           jnz     005859C0

* Reference to control TdmAnalise.qryGeral : TQuery
|
00585916   8B4358                 mov     eax, [ebx+$58]

|
00585919   E87E8DF1FF             call    0049E69C
0058591E   84C0                   test    al, al
00585920   7408                   jz      0058592A

* Reference to control TdmAnalise.qryGeral : TQuery
|
00585922   8B4358                 mov     eax, [ebx+$58]

|
00585925   E8E68BF1FF             call    0049E510

* Reference to control TdmAnalise.qryGeral : TQuery
|
0058592A   8B4358                 mov     eax, [ebx+$58]

* Reference to field TQuery.OFFS_0248
|
0058592D   8B8048020000           mov     eax, [eax+$0248]
00585933   8B10                   mov     edx, [eax]
00585935   FF5244                 call    dword ptr [edx+$44]

* Reference to control TdmAnalise.qryGeral : TQuery
|
00585938   8B4358                 mov     eax, [ebx+$58]

* Reference to field TQuery.OFFS_0248
|
0058593B   8B8048020000           mov     eax, [eax+$0248]

* Possible String Reference to: 'update roteiros'
|
00585941   BAD05C5800             mov     edx, $00585CD0
00585946   8B08                   mov     ecx, [eax]
00585948   FF5138                 call    dword ptr [ecx+$38]

* Reference to control TdmAnalise.qryGeral : TQuery
|
0058594B   8B4358                 mov     eax, [ebx+$58]

* Reference to field TQuery.OFFS_0248
|
0058594E   8B8048020000           mov     eax, [eax+$0248]

* Possible String Reference to: 'set rt_ind_leitura = 4'
|
00585954   BAE85C5800             mov     edx, $00585CE8
00585959   8B08                   mov     ecx, [eax]
0058595B   FF5138                 call    dword ptr [ecx+$38]
0058595E   8D55CC                 lea     edx, [ebp-$34]
00585961   8BC6                   mov     eax, esi

|
00585963   E88C56E8FF             call    0040AFF4
00585968   8B4DCC                 mov     ecx, [ebp-$34]
0058596B   8D45D0                 lea     eax, [ebp-$30]

* Possible String Reference to: 'where rt_grupo = '
|
0058596E   BA085D5800             mov     edx, $00585D08

|
00585973   E83C02E8FF             call    00405BB4
00585978   8B55D0                 mov     edx, [ebp-$30]

* Reference to control TdmAnalise.qryGeral : TQuery
|
0058597B   8B4358                 mov     eax, [ebx+$58]

* Reference to field TQuery.OFFS_0248
|
0058597E   8B8048020000           mov     eax, [eax+$0248]
00585984   8B08                   mov     ecx, [eax]
00585986   FF5138                 call    dword ptr [ecx+$38]
00585989   8D55C4                 lea     edx, [ebp-$3C]
0058598C   8BC7                   mov     eax, edi

|
0058598E   E86156E8FF             call    0040AFF4
00585993   8B4DC4                 mov     ecx, [ebp-$3C]
00585996   8D45C8                 lea     eax, [ebp-$38]

* Possible String Reference to: 'and rt_rota = '
|
00585999   BA245D5800             mov     edx, $00585D24

|
0058599E   E81102E8FF             call    00405BB4
005859A3   8B55C8                 mov     edx, [ebp-$38]

* Reference to control TdmAnalise.qryGeral : TQuery
|
005859A6   8B4358                 mov     eax, [ebx+$58]

* Reference to field TQuery.OFFS_0248
|
005859A9   8B8048020000           mov     eax, [eax+$0248]
005859AF   8B08                   mov     ecx, [eax]
005859B1   FF5138                 call    dword ptr [ecx+$38]

* Reference to control TdmAnalise.qryGeral : TQuery
|
005859B4   8B4358                 mov     eax, [ebx+$58]

|
005859B7   E8DC50F3FF             call    004BAA98
005859BC   C645FF01               mov     byte ptr [ebp-$01], $01
005859C0   33C0                   xor     eax, eax
005859C2   5A                     pop     edx
005859C3   59                     pop     ecx
005859C4   59                     pop     ecx
005859C5   648910                 mov     fs:[eax], edx

****** FINALLY
|
005859C8   68E2595800             push    $005859E2
005859CD   8D45C4                 lea     eax, [ebp-$3C]
005859D0   BA0E000000             mov     edx, $0000000E

|
005859D5   E8EEFEE7FF             call    004058C8
005859DA   C3                     ret


|
005859DB   E9B4F6E7FF             jmp     00405094
005859E0   EBEB                   jmp     005859CD

****** END
|
005859E2   0FB645FF               movzx   eax, byte ptr [ebp-$01]
005859E6   5F                     pop     edi
005859E7   5E                     pop     esi
005859E8   5B                     pop     ebx
005859E9   8BE5                   mov     esp, ebp
005859EB   5D                     pop     ebp
005859EC   C3                     ret

*)
end;

procedure TdmAnalise._PROC_00585C29(Sender : TObject);
begin
(*
00585C29   50                     push    eax
00585C2A   4F                     dec     edi
00585C2B   53                     push    ebx
00585C2C   2000                   and     [eax], al
00585C2E   0000                   add     [eax], al

*)
end;

procedure TdmAnalise._PROC_00585D35(Sender : TObject);
begin
(*
00585D35   8BEC                   mov     ebp, esp
00585D37   51                     push    ecx
00585D38   B201                   mov     dl, $01

* Reference to class TBitmap
|
00585D3A   A19C0B4300             mov     eax, dword ptr [$00430B9C]

* Reference to : TBitmapCanvas._PROC_004377A8()
|
00585D3F   E8641AEBFF             call    004377A8
00585D44   8945FC                 mov     [ebp-$04], eax
00585D47   33C0                   xor     eax, eax
00585D49   55                     push    ebp

* Possible String Reference to: 'È‚ÚÁˇÎY]√êUãÏ3¿Uh›]X'
|
00585D4A   68AD5D5800             push    $00585DAD

***** TRY
|
00585D4F   64FF30                 push    dword ptr fs:[eax]
00585D52   648920                 mov     fs:[eax], esp
00585D55   68F77F0000             push    $00007FF7
00585D5A   6A00                   push    $00

* Reference to: user32.LoadBitmapA()
|
00585D5C   E8B32FE8FF             call    00408D14
00585D61   8BD0                   mov     edx, eax
00585D63   8B45FC                 mov     eax, [ebp-$04]

* Reference to : TBitmapCanvas._PROC_00438AD4()
|
00585D66   E8692DEBFF             call    00438AD4
00585D6B   8B45FC                 mov     eax, [ebp-$04]
00585D6E   8B10                   mov     edx, [eax]

* Possible reference to virtual method TBitmap.OFFS_2C
|
00585D70   FF522C                 call    dword ptr [edx+$2C]
00585D73   85C0                   test    eax, eax
00585D75   7903                   jns     00585D7A
00585D77   83C003                 add     eax, +$03
00585D7A   C1F802                 sar     eax, $02

* Reference to GlobalVar_0064403C
|
00585D7D   A33C406400             mov     dword ptr [$0064403C], eax
00585D82   8B45FC                 mov     eax, [ebp-$04]
00585D85   8B10                   mov     edx, [eax]

* Possible reference to virtual method TBitmap.OFFS_20
|
00585D87   FF5220                 call    dword ptr [edx+$20]
00585D8A   B903000000             mov     ecx, $00000003
00585D8F   99                     cdq
00585D90   F7F9                   idiv    ecx 

* Reference to GlobalVar_00644040
|
00585D92   A340406400             mov     dword ptr [$00644040], eax
00585D97   33C0                   xor     eax, eax
00585D99   5A                     pop     edx
00585D9A   59                     pop     ecx
00585D9B   59                     pop     ecx
00585D9C   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: 'Y]√êUãÏ3¿Uh›]X'
|
00585D9F   68B45D5800             push    $00585DB4
00585DA4   8B45FC                 mov     eax, [ebp-$04]

|
00585DA7   E814EBE7FF             call    004048C0
00585DAC   C3                     ret


|
00585DAD   E9E2F2E7FF             jmp     00405094
00585DB2   EBF0                   jmp     00585DA4

****** END
|
00585DB4   59                     pop     ecx
00585DB5   5D                     pop     ebp
00585DB6   C3                     ret

*)
end;

procedure TdmAnalise._PROC_00585DB8(Sender : TObject);
begin
(*
00585DB8   55                     push    ebp
00585DB9   8BEC                   mov     ebp, esp
00585DBB   33C0                   xor     eax, eax
00585DBD   55                     push    ebp

* Possible String Reference to: 'È≤ÚÁˇÎ¯]√ã¿4^X'
|
00585DBE   68DD5D5800             push    $00585DDD

***** TRY
|
00585DC3   64FF30                 push    dword ptr fs:[eax]
00585DC6   648920                 mov     fs:[eax], esp
00585DC9   FF0538406400           inc     dword ptr [$00644038]
00585DCF   33C0                   xor     eax, eax
00585DD1   5A                     pop     edx
00585DD2   59                     pop     ecx
00585DD3   59                     pop     ecx
00585DD4   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: ']√ã¿4^X'
|
00585DD7   68E45D5800             push    $00585DE4
00585DDC   C3                     ret


|
00585DDD   E9B2F2E7FF             jmp     00405094
00585DE2   EBF8                   jmp     00585DDC

****** END
|
00585DE4   5D                     pop     ebp
00585DE5   C3                     ret

*)
end;

procedure TdmAnalise._PROC_00585DE8(Sender : TObject);
begin
(*
00585DE8   345E                   xor     al, $5E
00585DEA   58                     pop     eax
00585DEB   0000                   add     [eax], al

*)
end;

procedure TdmAnalise._PROC_00585E1E(Sender : TObject);
begin
(*
00585E1E   47                     inc     edi
00585E1F   001C4B                 add     [ebx+ecx*2], bl
00585E22   40                     inc     eax
00585E23   000C8547005848         add     [$48580047+eax*4], cl
00585E2A   40                     inc     eax
00585E2B   00744840               add     [eax+ecx*2+$40], dh
00585E2F   00905547008C           add     [eax+$8C004755], dl
00585E35   844600                 test    [esi+$00], al
00585E38   845B47                 test    [ebx+$47], bl
00585E3B   000C31                 add     [ecx+esi], cl
00585E3E   42                     inc     edx
00585E3F   006C5747               add     [edi+edx*2+$47], ch
00585E43   00B8574700F4           add     [eax+$F4004757], bh
00585E49   58                     pop     eax
00585E4A   47                     inc     edi
00585E4B   00E8                   add     al, ch
00585E4D   F8                     clc
00585E4E   45                     inc     ebp
00585E4F   0094C542008462         add     [ebp+eax*8+$62840042], dl
00585E56   47                     inc     edi
00585E57   0070C2                 add     [eax-$3E], dh
00585E5A   42                     inc     edx
00585E5B   0070AB                 add     [eax-$55], dh
00585E5E   47                     inc     edi
00585E5F   00E0                   add     al, ah
00585E61   51                     push    ecx
00585E62   47                     inc     edi
00585E63   00B07E4600BC           add     [eax+$BC00467E], dh
00585E69   844600                 test    [esi+$00], al
00585E6C   08844600B0EB45         or      [esi+eax*2+$45EBB000], al
00585E73   002C79                 add     [ecx+edi*2], ch
00585E76   46                     inc     esi
00585E77   00B85E4700B8           add     [eax+$B800475E], bh
00585E7D   7546                   jnz     00585EC5
00585E7F   00F0                   add     al, dh
00585E81   EA4500F4EA             jmp     $EAF40045
00585E86   45                     inc     ebp
00585E87   00AC5F47006C24         add     [edi+ebx*2+$246C0047], ch
00585E8E   46                     inc     esi
00585E8F   003CA8                 add     [eax+ebp*4], bh
00585E92   47                     inc     edi
00585E93   00CC                   add     ah, cl
00585E95   F8                     clc
00585E96   45                     inc     ebp
00585E97   002CED450058FA         add     [$FA580045+ebp*8], ch
00585E9E   45                     inc     ebp
00585E9F   00C8                   add     al, cl
00585EA1   61                     popa
00585EA2   47                     inc     edi
00585EA3   008460470094FB         add     [eax+$FB940047], al
00585EAA   45                     inc     ebp
00585EAB   00C4                   add     ah, al
00585EAD   624700                 bound   eax, qword ptr [edi+$00]
00585EB0   F0                     lock
00585EB1   2446                   and     al, $46
00585EB3   000C76                 add     [esi+esi*2], cl
00585EB6   46                     inc     esi
00585EB7   00CC                   add     ah, cl
00585EB9   7646                   jbe     00585F01
00585EBB   00C0                   add     al, al
00585EBD   7146                   jno     00585F05
00585EBF   00B0764600C8           add     [eax+$C8004676], dh
00585EC5   4F                     dec     edi
00585EC6   47                     inc     edi
00585EC7   0008                   add     [eax], cl
00585EC9   6A47                   push    $47
00585ECB   00A042460034           add     [eax+$34004642], ah
00585ED1   7D47                   jnl     00585F1A
00585ED3   004882                 add     [eax-$7E], cl
00585ED6   47                     inc     edi
00585ED7   00748047               add     [eax+eax*4+$47], dh
00585EDB   0038                   add     [eax], bh
00585EDD   43                     inc     ebx
00585EDE   46                     inc     esi
00585EDF   005C4346               add     [ebx+eax*2+$46], bl
00585EE3   00C4                   add     ah, al
00585EE5   834700C8               add     dword ptr [edi+$00], -$38
00585EE9   844700                 test    [edi+$00], al
00585EEC   94                     xchg    eax, esp
00585EED   41                     inc     ecx
00585EEE   46                     inc     esi
00585EEF   00A08C4600F8           add     [eax+$F800468C], ah
00585EF5   7746                   jnbe    00585F3D
00585EF7   0000                   add     [eax], al

00585EF9   8C4700                 mov     word ptr [edi+$00], es
00585EFC   148C                   adc     al, $8C
00585EFE   46                     inc     esi
00585EFF   006874                 add     [eax+$74], ch
00585F02   46                     inc     esi
00585F03   00648D46               add     [ebp+ecx*4+$46], ah
00585F07   0088A34700A8           add     [eax+$A80047A3], cl
00585F0D   49                     dec     ecx
00585F0E   47                     inc     edi
00585F0F   00584C                 add     [eax+$4C], bl
00585F12   47                     inc     edi
00585F13   004093                 add     [eax-$6D], al
00585F16   47                     inc     edi
00585F17   00905647000C           add     [eax+$C004756], dl
00585F1D   57                     push    edi
00585F1E   47                     inc     edi
00585F1F   00D4                   add     ah, dl
00585F21   A7                     cmpsd
00585F22   47                     inc     edi
00585F23   00A45347006CA2         add     [ebx+edx*2+$A26C0047], ah
00585F2A   47                     inc     edi
00585F2B   009C86470060A4         add     [esi+eax*4+$A4600047], bl
00585F32   47                     inc     edi
00585F33   00C4                   add     ah, al
00585F35   61                     popa
00585F36   47                     inc     edi
00585F37   009861580002           add     [eax+$2005861], bl
00585F3D   00835F580080           add     [ebx+$8000585F], al
00585F43   0300                   add     eax, [eax]
00585F45   0000                   add     [eax], al

*)
end;

end.