unit uFrmTransmissao;

interface

uses
  Windows, Messages, SysUtils, Classes, Graphics,
  Controls, Forms, Dialogs, StdCtrls
type
  TfrmTransmissao=class(TForm)
    ListBox: TListBox;
    sbtnConfirmar: TSpeedButton;
    ProgressBar: TProgressBar;
    procedure sbtnConfirmarClick(Sender : TObject);
    procedure _PROC_005A9013(Sender : TObject);
    procedure _PROC_005A90DE(Sender : TObject);
  private
    { Private declarations }
  public
    { Public declarations }
  end ;

var
  frmTransmissao: TfrmTransmissao;

{This file is generated by DeDe Ver 3.50.04 Copyright (c) 1999-2002 DaFixer}

implementation

{$R *.DFM}

procedure TfrmTransmissao.sbtnConfirmarClick(Sender : TObject);
begin
(*
005A8E54   55                     push    ebp
005A8E55   8BEC                   mov     ebp, esp
005A8E57   33C9                   xor     ecx, ecx
005A8E59   51                     push    ecx
005A8E5A   51                     push    ecx
005A8E5B   51                     push    ecx
005A8E5C   51                     push    ecx
005A8E5D   51                     push    ecx
005A8E5E   51                     push    ecx
005A8E5F   53                     push    ebx
005A8E60   56                     push    esi
005A8E61   57                     push    edi
005A8E62   8BD8                   mov     ebx, eax
005A8E64   33C0                   xor     eax, eax
005A8E66   55                     push    ebp

* Possible String Reference to: 'éŠÀåÿëã_^[‹å]Ã'
|
005A8E67   6805905A00             push    $005A9005

***** TRY
|
005A8E6C   64FF30                 push    dword ptr fs:[eax]
005A8E6F   648920                 mov     fs:[eax], esp
005A8E72   33D2                   xor     edx, edx
005A8E74   8BC3                   mov     eax, ebx

|
005A8E76   E8ED1CFCFF             call    0056AB68
005A8E7B   33D2                   xor     edx, edx

* Reference to control TfrmTransmissao.ListBox : TListBox
|
005A8E7D   8B8380030000           mov     eax, [ebx+$0380]
005A8E83   8B08                   mov     ecx, [eax]

* Possible reference to virtual method TListBox.OFFS_00E0
|
005A8E85   FF91E0000000           call    dword ptr [ecx+$00E0]
005A8E8B   E90D010000             jmp     005A8F9D
005A8E90   8D45F4                 lea     eax, [ebp-$0C]
005A8E93   50                     push    eax

* Reference to control TfrmTransmissao.ListBox : TListBox
|
005A8E94   8B8380030000           mov     eax, [ebx+$0380]
005A8E9A   8B10                   mov     edx, [eax]

* Possible reference to virtual method TListBox.OFFS_00DC
|
005A8E9C   FF92DC000000           call    dword ptr [edx+$00DC]
005A8EA2   8BD0                   mov     edx, eax
005A8EA4   8D4DF0                 lea     ecx, [ebp-$10]

* Reference to control TfrmTransmissao.ListBox : TListBox
|
005A8EA7   8B8380030000           mov     eax, [ebx+$0380]

* Reference to field TListBox.OFFS_0260
|
005A8EAD   8B8060020000           mov     eax, [eax+$0260]
005A8EB3   8B30                   mov     esi, [eax]
005A8EB5   FF560C                 call    dword ptr [esi+$0C]
005A8EB8   8B45F0                 mov     eax, [ebp-$10]
005A8EBB   B902000000             mov     ecx, $00000002
005A8EC0   BA07000000             mov     edx, $00000007

|
005A8EC5   E8FECEE5FF             call    00405DC8
005A8ECA   8B45F4                 mov     eax, [ebp-$0C]

|
005A8ECD   E87223E6FF             call    0040B244
005A8ED2   8BF0                   mov     esi, eax
005A8ED4   8D45EC                 lea     eax, [ebp-$14]
005A8ED7   50                     push    eax

* Reference to control TfrmTransmissao.ListBox : TListBox
|
005A8ED8   8B8380030000           mov     eax, [ebx+$0380]
005A8EDE   8B10                   mov     edx, [eax]

* Possible reference to virtual method TListBox.OFFS_00DC
|
005A8EE0   FF92DC000000           call    dword ptr [edx+$00DC]
005A8EE6   8BD0                   mov     edx, eax
005A8EE8   8D4DE8                 lea     ecx, [ebp-$18]

* Reference to control TfrmTransmissao.ListBox : TListBox
|
005A8EEB   8B8380030000           mov     eax, [ebx+$0380]

* Reference to field TListBox.OFFS_0260
|
005A8EF1   8B8060020000           mov     eax, [eax+$0260]
005A8EF7   8B38                   mov     edi, [eax]
005A8EF9   FF570C                 call    dword ptr [edi+$0C]
005A8EFC   8B45E8                 mov     eax, [ebp-$18]
005A8EFF   B903000000             mov     ecx, $00000003
005A8F04   BA15000000             mov     edx, $00000015

|
005A8F09   E8BACEE5FF             call    00405DC8
005A8F0E   8B45EC                 mov     eax, [ebp-$14]

|
005A8F11   E82E23E6FF             call    0040B244
005A8F16   8945F8                 mov     [ebp-$08], eax

* Reference to control TfrmTransmissao.ProgressBar : TProgressBar
|
005A8F19   8B8388030000           mov     eax, [ebx+$0388]
005A8F1F   50                     push    eax
005A8F20   8D45FC                 lea     eax, [ebp-$04]
005A8F23   50                     push    eax
005A8F24   A1B0FD6300             mov     eax, dword ptr [$0063FDB0]
005A8F29   8B00                   mov     eax, [eax]
005A8F2B   8B4DF8                 mov     ecx, [ebp-$08]
005A8F2E   8BD6                   mov     edx, esi

|
005A8F30   E81B7BFDFF             call    00580A50
005A8F35   84C0                   test    al, al
005A8F37   7540                   jnz     005A8F79
005A8F39   6A00                   push    $00
005A8F3B   0FB70D14905A00         movzx   ecx, word ptr [$005A9014]
005A8F42   B201                   mov     dl, $01
005A8F44   8B45FC                 mov     eax, [ebp-$04]

|
005A8F47   E85C7CEAFF             call    00450BA8
005A8F4C   6A00                   push    $00
005A8F4E   0FB70D14905A00         movzx   ecx, word ptr [$005A9014]
005A8F55   B201                   mov     dl, $01

* Possible String Reference to: 'Não Foi Possível Fazer Transmissão 
|                                para este Roteiro.Tentar Novamente.'
|
005A8F57   B820905A00             mov     eax, $005A9020

|
005A8F5C   E8477CEAFF             call    00450BA8
005A8F61   33D2                   xor     edx, edx

* Reference to control TfrmTransmissao.ProgressBar : TProgressBar
|
005A8F63   8B8388030000           mov     eax, [ebx+$0388]

* Reference to : TTabStrings._PROC_004C93E4()
|
005A8F69   E87604F2FF             call    004C93E4
005A8F6E   B201                   mov     dl, $01
005A8F70   8BC3                   mov     eax, ebx

|
005A8F72   E8F11BFCFF             call    0056AB68
005A8F77   EB69                   jmp     005A8FE2
005A8F79   33D2                   xor     edx, edx

* Reference to control TfrmTransmissao.ProgressBar : TProgressBar
|
005A8F7B   8B8388030000           mov     eax, [ebx+$0388]

* Reference to : TTabStrings._PROC_004C93E4()
|
005A8F81   E85E04F2FF             call    004C93E4
005A8F86   8BC3                   mov     eax, ebx

|
005A8F88   E8F7FBFFFF             call    005A8B84
005A8F8D   33D2                   xor     edx, edx

* Reference to control TfrmTransmissao.ListBox : TListBox
|
005A8F8F   8B8380030000           mov     eax, [ebx+$0380]
005A8F95   8B08                   mov     ecx, [eax]

* Possible reference to virtual method TListBox.OFFS_00E0
|
005A8F97   FF91E0000000           call    dword ptr [ecx+$00E0]

* Reference to control TfrmTransmissao.ListBox : TListBox
|
005A8F9D   8B8380030000           mov     eax, [ebx+$0380]
005A8FA3   8B10                   mov     edx, [eax]

* Possible reference to virtual method TListBox.OFFS_00DC
|
005A8FA5   FF92DC000000           call    dword ptr [edx+$00DC]
005A8FAB   40                     inc     eax
005A8FAC   0F85DEFEFFFF           jnz     005A8E90
005A8FB2   8BC3                   mov     eax, ebx

|
005A8FB4   E8CBFBFFFF             call    005A8B84
005A8FB9   84C0                   test    al, al
005A8FBB   751C                   jnz     005A8FD9
005A8FBD   6A00                   push    $00
005A8FBF   0FB70D14905A00         movzx   ecx, word ptr [$005A9014]
005A8FC6   B202                   mov     dl, $02

* Possible String Reference to: 'Não Existe Mais Nenhum Roteiro Para
|                                 Fazer Transmissão.'
|
005A8FC8   B870905A00             mov     eax, $005A9070

|
005A8FCD   E8D67BEAFF             call    00450BA8
005A8FD2   8BC3                   mov     eax, ebx

* Reference to : TApplication._PROC_0047A1C8()
|
005A8FD4   E8EF11EDFF             call    0047A1C8
005A8FD9   B201                   mov     dl, $01
005A8FDB   8BC3                   mov     eax, ebx

|
005A8FDD   E8861BFCFF             call    0056AB68
005A8FE2   33C0                   xor     eax, eax
005A8FE4   5A                     pop     edx
005A8FE5   59                     pop     ecx
005A8FE6   59                     pop     ecx
005A8FE7   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: '_^[‹å]Ã'
|
005A8FEA   680C905A00             push    $005A900C
005A8FEF   8D45E8                 lea     eax, [ebp-$18]
005A8FF2   BA04000000             mov     edx, $00000004

|
005A8FF7   E8CCC8E5FF             call    004058C8
005A8FFC   8D45FC                 lea     eax, [ebp-$04]

|
005A8FFF   E8A0C8E5FF             call    004058A4
005A9004   C3                     ret


|
005A9005   E98AC0E5FF             jmp     00405094
005A900A   EBE3                   jmp     005A8FEF

****** END
|
005A900C   5F                     pop     edi
005A900D   5E                     pop     esi
005A900E   5B                     pop     ebx
005A900F   8BE5                   mov     esp, ebp
005A9011   5D                     pop     ebp
005A9012   C3                     ret

*)
end;

procedure TfrmTransmissao._PROC_005A9013(Sender : TObject);
begin
(*
005A9013   000400                 add     [eax+eax], al
005A9016   0000                   add     [eax], al

*)
end;

procedure TfrmTransmissao._PROC_005A90DE(Sender : TObject);
begin
(*
005A90DE   47                     inc     edi
005A90DF   001C4B                 add     [ebx+ecx*2], bl
005A90E2   40                     inc     eax
005A90E3   000C8547005848         add     [$48580047+eax*4], cl
005A90EA   40                     inc     eax
005A90EB   00744840               add     [eax+ecx*2+$40], dh
005A90EF   00905547008C           add     [eax+$8C004755], dl
005A90F5   844600                 test    [esi+$00], al
005A90F8   845B47                 test    [ebx+$47], bl
005A90FB   000C31                 add     [ecx+esi], cl
005A90FE   42                     inc     edx
005A90FF   006C5747               add     [edi+edx*2+$47], ch
005A9103   00B8574700F4           add     [eax+$F4004757], bh
005A9109   58                     pop     eax
005A910A   47                     inc     edi
005A910B   00E8                   add     al, ch
005A910D   F8                     clc
005A910E   45                     inc     ebp
005A910F   0094C542008462         add     [ebp+eax*8+$62840042], dl
005A9116   47                     inc     edi
005A9117   0070C2                 add     [eax-$3E], dh
005A911A   42                     inc     edx
005A911B   0070AB                 add     [eax-$55], dh
005A911E   47                     inc     edi
005A911F   00E0                   add     al, ah
005A9121   51                     push    ecx
005A9122   47                     inc     edi
005A9123   00B07E4600BC           add     [eax+$BC00467E], dh
005A9129   844600                 test    [esi+$00], al
005A912C   08844600B0EB45         or      [esi+eax*2+$45EBB000], al
005A9133   002C79                 add     [ecx+edi*2], ch
005A9136   46                     inc     esi
005A9137   00B85E4700B8           add     [eax+$B800475E], bh
005A913D   7546                   jnz     005A9185
005A913F   00F0                   add     al, dh
005A9141   EA4500F4EA             jmp     $EAF40045
005A9146   45                     inc     ebp
005A9147   00AC5F47006C24         add     [edi+ebx*2+$246C0047], ch
005A914E   46                     inc     esi
005A914F   003CA8                 add     [eax+ebp*4], bh
005A9152   47                     inc     edi
005A9153   00CC                   add     ah, cl
005A9155   F8                     clc
005A9156   45                     inc     ebp
005A9157   002CED450058FA         add     [$FA580045+ebp*8], ch
005A915E   45                     inc     ebp
005A915F   00C8                   add     al, cl
005A9161   61                     popa
005A9162   47                     inc     edi
005A9163   008460470094FB         add     [eax+$FB940047], al
005A916A   45                     inc     ebp
005A916B   00C4                   add     ah, al
005A916D   624700                 bound   eax, qword ptr [edi+$00]
005A9170   F0                     lock
005A9171   2446                   and     al, $46
005A9173   000C76                 add     [esi+esi*2], cl
005A9176   46                     inc     esi
005A9177   00CC                   add     ah, cl
005A9179   7646                   jbe     005A91C1
005A917B   00C0                   add     al, al
005A917D   7146                   jno     005A91C5
005A917F   00B0764600C8           add     [eax+$C8004676], dh
005A9185   4F                     dec     edi
005A9186   47                     inc     edi
005A9187   0008                   add     [eax], cl
005A9189   6A47                   push    $47
005A918B   00A042460034           add     [eax+$34004642], ah
005A9191   7D47                   jnl     005A91DA
005A9193   004882                 add     [eax-$7E], cl
005A9196   47                     inc     edi
005A9197   00748047               add     [eax+eax*4+$47], dh
005A919B   0038                   add     [eax], bh
005A919D   43                     inc     ebx
005A919E   46                     inc     esi
005A919F   005C4346               add     [ebx+eax*2+$46], bl
005A91A3   00C4                   add     ah, al
005A91A5   834700C8               add     dword ptr [edi+$00], -$38
005A91A9   844700                 test    [edi+$00], al
005A91AC   94                     xchg    eax, esp
005A91AD   41                     inc     ecx
005A91AE   46                     inc     esi
005A91AF   00A08C4600F8           add     [eax+$F800468C], ah
005A91B5   7746                   jnbe    005A91FD
005A91B7   0000                   add     [eax], al

005A91B9   8C4700                 mov     word ptr [edi+$00], es
005A91BC   148C                   adc     al, $8C
005A91BE   46                     inc     esi
005A91BF   006874                 add     [eax+$74], ch
005A91C2   46                     inc     esi
005A91C3   00648D46               add     [ebp+ecx*4+$46], ah
005A91C7   0088A34700A8           add     [eax+$A80047A3], cl
005A91CD   49                     dec     ecx
005A91CE   47                     inc     edi
005A91CF   00584C                 add     [eax+$4C], bl
005A91D2   47                     inc     edi
005A91D3   004093                 add     [eax-$6D], al
005A91D6   47                     inc     edi
005A91D7   00905647000C           add     [eax+$C004756], dl
005A91DD   57                     push    edi
005A91DE   47                     inc     edi
005A91DF   00D4                   add     ah, dl
005A91E1   A7                     cmpsd
005A91E2   47                     inc     edi
005A91E3   00A45347006CA2         add     [ebx+edx*2+$A26C0047], ah
005A91EA   47                     inc     edi
005A91EB   009C86470060A4         add     [esi+eax*4+$A4600047], bl
005A91F2   47                     inc     edi
005A91F3   00C4                   add     ah, al
005A91F5   61                     popa
005A91F6   47                     inc     edi
005A91F7   00B8945A0003           add     [eax+$3005A94], bh
005A91FD   006792                 add     [edi-$6E], ah
005A9200   5A                     pop     edx
005A9201   008003000000           add     [eax+$0003], al
005A9207   0007                   add     [edi], al
005A9209   4C                     dec     esp
005A920A   697374426F7884         imul    esi, [ebx+$74], $84786F42
005A9211   0300                   add     eax, [eax]
005A9213   0001                   add     [ecx], al
005A9215   000D7362746E           add     [$6E746273], cl
005A921B   43                     inc     ebx
005A921C   6F                     outsd
005A921D   6E                     outsb
005A921E   6669726D6172           imul    si, word ptr [edx+$6D], $7261
005A9224   8803                   mov     [ebx], al
005A9226   0000                   add     [eax], al

*)
end;

end.