unit uFrmLogin;

interface

uses
  Windows, Messages, SysUtils, Classes, Graphics,
  Controls, Forms, Dialogs, StdCtrls
type
  TfrmLogin=class(TForm)
    TbChave: TTable;
    DataSource1: TDataSource;
    TbChavech_chave: TStringField;
    TbChavech_senha: TStringField;
    TbChavech_nome: TStringField;
    TbChavech_status: TBooleanField;
    BitBtSair: TBitBtn;
    BitBtEnter: TBitBtn;
    edNovaSenha: TEdit;
    Label4: TLabel;
    edSenha: TEdit;
    Label3: TLabel;
    edChave: TEdit;
    Label2: TLabel;
    Image1: TImage;
    procedure BitBtEnterClick(Sender : TObject);
    procedure FormShow(Sender : TObject);
    procedure BitBtSairClick(Sender : TObject);
    procedure ExtractDiskSerial(Sender : TObject);
    procedure edSenhaChange(Sender : TObject);
    procedure _PROC_0057BFFD(Sender : TObject);
    procedure _PROC_0057C3ED(Sender : TObject);
    procedure _PROC_0057CD0D(Sender : TObject);
  private
    { Private declarations }
  public
    { Public declarations }
  end ;

var
  frmLogin: TfrmLogin;

{This file is generated by DeDe Ver 3.50.04 Copyright (c) 1999-2002 DaFixer}

implementation

{$R *.DFM}

procedure TfrmLogin.BitBtEnterClick(Sender : TObject);
begin
(*
0057BAE4   55                     push    ebp
0057BAE5   8BEC                   mov     ebp, esp
0057BAE7   B909000000             mov     ecx, $00000009
0057BAEC   6A00                   push    $00
0057BAEE   6A00                   push    $00
0057BAF0   49                     dec     ecx
0057BAF1   75F9                   jnz     0057BAEC
0057BAF3   53                     push    ebx
0057BAF4   8BD8                   mov     ebx, eax
0057BAF6   33C0                   xor     eax, eax
0057BAF8   55                     push    ebp

* Possible String Reference to: 'éž‘èÿëœ[‹å]Ã'
|
0057BAF9   68F1BE5700             push    $0057BEF1

***** TRY
|
0057BAFE   64FF30                 push    dword ptr fs:[eax]
0057BB01   648920                 mov     fs:[eax], esp
0057BB04   8D55FC                 lea     edx, [ebp-$04]

* Reference to control TfrmLogin.edChave : TEdit
|
0057BB07   8B8390030000           mov     eax, [ebx+$0390]

|
0057BB0D   E8EE3FEEFF             call    0045FB00
0057BB12   8B45FC                 mov     eax, [ebp-$04]

* Possible String Reference to: 'STRATEGOS'
|
0057BB15   BA08BF5700             mov     edx, $0057BF08

|
0057BB1A   E895A1E8FF             call    00405CB4
0057BB1F   0F85FE000000           jnz     0057BC23
0057BB25   8D55F8                 lea     edx, [ebp-$08]

* Reference to control TfrmLogin.edSenha : TEdit
|
0057BB28   8B8388030000           mov     eax, [ebx+$0388]

|
0057BB2E   E8CD3FEEFF             call    0045FB00
0057BB33   8B45F8                 mov     eax, [ebp-$08]

* Possible String Reference to: 'STR'
|
0057BB36   BA1CBF5700             mov     edx, $0057BF1C

|
0057BB3B   E874A1E8FF             call    00405CB4
0057BB40   0F85DD000000           jnz     0057BC23
0057BB46   8D55F0                 lea     edx, [ebp-$10]

* Reference to control TfrmLogin.edNovaSenha : TEdit
|
0057BB49   8B8380030000           mov     eax, [ebx+$0380]

|
0057BB4F   E8AC3FEEFF             call    0045FB00
0057BB54   8B45F0                 mov     eax, [ebp-$10]
0057BB57   8D55F4                 lea     edx, [ebp-$0C]

|
0057BB5A   E8F5EDE8FF             call    0040A954
0057BB5F   8B45F4                 mov     eax, [ebp-$0C]
0057BB62   8945EC                 mov     [ebp-$14], eax
0057BB65   8B45EC                 mov     eax, [ebp-$14]
0057BB68   85C0                   test    eax, eax
0057BB6A   7405                   jz      0057BB71
0057BB6C   83E804                 sub     eax, +$04
0057BB6F   8B00                   mov     eax, [eax]
0057BB71   83F819                 cmp     eax, +$19
0057BB74   0F85A9000000           jnz     0057BC23
0057BB7A   A13CF86300             mov     eax, dword ptr [$0063F83C]
0057BB7F   8B00                   mov     eax, [eax]
0057BB81   8B8078030000           mov     eax, [eax+$0378]

|
0057BB87   E88429F2FF             call    0049E510

* Possible String Reference to: ' update dbo.sysconfig         set  
|                                  sy_date = getdate(),         sy_c
|                                have = ''
|
0057BB8C   6828BF5700             push    $0057BF28
0057BB91   8D55E4                 lea     edx, [ebp-$1C]

* Reference to control TfrmLogin.edNovaSenha : TEdit
|
0057BB94   8B8380030000           mov     eax, [ebx+$0380]

|
0057BB9A   E8613FEEFF             call    0045FB00
0057BB9F   FF75E4                 push    dword ptr [ebp-$1C]
0057BBA2   6880BF5700             push    $0057BF80
0057BBA7   8D45E8                 lea     eax, [ebp-$18]
0057BBAA   BA03000000             mov     edx, $00000003

|
0057BBAF   E874A0E8FF             call    00405C28
0057BBB4   8B55E8                 mov     edx, [ebp-$18]
0057BBB7   A13CF86300             mov     eax, dword ptr [$0063F83C]
0057BBBC   8B00                   mov     eax, [eax]
0057BBBE   8B8078030000           mov     eax, [eax+$0378]
0057BBC4   8B8048020000           mov     eax, [eax+$0248]
0057BBCA   8B08                   mov     ecx, [eax]
0057BBCC   FF512C                 call    dword ptr [ecx+$2C]
0057BBCF   A13CF86300             mov     eax, dword ptr [$0063F83C]
0057BBD4   8B00                   mov     eax, [eax]
0057BBD6   8B8078030000           mov     eax, [eax+$0378]

|
0057BBDC   E8B7EEF3FF             call    004BAA98
0057BBE1   6A00                   push    $00
0057BBE3   0FB70D84BF5700         movzx   ecx, word ptr [$0057BF84]
0057BBEA   B202                   mov     dl, $02

* Possible String Reference to: 'Chave atualizada.'
|
0057BBEC   B890BF5700             mov     eax, $0057BF90

|
0057BBF1   E8B24FEDFF             call    00450BA8
0057BBF6   33D2                   xor     edx, edx

* Reference to control TfrmLogin.edSenha : TEdit
|
0057BBF8   8B8388030000           mov     eax, [ebx+$0388]

|
0057BBFE   E82D3FEEFF             call    0045FB30
0057BC03   33D2                   xor     edx, edx

* Reference to control TfrmLogin.edNovaSenha : TEdit
|
0057BC05   8B8380030000           mov     eax, [ebx+$0380]

|
0057BC0B   E8203FEEFF             call    0045FB30

* Reference to control TfrmLogin.edSenha : TEdit
|
0057BC10   8B8388030000           mov     eax, [ebx+$0388]
0057BC16   8B10                   mov     edx, [eax]

* Possible reference to virtual method TEdit.OFFS_00D4
|
0057BC18   FF92D4000000           call    dword ptr [edx+$00D4]
0057BC1E   E964020000             jmp     0057BE87
0057BC23   8D55D8                 lea     edx, [ebp-$28]

* Reference to control TfrmLogin.edChave : TEdit
|
0057BC26   8B8390030000           mov     eax, [ebx+$0390]

|
0057BC2C   E8CF3EEEFF             call    0045FB00
0057BC31   8B45D8                 mov     eax, [ebp-$28]
0057BC34   8945DC                 mov     [ebp-$24], eax
0057BC37   C645E00B               mov     byte ptr [ebp-$20], $0B
0057BC3B   8D55DC                 lea     edx, [ebp-$24]
0057BC3E   33C9                   xor     ecx, ecx

* Reference to control TfrmLogin.TbChave : TTable
|
0057BC40   8B8360030000           mov     eax, [ebx+$0360]

|
0057BC46   E8B1D3F3FF             call    004B8FFC
0057BC4B   84C0                   test    al, al
0057BC4D   7533                   jnz     0057BC82
0057BC4F   6A00                   push    $00
0057BC51   0FB70D84BF5700         movzx   ecx, word ptr [$0057BF84]
0057BC58   B201                   mov     dl, $01

* Possible String Reference to: 'Chave não cadastrada. Contate super
|                                visor.'
|
0057BC5A   B8ACBF5700             mov     eax, $0057BFAC

|
0057BC5F   E8444FEDFF             call    00450BA8

* Reference to control TfrmLogin.edChave : TEdit
|
0057BC64   8B8390030000           mov     eax, [ebx+$0390]
0057BC6A   8B10                   mov     edx, [eax]

* Possible reference to virtual method TEdit.OFFS_00D4
|
0057BC6C   FF92D4000000           call    dword ptr [edx+$00D4]

* Reference to control TfrmLogin.edChave : TEdit
|
0057BC72   8B8390030000           mov     eax, [ebx+$0390]

|
0057BC78   E88B67ECFF             call    00442408
0057BC7D   E905020000             jmp     0057BE87
0057BC82   8D55D4                 lea     edx, [ebp-$2C]

* Reference to control TfrmLogin.edSenha : TEdit
|
0057BC85   8B8388030000           mov     eax, [ebx+$0388]

|
0057BC8B   E8703EEEFF             call    0045FB00
0057BC90   8B45D4                 mov     eax, [ebp-$2C]
0057BC93   50                     push    eax
0057BC94   8D55CC                 lea     edx, [ebp-$34]

* Reference to control TfrmLogin.TbChavech_senha : TStringField
|
0057BC97   8B836C030000           mov     eax, [ebx+$036C]

|
0057BC9D   E85278F1FF             call    004934F4
0057BCA2   8B45CC                 mov     eax, [ebp-$34]
0057BCA5   8D55D0                 lea     edx, [ebp-$30]

|
0057BCA8   E8EFE6E8FF             call    0040A39C
0057BCAD   8B55D0                 mov     edx, [ebp-$30]
0057BCB0   58                     pop     eax

|
0057BCB1   E8FE9FE8FF             call    00405CB4
0057BCB6   7433                   jz      0057BCEB
0057BCB8   6A00                   push    $00
0057BCBA   0FB70D84BF5700         movzx   ecx, word ptr [$0057BF84]
0057BCC1   B201                   mov     dl, $01

* Possible String Reference to: 'Senha não confere.'
|
0057BCC3   B8E0BF5700             mov     eax, $0057BFE0

|
0057BCC8   E8DB4EEDFF             call    00450BA8

* Reference to control TfrmLogin.edSenha : TEdit
|
0057BCCD   8B8388030000           mov     eax, [ebx+$0388]
0057BCD3   8B10                   mov     edx, [eax]

* Possible reference to virtual method TEdit.OFFS_00D4
|
0057BCD5   FF92D4000000           call    dword ptr [edx+$00D4]

* Reference to control TfrmLogin.edSenha : TEdit
|
0057BCDB   8B8388030000           mov     eax, [ebx+$0388]

|
0057BCE1   E82267ECFF             call    00442408
0057BCE6   E99C010000             jmp     0057BE87

* Reference to control TfrmLogin.TbChavech_status : TBooleanField
|
0057BCEB   8B8374030000           mov     eax, [ebx+$0374]
0057BCF1   8B10                   mov     edx, [eax]

* Possible reference to virtual method TBooleanField.OFFS_44
|
0057BCF3   FF5244                 call    dword ptr [edx+$44]
0057BCF6   84C0                   test    al, al
0057BCF8   7541                   jnz     0057BD3B
0057BCFA   6A00                   push    $00
0057BCFC   0FB70D84BF5700         movzx   ecx, word ptr [$0057BF84]
0057BD03   B202                   mov     dl, $02

* Possible String Reference to: 'Usuário inativo. Acesso não permiti
|                                do.'
|
0057BD05   B8FCBF5700             mov     eax, $0057BFFC

|
0057BD0A   E8994EEDFF             call    00450BA8

* Reference to control TfrmLogin.edSenha : TEdit
|
0057BD0F   8B8388030000           mov     eax, [ebx+$0388]
0057BD15   8B10                   mov     edx, [eax]

* Possible reference to virtual method TEdit.OFFS_00F0
|
0057BD17   FF92F0000000           call    dword ptr [edx+$00F0]

* Reference to control TfrmLogin.edChave : TEdit
|
0057BD1D   8B8390030000           mov     eax, [ebx+$0390]
0057BD23   8B10                   mov     edx, [eax]

* Possible reference to virtual method TEdit.OFFS_00D4
|
0057BD25   FF92D4000000           call    dword ptr [edx+$00D4]

* Reference to control TfrmLogin.edChave : TEdit
|
0057BD2B   8B8390030000           mov     eax, [ebx+$0390]

|
0057BD31   E8D266ECFF             call    00442408
0057BD36   E94C010000             jmp     0057BE87
0057BD3B   8D55C8                 lea     edx, [ebp-$38]

* Reference to control TfrmLogin.edNovaSenha : TEdit
|
0057BD3E   8B8380030000           mov     eax, [ebx+$0380]

|
0057BD44   E8B73DEEFF             call    0045FB00
0057BD49   837DC800               cmp     dword ptr [ebp-$38], +$00
0057BD4D   744F                   jz      0057BD9E
0057BD4F   6A00                   push    $00
0057BD51   0FB70D24C05700         movzx   ecx, word ptr [$0057C024]
0057BD58   B203                   mov     dl, $03

* Possible String Reference to: 'Confirma alteração da senha?'
|
0057BD5A   B830C05700             mov     eax, $0057C030

|
0057BD5F   E8444EEDFF             call    00450BA8
0057BD64   83F806                 cmp     eax, +$06
0057BD67   7535                   jnz     0057BD9E

* Reference to control TfrmLogin.TbChave : TTable
|
0057BD69   8B8360030000           mov     eax, [ebx+$0360]

|
0057BD6F   E8A853F2FF             call    004A111C
0057BD74   8D55C4                 lea     edx, [ebp-$3C]

* Reference to control TfrmLogin.edNovaSenha : TEdit
|
0057BD77   8B8380030000           mov     eax, [ebx+$0380]

|
0057BD7D   E87E3DEEFF             call    0045FB00
0057BD82   8B55C4                 mov     edx, [ebp-$3C]

* Reference to control TfrmLogin.TbChavech_senha : TStringField
|
0057BD85   8B836C030000           mov     eax, [ebx+$036C]

|
0057BD8B   E8B083F1FF             call    00494140

* Reference to control TfrmLogin.TbChave : TTable
|
0057BD90   8B8360030000           mov     eax, [ebx+$0360]
0057BD96   8B10                   mov     edx, [eax]

* Possible reference to virtual method TTable.OFFS_0270
|
0057BD98   FF9270020000           call    dword ptr [edx+$0270]
0057BD9E   8D55C0                 lea     edx, [ebp-$40]

* Reference to control TfrmLogin.edChave : TEdit
|
0057BDA1   8B8390030000           mov     eax, [ebx+$0390]

|
0057BDA7   E8543DEEFF             call    0045FB00
0057BDAC   8B55C0                 mov     edx, [ebp-$40]
0057BDAF   A13CF86300             mov     eax, dword ptr [$0063F83C]
0057BDB4   8B00                   mov     eax, [eax]
0057BDB6   05AC030000             add     eax, +$000003AC

|
0057BDBB   E8389BE8FF             call    004058F8
0057BDC0   8D55BC                 lea     edx, [ebp-$44]

* Reference to control TfrmLogin.edSenha : TEdit
|
0057BDC3   8B8388030000           mov     eax, [ebx+$0388]

|
0057BDC9   E8323DEEFF             call    0045FB00
0057BDCE   8B55BC                 mov     edx, [ebp-$44]
0057BDD1   A13CF86300             mov     eax, dword ptr [$0063F83C]
0057BDD6   8B00                   mov     eax, [eax]
0057BDD8   05B0030000             add     eax, +$000003B0

|
0057BDDD   E8169BE8FF             call    004058F8

* Reference to field TfrmLogin.OFFS_0294
|
0057BDE2   C7839402000001000000   mov     dword ptr [ebx+$0294], $00000001
0057BDEC   A13CF86300             mov     eax, dword ptr [$0063F83C]
0057BDF1   8B00                   mov     eax, [eax]
0057BDF3   8B80B4030000           mov     eax, [eax+$03B4]

|
0057BDF9   E872F8E8FF             call    0040B670
0057BDFE   84C0                   test    al, al
0057BE00   7552                   jnz     0057BE54
0057BE02   6A00                   push    $00

* Possible String Reference to: ' Não foi encontrado o arquivo "LOGO
|                                .BMP" no diretório                 
|                                "'
|
0057BE04   6858C05700             push    $0057C058
0057BE09   A13CF86300             mov     eax, dword ptr [$0063F83C]
0057BE0E   8B00                   mov     eax, [eax]
0057BE10   FFB0B4030000           push    dword ptr [eax+$03B4]

* Possible String Reference to: '".'
|
0057BE16   68ACC05700             push    $0057C0AC
0057BE1B   68B8C05700             push    $0057C0B8
0057BE20   68B8C05700             push    $0057C0B8

* Possible String Reference to: 'Por favor coloque o logotipo '
|
0057BE25   68C4C05700             push    $0057C0C4

* Possible String Reference to: ' no diretório designado acima.'
|
0057BE2A   68ECC05700             push    $0057C0EC
0057BE2F   8D45B8                 lea     eax, [ebp-$48]
0057BE32   BA07000000             mov     edx, $00000007

|
0057BE37   E8EC9DE8FF             call    00405C28
0057BE3C   8B45B8                 mov     eax, [ebp-$48]
0057BE3F   0FB70D84BF5700         movzx   ecx, word ptr [$0057BF84]
0057BE46   B202                   mov     dl, $02

|
0057BE48   E85B4DEDFF             call    00450BA8
0057BE4D   8BC3                   mov     eax, ebx

* Reference to : TApplication._PROC_0047A1C8()
|
0057BE4F   E874E3EFFF             call    0047A1C8
0057BE54   A13CF86300             mov     eax, dword ptr [$0063F83C]
0057BE59   8B00                   mov     eax, [eax]

|
0057BE5B   E8BC290B00             call    0062E81C
0057BE60   84C0                   test    al, al
0057BE62   751C                   jnz     0057BE80
0057BE64   6A00                   push    $00
0057BE66   0FB70D84BF5700         movzx   ecx, word ptr [$0057BF84]
0057BE6D   B202                   mov     dl, $02

* Possible String Reference to: 'Esta versão do Sistema OnPlace está
|                                 desatualizada.Atualize o Sistema O
|                                nPlace.'
|
0057BE6F   B814C15700             mov     eax, $0057C114

|
0057BE74   E82F4DEDFF             call    00450BA8
0057BE79   8BC3                   mov     eax, ebx

* Reference to : TApplication._PROC_0047A1C8()
|
0057BE7B   E848E3EFFF             call    0047A1C8
0057BE80   8BC3                   mov     eax, ebx

|
0057BE82   E865050000             call    0057C3EC
0057BE87   33C0                   xor     eax, eax
0057BE89   5A                     pop     edx
0057BE8A   59                     pop     ecx
0057BE8B   59                     pop     ecx
0057BE8C   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: '[‹å]Ã'
|
0057BE8F   68F8BE5700             push    $0057BEF8
0057BE94   8D45B8                 lea     eax, [ebp-$48]

|
0057BE97   E8089AE8FF             call    004058A4
0057BE9C   8D45BC                 lea     eax, [ebp-$44]
0057BE9F   BA04000000             mov     edx, $00000004

|
0057BEA4   E81F9AE8FF             call    004058C8
0057BEA9   8D45CC                 lea     eax, [ebp-$34]
0057BEAC   BA02000000             mov     edx, $00000002

|
0057BEB1   E8129AE8FF             call    004058C8
0057BEB6   8D45D4                 lea     eax, [ebp-$2C]
0057BEB9   BA02000000             mov     edx, $00000002

|
0057BEBE   E8059AE8FF             call    004058C8
0057BEC3   8D45E4                 lea     eax, [ebp-$1C]

|
0057BEC6   E8D999E8FF             call    004058A4
0057BECB   8D45E8                 lea     eax, [ebp-$18]

|
0057BECE   E8D199E8FF             call    004058A4
0057BED3   8D45F0                 lea     eax, [ebp-$10]

|
0057BED6   E8C999E8FF             call    004058A4
0057BEDB   8D45F4                 lea     eax, [ebp-$0C]

|
0057BEDE   E8C199E8FF             call    004058A4
0057BEE3   8D45F8                 lea     eax, [ebp-$08]
0057BEE6   BA02000000             mov     edx, $00000002

|
0057BEEB   E8D899E8FF             call    004058C8
0057BEF0   C3                     ret


|
0057BEF1   E99E91E8FF             jmp     00405094
0057BEF6   EB9C                   jmp     0057BE94

****** END
|
0057BEF8   5B                     pop     ebx
0057BEF9   8BE5                   mov     esp, ebp
0057BEFB   5D                     pop     ebp
0057BEFC   C3                     ret

*)
end;

procedure TfrmLogin.FormShow(Sender : TObject);
begin
(*
0057C164   55                     push    ebp
0057C165   8BEC                   mov     ebp, esp
0057C167   6A00                   push    $00
0057C169   6A00                   push    $00
0057C16B   53                     push    ebx
0057C16C   8BD8                   mov     ebx, eax
0057C16E   33C0                   xor     eax, eax
0057C170   55                     push    ebp
0057C171   6871C25700             push    $0057C271

***** TRY
|
0057C176   64FF30                 push    dword ptr fs:[eax]
0057C179   648920                 mov     fs:[eax], esp
0057C17C   8D4DFC                 lea     ecx, [ebp-$04]
0057C17F   BA88C25700             mov     edx, $0057C288
0057C184   8BC3                   mov     eax, ebx

* Reference to : TfrmLogin.ExtractDiskSerial()
|
0057C186   E8BD010000             call    0057C348
0057C18B   8B45FC                 mov     eax, [ebp-$04]

* Possible String Reference to: '54D98C58'
|
0057C18E   BA94C25700             mov     edx, $0057C294

|
0057C193   E81C9BE8FF             call    00405CB4
0057C198   743C                   jz      0057C1D6
0057C19A   8B45FC                 mov     eax, [ebp-$04]

* Possible String Reference to: '90C9134C'
|
0057C19D   BAA8C25700             mov     edx, $0057C2A8

|
0057C1A2   E80D9BE8FF             call    00405CB4
0057C1A7   742D                   jz      0057C1D6
0057C1A9   8B45FC                 mov     eax, [ebp-$04]

* Possible String Reference to: 'CC7BD948'
|
0057C1AC   BABCC25700             mov     edx, $0057C2BC

|
0057C1B1   E8FE9AE8FF             call    00405CB4
0057C1B6   741E                   jz      0057C1D6
0057C1B8   8B45FC                 mov     eax, [ebp-$04]

* Possible String Reference to: '009878A0'
|
0057C1BB   BAD0C25700             mov     edx, $0057C2D0

|
0057C1C0   E8EF9AE8FF             call    00405CB4
0057C1C5   740F                   jz      0057C1D6
0057C1C7   8B45FC                 mov     eax, [ebp-$04]

* Possible String Reference to: 'D8AE7471'
|
0057C1CA   BAE4C25700             mov     edx, $0057C2E4

|
0057C1CF   E8E09AE8FF             call    00405CB4
0057C1D4   7542                   jnz     0057C218

* Possible String Reference to: 'ALFREDO'
|
0057C1D6   BAF8C25700             mov     edx, $0057C2F8

* Reference to control TfrmLogin.edChave : TEdit
|
0057C1DB   8B8390030000           mov     eax, [ebx+$0390]

|
0057C1E1   E84A39EEFF             call    0045FB30

* Possible String Reference to: '270572'
|
0057C1E6   BA08C35700             mov     edx, $0057C308

* Reference to control TfrmLogin.edSenha : TEdit
|
0057C1EB   8B8388030000           mov     eax, [ebx+$0388]

|
0057C1F1   E83A39EEFF             call    0045FB30
0057C1F6   8D55F8                 lea     edx, [ebp-$08]

* Reference to control TfrmLogin.edChave : TEdit
|
0057C1F9   8B8390030000           mov     eax, [ebx+$0390]

|
0057C1FF   E8FC38EEFF             call    0045FB00
0057C204   8B55F8                 mov     edx, [ebp-$08]
0057C207   A13CF86300             mov     eax, dword ptr [$0063F83C]
0057C20C   8B00                   mov     eax, [eax]
0057C20E   05AC030000             add     eax, +$000003AC

|
0057C213   E8E096E8FF             call    004058F8

* Reference to control TfrmLogin.TbChave : TTable
|
0057C218   8B8360030000           mov     eax, [ebx+$0360]

* Reference to field TTable.OFFS_009D
|
0057C21E   80B89D00000000         cmp     byte ptr [eax+$009D], $00
0057C225   7505                   jnz     0057C22C

|
0057C227   E8D022F2FF             call    0049E4FC
0057C22C   A13CF86300             mov     eax, dword ptr [$0063F83C]
0057C231   8B00                   mov     eax, [eax]
0057C233   8B90AC030000           mov     edx, [eax+$03AC]

* Reference to control TfrmLogin.edChave : TEdit
|
0057C239   8B8390030000           mov     eax, [ebx+$0390]

|
0057C23F   E8EC38EEFF             call    0045FB30

* Possible String Reference to: 'Versão 8.9.45 de 01/12/2009'
|
0057C244   BA18C35700             mov     edx, $0057C318
0057C249   A124406400             mov     eax, dword ptr [$00644024]

|
0057C24E   E8DD38EEFF             call    0045FB30
0057C253   33C0                   xor     eax, eax
0057C255   5A                     pop     edx
0057C256   59                     pop     ecx
0057C257   59                     pop     ecx
0057C258   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: '[YY]Ã'
|
0057C25B   6878C25700             push    $0057C278
0057C260   8D45F8                 lea     eax, [ebp-$08]

|
0057C263   E83C96E8FF             call    004058A4
0057C268   8D45FC                 lea     eax, [ebp-$04]

|
0057C26B   E83496E8FF             call    004058A4
0057C270   C3                     ret


|
0057C271   E91E8EE8FF             jmp     00405094
0057C276   EBE8                   jmp     0057C260

****** END
|
0057C278   5B                     pop     ebx
0057C279   59                     pop     ecx
0057C27A   59                     pop     ecx
0057C27B   5D                     pop     ebp
0057C27C   C3                     ret

*)
end;

procedure TfrmLogin.BitBtSairClick(Sender : TObject);
begin
(*
0057C334   A13CF86300             mov     eax, dword ptr [$0063F83C]
0057C339   8B00                   mov     eax, [eax]
0057C33B   05AC030000             add     eax, +$000003AC

|
0057C340   E85F95E8FF             call    004058A4
0057C345   C3                     ret

*)
end;

procedure TfrmLogin.ExtractDiskSerial(Sender : TObject);
begin
(*
0057C348   55                     push    ebp
0057C349   8BEC                   mov     ebp, esp
0057C34B   83C4E0                 add     esp, -$20
0057C34E   53                     push    ebx
0057C34F   33DB                   xor     ebx, ebx
0057C351   895DE0                 mov     [ebp-$20], ebx
0057C354   8BD9                   mov     ebx, ecx
0057C356   8955FC                 mov     [ebp-$04], edx
0057C359   8B45FC                 mov     eax, [ebp-$04]

|
0057C35C   E8F799E8FF             call    00405D58
0057C361   33C0                   xor     eax, eax
0057C363   55                     push    ebp
0057C364   68D4C35700             push    $0057C3D4

***** TRY
|
0057C369   64FF30                 push    dword ptr fs:[eax]
0057C36C   648920                 mov     fs:[eax], esp
0057C36F   6A00                   push    $00
0057C371   6A00                   push    $00
0057C373   8D45F0                 lea     eax, [ebp-$10]
0057C376   50                     push    eax
0057C377   8D45F4                 lea     eax, [ebp-$0C]
0057C37A   50                     push    eax
0057C37B   8D45F8                 lea     eax, [ebp-$08]
0057C37E   50                     push    eax
0057C37F   6A0C                   push    $0C
0057C381   8D45E4                 lea     eax, [ebp-$1C]
0057C384   50                     push    eax
0057C385   8D45E0                 lea     eax, [ebp-$20]

* Possible String Reference to: ':\'
|
0057C388   B9E8C35700             mov     ecx, $0057C3E8
0057C38D   8B55FC                 mov     edx, [ebp-$04]

|
0057C390   E81F98E8FF             call    00405BB4
0057C395   8B45E0                 mov     eax, [ebp-$20]

|
0057C398   E8CB99E8FF             call    00405D68
0057C39D   50                     push    eax

* Reference to: kernel32.GetVolumeInformationA()
|
0057C39E   E889C0E8FF             call    0040842C
0057C3A3   8B45F8                 mov     eax, [ebp-$08]
0057C3A6   33D2                   xor     edx, edx
0057C3A8   52                     push    edx
0057C3A9   50                     push    eax
0057C3AA   8BD3                   mov     edx, ebx
0057C3AC   B808000000             mov     eax, $00000008

|
0057C3B1   E85EEEE8FF             call    0040B214
0057C3B6   33C0                   xor     eax, eax
0057C3B8   5A                     pop     edx
0057C3B9   59                     pop     ecx
0057C3BA   59                     pop     ecx
0057C3BB   648910                 mov     fs:[eax], edx

****** FINALLY
|
0057C3BE   68DBC35700             push    $0057C3DB
0057C3C3   8D45E0                 lea     eax, [ebp-$20]

|
0057C3C6   E8D994E8FF             call    004058A4
0057C3CB   8D45FC                 lea     eax, [ebp-$04]

|
0057C3CE   E8D194E8FF             call    004058A4
0057C3D3   C3                     ret


|
0057C3D4   E9BB8CE8FF             jmp     00405094
0057C3D9   EBE8                   jmp     0057C3C3

****** END
|
0057C3DB   5B                     pop     ebx
0057C3DC   8BE5                   mov     esp, ebp
0057C3DE   5D                     pop     ebp
0057C3DF   C3                     ret

*)
end;

procedure TfrmLogin.edSenhaChange(Sender : TObject);
begin
(*
0057C6C0   55                     push    ebp
0057C6C1   8BEC                   mov     ebp, esp
0057C6C3   6A00                   push    $00
0057C6C5   6A00                   push    $00
0057C6C7   53                     push    ebx
0057C6C8   8BD8                   mov     ebx, eax
0057C6CA   33C0                   xor     eax, eax
0057C6CC   55                     push    ebp
0057C6CD   685CC75700             push    $0057C75C

***** TRY
|
0057C6D2   64FF30                 push    dword ptr fs:[eax]
0057C6D5   648920                 mov     fs:[eax], esp
0057C6D8   33D2                   xor     edx, edx

* Reference to control TfrmLogin.edNovaSenha : TEdit
|
0057C6DA   8B8380030000           mov     eax, [ebx+$0380]

|
0057C6E0   E84B34EEFF             call    0045FB30
0057C6E5   8D55FC                 lea     edx, [ebp-$04]

* Reference to control TfrmLogin.edChave : TEdit
|
0057C6E8   8B8390030000           mov     eax, [ebx+$0390]

|
0057C6EE   E80D34EEFF             call    0045FB00
0057C6F3   8B45FC                 mov     eax, [ebp-$04]

* Possible String Reference to: 'STRATEGOS'
|
0057C6F6   BA70C75700             mov     edx, $0057C770

|
0057C6FB   E8B495E8FF             call    00405CB4
0057C700   752F                   jnz     0057C731
0057C702   8D55F8                 lea     edx, [ebp-$08]

* Reference to control TfrmLogin.edSenha : TEdit
|
0057C705   8B8388030000           mov     eax, [ebx+$0388]

|
0057C70B   E8F033EEFF             call    0045FB00
0057C710   8B45F8                 mov     eax, [ebp-$08]

* Possible String Reference to: 'STR'
|
0057C713   BA84C75700             mov     edx, $0057C784

|
0057C718   E89795E8FF             call    00405CB4
0057C71D   7512                   jnz     0057C731
0057C71F   BA19000000             mov     edx, $00000019

* Reference to control TfrmLogin.edNovaSenha : TEdit
|
0057C724   8B8380030000           mov     eax, [ebx+$0380]

|
0057C72A   E8515AECFF             call    00442180
0057C72F   EB10                   jmp     0057C741
0057C731   BA0F000000             mov     edx, $0000000F

* Reference to control TfrmLogin.edNovaSenha : TEdit
|
0057C736   8B8380030000           mov     eax, [ebx+$0380]

|
0057C73C   E83F5AECFF             call    00442180
0057C741   33C0                   xor     eax, eax
0057C743   5A                     pop     edx
0057C744   59                     pop     ecx
0057C745   59                     pop     ecx
0057C746   648910                 mov     fs:[eax], edx

****** FINALLY
|
0057C749   6863C75700             push    $0057C763
0057C74E   8D45F8                 lea     eax, [ebp-$08]
0057C751   BA02000000             mov     edx, $00000002

|
0057C756   E86D91E8FF             call    004058C8
0057C75B   C3                     ret


|
0057C75C   E93389E8FF             jmp     00405094
0057C761   EBEB                   jmp     0057C74E

****** END
|
0057C763   5B                     pop     ebx
0057C764   59                     pop     ecx
0057C765   59                     pop     ecx
0057C766   5D                     pop     ebp
0057C767   C3                     ret

*)
end;

procedure TfrmLogin._PROC_0057BFFD(Sender : TObject);
begin
(*
0057BFFD   7375                   jnb     0057C074
0057BFFF   E172                   loope   +$72
0057C001   696F20696E6174         imul    ebp, [edi+$20], $74616E69
0057C008   69766F2E204163         imul    esi, [esi+$6F], $6341202E
0057C00F   657373                 jnb     0057C085
0057C012   6F                     outsd
0057C013   206EE3                 and     [esi-$1D], ch
0057C016   6F                     outsd
0057C017   207065                 and     [eax+$65], dh
0057C01A   726D                   jb      0057C089
0057C01C   697469646F2E0000       imul    esi, [ecx+ebp*2+$64], $00002E6F
0057C024   0300                   add     eax, [eax]
0057C026   0000                   add     [eax], al

0057C028   FFFF                   DB  $FF, $FF  //      
0057C02A   FFFF                   DB  $FF, $FF  //      
0057C02C   1C00                   sbb     al, $00
0057C02E   0000                   add     [eax], al

0057C030   43                     inc     ebx
0057C031   6F                     outsd
0057C032   6E                     outsb
0057C033   6669726D6120           imul    si, word ptr [edx+$6D], $2061
0057C039   61                     popa
0057C03A   6C                     insb
0057C03B   7465                   jz      0057C0A2
0057C03D   7261                   jb      0057C0A0
0057C03F   E7E3                   out     $E3, eax
0057C041   6F                     outsd
0057C042   20646120               and     [ecx+$20], ah
0057C046   7365                   jnb     0057C0AD
0057C048   6E                     outsb
0057C049   68613F0000             push    $00003F61
0057C04E   0000                   add     [eax], al

0057C050   FFFF                   DB  $FF, $FF  //      
0057C052   FFFF                   DB  $FF, $FF  //      
0057C054   48                     dec     eax
0057C055   0000                   add     [eax], al

0057C057   0020                   add     [eax], ah
0057C059   4E                     dec     esi
0057C05A   E36F                   jcxz    +$6F
0057C05C   20666F                 and     [esi+$6F], ah
0057C05F   6920656E636F           imul    esp, [eax], $6F636E65
0057C065   6E                     outsb
0057C066   7472                   jz      0057C0DA
0057C068   61                     popa
0057C069   646F                   outsd
0057C06B   206F20                 and     [edi+$20], ch
0057C06E   61                     popa
0057C06F   7271                   jb      0057C0E2
0057C071   7569                   jnz     0057C0DC
0057C073   766F                   jbe     0057C0E4
0057C075   2022                   and     [edx], ah
0057C077   4C                     dec     esp
0057C078   4F                     dec     edi
0057C079   47                     inc     edi
0057C07A   4F                     dec     edi
0057C07B   2E42                   inc     edx
0057C07D   4D                     dec     ebp
0057C07E   50                     push    eax
0057C07F   2220                   and     ah, byte ptr [eax]
0057C081   6E                     outsb
0057C082   6F                     outsd
0057C083   20646972               and     [ecx+ebp*2+$72], ah
0057C087   6574F3                 jz      0057C07D
0057C08A   7269                   jb      0057C0F5
0057C08C   6F                     outsd
0057C08D   200D20202020           and     [$20202020], cl
0057C093   2020                   and     [eax], ah
0057C095   2020                   and     [eax], ah
0057C097   2020                   and     [eax], ah
0057C099   2020                   and     [eax], ah
0057C09B   2020                   and     [eax], ah
0057C09D   2020                   and     [eax], ah
0057C09F   2200                   and     al, byte ptr [eax]
0057C0A1   0000                   add     [eax], al

0057C0A3   00FF                   add     bh, bh
0057C0A5   FFFF                   DB  $FF, $FF  //      
0057C0A7   FF02                   inc     dword ptr [edx]
0057C0A9   0000                   add     [eax], al

0057C0AB   0022                   add     [edx], ah
0057C0AD   2E0000                 add     cs:[eax], al
0057C0B0   FFFF                   DB  $FF, $FF  //      
0057C0B2   FFFF                   DB  $FF, $FF  //      
0057C0B4   0100                   add     [eax], eax
0057C0B6   0000                   add     [eax], al

0057C0B8   0D000000FF             or      eax, $FF000000
0057C0BD   FFFF                   DB  $FF, $FF  //      
0057C0BF   FF1D00000050           call    [$50000000]
0057C0C5   6F                     outsd
0057C0C6   7220                   jb      0057C0E8
0057C0C8   6661                   popa
0057C0CA   766F                   jbe     0057C13B
0057C0CC   7220                   jb      0057C0EE
0057C0CE   636F6C                 arpl    [edi+$6C], bp
0057C0D1   6F                     outsd
0057C0D2   7175                   jno     0057C149
0057C0D4   65206F20               and     gs:[edi+$20], ch
0057C0D8   6C                     insb
0057C0D9   6F                     outsd
0057C0DA   676F                   outsd
0057C0DC   7469                   jz      0057C147
0057C0DE   706F                   jo      0057C14F
0057C0E0   2000                   and     [eax], al
0057C0E2   0000                   add     [eax], al

0057C0E4   FFFF                   DB  $FF, $FF  //      
0057C0E6   FFFF                   DB  $FF, $FF  //      
0057C0E8   1E                     push    ds
0057C0E9   0000                   add     [eax], al

0057C0EB   0020                   add     [eax], ah
0057C0ED   6E                     outsb
0057C0EE   6F                     outsd
0057C0EF   20646972               and     [ecx+ebp*2+$72], ah
0057C0F3   6574F3                 jz      0057C0E9
0057C0F6   7269                   jb      0057C161
0057C0F8   6F                     outsd
0057C0F9   20646573               and     [ebp+$73], ah
0057C0FD   69676E61646F20         imul    esp, [edi+$6E], $206F6461
0057C104   61                     popa
0057C105   63696D                 arpl    [ecx+$6D], bp
0057C108   61                     popa
0057C109   2E0000                 add     cs:[eax], al
0057C10C   FFFF                   DB  $FF, $FF  //      
0057C10E   FFFF                   DB  $FF, $FF  //      
0057C110   4E                     dec     esi
0057C111   0000                   add     [eax], al

0057C113   004573                 add     [ebp+$73], al
0057C116   7461                   jz      0057C179
0057C118   207665                 and     [esi+$65], dh
0057C11B   7273                   jb      0057C190
0057C11D   E36F                   jcxz    +$6F
0057C11F   20646F20               and     [edi+ebp*2+$20], ah
0057C123   53                     push    ebx
0057C124   697374656D6120         imul    esi, [ebx+$74], $20616D65
0057C12B   4F                     dec     edi
0057C12C   6E                     outsb
0057C12D   50                     push    eax
0057C12E   6C                     insb
0057C12F   61                     popa
0057C130   636520                 arpl    [ebp+$20], sp
0057C133   657374                 jnb     0057C1AA
0057C136   E120                   loope   +$20
0057C138   64657361               jnb     0057C19D
0057C13C   7475                   jz      0057C1B3
0057C13E   61                     popa
0057C13F   6C                     insb
0057C140   697A6164612E0D         imul    edi, [edx+$61], $0D2E6164
0057C147   41                     inc     ecx
0057C148   7475                   jz      0057C1BF
0057C14A   61                     popa
0057C14B   6C                     insb
0057C14C   697A65206F2053         imul    edi, [edx+$65], $53206F20
0057C153   697374656D6120         imul    esi, [ebx+$74], $20616D65
0057C15A   4F                     dec     edi
0057C15B   6E                     outsb
0057C15C   50                     push    eax
0057C15D   6C                     insb
0057C15E   61                     popa
0057C15F   63652E                 arpl    [ebp+$2E], sp
0057C162   0000                   add     [eax], al

0057C164   55                     push    ebp
0057C165   8BEC                   mov     ebp, esp
0057C167   6A00                   push    $00
0057C169   6A00                   push    $00
0057C16B   53                     push    ebx
0057C16C   8BD8                   mov     ebx, eax
0057C16E   33C0                   xor     eax, eax
0057C170   55                     push    ebp
0057C171   6871C25700             push    $0057C271

***** TRY
|
0057C176   64FF30                 push    dword ptr fs:[eax]
0057C179   648920                 mov     fs:[eax], esp
0057C17C   8D4DFC                 lea     ecx, [ebp-$04]
0057C17F   BA88C25700             mov     edx, $0057C288
0057C184   8BC3                   mov     eax, ebx

* Reference to : TfrmLogin.ExtractDiskSerial()
|
0057C186   E8BD010000             call    0057C348
0057C18B   8B45FC                 mov     eax, [ebp-$04]

* Possible String Reference to: '54D98C58'
|
0057C18E   BA94C25700             mov     edx, $0057C294

|
0057C193   E81C9BE8FF             call    00405CB4
0057C198   743C                   jz      0057C1D6
0057C19A   8B45FC                 mov     eax, [ebp-$04]

* Possible String Reference to: '90C9134C'
|
0057C19D   BAA8C25700             mov     edx, $0057C2A8

|
0057C1A2   E80D9BE8FF             call    00405CB4
0057C1A7   742D                   jz      0057C1D6
0057C1A9   8B45FC                 mov     eax, [ebp-$04]

* Possible String Reference to: 'CC7BD948'
|
0057C1AC   BABCC25700             mov     edx, $0057C2BC

|
0057C1B1   E8FE9AE8FF             call    00405CB4
0057C1B6   741E                   jz      0057C1D6
0057C1B8   8B45FC                 mov     eax, [ebp-$04]

* Possible String Reference to: '009878A0'
|
0057C1BB   BAD0C25700             mov     edx, $0057C2D0

|
0057C1C0   E8EF9AE8FF             call    00405CB4
0057C1C5   740F                   jz      0057C1D6
0057C1C7   8B45FC                 mov     eax, [ebp-$04]

* Possible String Reference to: 'D8AE7471'
|
0057C1CA   BAE4C25700             mov     edx, $0057C2E4

|
0057C1CF   E8E09AE8FF             call    00405CB4
0057C1D4   7542                   jnz     0057C218

* Possible String Reference to: 'ALFREDO'
|
0057C1D6   BAF8C25700             mov     edx, $0057C2F8

* Reference to control qryGrupo : N.A.
|
0057C1DB   8B8390030000           mov     eax, [ebx+$0390]

|
0057C1E1   E84A39EEFF             call    0045FB30

* Possible String Reference to: '270572'
|
0057C1E6   BA08C35700             mov     edx, $0057C308

* Reference to control cmbGrupo : N.A.
|
0057C1EB   8B8388030000           mov     eax, [ebx+$0388]

|
0057C1F1   E83A39EEFF             call    0045FB30
0057C1F6   8D55F8                 lea     edx, [ebp-$08]

* Reference to control qryGrupo : N.A.
|
0057C1F9   8B8390030000           mov     eax, [ebx+$0390]

|
0057C1FF   E8FC38EEFF             call    0045FB00
0057C204   8B55F8                 mov     edx, [ebp-$08]
0057C207   A13CF86300             mov     eax, dword ptr [$0063F83C]
0057C20C   8B00                   mov     eax, [eax]
0057C20E   05AC030000             add     eax, +$000003AC

|
0057C213   E8E096E8FF             call    004058F8
0057C218   8B8360030000           mov     eax, [ebx+$0360]
0057C21E   80B89D00000000         cmp     byte ptr [eax+$009D], $00
0057C225   7505                   jnz     0057C22C

|
0057C227   E8D022F2FF             call    0049E4FC
0057C22C   A13CF86300             mov     eax, dword ptr [$0063F83C]
0057C231   8B00                   mov     eax, [eax]
0057C233   8B90AC030000           mov     edx, [eax+$03AC]

* Reference to control qryGrupo : N.A.
|
0057C239   8B8390030000           mov     eax, [ebx+$0390]

|
0057C23F   E8EC38EEFF             call    0045FB30

* Possible String Reference to: 'Versão 8.9.45 de 01/12/2009'
|
0057C244   BA18C35700             mov     edx, $0057C318
0057C249   A124406400             mov     eax, dword ptr [$00644024]

|
0057C24E   E8DD38EEFF             call    0045FB30
0057C253   33C0                   xor     eax, eax
0057C255   5A                     pop     edx
0057C256   59                     pop     ecx
0057C257   59                     pop     ecx
0057C258   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: '[YY]Ã'
|
0057C25B   6878C25700             push    $0057C278
0057C260   8D45F8                 lea     eax, [ebp-$08]

|
0057C263   E83C96E8FF             call    004058A4
0057C268   8D45FC                 lea     eax, [ebp-$04]

|
0057C26B   E83496E8FF             call    004058A4
0057C270   C3                     ret

*)
end;

procedure TfrmLogin._PROC_0057C3ED(Sender : TObject);
begin
(*
0057C3ED   8BEC                   mov     ebp, esp
0057C3EF   33C9                   xor     ecx, ecx
0057C3F1   51                     push    ecx
0057C3F2   51                     push    ecx
0057C3F3   51                     push    ecx
0057C3F4   51                     push    ecx
0057C3F5   51                     push    ecx
0057C3F6   53                     push    ebx
0057C3F7   56                     push    esi
0057C3F8   33C0                   xor     eax, eax
0057C3FA   55                     push    ebp

* Possible String Reference to: 'éí‰èÿëè^[‹å]Ã'
|
0057C3FB   68A2C65700             push    $0057C6A2

***** TRY
|
0057C400   64FF30                 push    dword ptr fs:[eax]
0057C403   648920                 mov     fs:[eax], esp
0057C406   A13CF86300             mov     eax, dword ptr [$0063F83C]
0057C40B   8B00                   mov     eax, [eax]
0057C40D   8B8064030000           mov     eax, [eax+$0364]

|
0057C413   E88422F2FF             call    0049E69C
0057C418   84C0                   test    al, al
0057C41A   7412                   jz      0057C42E
0057C41C   A13CF86300             mov     eax, dword ptr [$0063F83C]
0057C421   8B00                   mov     eax, [eax]
0057C423   8B8064030000           mov     eax, [eax+$0364]

|
0057C429   E8E220F2FF             call    0049E510
0057C42E   A13CF86300             mov     eax, dword ptr [$0063F83C]
0057C433   8B00                   mov     eax, [eax]
0057C435   8B8064030000           mov     eax, [eax+$0364]

* Possible String Reference to: 'chave'
|
0057C43B   BAB8C65700             mov     edx, $0057C6B8

|
0057C440   E83BE5F3FF             call    004BA980
0057C445   8B153CF86300           mov     edx, [$0063F83C]
0057C44B   8B12                   mov     edx, [edx]
0057C44D   8B92AC030000           mov     edx, [edx+$03AC]

|
0057C453   E8C413F2FF             call    0049D81C
0057C458   A13CF86300             mov     eax, dword ptr [$0063F83C]
0057C45D   8B00                   mov     eax, [eax]
0057C45F   8B8064030000           mov     eax, [eax+$0364]

|
0057C465   E89220F2FF             call    0049E4FC
0057C46A   A13CF86300             mov     eax, dword ptr [$0063F83C]
0057C46F   8B00                   mov     eax, [eax]
0057C471   8B8070030000           mov     eax, [eax+$0370]

|
0057C477   E82022F2FF             call    0049E69C
0057C47C   84C0                   test    al, al
0057C47E   7412                   jz      0057C492
0057C480   A13CF86300             mov     eax, dword ptr [$0063F83C]
0057C485   8B00                   mov     eax, [eax]
0057C487   8B8070030000           mov     eax, [eax+$0370]

|
0057C48D   E87E20F2FF             call    0049E510
0057C492   A13CF86300             mov     eax, dword ptr [$0063F83C]
0057C497   8B00                   mov     eax, [eax]
0057C499   8B8070030000           mov     eax, [eax+$0370]
0057C49F   8B4038                 mov     eax, [eax+$38]

|
0057C4A2   E80D73EAFF             call    004237B4
0057C4A7   A13CF86300             mov     eax, dword ptr [$0063F83C]
0057C4AC   8B00                   mov     eax, [eax]
0057C4AE   8B8064030000           mov     eax, [eax+$0364]

|
0057C4B4   E8372FF2FF             call    0049F3F0
0057C4B9   8BF0                   mov     esi, eax
0057C4BB   4E                     dec     esi
0057C4BC   85F6                   test    esi, esi
0057C4BE   0F8C9E000000           jl      0057C562
0057C4C4   46                     inc     esi
0057C4C5   33DB                   xor     ebx, ebx
0057C4C7   A13CF86300             mov     eax, dword ptr [$0063F83C]
0057C4CC   8B00                   mov     eax, [eax]
0057C4CE   8B8064030000           mov     eax, [eax+$0364]
0057C4D4   8B4030                 mov     eax, [eax+$30]
0057C4D7   8BD3                   mov     edx, ebx

|
0057C4D9   E82260F1FF             call    00492500
0057C4DE   8B10                   mov     edx, [eax]
0057C4E0   FF928C000000           call    dword ptr [edx+$008C]
0057C4E6   50                     push    eax
0057C4E7   A13CF86300             mov     eax, dword ptr [$0063F83C]
0057C4EC   8B00                   mov     eax, [eax]
0057C4EE   8B8064030000           mov     eax, [eax+$0364]
0057C4F4   8B4030                 mov     eax, [eax+$30]
0057C4F7   8BD3                   mov     edx, ebx

|
0057C4F9   E80260F1FF             call    00492500
0057C4FE   0FB64045               movzx   eax, byte ptr [eax+$45]
0057C502   50                     push    eax
0057C503   A13CF86300             mov     eax, dword ptr [$0063F83C]
0057C508   8B00                   mov     eax, [eax]
0057C50A   8B8064030000           mov     eax, [eax+$0364]
0057C510   8B4030                 mov     eax, [eax+$30]
0057C513   8BD3                   mov     edx, ebx

|
0057C515   E8E65FF1FF             call    00492500
0057C51A   0FB64040               movzx   eax, byte ptr [eax+$40]
0057C51E   50                     push    eax
0057C51F   A13CF86300             mov     eax, dword ptr [$0063F83C]
0057C524   8B00                   mov     eax, [eax]
0057C526   8B8064030000           mov     eax, [eax+$0364]
0057C52C   8B4030                 mov     eax, [eax+$30]
0057C52F   8BD3                   mov     edx, ebx

|
0057C531   E8CA5FF1FF             call    00492500
0057C536   8B5038                 mov     edx, [eax+$38]
0057C539   8D45FC                 lea     eax, [ebp-$04]

|
0057C53C   E8EB95E8FF             call    00405B2C
0057C541   8B55FC                 mov     edx, [ebp-$04]
0057C544   A13CF86300             mov     eax, dword ptr [$0063F83C]
0057C549   8B00                   mov     eax, [eax]
0057C54B   8B8070030000           mov     eax, [eax+$0370]
0057C551   8B4038                 mov     eax, [eax+$38]
0057C554   59                     pop     ecx

|
0057C555   E82A54F1FF             call    00491984
0057C55A   43                     inc     ebx
0057C55B   4E                     dec     esi
0057C55C   0F8565FFFFFF           jnz     0057C4C7
0057C562   A13CF86300             mov     eax, dword ptr [$0063F83C]
0057C567   8B00                   mov     eax, [eax]
0057C569   8B8070030000           mov     eax, [eax+$0370]

|
0057C56F   E81CC4F5FF             call    004D8990
0057C574   A13CF86300             mov     eax, dword ptr [$0063F83C]
0057C579   8B00                   mov     eax, [eax]
0057C57B   8B8064030000           mov     eax, [eax+$0364]

|
0057C581   E87E47F2FF             call    004A0D04
0057C586   A13CF86300             mov     eax, dword ptr [$0063F83C]
0057C58B   8B00                   mov     eax, [eax]
0057C58D   8B8070030000           mov     eax, [eax+$0370]

|
0057C593   E8641FF2FF             call    0049E4FC
0057C598   E9AE000000             jmp     0057C64B
0057C59D   A13CF86300             mov     eax, dword ptr [$0063F83C]
0057C5A2   8B00                   mov     eax, [eax]
0057C5A4   8B8070030000           mov     eax, [eax+$0370]

|
0057C5AA   E8B14CF2FF             call    004A1260
0057C5AF   A13CF86300             mov     eax, dword ptr [$0063F83C]
0057C5B4   8B00                   mov     eax, [eax]
0057C5B6   8B8070030000           mov     eax, [eax+$0370]

|
0057C5BC   E85B4BF2FF             call    004A111C
0057C5C1   A13CF86300             mov     eax, dword ptr [$0063F83C]
0057C5C6   8B00                   mov     eax, [eax]
0057C5C8   8B8064030000           mov     eax, [eax+$0364]

|
0057C5CE   E81D2EF2FF             call    0049F3F0
0057C5D3   8BF0                   mov     esi, eax
0057C5D5   4E                     dec     esi
0057C5D6   85F6                   test    esi, esi
0057C5D8   7C4A                   jl      0057C624
0057C5DA   46                     inc     esi
0057C5DB   33DB                   xor     ebx, ebx
0057C5DD   A13CF86300             mov     eax, dword ptr [$0063F83C]
0057C5E2   8B00                   mov     eax, [eax]
0057C5E4   8B8064030000           mov     eax, [eax+$0364]
0057C5EA   8B4030                 mov     eax, [eax+$30]
0057C5ED   8BD3                   mov     edx, ebx

|
0057C5EF   E80C5FF1FF             call    00492500
0057C5F4   8D55EC                 lea     edx, [ebp-$14]
0057C5F7   8B08                   mov     ecx, [eax]
0057C5F9   FF5168                 call    dword ptr [ecx+$68]
0057C5FC   8D45EC                 lea     eax, [ebp-$14]
0057C5FF   50                     push    eax
0057C600   A13CF86300             mov     eax, dword ptr [$0063F83C]
0057C605   8B00                   mov     eax, [eax]
0057C607   8B8070030000           mov     eax, [eax+$0370]
0057C60D   8B4030                 mov     eax, [eax+$30]
0057C610   8BD3                   mov     edx, ebx

|
0057C612   E8E95EF1FF             call    00492500
0057C617   5A                     pop     edx
0057C618   8B08                   mov     ecx, [eax]
0057C61A   FF91C0000000           call    dword ptr [ecx+$00C0]
0057C620   43                     inc     ebx
0057C621   4E                     dec     esi
0057C622   75B9                   jnz     0057C5DD
0057C624   A13CF86300             mov     eax, dword ptr [$0063F83C]
0057C629   8B00                   mov     eax, [eax]
0057C62B   8B8070030000           mov     eax, [eax+$0370]
0057C631   8B10                   mov     edx, [eax]
0057C633   FF9270020000           call    dword ptr [edx+$0270]
0057C639   A13CF86300             mov     eax, dword ptr [$0063F83C]
0057C63E   8B00                   mov     eax, [eax]
0057C640   8B8064030000           mov     eax, [eax+$0364]

|
0057C646   E8D549F2FF             call    004A1020
0057C64B   A13CF86300             mov     eax, dword ptr [$0063F83C]
0057C650   8B00                   mov     eax, [eax]
0057C652   8B8064030000           mov     eax, [eax+$0364]
0057C658   80B8A100000000         cmp     byte ptr [eax+$00A1], $00
0057C65F   0F8438FFFFFF           jz      0057C59D
0057C665   A13CF86300             mov     eax, dword ptr [$0063F83C]
0057C66A   8B00                   mov     eax, [eax]
0057C66C   50                     push    eax
0057C66D   68E8F16200             push    $0062F1E8
0057C672   A13CF86300             mov     eax, dword ptr [$0063F83C]
0057C677   8B00                   mov     eax, [eax]
0057C679   8B8060030000           mov     eax, [eax+$0360]

|
0057C67F   E87830F6FF             call    004DF6FC
0057C684   33C0                   xor     eax, eax
0057C686   5A                     pop     edx
0057C687   59                     pop     ecx
0057C688   59                     pop     ecx
0057C689   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: '^[‹å]Ã'
|
0057C68C   68A9C65700             push    $0057C6A9
0057C691   8D45EC                 lea     eax, [ebp-$14]

|
0057C694   E8838CE9FF             call    0041531C
0057C699   8D45FC                 lea     eax, [ebp-$04]

|
0057C69C   E80392E8FF             call    004058A4
0057C6A1   C3                     ret


|
0057C6A2   E9ED89E8FF             jmp     00405094
0057C6A7   EBE8                   jmp     0057C691

****** END
|
0057C6A9   5E                     pop     esi
0057C6AA   5B                     pop     ebx
0057C6AB   8BE5                   mov     esp, ebp
0057C6AD   5D                     pop     ebp
0057C6AE   C3                     ret

*)
end;

procedure TfrmLogin._PROC_0057CD0D(Sender : TObject);
begin
(*
0057CD0D   8BEC                   mov     ebp, esp
0057CD0F   6A00                   push    $00
0057CD11   6A00                   push    $00
0057CD13   6A00                   push    $00
0057CD15   53                     push    ebx
0057CD16   56                     push    esi
0057CD17   57                     push    edi
0057CD18   8BF1                   mov     esi, ecx
0057CD1A   8955FC                 mov     [ebp-$04], edx
0057CD1D   8BF8                   mov     edi, eax
0057CD1F   33C0                   xor     eax, eax
0057CD21   55                     push    ebp
0057CD22   6829CE5700             push    $0057CE29

***** TRY
|
0057CD27   64FF30                 push    dword ptr fs:[eax]
0057CD2A   648920                 mov     fs:[eax], esp
0057CD2D   B301                   mov     bl, $01
0057CD2F   33C0                   xor     eax, eax
0057CD31   55                     push    ebp
0057CD32   68DCCD5700             push    $0057CDDC

***** TRY
|
0057CD37   64FF30                 push    dword ptr fs:[eax]
0057CD3A   648920                 mov     fs:[eax], esp
0057CD3D   85F6                   test    esi, esi
0057CD3F   7421                   jz      0057CD62
0057CD41   33D2                   xor     edx, edx
0057CD43   8BC6                   mov     eax, esi

* Reference to : TTabStrings._PROC_004C93C8()
|
0057CD45   E87EC6F4FF             call    004C93C8
0057CD4A   BA01000000             mov     edx, $00000001
0057CD4F   8BC6                   mov     eax, esi

* Reference to : TTabStrings._PROC_004C93D4()
|
0057CD51   E87EC6F4FF             call    004C93D4
0057CD56   BA01000000             mov     edx, $00000001
0057CD5B   8BC6                   mov     eax, esi

* Reference to : TTabStrings._PROC_004C9430()
|
0057CD5D   E8CEC6F4FF             call    004C9430
0057CD62   8B8788000000           mov     eax, [edi+$0088]

|
0057CD68   E82F19F2FF             call    0049E69C
0057CD6D   84C0                   test    al, al
0057CD6F   740B                   jz      0057CD7C
0057CD71   8B8788000000           mov     eax, [edi+$0088]

|
0057CD77   E89417F2FF             call    0049E510
0057CD7C   8B8788000000           mov     eax, [edi+$0088]
0057CD82   8B8048020000           mov     eax, [eax+$0248]
0057CD88   8B10                   mov     edx, [eax]
0057CD8A   FF5244                 call    dword ptr [edx+$44]
0057CD8D   8D55F4                 lea     edx, [ebp-$0C]
0057CD90   8B45FC                 mov     eax, [ebp-$04]

|
0057CD93   E85CE2E8FF             call    0040AFF4
0057CD98   8B4DF4                 mov     ecx, [ebp-$0C]
0057CD9B   8D45F8                 lea     eax, [ebp-$08]

* Possible String Reference to: 'exec OnPlaceSaned_Movimento..sp_des
|                                faz_carga_movimento '
|
0057CD9E   BA44CE5700             mov     edx, $0057CE44

|
0057CDA3   E80C8EE8FF             call    00405BB4
0057CDA8   8B55F8                 mov     edx, [ebp-$08]
0057CDAB   8B8788000000           mov     eax, [edi+$0088]
0057CDB1   8B8048020000           mov     eax, [eax+$0248]
0057CDB7   8B08                   mov     ecx, [eax]
0057CDB9   FF5138                 call    dword ptr [ecx+$38]
0057CDBC   8B8788000000           mov     eax, [edi+$0088]

|
0057CDC2   E8D1DCF3FF             call    004BAA98
0057CDC7   85F6                   test    esi, esi
0057CDC9   7407                   jz      0057CDD2
0057CDCB   8BC6                   mov     eax, esi

* Reference to : TTabStrings._PROC_004C946C()
|
0057CDCD   E89AC6F4FF             call    004C946C
0057CDD2   33C0                   xor     eax, eax
0057CDD4   5A                     pop     edx
0057CDD5   59                     pop     ecx
0057CDD6   59                     pop     ecx
0057CDD7   648910                 mov     fs:[eax], edx
0057CDDA   EB32                   jmp     0057CE0E

|
0057CDDC   E92B81E8FF             jmp     00404F0C
0057CDE1   0100                   add     [eax], eax
0057CDE3   0000                   add     [eax], al
0057CDE5   A895                   test    al, $95
0057CDE7   40                     inc     eax
0057CDE8   00ED                   add     ch, ch
0057CDEA   CD57                   int     $57
0057CDEC   0089C633DB8B           add     [ecx+$8BDB33C6], cl
0057CDF2   45                     inc     ebp
0057CDF3   088338007510           or      [ebx+$10750038], al
0057CDF9   8B4E04                 mov     ecx, [esi+$04]
0057CDFC   8B4508                 mov     eax, [ebp+$08]

* Possible String Reference to: 'Ocorreu um erro inesperado do siste
|                                ma ao Desfazer a Carga.Anote a desc
|                                rição abaixo e entre em contato com
|                                 a Strategos.'
|
0057CDFF   BA84CE5700             mov     edx, $0057CE84

|
0057CE04   E8AB8DE8FF             call    00405BB4

|
0057CE09   E8A684E8FF             call    004052B4

****** END
|
0057CE0E   33C0                   xor     eax, eax
0057CE10   5A                     pop     edx
0057CE11   59                     pop     ecx
0057CE12   59                     pop     ecx
0057CE13   648910                 mov     fs:[eax], edx

****** FINALLY
|
0057CE16   6830CE5700             push    $0057CE30
0057CE1B   8D45F4                 lea     eax, [ebp-$0C]
0057CE1E   BA02000000             mov     edx, $00000002

|
0057CE23   E8A08AE8FF             call    004058C8
0057CE28   C3                     ret


|
0057CE29   E96682E8FF             jmp     00405094
0057CE2E   EBEB                   jmp     0057CE1B

****** END
|
0057CE30   8BC3                   mov     eax, ebx
0057CE32   5F                     pop     edi
0057CE33   5E                     pop     esi
0057CE34   5B                     pop     ebx
0057CE35   8BE5                   mov     esp, ebp
0057CE37   5D                     pop     ebp
0057CE38   C20400                 ret     $0004

*)
end;

end.