unit uFrmAbertura;

interface

uses
  Windows, Messages, SysUtils, Classes, Graphics,
  Controls, Forms, Dialogs, StdCtrls
type
  TfrmAbertura=class(TForm)
    Image1: TImage;
    Timer1: TTimer;
    procedure Timer1Timer(Sender : TObject);
  private
    { Private declarations }
  public
    { Public declarations }
  end ;

var
  frmAbertura: TfrmAbertura;

{This file is generated by DeDe Ver 3.50.04 Copyright (c) 1999-2002 DaFixer}

implementation

{$R *.DFM}

procedure TfrmAbertura.Timer1Timer(Sender : TObject);
begin
(*

* Reference to : TApplication._PROC_0047A1C8()
|
006333D4   E8EF6DE4FF             call    0047A1C8
006333D9   C3                     ret

*)
end;

end.