unit uFrmDesfazRetorno;

interface

uses
  Windows, Messages, SysUtils, Classes, Graphics,
  Controls, Forms, Dialogs, StdCtrls
type
  TfrmDesfazRetorno=class(TForm)
    ListBox: TListBox;
    sbtnConfirmar: TSpeedButton;
    ProgressBar: TProgressBar;
    procedure sbtnConfirmarClick(Sender : TObject);
    procedure _PROC_005A84E0(Sender : TObject);
    procedure _PROC_005A89BE(Sender : TObject);
  private
    { Private declarations }
  public
    { Public declarations }
  end ;

var
  frmDesfazRetorno: TfrmDesfazRetorno;

{This file is generated by DeDe Ver 3.50.04 Copyright (c) 1999-2002 DaFixer}

implementation

{$R *.DFM}

procedure TfrmDesfazRetorno.sbtnConfirmarClick(Sender : TObject);
begin
(*
005A8614   55                     push    ebp
005A8615   8BEC                   mov     ebp, esp
005A8617   B906000000             mov     ecx, $00000006
005A861C   6A00                   push    $00
005A861E   6A00                   push    $00
005A8620   49                     dec     ecx
005A8621   75F9                   jnz     005A861C
005A8623   51                     push    ecx
005A8624   53                     push    ebx
005A8625   56                     push    esi
005A8626   57                     push    edi
005A8627   8BD8                   mov     ebx, eax
005A8629   33C0                   xor     eax, eax
005A862B   55                     push    ebp
005A862C   6880885A00             push    $005A8880

***** TRY
|
005A8631   64FF30                 push    dword ptr fs:[eax]
005A8634   648920                 mov     fs:[eax], esp
005A8637   33D2                   xor     edx, edx
005A8639   8BC3                   mov     eax, ebx

|
005A863B   E82825FCFF             call    0056AB68

* Reference to control TfrmDesfazRetorno.ListBox : TListBox
|
005A8640   8B8380030000           mov     eax, [ebx+$0380]
005A8646   8B10                   mov     edx, [eax]

* Possible reference to virtual method TListBox.OFFS_00DC
|
005A8648   FF92DC000000           call    dword ptr [edx+$00DC]
005A864E   40                     inc     eax
005A864F   7504                   jnz     005A8655
005A8651   B001                   mov     al, $01
005A8653   EB42                   jmp     005A8697

* Reference to control TfrmDesfazRetorno.ListBox : TListBox
|
005A8655   8BB380030000           mov     esi, [ebx+$0380]
005A865B   8BC6                   mov     eax, esi
005A865D   8B10                   mov     edx, [eax]

* Possible reference to virtual method TListBox.OFFS_00DC
|
005A865F   FF92DC000000           call    dword ptr [edx+$00DC]
005A8665   8BD0                   mov     edx, eax
005A8667   8D4DF4                 lea     ecx, [ebp-$0C]

* Reference to field TListBox.OFFS_0260
|
005A866A   8B8660020000           mov     eax, [esi+$0260]
005A8670   8B30                   mov     esi, [eax]
005A8672   FF560C                 call    dword ptr [esi+$0C]
005A8675   8B45F4                 mov     eax, [ebp-$0C]
005A8678   8D55F8                 lea     edx, [ebp-$08]

|
005A867B   E8D422E6FF             call    0040A954
005A8680   8B45F8                 mov     eax, [ebp-$08]
005A8683   8945F0                 mov     [ebp-$10], eax
005A8686   8B45F0                 mov     eax, [ebp-$10]
005A8689   85C0                   test    eax, eax
005A868B   7405                   jz      005A8692
005A868D   83E804                 sub     eax, +$04
005A8690   8B00                   mov     eax, [eax]
005A8692   85C0                   test    eax, eax
005A8694   0F94C0                 setz    al
005A8697   84C0                   test    al, al
005A8699   7431                   jz      005A86CC
005A869B   6A00                   push    $00
005A869D   0FB70D90885A00         movzx   ecx, word ptr [$005A8890]
005A86A4   B202                   mov     dl, $02

* Possible String Reference to: 'Selecione um Roteiro !'
|
005A86A6   B89C885A00             mov     eax, $005A889C

|
005A86AB   E8F884EAFF             call    00450BA8

* Reference to control TfrmDesfazRetorno.ListBox : TListBox
|
005A86B0   8B8380030000           mov     eax, [ebx+$0380]
005A86B6   8B10                   mov     edx, [eax]

* Possible reference to virtual method TListBox.OFFS_00D4
|
005A86B8   FF92D4000000           call    dword ptr [edx+$00D4]
005A86BE   B201                   mov     dl, $01
005A86C0   8BC3                   mov     eax, ebx

|
005A86C2   E8A124FCFF             call    0056AB68
005A86C7   E98C010000             jmp     005A8858
005A86CC   8D45EC                 lea     eax, [ebp-$14]
005A86CF   50                     push    eax

* Reference to control TfrmDesfazRetorno.ListBox : TListBox
|
005A86D0   8BB380030000           mov     esi, [ebx+$0380]
005A86D6   8BC6                   mov     eax, esi
005A86D8   8B10                   mov     edx, [eax]

* Possible reference to virtual method TListBox.OFFS_00DC
|
005A86DA   FF92DC000000           call    dword ptr [edx+$00DC]
005A86E0   8BD0                   mov     edx, eax
005A86E2   8D4DE8                 lea     ecx, [ebp-$18]

* Reference to field TListBox.OFFS_0260
|
005A86E5   8B8660020000           mov     eax, [esi+$0260]
005A86EB   8B30                   mov     esi, [eax]
005A86ED   FF560C                 call    dword ptr [esi+$0C]
005A86F0   8B45E8                 mov     eax, [ebp-$18]
005A86F3   B902000000             mov     ecx, $00000002
005A86F8   BA07000000             mov     edx, $00000007

|
005A86FD   E8C6D6E5FF             call    00405DC8
005A8702   8B45EC                 mov     eax, [ebp-$14]

|
005A8705   E83A2BE6FF             call    0040B244
005A870A   8BF0                   mov     esi, eax
005A870C   8D45E4                 lea     eax, [ebp-$1C]
005A870F   50                     push    eax

* Reference to control TfrmDesfazRetorno.ListBox : TListBox
|
005A8710   8B8380030000           mov     eax, [ebx+$0380]
005A8716   8B10                   mov     edx, [eax]

* Possible reference to virtual method TListBox.OFFS_00DC
|
005A8718   FF92DC000000           call    dword ptr [edx+$00DC]
005A871E   8BD0                   mov     edx, eax
005A8720   8D4DE0                 lea     ecx, [ebp-$20]

* Reference to control TfrmDesfazRetorno.ListBox : TListBox
|
005A8723   8B8380030000           mov     eax, [ebx+$0380]

* Reference to field TListBox.OFFS_0260
|
005A8729   8B8060020000           mov     eax, [eax+$0260]
005A872F   8B38                   mov     edi, [eax]
005A8731   FF570C                 call    dword ptr [edi+$0C]
005A8734   8B45E0                 mov     eax, [ebp-$20]
005A8737   B903000000             mov     ecx, $00000003
005A873C   BA15000000             mov     edx, $00000015

|
005A8741   E882D6E5FF             call    00405DC8
005A8746   8B45E4                 mov     eax, [ebp-$1C]

|
005A8749   E8F62AE6FF             call    0040B244
005A874E   8BF8                   mov     edi, eax

* Reference to control TfrmDesfazRetorno.ProgressBar : TProgressBar
|
005A8750   8B8388030000           mov     eax, [ebx+$0388]
005A8756   50                     push    eax
005A8757   8D45FC                 lea     eax, [ebp-$04]
005A875A   50                     push    eax
005A875B   A1ACFB6300             mov     eax, dword ptr [$0063FBAC]
005A8760   8B00                   mov     eax, [eax]
005A8762   8BCF                   mov     ecx, edi
005A8764   8BD6                   mov     edx, esi

|
005A8766   E8ADDFFEFF             call    00596718
005A876B   84C0                   test    al, al
005A876D   7543                   jnz     005A87B2
005A876F   6A00                   push    $00
005A8771   0FB70D90885A00         movzx   ecx, word ptr [$005A8890]
005A8778   B201                   mov     dl, $01
005A877A   8B45FC                 mov     eax, [ebp-$04]

|
005A877D   E82684EAFF             call    00450BA8
005A8782   6A00                   push    $00
005A8784   0FB70D90885A00         movzx   ecx, word ptr [$005A8890]
005A878B   B201                   mov     dl, $01

* Possible String Reference to: 'Não Foi Possível Desfazer Retorno p
|                                ara este Roteiro.Tentar Novamente.'
|
005A878D   B8BC885A00             mov     eax, $005A88BC

|
005A8792   E81184EAFF             call    00450BA8
005A8797   33D2                   xor     edx, edx

* Reference to control TfrmDesfazRetorno.ProgressBar : TProgressBar
|
005A8799   8B8388030000           mov     eax, [ebx+$0388]

* Reference to : TTabStrings._PROC_004C93E4()
|
005A879F   E8400CF2FF             call    004C93E4
005A87A4   B201                   mov     dl, $01
005A87A6   8BC3                   mov     eax, ebx

|
005A87A8   E8BB23FCFF             call    0056AB68
005A87AD   E9A6000000             jmp     005A8858
005A87B2   6A00                   push    $00

* Possible String Reference to: 'Retorno Desfeito para Rota '
|
005A87B4   680C895A00             push    $005A890C
005A87B9   8D55D4                 lea     edx, [ebp-$2C]
005A87BC   8BC7                   mov     eax, edi

|
005A87BE   E83128E6FF             call    0040AFF4
005A87C3   8B45D4                 mov     eax, [ebp-$2C]
005A87C6   8D4DD8                 lea     ecx, [ebp-$28]
005A87C9   BA03000000             mov     edx, $00000003

* Reference to : TfrmBaseClient._PROC_00577BF4()
|
005A87CE   E821F4FCFF             call    00577BF4
005A87D3   FF75D8                 push    dword ptr [ebp-$28]

* Possible String Reference to: ' do Grupo '
|
005A87D6   6830895A00             push    $005A8930
005A87DB   8D55CC                 lea     edx, [ebp-$34]
005A87DE   8BC6                   mov     eax, esi

|
005A87E0   E80F28E6FF             call    0040AFF4
005A87E5   8B45CC                 mov     eax, [ebp-$34]
005A87E8   8D4DD0                 lea     ecx, [ebp-$30]
005A87EB   BA02000000             mov     edx, $00000002

* Reference to : TfrmBaseClient._PROC_00577BF4()
|
005A87F0   E8FFF3FCFF             call    00577BF4
005A87F5   FF75D0                 push    dword ptr [ebp-$30]
005A87F8   6844895A00             push    $005A8944
005A87FD   8D45DC                 lea     eax, [ebp-$24]
005A8800   BA05000000             mov     edx, $00000005

|
005A8805   E81ED4E5FF             call    00405C28
005A880A   8B45DC                 mov     eax, [ebp-$24]
005A880D   0FB70D90885A00         movzx   ecx, word ptr [$005A8890]
005A8814   B202                   mov     dl, $02

|
005A8816   E88D83EAFF             call    00450BA8
005A881B   33D2                   xor     edx, edx

* Reference to control TfrmDesfazRetorno.ProgressBar : TProgressBar
|
005A881D   8B8388030000           mov     eax, [ebx+$0388]

* Reference to : TTabStrings._PROC_004C93E4()
|
005A8823   E8BC0BF2FF             call    004C93E4
005A8828   8BC3                   mov     eax, ebx

|
005A882A   E829FBFFFF             call    005A8358
005A882F   84C0                   test    al, al
005A8831   751C                   jnz     005A884F
005A8833   6A00                   push    $00
005A8835   0FB70D90885A00         movzx   ecx, word ptr [$005A8890]
005A883C   B202                   mov     dl, $02

* Possible String Reference to: 'Não Existe Mais Nenhum Roteiro Para
|                                 Desfazer Retorno.'
|
005A883E   B850895A00             mov     eax, $005A8950

|
005A8843   E86083EAFF             call    00450BA8
005A8848   8BC3                   mov     eax, ebx

* Reference to : TApplication._PROC_0047A1C8()
|
005A884A   E87919EDFF             call    0047A1C8
005A884F   B201                   mov     dl, $01
005A8851   8BC3                   mov     eax, ebx

|
005A8853   E81023FCFF             call    0056AB68
005A8858   33C0                   xor     eax, eax
005A885A   5A                     pop     edx
005A885B   59                     pop     ecx
005A885C   59                     pop     ecx
005A885D   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: '_^[‹å]Ã'
|
005A8860   6887885A00             push    $005A8887
005A8865   8D45CC                 lea     eax, [ebp-$34]
005A8868   BA09000000             mov     edx, $00000009

|
005A886D   E856D0E5FF             call    004058C8
005A8872   8D45F4                 lea     eax, [ebp-$0C]
005A8875   BA03000000             mov     edx, $00000003

|
005A887A   E849D0E5FF             call    004058C8
005A887F   C3                     ret


|
005A8880   E90FC8E5FF             jmp     00405094
005A8885   EBDE                   jmp     005A8865

****** END
|
005A8887   5F                     pop     edi
005A8888   5E                     pop     esi
005A8889   5B                     pop     ebx
005A888A   8BE5                   mov     esp, ebp
005A888C   5D                     pop     ebp
005A888D   C3                     ret

*)
end;

procedure TfrmDesfazRetorno._PROC_005A84E0(Sender : TObject);
begin
(*
005A84E0   1400                   adc     al, $00
005A84E2   0000                   add     [eax], al

*)
end;

procedure TfrmDesfazRetorno._PROC_005A89BE(Sender : TObject);
begin
(*
005A89BE   47                     inc     edi
005A89BF   001C4B                 add     [ebx+ecx*2], bl
005A89C2   40                     inc     eax
005A89C3   000C8547005848         add     [$48580047+eax*4], cl
005A89CA   40                     inc     eax
005A89CB   00744840               add     [eax+ecx*2+$40], dh
005A89CF   00905547008C           add     [eax+$8C004755], dl
005A89D5   844600                 test    [esi+$00], al
005A89D8   845B47                 test    [ebx+$47], bl
005A89DB   000C31                 add     [ecx+esi], cl
005A89DE   42                     inc     edx
005A89DF   006C5747               add     [edi+edx*2+$47], ch
005A89E3   00B8574700F4           add     [eax+$F4004757], bh
005A89E9   58                     pop     eax
005A89EA   47                     inc     edi
005A89EB   00E8                   add     al, ch
005A89ED   F8                     clc
005A89EE   45                     inc     ebp
005A89EF   0094C542008462         add     [ebp+eax*8+$62840042], dl
005A89F6   47                     inc     edi
005A89F7   0070C2                 add     [eax-$3E], dh
005A89FA   42                     inc     edx
005A89FB   0070AB                 add     [eax-$55], dh
005A89FE   47                     inc     edi
005A89FF   00E0                   add     al, ah
005A8A01   51                     push    ecx
005A8A02   47                     inc     edi
005A8A03   00B07E4600BC           add     [eax+$BC00467E], dh
005A8A09   844600                 test    [esi+$00], al
005A8A0C   08844600B0EB45         or      [esi+eax*2+$45EBB000], al
005A8A13   002C79                 add     [ecx+edi*2], ch
005A8A16   46                     inc     esi
005A8A17   00B85E4700B8           add     [eax+$B800475E], bh
005A8A1D   7546                   jnz     005A8A65
005A8A1F   00F0                   add     al, dh
005A8A21   EA4500F4EA             jmp     $EAF40045
005A8A26   45                     inc     ebp
005A8A27   00AC5F47006C24         add     [edi+ebx*2+$246C0047], ch
005A8A2E   46                     inc     esi
005A8A2F   003CA8                 add     [eax+ebp*4], bh
005A8A32   47                     inc     edi
005A8A33   00CC                   add     ah, cl
005A8A35   F8                     clc
005A8A36   45                     inc     ebp
005A8A37   002CED450058FA         add     [$FA580045+ebp*8], ch
005A8A3E   45                     inc     ebp
005A8A3F   00C8                   add     al, cl
005A8A41   61                     popa
005A8A42   47                     inc     edi
005A8A43   008460470094FB         add     [eax+$FB940047], al
005A8A4A   45                     inc     ebp
005A8A4B   00C4                   add     ah, al
005A8A4D   624700                 bound   eax, qword ptr [edi+$00]
005A8A50   F0                     lock
005A8A51   2446                   and     al, $46
005A8A53   000C76                 add     [esi+esi*2], cl
005A8A56   46                     inc     esi
005A8A57   00CC                   add     ah, cl
005A8A59   7646                   jbe     005A8AA1
005A8A5B   00C0                   add     al, al
005A8A5D   7146                   jno     005A8AA5
005A8A5F   00B0764600C8           add     [eax+$C8004676], dh
005A8A65   4F                     dec     edi
005A8A66   47                     inc     edi
005A8A67   0008                   add     [eax], cl
005A8A69   6A47                   push    $47
005A8A6B   00A042460034           add     [eax+$34004642], ah
005A8A71   7D47                   jnl     005A8ABA
005A8A73   004882                 add     [eax-$7E], cl
005A8A76   47                     inc     edi
005A8A77   00748047               add     [eax+eax*4+$47], dh
005A8A7B   0038                   add     [eax], bh
005A8A7D   43                     inc     ebx
005A8A7E   46                     inc     esi
005A8A7F   005C4346               add     [ebx+eax*2+$46], bl
005A8A83   00C4                   add     ah, al
005A8A85   834700C8               add     dword ptr [edi+$00], -$38
005A8A89   844700                 test    [edi+$00], al
005A8A8C   94                     xchg    eax, esp
005A8A8D   41                     inc     ecx
005A8A8E   46                     inc     esi
005A8A8F   00A08C4600F8           add     [eax+$F800468C], ah
005A8A95   7746                   jnbe    005A8ADD
005A8A97   0000                   add     [eax], al

005A8A99   8C4700                 mov     word ptr [edi+$00], es
005A8A9C   148C                   adc     al, $8C
005A8A9E   46                     inc     esi
005A8A9F   006874                 add     [eax+$74], ch
005A8AA2   46                     inc     esi
005A8AA3   00648D46               add     [ebp+ecx*4+$46], ah
005A8AA7   0088A34700A8           add     [eax+$A80047A3], cl
005A8AAD   49                     dec     ecx
005A8AAE   47                     inc     edi
005A8AAF   00584C                 add     [eax+$4C], bl
005A8AB2   47                     inc     edi
005A8AB3   004093                 add     [eax-$6D], al
005A8AB6   47                     inc     edi
005A8AB7   00905647000C           add     [eax+$C004756], dl
005A8ABD   57                     push    edi
005A8ABE   47                     inc     edi
005A8ABF   00D4                   add     ah, dl
005A8AC1   A7                     cmpsd
005A8AC2   47                     inc     edi
005A8AC3   00A45347006CA2         add     [ebx+edx*2+$A26C0047], ah
005A8ACA   47                     inc     edi
005A8ACB   009C86470060A4         add     [esi+eax*4+$A4600047], bl
005A8AD2   47                     inc     edi
005A8AD3   00C4                   add     ah, al
005A8AD5   61                     popa
005A8AD6   47                     inc     edi
005A8AD7   00A08D5A0003           add     [eax+$3005A8D], ah
005A8ADD   00418B                 add     [ecx-$75], al
005A8AE0   5A                     pop     edx
005A8AE1   008003000000           add     [eax+$0003], al
005A8AE7   0007                   add     [edi], al
005A8AE9   4C                     dec     esp
005A8AEA   697374426F7884         imul    esi, [ebx+$74], $84786F42
005A8AF1   0300                   add     eax, [eax]
005A8AF3   0001                   add     [ecx], al
005A8AF5   000D7362746E           add     [$6E746273], cl
005A8AFB   43                     inc     ebx
005A8AFC   6F                     outsd
005A8AFD   6E                     outsb
005A8AFE   6669726D6172           imul    si, word ptr [edx+$6D], $7261
005A8B04   8803                   mov     [ebx], al
005A8B06   0000                   add     [eax], al

*)
end;

end.