unit uFrmRelatorioOcorrencia;

interface

uses
  Windows, Messages, SysUtils, Classes, Graphics,
  Controls, Forms, Dialogs, StdCtrls
type
  TfrmRelatorioOcorrencia=class(TForm)
    GroupBox1: TGroupBox;
    LGrupo: TLabel;
    LRota: TLabel;
    Label1: TLabel;
    cmbGrupo: TComboBox;
    cmbRota: TComboBox;
    ckbTodos: TCheckBox;
    cmbRotaFim: TComboBox;
    sbtnImprimir: TSpeedButton;
    Label2: TLabel;
    cmbOcorrencia: TComboBox;
    qryGrupo: TQuery;
    qryRota: TQuery;
    qryOcorrencia: TQuery;
    procedure sbtnImprimirClick(Sender : TObject);
    procedure cmbGrupoChange(Sender : TObject);
    procedure cmbGrupoDropDown(Sender : TObject);
    procedure ckbTodosClick(Sender : TObject);
    procedure _PROC_005DDD8F(Sender : TObject);
    procedure _PROC_005DDECB(Sender : TObject);
    procedure _PROC_005DDEDD(Sender : TObject);
    procedure _PROC_005DE31C(Sender : TObject);
    procedure _PROC_005DE3F2(Sender : TObject);
  private
    { Private declarations }
  public
    { Public declarations }
  end ;

var
  frmRelatorioOcorrencia: TfrmRelatorioOcorrencia;

{This file is generated by DeDe Ver 3.50.04 Copyright (c) 1999-2002 DaFixer}

implementation

{$R *.DFM}

procedure TfrmRelatorioOcorrencia.sbtnImprimirClick(Sender : TObject);
begin
(*
005DE0C4   55                     push    ebp
005DE0C5   8BEC                   mov     ebp, esp
005DE0C7   B908000000             mov     ecx, $00000008
005DE0CC   6A00                   push    $00
005DE0CE   6A00                   push    $00
005DE0D0   49                     dec     ecx
005DE0D1   75F9                   jnz     005DE0CC
005DE0D3   53                     push    ebx
005DE0D4   56                     push    esi
005DE0D5   57                     push    edi
005DE0D6   8BD8                   mov     ebx, eax
005DE0D8   33C0                   xor     eax, eax
005DE0DA   55                     push    ebp
005DE0DB   680EE35D00             push    $005DE30E

***** TRY
|
005DE0E0   64FF30                 push    dword ptr fs:[eax]
005DE0E3   648920                 mov     fs:[eax], esp
005DE0E6   8D55F0                 lea     edx, [ebp-$10]

* Reference to control TfrmRelatorioOcorrencia.cmbGrupo : TComboBox
|
005DE0E9   8B8390030000           mov     eax, [ebx+$0390]

|
005DE0EF   E80C1AE8FF             call    0045FB00
005DE0F4   8B45F0                 mov     eax, [ebp-$10]
005DE0F7   8D55F4                 lea     edx, [ebp-$0C]

|
005DE0FA   E855C8E2FF             call    0040A954
005DE0FF   837DF400               cmp     dword ptr [ebp-$0C], +$00
005DE103   7528                   jnz     005DE12D
005DE105   6A00                   push    $00
005DE107   0FB70D1CE35D00         movzx   ecx, word ptr [$005DE31C]
005DE10E   B202                   mov     dl, $02

* Possible String Reference to: 'Informar o grupo.'
|
005DE110   B828E35D00             mov     eax, $005DE328

|
005DE115   E88E2AE7FF             call    00450BA8

* Reference to control TfrmRelatorioOcorrencia.cmbGrupo : TComboBox
|
005DE11A   8B8390030000           mov     eax, [ebx+$0390]
005DE120   8B10                   mov     edx, [eax]

* Possible reference to virtual method TComboBox.OFFS_00D4
|
005DE122   FF92D4000000           call    dword ptr [edx+$00D4]
005DE128   E99E010000             jmp     005DE2CB

* Reference to control TfrmRelatorioOcorrencia.ckbTodos : TCheckBox
|
005DE12D   8B8398030000           mov     eax, [ebx+$0398]
005DE133   8B10                   mov     edx, [eax]

* Possible reference to virtual method TCheckBox.OFFS_00D8
|
005DE135   FF92D8000000           call    dword ptr [edx+$00D8]
005DE13B   84C0                   test    al, al
005DE13D   7566                   jnz     005DE1A5
005DE13F   8D55E8                 lea     edx, [ebp-$18]

* Reference to control TfrmRelatorioOcorrencia.cmbRota : TComboBox
|
005DE142   8B8394030000           mov     eax, [ebx+$0394]

|
005DE148   E8B319E8FF             call    0045FB00
005DE14D   8B45E8                 mov     eax, [ebp-$18]
005DE150   8D55EC                 lea     edx, [ebp-$14]

|
005DE153   E8FCC7E2FF             call    0040A954
005DE158   837DEC00               cmp     dword ptr [ebp-$14], +$00
005DE15C   7547                   jnz     005DE1A5
005DE15E   8D55E0                 lea     edx, [ebp-$20]

* Reference to control TfrmRelatorioOcorrencia.cmbRotaFim : TComboBox
|
005DE161   8B839C030000           mov     eax, [ebx+$039C]

|
005DE167   E89419E8FF             call    0045FB00
005DE16C   8B45E0                 mov     eax, [ebp-$20]
005DE16F   8D55E4                 lea     edx, [ebp-$1C]

|
005DE172   E8DDC7E2FF             call    0040A954
005DE177   837DE400               cmp     dword ptr [ebp-$1C], +$00
005DE17B   7528                   jnz     005DE1A5
005DE17D   6A00                   push    $00
005DE17F   0FB70D1CE35D00         movzx   ecx, word ptr [$005DE31C]
005DE186   B202                   mov     dl, $02

* Possible String Reference to: 'Selecionar a(s) rota(s).'
|
005DE188   B844E35D00             mov     eax, $005DE344

|
005DE18D   E8162AE7FF             call    00450BA8

* Reference to control TfrmRelatorioOcorrencia.ckbTodos : TCheckBox
|
005DE192   8B8398030000           mov     eax, [ebx+$0398]
005DE198   8B10                   mov     edx, [eax]

* Possible reference to virtual method TCheckBox.OFFS_00D4
|
005DE19A   FF92D4000000           call    dword ptr [edx+$00D4]
005DE1A0   E926010000             jmp     005DE2CB
005DE1A5   8D55DC                 lea     edx, [ebp-$24]

* Reference to control TfrmRelatorioOcorrencia.cmbRota : TComboBox
|
005DE1A8   8B8394030000           mov     eax, [ebx+$0394]

|
005DE1AE   E84D19E8FF             call    0045FB00
005DE1B3   8B45DC                 mov     eax, [ebp-$24]
005DE1B6   33D2                   xor     edx, edx

|
005DE1B8   E8C3D0E2FF             call    0040B280
005DE1BD   8BF0                   mov     esi, eax
005DE1BF   8D55D8                 lea     edx, [ebp-$28]

* Reference to control TfrmRelatorioOcorrencia.cmbRotaFim : TComboBox
|
005DE1C2   8B839C030000           mov     eax, [ebx+$039C]

|
005DE1C8   E83319E8FF             call    0045FB00
005DE1CD   8B45D8                 mov     eax, [ebp-$28]
005DE1D0   BA3F420F00             mov     edx, $000F423F

|
005DE1D5   E8A6D0E2FF             call    0040B280
005DE1DA   3BF0                   cmp     esi, eax
005DE1DC   7E28                   jle     005DE206
005DE1DE   6A00                   push    $00
005DE1E0   0FB70D1CE35D00         movzx   ecx, word ptr [$005DE31C]
005DE1E7   B202                   mov     dl, $02

* Possible String Reference to: 'Intervalo de Rotas inválido.'
|
005DE1E9   B868E35D00             mov     eax, $005DE368

|
005DE1EE   E8B529E7FF             call    00450BA8

* Reference to control TfrmRelatorioOcorrencia.ckbTodos : TCheckBox
|
005DE1F3   8B8398030000           mov     eax, [ebx+$0398]
005DE1F9   8B10                   mov     edx, [eax]

* Possible reference to virtual method TCheckBox.OFFS_00D4
|
005DE1FB   FF92D4000000           call    dword ptr [edx+$00D4]
005DE201   E9C5000000             jmp     005DE2CB
005DE206   8D55D4                 lea     edx, [ebp-$2C]

* Reference to control TfrmRelatorioOcorrencia.cmbGrupo : TComboBox
|
005DE209   8B8390030000           mov     eax, [ebx+$0390]

|
005DE20F   E8EC18E8FF             call    0045FB00
005DE214   8B45D4                 mov     eax, [ebp-$2C]
005DE217   33D2                   xor     edx, edx

|
005DE219   E862D0E2FF             call    0040B280
005DE21E   8BF8                   mov     edi, eax
005DE220   8D55D0                 lea     edx, [ebp-$30]

* Reference to control TfrmRelatorioOcorrencia.cmbRota : TComboBox
|
005DE223   8B8394030000           mov     eax, [ebx+$0394]

|
005DE229   E8D218E8FF             call    0045FB00
005DE22E   8B45D0                 mov     eax, [ebp-$30]
005DE231   33D2                   xor     edx, edx

|
005DE233   E848D0E2FF             call    0040B280
005DE238   8945FC                 mov     [ebp-$04], eax
005DE23B   8D55CC                 lea     edx, [ebp-$34]

* Reference to control TfrmRelatorioOcorrencia.cmbRotaFim : TComboBox
|
005DE23E   8B839C030000           mov     eax, [ebx+$039C]

|
005DE244   E8B718E8FF             call    0045FB00
005DE249   8B45CC                 mov     eax, [ebp-$34]
005DE24C   BA3F420F00             mov     edx, $000F423F

|
005DE251   E82AD0E2FF             call    0040B280
005DE256   8945F8                 mov     [ebp-$08], eax
005DE259   83CEFF                 or      esi, -$01
005DE25C   8D55C8                 lea     edx, [ebp-$38]

* Reference to control TfrmRelatorioOcorrencia.cmbOcorrencia : TComboBox
|
005DE25F   8B83A8030000           mov     eax, [ebx+$03A8]

|
005DE265   E89618E8FF             call    0045FB00
005DE26A   8B45C8                 mov     eax, [ebp-$38]

* Possible String Reference to: 'Exceto Leitura Normal (71)'
|
005DE26D   BA90E35D00             mov     edx, $005DE390

|
005DE272   E83D7AE2FF             call    00405CB4
005DE277   7507                   jnz     005DE280
005DE279   BEFEFFFFFF             mov     esi, $FFFFFFFE
005DE27E   EB35                   jmp     005DE2B5
005DE280   8D55C4                 lea     edx, [ebp-$3C]

* Reference to control TfrmRelatorioOcorrencia.cmbOcorrencia : TComboBox
|
005DE283   8B83A8030000           mov     eax, [ebx+$03A8]

|
005DE289   E87218E8FF             call    0045FB00
005DE28E   8B45C4                 mov     eax, [ebp-$3C]

* Possible String Reference to: 'TODOS'
|
005DE291   BAB4E35D00             mov     edx, $005DE3B4

|
005DE296   E8197AE2FF             call    00405CB4
005DE29B   7418                   jz      005DE2B5
005DE29D   8D55C0                 lea     edx, [ebp-$40]

* Reference to control TfrmRelatorioOcorrencia.cmbOcorrencia : TComboBox
|
005DE2A0   8B83A8030000           mov     eax, [ebx+$03A8]

|
005DE2A6   E85518E8FF             call    0045FB00
005DE2AB   8B45C0                 mov     eax, [ebp-$40]

|
005DE2AE   E89596F9FF             call    00577948
005DE2B3   8BF0                   mov     esi, eax
005DE2B5   8B45F8                 mov     eax, [ebp-$08]
005DE2B8   50                     push    eax
005DE2B9   56                     push    esi
005DE2BA   A1C8FC6300             mov     eax, dword ptr [$0063FCC8]
005DE2BF   8B00                   mov     eax, [eax]
005DE2C1   8B4DFC                 mov     ecx, [ebp-$04]
005DE2C4   8BD7                   mov     edx, edi

|
005DE2C6   E8B9CBF9FF             call    0057AE84
005DE2CB   33C0                   xor     eax, eax
005DE2CD   5A                     pop     edx
005DE2CE   59                     pop     ecx
005DE2CF   59                     pop     ecx
005DE2D0   648910                 mov     fs:[eax], edx

****** FINALLY
|
005DE2D3   6815E35D00             push    $005DE315
005DE2D8   8D45C0                 lea     eax, [ebp-$40]
005DE2DB   BA09000000             mov     edx, $00000009

|
005DE2E0   E8E375E2FF             call    004058C8
005DE2E5   8D45E4                 lea     eax, [ebp-$1C]

|
005DE2E8   E8B775E2FF             call    004058A4
005DE2ED   8D45E8                 lea     eax, [ebp-$18]

|
005DE2F0   E8AF75E2FF             call    004058A4
005DE2F5   8D45EC                 lea     eax, [ebp-$14]

|
005DE2F8   E8A775E2FF             call    004058A4
005DE2FD   8D45F0                 lea     eax, [ebp-$10]

|
005DE300   E89F75E2FF             call    004058A4
005DE305   8D45F4                 lea     eax, [ebp-$0C]

|
005DE308   E89775E2FF             call    004058A4
005DE30D   C3                     ret


|
005DE30E   E9816DE2FF             jmp     00405094
005DE313   EBC3                   jmp     005DE2D8

****** END
|
005DE315   5F                     pop     edi
005DE316   5E                     pop     esi
005DE317   5B                     pop     ebx
005DE318   8BE5                   mov     esp, ebp
005DE31A   5D                     pop     ebp
005DE31B   C3                     ret

*)
end;

procedure TfrmRelatorioOcorrencia.cmbGrupoChange(Sender : TObject);
begin
(*
005DDBFC   55                     push    ebp
005DDBFD   8BEC                   mov     ebp, esp
005DDBFF   33C9                   xor     ecx, ecx
005DDC01   51                     push    ecx
005DDC02   51                     push    ecx
005DDC03   51                     push    ecx
005DDC04   51                     push    ecx
005DDC05   53                     push    ebx
005DDC06   56                     push    esi
005DDC07   8BF0                   mov     esi, eax
005DDC09   33C0                   xor     eax, eax
005DDC0B   55                     push    ebp

* Possible String Reference to: 'ésâÿëÞ^[‹å]Ã'
|
005DDC0C   6882DD5D00             push    $005DDD82

***** TRY
|
005DDC11   64FF30                 push    dword ptr fs:[eax]
005DDC14   648920                 mov     fs:[eax], esp

* Reference to control TfrmRelatorioOcorrencia.cmbRota : TComboBox
|
005DDC17   8B8694030000           mov     eax, [esi+$0394]
005DDC1D   8B10                   mov     edx, [eax]

* Possible reference to virtual method TComboBox.OFFS_00E8
|
005DDC1F   FF92E8000000           call    dword ptr [edx+$00E8]

* Reference to control TfrmRelatorioOcorrencia.cmbRotaFim : TComboBox
|
005DDC25   8B869C030000           mov     eax, [esi+$039C]
005DDC2B   8B10                   mov     edx, [eax]

* Possible reference to virtual method TComboBox.OFFS_00E8
|
005DDC2D   FF92E8000000           call    dword ptr [edx+$00E8]

* Reference to control TfrmRelatorioOcorrencia.cmbRota : TComboBox
|
005DDC33   8B8694030000           mov     eax, [esi+$0394]

* Reference to field TComboBox.OFFS_0284
|
005DDC39   8B8084020000           mov     eax, [eax+$0284]
005DDC3F   8B10                   mov     edx, [eax]
005DDC41   FF5244                 call    dword ptr [edx+$44]

* Reference to control TfrmRelatorioOcorrencia.cmbRotaFim : TComboBox
|
005DDC44   8B869C030000           mov     eax, [esi+$039C]

* Reference to field TComboBox.OFFS_0284
|
005DDC4A   8B8084020000           mov     eax, [eax+$0284]
005DDC50   8B10                   mov     edx, [eax]
005DDC52   FF5244                 call    dword ptr [edx+$44]
005DDC55   8D55FC                 lea     edx, [ebp-$04]

* Reference to control TfrmRelatorioOcorrencia.cmbGrupo : TComboBox
|
005DDC58   8B8690030000           mov     eax, [esi+$0390]

|
005DDC5E   E89D1EE8FF             call    0045FB00
005DDC63   8B45FC                 mov     eax, [ebp-$04]
005DDC66   83CAFF                 or      edx, -$01

|
005DDC69   E812D6E2FF             call    0040B280
005DDC6E   85C0                   test    eax, eax
005DDC70   7D28                   jnl     005DDC9A
005DDC72   6A00                   push    $00
005DDC74   0FB70D90DD5D00         movzx   ecx, word ptr [$005DDD90]
005DDC7B   B202                   mov     dl, $02

* Possible String Reference to: 'Informar o grupo.'
|
005DDC7D   B89CDD5D00             mov     eax, $005DDD9C

|
005DDC82   E8212FE7FF             call    00450BA8

* Reference to control TfrmRelatorioOcorrencia.cmbGrupo : TComboBox
|
005DDC87   8B8690030000           mov     eax, [esi+$0390]
005DDC8D   8B10                   mov     edx, [eax]

* Possible reference to virtual method TComboBox.OFFS_00D4
|
005DDC8F   FF92D4000000           call    dword ptr [edx+$00D4]
005DDC95   E9C0000000             jmp     005DDD5A

* Reference to control TfrmRelatorioOcorrencia.qryRota : TQuery
|
005DDC9A   8B86B0030000           mov     eax, [esi+$03B0]

|
005DDCA0   E86B08ECFF             call    0049E510
005DDCA5   8D55F8                 lea     edx, [ebp-$08]

* Reference to control TfrmRelatorioOcorrencia.cmbGrupo : TComboBox
|
005DDCA8   8B8690030000           mov     eax, [esi+$0390]

|
005DDCAE   E84D1EE8FF             call    0045FB00
005DDCB3   8B45F8                 mov     eax, [ebp-$08]
005DDCB6   33D2                   xor     edx, edx

|
005DDCB8   E8C3D5E2FF             call    0040B280
005DDCBD   50                     push    eax

* Possible String Reference to: 'nGrupo'
|
005DDCBE   BAB8DD5D00             mov     edx, $005DDDB8

* Reference to control TfrmRelatorioOcorrencia.qryRota : TQuery
|
005DDCC3   8B86B0030000           mov     eax, [esi+$03B0]

|
005DDCC9   E8B2CCEDFF             call    004BA980
005DDCCE   5A                     pop     edx

|
005DDCCF   E818FAEBFF             call    0049D6EC

* Reference to control TfrmRelatorioOcorrencia.qryRota : TQuery
|
005DDCD4   8B86B0030000           mov     eax, [esi+$03B0]

|
005DDCDA   E81D08ECFF             call    0049E4FC
005DDCDF   EB5F                   jmp     005DDD40
005DDCE1   BAC4DD5D00             mov     edx, $005DDDC4
005DDCE6   8BC3                   mov     eax, ebx

|
005DDCE8   E84B1BECFF             call    0049F838
005DDCED   8D55F4                 lea     edx, [ebp-$0C]
005DDCF0   8B08                   mov     ecx, [eax]
005DDCF2   FF5160                 call    dword ptr [ecx+$60]
005DDCF5   8B55F4                 mov     edx, [ebp-$0C]

* Reference to control TfrmRelatorioOcorrencia.cmbRota : TComboBox
|
005DDCF8   8B8694030000           mov     eax, [esi+$0394]

* Reference to field TComboBox.OFFS_0284
|
005DDCFE   8B8084020000           mov     eax, [eax+$0284]
005DDD04   8B08                   mov     ecx, [eax]
005DDD06   FF5138                 call    dword ptr [ecx+$38]
005DDD09   BAC4DD5D00             mov     edx, $005DDDC4

* Reference to control TfrmRelatorioOcorrencia.qryRota : TQuery
|
005DDD0E   8B86B0030000           mov     eax, [esi+$03B0]

|
005DDD14   E81F1BECFF             call    0049F838
005DDD19   8D55F0                 lea     edx, [ebp-$10]
005DDD1C   8B08                   mov     ecx, [eax]

* Possible reference to virtual method TQuery.OFFS_60
|
005DDD1E   FF5160                 call    dword ptr [ecx+$60]
005DDD21   8B55F0                 mov     edx, [ebp-$10]

* Reference to control TfrmRelatorioOcorrencia.cmbRotaFim : TComboBox
|
005DDD24   8B869C030000           mov     eax, [esi+$039C]

* Reference to field TComboBox.OFFS_0284
|
005DDD2A   8B8084020000           mov     eax, [eax+$0284]
005DDD30   8B08                   mov     ecx, [eax]
005DDD32   FF5138                 call    dword ptr [ecx+$38]

* Reference to control TfrmRelatorioOcorrencia.qryRota : TQuery
|
005DDD35   8B86B0030000           mov     eax, [esi+$03B0]

|
005DDD3B   E8E032ECFF             call    004A1020

* Reference to control TfrmRelatorioOcorrencia.qryRota : TQuery
|
005DDD40   8B9EB0030000           mov     ebx, [esi+$03B0]

* Reference to field TQuery.OFFS_00A1
|
005DDD46   80BBA100000000         cmp     byte ptr [ebx+$00A1], $00
005DDD4D   7492                   jz      005DDCE1

* Reference to control TfrmRelatorioOcorrencia.qryRota : TQuery
|
005DDD4F   8B86B0030000           mov     eax, [esi+$03B0]

|
005DDD55   E8B607ECFF             call    0049E510
005DDD5A   33C0                   xor     eax, eax
005DDD5C   5A                     pop     edx
005DDD5D   59                     pop     ecx
005DDD5E   59                     pop     ecx
005DDD5F   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: '^[‹å]Ã'
|
005DDD62   6889DD5D00             push    $005DDD89
005DDD67   8D45F0                 lea     eax, [ebp-$10]
005DDD6A   BA02000000             mov     edx, $00000002

|
005DDD6F   E8547BE2FF             call    004058C8
005DDD74   8D45F8                 lea     eax, [ebp-$08]
005DDD77   BA02000000             mov     edx, $00000002

|
005DDD7C   E8477BE2FF             call    004058C8
005DDD81   C3                     ret


|
005DDD82   E90D73E2FF             jmp     00405094
005DDD87   EBDE                   jmp     005DDD67

****** END
|
005DDD89   5E                     pop     esi
005DDD8A   5B                     pop     ebx
005DDD8B   8BE5                   mov     esp, ebp
005DDD8D   5D                     pop     ebp
005DDD8E   C3                     ret

*)
end;

procedure TfrmRelatorioOcorrencia.cmbGrupoDropDown(Sender : TObject);
begin
(*
005DDDD0   55                     push    ebp
005DDDD1   8BEC                   mov     ebp, esp
005DDDD3   6A00                   push    $00
005DDDD5   53                     push    ebx
005DDDD6   56                     push    esi
005DDDD7   8BD8                   mov     ebx, eax
005DDDD9   33C0                   xor     eax, eax
005DDDDB   55                     push    ebp

* Possible String Reference to: 'éÐqâÿëð^[Y]Ã'
|
005DDDDC   68BFDE5D00             push    $005DDEBF

***** TRY
|
005DDDE1   64FF30                 push    dword ptr fs:[eax]
005DDDE4   648920                 mov     fs:[eax], esp

* Reference to control TfrmRelatorioOcorrencia.cmbRota : TComboBox
|
005DDDE7   8B8394030000           mov     eax, [ebx+$0394]
005DDDED   8B10                   mov     edx, [eax]

* Possible reference to virtual method TComboBox.OFFS_00E8
|
005DDDEF   FF92E8000000           call    dword ptr [edx+$00E8]

* Reference to control TfrmRelatorioOcorrencia.cmbRotaFim : TComboBox
|
005DDDF5   8B839C030000           mov     eax, [ebx+$039C]
005DDDFB   8B10                   mov     edx, [eax]

* Possible reference to virtual method TComboBox.OFFS_00E8
|
005DDDFD   FF92E8000000           call    dword ptr [edx+$00E8]

* Reference to control TfrmRelatorioOcorrencia.cmbRota : TComboBox
|
005DDE03   8B8394030000           mov     eax, [ebx+$0394]

* Reference to field TComboBox.OFFS_0284
|
005DDE09   8B8084020000           mov     eax, [eax+$0284]
005DDE0F   8B10                   mov     edx, [eax]
005DDE11   FF5244                 call    dword ptr [edx+$44]

* Reference to control TfrmRelatorioOcorrencia.cmbRotaFim : TComboBox
|
005DDE14   8B839C030000           mov     eax, [ebx+$039C]

* Reference to field TComboBox.OFFS_0284
|
005DDE1A   8B8084020000           mov     eax, [eax+$0284]
005DDE20   8B10                   mov     edx, [eax]
005DDE22   FF5244                 call    dword ptr [edx+$44]

* Reference to control TfrmRelatorioOcorrencia.cmbGrupo : TComboBox
|
005DDE25   8B8390030000           mov     eax, [ebx+$0390]
005DDE2B   8B10                   mov     edx, [eax]

* Possible reference to virtual method TComboBox.OFFS_00E8
|
005DDE2D   FF92E8000000           call    dword ptr [edx+$00E8]

* Reference to control TfrmRelatorioOcorrencia.cmbGrupo : TComboBox
|
005DDE33   8B8390030000           mov     eax, [ebx+$0390]

* Reference to field TComboBox.OFFS_0284
|
005DDE39   8B8084020000           mov     eax, [eax+$0284]
005DDE3F   8B10                   mov     edx, [eax]
005DDE41   FF5244                 call    dword ptr [edx+$44]

* Reference to control TfrmRelatorioOcorrencia.qryGrupo : TQuery
|
005DDE44   8B83AC030000           mov     eax, [ebx+$03AC]

|
005DDE4A   E8C106ECFF             call    0049E510

* Reference to control TfrmRelatorioOcorrencia.qryGrupo : TQuery
|
005DDE4F   8B83AC030000           mov     eax, [ebx+$03AC]

|
005DDE55   E8A206ECFF             call    0049E4FC
005DDE5A   EB33                   jmp     005DDE8F
005DDE5C   BAD0DE5D00             mov     edx, $005DDED0
005DDE61   8BC6                   mov     eax, esi

|
005DDE63   E8D019ECFF             call    0049F838
005DDE68   8D55FC                 lea     edx, [ebp-$04]
005DDE6B   8B08                   mov     ecx, [eax]
005DDE6D   FF5160                 call    dword ptr [ecx+$60]
005DDE70   8B55FC                 mov     edx, [ebp-$04]

* Reference to control TfrmRelatorioOcorrencia.cmbGrupo : TComboBox
|
005DDE73   8B8390030000           mov     eax, [ebx+$0390]

* Reference to field TComboBox.OFFS_0284
|
005DDE79   8B8084020000           mov     eax, [eax+$0284]
005DDE7F   8B08                   mov     ecx, [eax]
005DDE81   FF5138                 call    dword ptr [ecx+$38]

* Reference to control TfrmRelatorioOcorrencia.qryGrupo : TQuery
|
005DDE84   8B83AC030000           mov     eax, [ebx+$03AC]

|
005DDE8A   E89131ECFF             call    004A1020

* Reference to control TfrmRelatorioOcorrencia.qryGrupo : TQuery
|
005DDE8F   8BB3AC030000           mov     esi, [ebx+$03AC]

* Reference to field TQuery.OFFS_00A1
|
005DDE95   80BEA100000000         cmp     byte ptr [esi+$00A1], $00
005DDE9C   74BE                   jz      005DDE5C

* Reference to control TfrmRelatorioOcorrencia.qryGrupo : TQuery
|
005DDE9E   8B83AC030000           mov     eax, [ebx+$03AC]

|
005DDEA4   E86706ECFF             call    0049E510
005DDEA9   33C0                   xor     eax, eax
005DDEAB   5A                     pop     edx
005DDEAC   59                     pop     ecx
005DDEAD   59                     pop     ecx
005DDEAE   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: '^[Y]Ã'
|
005DDEB1   68C6DE5D00             push    $005DDEC6
005DDEB6   8D45FC                 lea     eax, [ebp-$04]

|
005DDEB9   E8E679E2FF             call    004058A4
005DDEBE   C3                     ret


|
005DDEBF   E9D071E2FF             jmp     00405094
005DDEC4   EBF0                   jmp     005DDEB6

****** END
|
005DDEC6   5E                     pop     esi
005DDEC7   5B                     pop     ebx
005DDEC8   59                     pop     ecx
005DDEC9   5D                     pop     ebp
005DDECA   C3                     ret

*)
end;

procedure TfrmRelatorioOcorrencia.ckbTodosClick(Sender : TObject);
begin
(*
005DDB98   53                     push    ebx
005DDB99   8BD8                   mov     ebx, eax
005DDB9B   83CAFF                 or      edx, -$01

* Reference to control TfrmRelatorioOcorrencia.cmbRota : TComboBox
|
005DDB9E   8B8394030000           mov     eax, [ebx+$0394]
005DDBA4   8B08                   mov     ecx, [eax]

* Possible reference to virtual method TComboBox.OFFS_00E0
|
005DDBA6   FF91E0000000           call    dword ptr [ecx+$00E0]
005DDBAC   83CAFF                 or      edx, -$01

* Reference to control TfrmRelatorioOcorrencia.cmbRotaFim : TComboBox
|
005DDBAF   8B839C030000           mov     eax, [ebx+$039C]
005DDBB5   8B08                   mov     ecx, [eax]

* Possible reference to virtual method TComboBox.OFFS_00E0
|
005DDBB7   FF91E0000000           call    dword ptr [ecx+$00E0]

* Reference to control TfrmRelatorioOcorrencia.ckbTodos : TCheckBox
|
005DDBBD   8B8398030000           mov     eax, [ebx+$0398]
005DDBC3   8B10                   mov     edx, [eax]

* Possible reference to virtual method TCheckBox.OFFS_00D8
|
005DDBC5   FF92D8000000           call    dword ptr [edx+$00D8]
005DDBCB   8BD0                   mov     edx, eax
005DDBCD   80F201                 xor     dl, $01

* Reference to control TfrmRelatorioOcorrencia.cmbRota : TComboBox
|
005DDBD0   8B8394030000           mov     eax, [ebx+$0394]
005DDBD6   8B08                   mov     ecx, [eax]

* Possible reference to virtual method TComboBox.OFFS_68
|
005DDBD8   FF5168                 call    dword ptr [ecx+$68]

* Reference to control TfrmRelatorioOcorrencia.ckbTodos : TCheckBox
|
005DDBDB   8B8398030000           mov     eax, [ebx+$0398]
005DDBE1   8B10                   mov     edx, [eax]

* Possible reference to virtual method TCheckBox.OFFS_00D8
|
005DDBE3   FF92D8000000           call    dword ptr [edx+$00D8]
005DDBE9   8BD0                   mov     edx, eax
005DDBEB   80F201                 xor     dl, $01

* Reference to control TfrmRelatorioOcorrencia.cmbRotaFim : TComboBox
|
005DDBEE   8B839C030000           mov     eax, [ebx+$039C]
005DDBF4   8B08                   mov     ecx, [eax]

* Possible reference to virtual method TComboBox.OFFS_68
|
005DDBF6   FF5168                 call    dword ptr [ecx+$68]
005DDBF9   5B                     pop     ebx
005DDBFA   C3                     ret

*)
end;

procedure TfrmRelatorioOcorrencia._PROC_005DDD8F(Sender : TObject);
begin
(*
005DDD8F   000400                 add     [eax+eax], al
005DDD92   0000                   add     [eax], al

*)
end;

procedure TfrmRelatorioOcorrencia._PROC_005DDECB(Sender : TObject);
begin
(*
005DDECB   000A                   add     [edx], cl
005DDECD   0000                   add     [eax], al

*)
end;

procedure TfrmRelatorioOcorrencia._PROC_005DDEDD(Sender : TObject);
begin
(*
005DDEDD   8BEC                   mov     ebp, esp
005DDEDF   83C4F8                 add     esp, -$08
005DDEE2   53                     push    ebx
005DDEE3   56                     push    esi
005DDEE4   33D2                   xor     edx, edx
005DDEE6   8955F8                 mov     [ebp-$08], edx
005DDEE9   8BD8                   mov     ebx, eax
005DDEEB   33C0                   xor     eax, eax
005DDEED   55                     push    ebp
005DDEEE   6810E05D00             push    $005DE010

***** TRY
|
005DDEF3   64FF30                 push    dword ptr fs:[eax]
005DDEF6   648920                 mov     fs:[eax], esp

* Reference to field TfrmRelatorioOcorrencia.OFFS_0374
|
005DDEF9   8D8374030000           lea     eax, [ebx+$0374]

* Possible String Reference to: 'Relatório de Ocorrências'
|
005DDEFF   BA2CE05D00             mov     edx, $005DE02C

|
005DDF04   E8EF79E2FF             call    004058F8

* Reference to field TfrmRelatorioOcorrencia.OFFS_0378
|
005DDF09   8D8378030000           lea     eax, [ebx+$0378]

* Possible String Reference to: 'Versão 8.0'
|
005DDF0F   BA50E05D00             mov     edx, $005DE050

|
005DDF14   E8DF79E2FF             call    004058F8
005DDF19   C645FF01               mov     byte ptr [ebp-$01], $01

* Reference to control TfrmRelatorioOcorrencia.cmbOcorrencia : TComboBox
|
005DDF1D   8B83A8030000           mov     eax, [ebx+$03A8]
005DDF23   8B10                   mov     edx, [eax]

* Possible reference to virtual method TComboBox.OFFS_00E8
|
005DDF25   FF92E8000000           call    dword ptr [edx+$00E8]

* Reference to control TfrmRelatorioOcorrencia.cmbOcorrencia : TComboBox
|
005DDF2B   8B83A8030000           mov     eax, [ebx+$03A8]

* Reference to field TComboBox.OFFS_0284
|
005DDF31   8B8084020000           mov     eax, [eax+$0284]
005DDF37   8B10                   mov     edx, [eax]
005DDF39   FF5244                 call    dword ptr [edx+$44]

* Reference to control TfrmRelatorioOcorrencia.cmbOcorrencia : TComboBox
|
005DDF3C   8B83A8030000           mov     eax, [ebx+$03A8]

* Reference to field TComboBox.OFFS_0284
|
005DDF42   8B8084020000           mov     eax, [eax+$0284]

* Possible String Reference to: 'TODOS'
|
005DDF48   BA64E05D00             mov     edx, $005DE064
005DDF4D   8B08                   mov     ecx, [eax]
005DDF4F   FF5138                 call    dword ptr [ecx+$38]

* Reference to control TfrmRelatorioOcorrencia.cmbOcorrencia : TComboBox
|
005DDF52   8B83A8030000           mov     eax, [ebx+$03A8]

* Reference to field TComboBox.OFFS_0284
|
005DDF58   8B8084020000           mov     eax, [eax+$0284]

* Possible String Reference to: 'Não Faturado · 0'
|
005DDF5E   BA74E05D00             mov     edx, $005DE074
005DDF63   8B08                   mov     ecx, [eax]
005DDF65   FF5138                 call    dword ptr [ecx+$38]

* Reference to control TfrmRelatorioOcorrencia.cmbOcorrencia : TComboBox
|
005DDF68   8B83A8030000           mov     eax, [ebx+$03A8]

* Reference to field TComboBox.OFFS_0284
|
005DDF6E   8B8084020000           mov     eax, [eax+$0284]

* Possible String Reference to: 'Exceto Leitura Normal (71)'
|
005DDF74   BA90E05D00             mov     edx, $005DE090
005DDF79   8B08                   mov     ecx, [eax]
005DDF7B   FF5138                 call    dword ptr [ecx+$38]
005DDF7E   33D2                   xor     edx, edx

* Reference to control TfrmRelatorioOcorrencia.cmbOcorrencia : TComboBox
|
005DDF80   8B83A8030000           mov     eax, [ebx+$03A8]
005DDF86   8B08                   mov     ecx, [eax]

* Possible reference to virtual method TComboBox.OFFS_00E0
|
005DDF88   FF91E0000000           call    dword ptr [ecx+$00E0]

* Reference to control TfrmRelatorioOcorrencia.qryOcorrencia : TQuery
|
005DDF8E   8B83B4030000           mov     eax, [ebx+$03B4]

|
005DDF94   E87705ECFF             call    0049E510

* Reference to control TfrmRelatorioOcorrencia.qryOcorrencia : TQuery
|
005DDF99   8B83B4030000           mov     eax, [ebx+$03B4]

|
005DDF9F   E85805ECFF             call    0049E4FC
005DDFA4   EB33                   jmp     005DDFD9
005DDFA6   BAB0E05D00             mov     edx, $005DE0B0
005DDFAB   8BC6                   mov     eax, esi

|
005DDFAD   E88618ECFF             call    0049F838
005DDFB2   8D55F8                 lea     edx, [ebp-$08]
005DDFB5   8B08                   mov     ecx, [eax]
005DDFB7   FF5160                 call    dword ptr [ecx+$60]
005DDFBA   8B55F8                 mov     edx, [ebp-$08]

* Reference to control TfrmRelatorioOcorrencia.cmbOcorrencia : TComboBox
|
005DDFBD   8B83A8030000           mov     eax, [ebx+$03A8]

* Reference to field TComboBox.OFFS_0284
|
005DDFC3   8B8084020000           mov     eax, [eax+$0284]
005DDFC9   8B08                   mov     ecx, [eax]
005DDFCB   FF5138                 call    dword ptr [ecx+$38]

* Reference to control TfrmRelatorioOcorrencia.qryOcorrencia : TQuery
|
005DDFCE   8B83B4030000           mov     eax, [ebx+$03B4]

|
005DDFD4   E84730ECFF             call    004A1020

* Reference to control TfrmRelatorioOcorrencia.qryOcorrencia : TQuery
|
005DDFD9   8BB3B4030000           mov     esi, [ebx+$03B4]

* Reference to field TQuery.OFFS_00A1
|
005DDFDF   80BEA100000000         cmp     byte ptr [esi+$00A1], $00
005DDFE6   74BE                   jz      005DDFA6

* Reference to control TfrmRelatorioOcorrencia.qryOcorrencia : TQuery
|
005DDFE8   8B83B4030000           mov     eax, [ebx+$03B4]

|
005DDFEE   E81D05ECFF             call    0049E510
005DDFF3   8BC3                   mov     eax, ebx

|
005DDFF5   E8CECCF8FF             call    0056ACC8
005DDFFA   33C0                   xor     eax, eax
005DDFFC   5A                     pop     edx
005DDFFD   59                     pop     ecx
005DDFFE   59                     pop     ecx
005DDFFF   648910                 mov     fs:[eax], edx

****** FINALLY
|
005DE002   6817E05D00             push    $005DE017
005DE007   8D45F8                 lea     eax, [ebp-$08]

|
005DE00A   E89578E2FF             call    004058A4
005DE00F   C3                     ret


|
005DE010   E97F70E2FF             jmp     00405094
005DE015   EBF0                   jmp     005DE007

****** END
|
005DE017   0FB645FF               movzx   eax, byte ptr [ebp-$01]
005DE01B   5E                     pop     esi
005DE01C   5B                     pop     ebx
005DE01D   59                     pop     ecx
005DE01E   59                     pop     ecx
005DE01F   5D                     pop     ebp
005DE020   C3                     ret

*)
end;

procedure TfrmRelatorioOcorrencia._PROC_005DE31C(Sender : TObject);
begin
(*
005DE31C   0400                   add     al, +$00
005DE31E   0000                   add     [eax], al

*)
end;

procedure TfrmRelatorioOcorrencia._PROC_005DE3F2(Sender : TObject);
begin
(*
005DE3F2   47                     inc     edi
005DE3F3   001C4B                 add     [ebx+ecx*2], bl
005DE3F6   40                     inc     eax
005DE3F7   000C8547005848         add     [$48580047+eax*4], cl
005DE3FE   40                     inc     eax
005DE3FF   00744840               add     [eax+ecx*2+$40], dh
005DE403   00905547008C           add     [eax+$8C004755], dl
005DE409   844600                 test    [esi+$00], al
005DE40C   845B47                 test    [ebx+$47], bl
005DE40F   000C31                 add     [ecx+esi], cl
005DE412   42                     inc     edx
005DE413   006C5747               add     [edi+edx*2+$47], ch
005DE417   00B8574700F4           add     [eax+$F4004757], bh
005DE41D   58                     pop     eax
005DE41E   47                     inc     edi
005DE41F   00E8                   add     al, ch
005DE421   F8                     clc
005DE422   45                     inc     ebp
005DE423   0094C542008462         add     [ebp+eax*8+$62840042], dl
005DE42A   47                     inc     edi
005DE42B   0070C2                 add     [eax-$3E], dh
005DE42E   42                     inc     edx
005DE42F   0070AB                 add     [eax-$55], dh
005DE432   47                     inc     edi
005DE433   00E0                   add     al, ah
005DE435   51                     push    ecx
005DE436   47                     inc     edi
005DE437   00B07E4600BC           add     [eax+$BC00467E], dh
005DE43D   844600                 test    [esi+$00], al
005DE440   08844600B0EB45         or      [esi+eax*2+$45EBB000], al
005DE447   002C79                 add     [ecx+edi*2], ch
005DE44A   46                     inc     esi
005DE44B   00B85E4700B8           add     [eax+$B800475E], bh
005DE451   7546                   jnz     005DE499
005DE453   00F0                   add     al, dh
005DE455   EA4500F4EA             jmp     $EAF40045
005DE45A   45                     inc     ebp
005DE45B   00AC5F47006C24         add     [edi+ebx*2+$246C0047], ch
005DE462   46                     inc     esi
005DE463   003CA8                 add     [eax+ebp*4], bh
005DE466   47                     inc     edi
005DE467   00CC                   add     ah, cl
005DE469   F8                     clc
005DE46A   45                     inc     ebp
005DE46B   002CED450058FA         add     [$FA580045+ebp*8], ch
005DE472   45                     inc     ebp
005DE473   00C8                   add     al, cl
005DE475   61                     popa
005DE476   47                     inc     edi
005DE477   008460470094FB         add     [eax+$FB940047], al
005DE47E   45                     inc     ebp
005DE47F   00C4                   add     ah, al
005DE481   624700                 bound   eax, qword ptr [edi+$00]
005DE484   F0                     lock
005DE485   2446                   and     al, $46
005DE487   000C76                 add     [esi+esi*2], cl
005DE48A   46                     inc     esi
005DE48B   00CC                   add     ah, cl
005DE48D   7646                   jbe     005DE4D5
005DE48F   00C0                   add     al, al
005DE491   7146                   jno     005DE4D9
005DE493   00B0764600C8           add     [eax+$C8004676], dh
005DE499   4F                     dec     edi
005DE49A   47                     inc     edi
005DE49B   0008                   add     [eax], cl
005DE49D   6A47                   push    $47
005DE49F   00A042460034           add     [eax+$34004642], ah
005DE4A5   7D47                   jnl     005DE4EE
005DE4A7   004882                 add     [eax-$7E], cl
005DE4AA   47                     inc     edi
005DE4AB   00748047               add     [eax+eax*4+$47], dh
005DE4AF   0038                   add     [eax], bh
005DE4B1   43                     inc     ebx
005DE4B2   46                     inc     esi
005DE4B3   005C4346               add     [ebx+eax*2+$46], bl
005DE4B7   00C4                   add     ah, al
005DE4B9   834700C8               add     dword ptr [edi+$00], -$38
005DE4BD   844700                 test    [edi+$00], al
005DE4C0   94                     xchg    eax, esp
005DE4C1   41                     inc     ecx
005DE4C2   46                     inc     esi
005DE4C3   00A08C4600F8           add     [eax+$F800468C], ah
005DE4C9   7746                   jnbe    005DE511
005DE4CB   0000                   add     [eax], al

005DE4CD   8C4700                 mov     word ptr [edi+$00], es
005DE4D0   148C                   adc     al, $8C
005DE4D2   46                     inc     esi
005DE4D3   006874                 add     [eax+$74], ch
005DE4D6   46                     inc     esi
005DE4D7   00648D46               add     [ebp+ecx*4+$46], ah
005DE4DB   0088A34700A8           add     [eax+$A80047A3], cl
005DE4E1   49                     dec     ecx
005DE4E2   47                     inc     edi
005DE4E3   00584C                 add     [eax+$4C], bl
005DE4E6   47                     inc     edi
005DE4E7   004093                 add     [eax-$6D], al
005DE4EA   47                     inc     edi
005DE4EB   00905647000C           add     [eax+$C004756], dl
005DE4F1   57                     push    edi
005DE4F2   47                     inc     edi
005DE4F3   00D4                   add     ah, dl
005DE4F5   A7                     cmpsd
005DE4F6   47                     inc     edi
005DE4F7   00A45347006CA2         add     [ebx+edx*2+$A26C0047], ah
005DE4FE   47                     inc     edi
005DE4FF   009C86470060A4         add     [esi+eax*4+$A4600047], bl
005DE506   47                     inc     edi
005DE507   00C4                   add     ah, al
005DE509   61                     popa
005DE50A   47                     inc     edi
005DE50B   0008                   add     [eax], cl
005DE50D   E75D                   out     $5D, eax
005DE50F   001400                 add     [eax+eax], dl
005DE512   B3E6                   mov     bl, $E6
005DE514   5D                     pop     ebp
005DE515   008003000000           add     [eax+$0003], al
005DE51B   0009                   add     [ecx], cl
005DE51D   47                     inc     edi
005DE51E   726F                   jb      005DE58F
005DE520   7570                   jnz     005DE592
005DE522   42                     inc     edx
005DE523   6F                     outsd
005DE524   7831                   js      005DE557
005DE526   8403                   test    [ebx], al
005DE528   0000                   add     [eax], al

005DE52A   0100                   add     [eax], eax
005DE52C   06                     push    es
005DE52D   4C                     dec     esp
005DE52E   47                     inc     edi
005DE52F   7275                   jb      005DE5A6
005DE531   706F                   jo      005DE5A2
005DE533   8803                   mov     [ebx], al
005DE535   0000                   add     [eax], al

005DE537   0100                   add     [eax], eax
005DE539   054C526F74             add     eax, +$746F524C
005DE53E   61                     popa
005DE53F   8C03                   mov     word ptr [ebx], es
005DE541   0000                   add     [eax], al

005DE543   0100                   add     [eax], eax
005DE545   06                     push    es
005DE546   4C                     dec     esp
005DE547   61                     popa
005DE548   62656C                 bound   esp, qword ptr [ebp+$6C]
005DE54B   319003000002           xor     [eax+$2000003], edx
005DE551   0008                   add     [eax], cl
005DE553   636D62                 arpl    [ebp+$62], bp
005DE556   47                     inc     edi
005DE557   7275                   jb      005DE5CE
005DE559   706F                   jo      005DE5CA
005DE55B   94                     xchg    eax, esp
005DE55C   0300                   add     eax, [eax]
005DE55E   0002                   add     [edx], al
005DE560   0007                   add     [edi], al
005DE562   636D62                 arpl    [ebp+$62], bp
005DE565   52                     push    edx
005DE566   6F                     outsd
005DE567   7461                   jz      005DE5CA
005DE569   98                     cwde 
005DE56A   0300                   add     eax, [eax]
005DE56C   0003                   add     [ebx], al
005DE56E   0008                   add     [eax], cl
005DE570   636B62                 arpl    [ebx+$62], bp
005DE573   54                     push    esp
005DE574   6F                     outsd
005DE575   646F                   outsd
005DE577   739C                   jnb     005DE515
005DE579   0300                   add     eax, [eax]
005DE57B   0002                   add     [edx], al
005DE57D   000A                   add     [edx], cl
005DE57F   636D62                 arpl    [ebp+$62], bp
005DE582   52                     push    edx
005DE583   6F                     outsd
005DE584   7461                   jz      005DE5E7
005DE586   46                     inc     esi
005DE587   696DA003000004         imul    ebp, [ebp-$60], $04000003
005DE58E   000C73                 add     [ebx+esi*2], cl
005DE591   62746E49               bound   esi, qword ptr [esi+ebp*2+$49]
005DE595   6D                     insd
005DE596   7072                   jo      005DE60A
005DE598   696D6972A40300         imul    ebp, [ebp+$69], $0003A472
005DE59F   0001                   add     [ecx], al
005DE5A1   0006                   add     [esi], al
005DE5A3   4C                     dec     esp
005DE5A4   61                     popa
005DE5A5   62656C                 bound   esp, qword ptr [ebp+$6C]
005DE5A8   32A803000005           xor     ch, byte ptr [eax+$5000003]
005DE5AE   000545644344           add     [$44436445], al
005DE5B4   43                     inc     ebx
005DE5B5   AC                     lodsb
005DE5B6   0300                   add     eax, [eax]
005DE5B8   0000                   add     [eax], al

005DE5BA   000A                   add     [edx], cl
005DE5BC   677262                 jb      005DE621
005DE5BF   45                     inc     ebp
005DE5C0   6D                     insd
005DE5C1   697373616FB003         imul    esi, [ebx+$73], $03B06F61
005DE5C8   0000                   add     [eax], al

005DE5CA   06                     push    es
005DE5CB   0008                   add     [eax], cl
005DE5CD   7264                   jb      005DE633
005DE5CF   624176                 bound   eax, qword ptr [ecx+$76]
005DE5D2   69736FB4030000         imul    esi, [ebx+$6F], $000003B4
005DE5D9   06                     push    es
005DE5DA   000E                   add     [esi], cl
005DE5DC   7264                   jb      005DE642
005DE5DE   624E6F                 bound   ecx, qword ptr [esi+$6F]
005DE5E1   7469                   jz      005DE64C
005DE5E3   666963616361           imul    sp, word ptr [ebx+$61], $6163
005DE5E9   6F                     outsd
005DE5EA   B803000007             mov     eax, $07000003
005DE5EF   0008                   add     [eax], cl
005DE5F1   7172                   jno     005DE665
005DE5F3   7947                   jns     005DE63C
005DE5F5   7275                   jb      005DE66C
005DE5F7   706F                   jo      005DE668
005DE5F9   BC03000007             mov     esp, $07000003
005DE5FE   0007                   add     [edi], al
005DE600   7172                   jno     005DE674
005DE602   7952                   jns     005DE656
005DE604   6F                     outsd
005DE605   7461                   jz      005DE668
005DE607   C00300                 rol     byte ptr [ebx], $00
005DE60A   0000                   add     [eax], al

005DE60C   0009                   add     [ecx], cl
005DE60E   677262                 jb      005DE673
005DE611   46                     inc     esi
005DE612   61                     popa
005DE613   7475                   jz      005DE68A
005DE615   7261                   jb      005DE678
005DE617   C403                   les     eax, [ebx]
005DE619   0000                   add     [eax], al

005DE61B   06                     push    es
005DE61C   0008                   add     [eax], cl
005DE61E   7264                   jb      005DE684
005DE620   62546F64               bound   edx, qword ptr [edi+ebp*2+$64]
005DE624   61                     popa
005DE625   73C8                   jnb     005DE5EF
005DE627   0300                   add     eax, [eax]
005DE629   0006                   add     [esi], al
005DE62B   000A                   add     [edx], cl
005DE62D   7264                   jb      005DE693
005DE62F   625265                 bound   edx, qword ptr [edx+$65]
005DE632   7469                   jz      005DE69D
005DE634   6461                   popa
005DE636   73CC                   jnb     005DE604
005DE638   0300                   add     eax, [eax]
005DE63A   0006                   add     [esi], al
005DE63C   000C72                 add     [edx+esi*2], cl
005DE63F   6462436F               bound   eax, qword ptr fs:[ebx+$6F]
005DE643   6C                     insb
005DE644   657461                 jz      005DE6A8
005DE647   6461                   popa
005DE649   7304                   jnb     005DE64F
005DE64B   0018                   add     [eax], bl
005DE64D   004CE75D               add     [edi+$5D], cl
005DE651   0011                   add     [ecx], dl
005DE653   7362                   jnb     005DE6B7
005DE655   746E                   jz      005DE6C5
005DE657   49                     dec     ecx
005DE658   6D                     insd
005DE659   7072                   jo      005DE6CD
005DE65B   696D6972436C69         imul    ebp, [ebp+$69], $696C4372
005DE662   636B14                 arpl    [ebx+$14], bp
005DE665   0088EB5D000D           add     [eax+$D005DEB], cl
005DE66B   636B62                 arpl    [ebx+$62], bp
005DE66E   54                     push    esp
005DE66F   6F                     outsd
005DE670   646F                   outsd
005DE672   7343                   jnb     005DE6B7
005DE674   6C                     insb
005DE675   69636B1500ECEB         imul    esp, [ebx+$6B], $EBEC0015
005DE67C   5D                     pop     ebp
005DE67D   000E                   add     [esi], cl
005DE67F   636D62                 arpl    [ebp+$62], bp
005DE682   47                     inc     edi
005DE683   7275                   jb      005DE6FA
005DE685   706F                   jo      005DE6F6
005DE687   43                     inc     ebx
005DE688   68616E6765             push    $65676E61
005DE68D   17                     pop     ss
005DE68E   00C0                   add     al, al
005DE690   ED                     in      eax, dx
005DE691   5D                     pop     ebp
005DE692   0010                   add     [eax], dl
005DE694   636D62                 arpl    [ebp+$62], bp
005DE697   47                     inc     edi
005DE698   7275                   jb      005DE70F
005DE69A   706F                   jo      005DE70B
005DE69C   44                     inc     esp
005DE69D   726F                   jb      005DE70E
005DE69F   7044                   jo      005DE6E5
005DE6A1   6F                     outsd
005DE6A2   776E                   jnbe    005DE712
005DE6A4   0E                     push    cs
005DE6A5   54                     push    esp
005DE6A6   66726D                 jb      005DE716
005DE6A9   45                     inc     ebp
005DE6AA   6D                     insd
005DE6AB   697465436F6E7461       imul    esi, [ebp+$43], $61746E6F
005DE6B3   0800                   or      [eax], al
005DE6B5   D0AB4300E4B5           shr     byte ptr [ebx+$B5E40043], 1
005DE6BB   43                     inc     ebx
005DE6BC   00B0DA43000C           add     [eax+$C0043DA], dh
005DE6C2   F1                     DB  $F1  //
005DE6C3   43                     inc     ebx
005DE6C4   0064C54B               add     [ebp+eax*8+$4B], ah
005DE6C8   00EC                   add     ah, ch
005DE6CA   BE430008F9             mov     esi, $F9080043
005DE6CF   43                     inc     ebx
005DE6D0   000CD1                 add     [ecx+edx*8], cl
005DE6D3   4A                     dec     edx
005DE6D4   008D4000DCE6           add     [ebp+$E6DC0040], cl
005DE6DA   5D                     pop     ebp
005DE6DB   0007                   add     [edi], al
005DE6DD   0E                     push    cs
005DE6DE   54                     push    esp
005DE6DF   66726D                 jb      005DE74F
005DE6E2   45                     inc     ebp
005DE6E3   6D                     insd
005DE6E4   697465436F6E7461       imul    esi, [ebp+$43], $61746E6F
005DE6EC   08E4                   or      ah, ah
005DE6EE   5D                     pop     ebp
005DE6EF   00C0                   add     al, al
005DE6F1   AA                     stosb
005DE6F2   56                     push    esi
005DE6F3   006B00                 add     [ebx+$00], ch
005DE6F6   0E                     push    cs
005DE6F7   7546                   jnz     005DE73F
005DE6F9   726D                   jb      005DE768
005DE6FB   45                     inc     ebp
005DE6FC   6D                     insd
005DE6FD   697465436F6E7461       imul    esi, [ebp+$43], $61746E6F
005DE705   0000                   add     [eax], al

005DE707   90                     nop
005DE708   53                     push    ebx
005DE709   56                     push    esi
005DE70A   8BF0                   mov     esi, eax
005DE70C   8D8674030000           lea     eax, [esi+$0374]

|
005DE712   E88D71E2FF             call    004058A4
005DE717   8D8678030000           lea     eax, [esi+$0378]

* Possible String Reference to: 'Versão 8.1'
|
005DE71D   BA40E75D00             mov     edx, $005DE740

|
005DE722   E8D171E2FF             call    004058F8
005DE727   B301                   mov     bl, $01
005DE729   8BC6                   mov     eax, esi

|
005DE72B   E898C5F8FF             call    0056ACC8
005DE730   8BC3                   mov     eax, ebx
005DE732   5E                     pop     esi
005DE733   5B                     pop     ebx
005DE734   C3                     ret

005DE735   0000                   add     [eax], al

005DE737   00FF                   add     bh, bh
005DE739   FFFF                   DB  $FF, $FF  //      
005DE73B   FF0A                   dec     dword ptr [edx]
005DE73D   0000                   add     [eax], al

005DE73F   005665                 add     [esi+$65], dl
005DE742   7273                   jb      005DE7B7
005DE744   E36F                   jcxz    +$6F
005DE746   2038                   and     [eax], bh
005DE748   2E3100                 xor     cs:[eax], eax
005DE74B   00558B                 add     [ebp-$75], dl
005DE74E   EC                     in      al, dx
005DE74F   B909000000             mov     ecx, $00000009
005DE754   6A00                   push    $00
005DE756   6A00                   push    $00
005DE758   49                     dec     ecx
005DE759   75F9                   jnz     005DE754
005DE75B   51                     push    ecx
005DE75C   53                     push    ebx
005DE75D   56                     push    esi
005DE75E   57                     push    edi
005DE75F   8BD8                   mov     ebx, eax
005DE761   33C0                   xor     eax, eax
005DE763   55                     push    ebp
005DE764   68E2EA5D00             push    $005DEAE2

***** TRY
|
005DE769   64FF30                 push    dword ptr fs:[eax]
005DE76C   648920                 mov     fs:[eax], esp
005DE76F   8D55F0                 lea     edx, [ebp-$10]

* Reference to control qryGrupo : TQuery
|
005DE772   8B8390030000           mov     eax, [ebx+$0390]

|
005DE778   E88313E8FF             call    0045FB00
005DE77D   8B45F0                 mov     eax, [ebp-$10]
005DE780   8D55F4                 lea     edx, [ebp-$0C]

|
005DE783   E8CCC1E2FF             call    0040A954
005DE788   837DF400               cmp     dword ptr [ebp-$0C], +$00
005DE78C   7547                   jnz     005DE7D5
005DE78E   8D55E8                 lea     edx, [ebp-$18]
005DE791   8B83A8030000           mov     eax, [ebx+$03A8]

|
005DE797   E86413E8FF             call    0045FB00
005DE79C   8B45E8                 mov     eax, [ebp-$18]
005DE79F   8D55EC                 lea     edx, [ebp-$14]

|
005DE7A2   E8ADC1E2FF             call    0040A954
005DE7A7   837DEC00               cmp     dword ptr [ebp-$14], +$00
005DE7AB   7528                   jnz     005DE7D5
005DE7AD   6A00                   push    $00
005DE7AF   0FB70DF0EA5D00         movzx   ecx, word ptr [$005DEAF0]
005DE7B6   B202                   mov     dl, $02

* Possible String Reference to: 'Informar o grupo e/ou o CDC.'
|
005DE7B8   B8FCEA5D00             mov     eax, $005DEAFC

|
005DE7BD   E8E623E7FF             call    00450BA8

* Reference to control qryGrupo : TQuery
|
005DE7C2   8B8390030000           mov     eax, [ebx+$0390]
005DE7C8   8B10                   mov     edx, [eax]

* Possible reference to virtual method TQuery.OFFS_00D4
|
005DE7CA   FF92D4000000           call    dword ptr [edx+$00D4]
005DE7D0   E99A020000             jmp     005DEA6F

* Reference to control DataSource1 : N.A.
|
005DE7D5   8B8398030000           mov     eax, [ebx+$0398]
005DE7DB   8B10                   mov     edx, [eax]

* Possible reference to virtual method TN.A..OFFS_00D8
|
005DE7DD   FF92D8000000           call    dword ptr [edx+$00D8]
005DE7E3   84C0                   test    al, al
005DE7E5   7566                   jnz     005DE84D
005DE7E7   8D55E0                 lea     edx, [ebp-$20]

* Reference to control qryRoteiro : N.A.
|
005DE7EA   8B8394030000           mov     eax, [ebx+$0394]

|
005DE7F0   E80B13E8FF             call    0045FB00
005DE7F5   8B45E0                 mov     eax, [ebp-$20]
005DE7F8   8D55E4                 lea     edx, [ebp-$1C]

|
005DE7FB   E854C1E2FF             call    0040A954
005DE800   837DE400               cmp     dword ptr [ebp-$1C], +$00
005DE804   7547                   jnz     005DE84D
005DE806   8D55D8                 lea     edx, [ebp-$28]

* Reference to control DBGrRota : N.A.
|
005DE809   8B839C030000           mov     eax, [ebx+$039C]

|
005DE80F   E8EC12E8FF             call    0045FB00
005DE814   8B45D8                 mov     eax, [ebp-$28]
005DE817   8D55DC                 lea     edx, [ebp-$24]

|
005DE81A   E835C1E2FF             call    0040A954
005DE81F   837DDC00               cmp     dword ptr [ebp-$24], +$00
005DE823   7528                   jnz     005DE84D
005DE825   6A00                   push    $00
005DE827   0FB70DF0EA5D00         movzx   ecx, word ptr [$005DEAF0]
005DE82E   B202                   mov     dl, $02

* Possible String Reference to: 'Selecionar a(s) rota(s).'
|
005DE830   B824EB5D00             mov     eax, $005DEB24

|
005DE835   E86E23E7FF             call    00450BA8

* Reference to control DataSource1 : N.A.
|
005DE83A   8B8398030000           mov     eax, [ebx+$0398]
005DE840   8B10                   mov     edx, [eax]

* Possible reference to virtual method TN.A..OFFS_00D4
|
005DE842   FF92D4000000           call    dword ptr [edx+$00D4]
005DE848   E922020000             jmp     005DEA6F
005DE84D   8D55D4                 lea     edx, [ebp-$2C]

* Reference to control qryRoteiro : N.A.
|
005DE850   8B8394030000           mov     eax, [ebx+$0394]

|
005DE856   E8A512E8FF             call    0045FB00
005DE85B   8B45D4                 mov     eax, [ebp-$2C]
005DE85E   33D2                   xor     edx, edx

|
005DE860   E81BCAE2FF             call    0040B280
005DE865   8BF0                   mov     esi, eax
005DE867   8D55D0                 lea     edx, [ebp-$30]

* Reference to control DBGrRota : N.A.
|
005DE86A   8B839C030000           mov     eax, [ebx+$039C]

|
005DE870   E88B12E8FF             call    0045FB00
005DE875   8B45D0                 mov     eax, [ebp-$30]
005DE878   BA3F420F00             mov     edx, $000F423F

|
005DE87D   E8FEC9E2FF             call    0040B280
005DE882   3BF0                   cmp     esi, eax
005DE884   7E28                   jle     005DE8AE
005DE886   6A00                   push    $00
005DE888   0FB70DF0EA5D00         movzx   ecx, word ptr [$005DEAF0]
005DE88F   B202                   mov     dl, $02

* Possible String Reference to: 'Intervalo de Rotas inválido.'
|
005DE891   B848EB5D00             mov     eax, $005DEB48

|
005DE896   E80D23E7FF             call    00450BA8

* Reference to control DataSource1 : N.A.
|
005DE89B   8B8398030000           mov     eax, [ebx+$0398]
005DE8A1   8B10                   mov     edx, [eax]

* Possible reference to virtual method TN.A..OFFS_00D4
|
005DE8A3   FF92D4000000           call    dword ptr [edx+$00D4]
005DE8A9   E9C1010000             jmp     005DEA6F
005DE8AE   8D55CC                 lea     edx, [ebp-$34]

* Reference to control qryGrupo : TQuery
|
005DE8B1   8B8390030000           mov     eax, [ebx+$0390]

|
005DE8B7   E84412E8FF             call    0045FB00
005DE8BC   8B45CC                 mov     eax, [ebp-$34]
005DE8BF   33D2                   xor     edx, edx

|
005DE8C1   E8BAC9E2FF             call    0040B280
005DE8C6   8BF8                   mov     edi, eax
005DE8C8   8D55C8                 lea     edx, [ebp-$38]

* Reference to control qryRoteiro : N.A.
|
005DE8CB   8B8394030000           mov     eax, [ebx+$0394]

|
005DE8D1   E82A12E8FF             call    0045FB00
005DE8D6   8B45C8                 mov     eax, [ebp-$38]
005DE8D9   33D2                   xor     edx, edx

|
005DE8DB   E8A0C9E2FF             call    0040B280
005DE8E0   8945FC                 mov     [ebp-$04], eax
005DE8E3   8D55C4                 lea     edx, [ebp-$3C]

* Reference to control DBGrRota : N.A.
|
005DE8E6   8B839C030000           mov     eax, [ebx+$039C]

|
005DE8EC   E80F12E8FF             call    0045FB00
005DE8F1   8B45C4                 mov     eax, [ebp-$3C]
005DE8F4   BA3F420F00             mov     edx, $000F423F

|
005DE8F9   E882C9E2FF             call    0040B280
005DE8FE   8945F8                 mov     [ebp-$08], eax
005DE901   33F6                   xor     esi, esi
005DE903   8D55BC                 lea     edx, [ebp-$44]
005DE906   8B83A8030000           mov     eax, [ebx+$03A8]

|
005DE90C   E8EF11E8FF             call    0045FB00
005DE911   8B45BC                 mov     eax, [ebp-$44]
005DE914   8D55C0                 lea     edx, [ebp-$40]

|
005DE917   E838C0E2FF             call    0040A954
005DE91C   837DC000               cmp     dword ptr [ebp-$40], +$00
005DE920   7452                   jz      005DE974
005DE922   8D55B4                 lea     edx, [ebp-$4C]
005DE925   8B83A8030000           mov     eax, [ebx+$03A8]

|
005DE92B   E8D011E8FF             call    0045FB00
005DE930   8B45B4                 mov     eax, [ebp-$4C]
005DE933   8D55B8                 lea     edx, [ebp-$48]

|
005DE936   E819C0E2FF             call    0040A954
005DE93B   8B45B8                 mov     eax, [ebp-$48]
005DE93E   83CAFF                 or      edx, -$01

|
005DE941   E83AC9E2FF             call    0040B280
005DE946   8BF0                   mov     esi, eax
005DE948   85F6                   test    esi, esi
005DE94A   7F28                   jnle    005DE974
005DE94C   6A00                   push    $00
005DE94E   0FB70DF0EA5D00         movzx   ecx, word ptr [$005DEAF0]
005DE955   B202                   mov     dl, $02

* Possible String Reference to: 'CDC informado inválido.'
|
005DE957   B870EB5D00             mov     eax, $005DEB70

|
005DE95C   E84722E7FF             call    00450BA8
005DE961   8B83A8030000           mov     eax, [ebx+$03A8]
005DE967   8B10                   mov     edx, [eax]
005DE969   FF92D4000000           call    dword ptr [edx+$00D4]
005DE96F   E9FB000000             jmp     005DEA6F
005DE974   8B83D0030000           mov     eax, [ebx+$03D0]
005DE97A   83F801                 cmp     eax, +$01
005DE97D   0F858A000000           jnz     005DEA0D
005DE983   8B83C4030000           mov     eax, [ebx+$03C4]
005DE989   8B10                   mov     edx, [eax]
005DE98B   FF92D8000000           call    dword ptr [edx+$00D8]
005DE991   84C0                   test    al, al
005DE993   741D                   jz      005DE9B2
005DE995   8B45F8                 mov     eax, [ebp-$08]
005DE998   50                     push    eax
005DE999   56                     push    esi
005DE99A   6A00                   push    $00
005DE99C   A1C8FC6300             mov     eax, dword ptr [$0063FCC8]
005DE9A1   8B00                   mov     eax, [eax]
005DE9A3   8B4DFC                 mov     ecx, [ebp-$04]
005DE9A6   8BD7                   mov     edx, edi

|
005DE9A8   E847BDF9FF             call    0057A6F4
005DE9AD   E9BD000000             jmp     005DEA6F
005DE9B2   8B83CC030000           mov     eax, [ebx+$03CC]
005DE9B8   8B10                   mov     edx, [eax]
005DE9BA   FF92D8000000           call    dword ptr [edx+$00D8]
005DE9C0   84C0                   test    al, al
005DE9C2   741D                   jz      005DE9E1
005DE9C4   8B45F8                 mov     eax, [ebp-$08]
005DE9C7   50                     push    eax
005DE9C8   56                     push    esi
005DE9C9   6A01                   push    $01
005DE9CB   A1C8FC6300             mov     eax, dword ptr [$0063FCC8]
005DE9D0   8B00                   mov     eax, [eax]
005DE9D2   8B4DFC                 mov     ecx, [ebp-$04]
005DE9D5   8BD7                   mov     edx, edi

|
005DE9D7   E818BDF9FF             call    0057A6F4
005DE9DC   E98E000000             jmp     005DEA6F
005DE9E1   8B83C8030000           mov     eax, [ebx+$03C8]
005DE9E7   8B10                   mov     edx, [eax]
005DE9E9   FF92D8000000           call    dword ptr [edx+$00D8]
005DE9EF   84C0                   test    al, al
005DE9F1   747C                   jz      005DEA6F
005DE9F3   8B45F8                 mov     eax, [ebp-$08]
005DE9F6   50                     push    eax
005DE9F7   56                     push    esi
005DE9F8   6A02                   push    $02
005DE9FA   A1C8FC6300             mov     eax, dword ptr [$0063FCC8]
005DE9FF   8B00                   mov     eax, [eax]
005DEA01   8B4DFC                 mov     ecx, [ebp-$04]
005DEA04   8BD7                   mov     edx, edi

|
005DEA06   E8E9BCF9FF             call    0057A6F4
005DEA0B   EB62                   jmp     005DEA6F
005DEA0D   83F802                 cmp     eax, +$02
005DEA10   7518                   jnz     005DEA2A
005DEA12   8B45F8                 mov     eax, [ebp-$08]
005DEA15   50                     push    eax
005DEA16   56                     push    esi
005DEA17   A1C8FC6300             mov     eax, dword ptr [$0063FCC8]
005DEA1C   8B00                   mov     eax, [eax]
005DEA1E   8B4DFC                 mov     ecx, [ebp-$04]
005DEA21   8BD7                   mov     edx, edi

|
005DEA23   E828B3F9FF             call    00579D50
005DEA28   EB45                   jmp     005DEA6F
005DEA2A   83F803                 cmp     eax, +$03
005DEA2D   7540                   jnz     005DEA6F
005DEA2F   8B83B0030000           mov     eax, [ebx+$03B0]
005DEA35   8B10                   mov     edx, [eax]
005DEA37   FF92D8000000           call    dword ptr [edx+$00D8]
005DEA3D   84C0                   test    al, al
005DEA3F   7418                   jz      005DEA59
005DEA41   8B45F8                 mov     eax, [ebp-$08]
005DEA44   50                     push    eax
005DEA45   56                     push    esi
005DEA46   A1C8FC6300             mov     eax, dword ptr [$0063FCC8]
005DEA4B   8B00                   mov     eax, [eax]
005DEA4D   8B4DFC                 mov     ecx, [ebp-$04]
005DEA50   8BD7                   mov     edx, edi

|
005DEA52   E875B7F9FF             call    0057A1CC
005DEA57   EB16                   jmp     005DEA6F
005DEA59   8B45F8                 mov     eax, [ebp-$08]
005DEA5C   50                     push    eax
005DEA5D   56                     push    esi
005DEA5E   A1C8FC6300             mov     eax, dword ptr [$0063FCC8]
005DEA63   8B00                   mov     eax, [eax]
005DEA65   8B4DFC                 mov     ecx, [ebp-$04]
005DEA68   8BD7                   mov     edx, edi

|
005DEA6A   E8F1B9F9FF             call    0057A460
005DEA6F   33C0                   xor     eax, eax
005DEA71   5A                     pop     edx
005DEA72   59                     pop     ecx
005DEA73   59                     pop     ecx
005DEA74   648910                 mov     fs:[eax], edx

****** FINALLY
|
005DEA77   68E9EA5D00             push    $005DEAE9
005DEA7C   8D45B4                 lea     eax, [ebp-$4C]

|
005DEA7F   E8206EE2FF             call    004058A4
005DEA84   8D45B8                 lea     eax, [ebp-$48]

|
005DEA87   E8186EE2FF             call    004058A4
005DEA8C   8D45BC                 lea     eax, [ebp-$44]

|
005DEA8F   E8106EE2FF             call    004058A4
005DEA94   8D45C0                 lea     eax, [ebp-$40]

|
005DEA97   E8086EE2FF             call    004058A4
005DEA9C   8D45C4                 lea     eax, [ebp-$3C]
005DEA9F   BA06000000             mov     edx, $00000006

|
005DEAA4   E81F6EE2FF             call    004058C8
005DEAA9   8D45DC                 lea     eax, [ebp-$24]

|
005DEAAC   E8F36DE2FF             call    004058A4
005DEAB1   8D45E0                 lea     eax, [ebp-$20]

|
005DEAB4   E8EB6DE2FF             call    004058A4
005DEAB9   8D45E4                 lea     eax, [ebp-$1C]

|
005DEABC   E8E36DE2FF             call    004058A4
005DEAC1   8D45E8                 lea     eax, [ebp-$18]

|
005DEAC4   E8DB6DE2FF             call    004058A4
005DEAC9   8D45EC                 lea     eax, [ebp-$14]

|
005DEACC   E8D36DE2FF             call    004058A4
005DEAD1   8D45F0                 lea     eax, [ebp-$10]

|
005DEAD4   E8CB6DE2FF             call    004058A4
005DEAD9   8D45F4                 lea     eax, [ebp-$0C]

|
005DEADC   E8C36DE2FF             call    004058A4
005DEAE1   C3                     ret

*)
end;

end.