unit uFrmTabChaveAcesso;

interface

uses
  Windows, Messages, SysUtils, Classes, Graphics,
  Controls, Forms, Dialogs, StdCtrls
type
  TfrmTabChaveAcesso=class(TForm)
    tbPai: TTable;
    DSPai: TDataSource;
    tbPrincipalca_chave: TStringField;
    tbPrincipalca_id: TIntegerField;
    tbPrincipalca_status: TBooleanField;
    tbPaich_chave: TStringField;
    tbPaich_senha: TStringField;
    tbPaich_nome: TStringField;
    tbPaich_status: TBooleanField;
    Label1: TLabel [0];
    DBEdit1: TDBEdit [5];
    Label2: TLabel [1];
    DBEdit2: TDBEdit [6];
    DBCheckBox1: TDBCheckBox [7];
    PageControl: TPageControl [8];
    qryAcesso: TQuery;
    qryAcessoac_id: TIntegerField;
    qryAcessoac_ordem: TIntegerField;
    qryAcessoac_name: TStringField;
    qryAcessoac_caption: TStringField;
    qryAcessoac_nivel: TIntegerField;
    qryAcessoac_onclick: TBooleanField;
    chbTotal: TCheckBox;
    OFFS_03B0: N.A.;
    procedure chbTotalClick(Sender : TObject);
    procedure sbtnConfirmaClick(Sender : TObject);
    procedure DSPaiDataChange(Sender : TObject);
    procedure _PROC_005D0E44(Sender : TObject);
    procedure _PROC_005D1138(Sender : TObject);
    procedure _PROC_005D1151(Sender : TObject);
    procedure _PROC_005D1317(Sender : TObject);
    procedure _PROC_005D134D(Sender : TObject);
    procedure _PROC_005D163A(Sender : TObject);
  private
    { Private declarations }
  public
    { Public declarations }
  end ;

var
  frmTabChaveAcesso: TfrmTabChaveAcesso;

{This file is generated by DeDe Ver 3.50.04 Copyright (c) 1999-2002 DaFixer}

implementation

{$R *.DFM}

procedure TfrmTabChaveAcesso.chbTotalClick(Sender : TObject);
begin
(*
005D1058   55                     push    ebp
005D1059   8BEC                   mov     ebp, esp
005D105B   6A00                   push    $00
005D105D   53                     push    ebx
005D105E   56                     push    esi
005D105F   57                     push    edi
005D1060   8BD8                   mov     ebx, eax
005D1062   33C0                   xor     eax, eax
005D1064   55                     push    ebp

* Possible String Reference to: 'éŠ?ãÿëð_^[Y]Ã'
|
005D1065   6805115D00             push    $005D1105

***** TRY
|
005D106A   64FF30                 push    dword ptr fs:[eax]
005D106D   648920                 mov     fs:[eax], esp

* Reference to control TfrmTabChaveAcesso.chbTotal : TCheckBox
|
005D1070   8B8318040000           mov     eax, [ebx+$0418]
005D1076   8B10                   mov     edx, [eax]

* Possible reference to virtual method TCheckBox.OFFS_00D8
|
005D1078   FF92D8000000           call    dword ptr [edx+$00D8]
005D107E   84C0                   test    al, al
005D1080   746D                   jz      005D10EF

* Reference to field TfrmTabChaveAcesso.OFFS_03B0 : Byte
|
005D1082   80BBB003000002         cmp     byte ptr [ebx+$03B0], $02
005D1089   7564                   jnz     005D10EF
005D108B   8BC3                   mov     eax, ebx

|
005D108D   E89EB3E5FF             call    0042C430
005D1092   8BF8                   mov     edi, eax
005D1094   4F                     dec     edi
005D1095   85FF                   test    edi, edi
005D1097   7C56                   jl      005D10EF
005D1099   47                     inc     edi
005D109A   33F6                   xor     esi, esi
005D109C   8D45FC                 lea     eax, [ebp-$04]
005D109F   50                     push    eax
005D10A0   8BD6                   mov     edx, esi
005D10A2   8BC3                   mov     eax, ebx

|
005D10A4   E85BB3E5FF             call    0042C404

* Reference to field TfrmTabChaveAcesso.OFFS_0008
|
005D10A9   8B4008                 mov     eax, [eax+$08]
005D10AC   B902000000             mov     ecx, $00000002
005D10B1   BA01000000             mov     edx, $00000001

|
005D10B6   E80D4DE3FF             call    00405DC8
005D10BB   8B45FC                 mov     eax, [ebp-$04]

* Possible String Reference to: 'CB'
|
005D10BE   BA1C115D00             mov     edx, $005D111C

|
005D10C3   E8EC4BE3FF             call    00405CB4
005D10C8   7521                   jnz     005D10EB

* Reference to control TfrmTabChaveAcesso.chbTotal : TCheckBox
|
005D10CA   8B8318040000           mov     eax, [ebx+$0418]
005D10D0   8B10                   mov     edx, [eax]

* Possible reference to virtual method TCheckBox.OFFS_00D8
|
005D10D2   FF92D8000000           call    dword ptr [edx+$00D8]
005D10D8   50                     push    eax
005D10D9   8BD6                   mov     edx, esi
005D10DB   8BC3                   mov     eax, ebx

|
005D10DD   E822B3E5FF             call    0042C404
005D10E2   5A                     pop     edx
005D10E3   8B08                   mov     ecx, [eax]

* Possible reference to virtual method TfrmTabChaveAcesso.OFFS_00DC
|
005D10E5   FF91DC000000           call    dword ptr [ecx+$00DC]
005D10EB   46                     inc     esi
005D10EC   4F                     dec     edi
005D10ED   75AD                   jnz     005D109C
005D10EF   33C0                   xor     eax, eax
005D10F1   5A                     pop     edx
005D10F2   59                     pop     ecx
005D10F3   59                     pop     ecx
005D10F4   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: '_^[Y]Ã'
|
005D10F7   680C115D00             push    $005D110C
005D10FC   8D45FC                 lea     eax, [ebp-$04]

|
005D10FF   E8A047E3FF             call    004058A4
005D1104   C3                     ret


|
005D1105   E98A3FE3FF             jmp     00405094
005D110A   EBF0                   jmp     005D10FC

****** END
|
005D110C   5F                     pop     edi
005D110D   5E                     pop     esi
005D110E   5B                     pop     ebx
005D110F   59                     pop     ecx
005D1110   5D                     pop     ebp
005D1111   C3                     ret

*)
end;

procedure TfrmTabChaveAcesso.sbtnConfirmaClick(Sender : TObject);
begin
(*
005D1028   53                     push    ebx
005D1029   56                     push    esi
005D102A   8BF2                   mov     esi, edx
005D102C   8BD8                   mov     ebx, eax
005D102E   B202                   mov     dl, $02
005D1030   8BC3                   mov     eax, ebx

|
005D1032   E819010000             call    005D1150
005D1037   8BD6                   mov     edx, esi
005D1039   8BC3                   mov     eax, ebx

* Reference to : TfrmBaseClientTabela.sbtnConfirmaClick()
|
005D103B   E8AC84FFFF             call    005C94EC
005D1040   5E                     pop     esi
005D1041   5B                     pop     ebx
005D1042   C3                     ret

*)
end;

procedure TfrmTabChaveAcesso.DSPaiDataChange(Sender : TObject);
begin
(*
005D1148   B201                   mov     dl, $01

|
005D114A   E801000000             call    005D1150
005D114F   C3                     ret

*)
end;

procedure TfrmTabChaveAcesso._PROC_005D0E44(Sender : TObject);
begin
(*
005D0E44   7375                   jnb     005D0EBB
005D0E46   E172                   loope   +$72
005D0E48   696F0000558BEC         imul    ebp, [edi+$00], $EC8B5500
005D0E4F   33C9                   xor     ecx, ecx
005D0E51   51                     push    ecx
005D0E52   51                     push    ecx
005D0E53   51                     push    ecx
005D0E54   51                     push    ecx
005D0E55   51                     push    ecx
005D0E56   51                     push    ecx
005D0E57   53                     push    ebx
005D0E58   56                     push    esi
005D0E59   57                     push    edi
005D0E5A   8855FF                 mov     [ebp-$01], dl
005D0E5D   8BD8                   mov     ebx, eax
005D0E5F   33C0                   xor     eax, eax
005D0E61   55                     push    ebp

* Possible String Reference to: 'é“@ãÿëë_^[‹å]Ã'
|
005D0E62   68FC0F5D00             push    $005D0FFC

***** TRY
|
005D0E67   64FF30                 push    dword ptr fs:[eax]
005D0E6A   648920                 mov     fs:[eax], esp
005D0E6D   0FB655FF               movzx   edx, byte ptr [ebp-$01]
005D0E71   8BC3                   mov     eax, ebx

|
005D0E73   E84083FFFF             call    005C91B8
005D0E78   807DFF02               cmp     byte ptr [ebp-$01], $02
005D0E7C   0F94C2                 setz    dl

* Reference to control TfrmTabChaveAcesso.chbTotal : TCheckBox
|
005D0E7F   8B8318040000           mov     eax, [ebx+$0418]

|
005D0E85   E896EBE8FF             call    0045FA20
005D0E8A   33D2                   xor     edx, edx

* Reference to control TfrmTabChaveAcesso.chbTotal : TCheckBox
|
005D0E8C   8B8318040000           mov     eax, [ebx+$0418]
005D0E92   8B08                   mov     ecx, [eax]

* Possible reference to virtual method TCheckBox.OFFS_00DC
|
005D0E94   FF91DC000000           call    dword ptr [ecx+$00DC]

* Reference to field TfrmTabChaveAcesso.OFFS_03A0
|
005D0E9A   8B83A0030000           mov     eax, [ebx+$03A0]

|
005D0EA0   E85FFEECFF             call    004A0D04

* Reference to field TfrmTabChaveAcesso.OFFS_03A0
|
005D0EA5   8B83A0030000           mov     eax, [ebx+$03A0]
005D0EAB   8B10                   mov     edx, [eax]
005D0EAD   FF926C010000           call    dword ptr [edx+$016C]
005D0EB3   48                     dec     eax
005D0EB4   85C0                   test    eax, eax
005D0EB6   0F8C25010000           jl      005D0FE1
005D0EBC   40                     inc     eax
005D0EBD   8945F8                 mov     [ebp-$08], eax
005D0EC0   8BC3                   mov     eax, ebx

|
005D0EC2   E869B5E5FF             call    0042C430
005D0EC7   8BF0                   mov     esi, eax
005D0EC9   4E                     dec     esi
005D0ECA   85F6                   test    esi, esi
005D0ECC   0F8CFB000000           jl      005D0FCD
005D0ED2   46                     inc     esi
005D0ED3   33FF                   xor     edi, edi
005D0ED5   807DFF01               cmp     byte ptr [ebp-$01], $01
005D0ED9   7559                   jnz     005D0F34
005D0EDB   8BD7                   mov     edx, edi
005D0EDD   8BC3                   mov     eax, ebx

|
005D0EDF   E820B5E5FF             call    0042C404

* Reference to field TfrmTabChaveAcesso.OFFS_0008
|
005D0EE4   8B4008                 mov     eax, [eax+$08]
005D0EE7   50                     push    eax
005D0EE8   BA10105D00             mov     edx, $005D1010

* Reference to field TfrmTabChaveAcesso.OFFS_03A0
|
005D0EED   8B83A0030000           mov     eax, [ebx+$03A0]

|
005D0EF3   E840E9ECFF             call    0049F838
005D0EF8   8D55F0                 lea     edx, [ebp-$10]
005D0EFB   8B08                   mov     ecx, [eax]
005D0EFD   FF5160                 call    dword ptr [ecx+$60]
005D0F00   8B4DF0                 mov     ecx, [ebp-$10]
005D0F03   8D45F4                 lea     eax, [ebp-$0C]

* Possible String Reference to: 'CB'
|
005D0F06   BA24105D00             mov     edx, $005D1024

|
005D0F0B   E8A44CE3FF             call    00405BB4
005D0F10   8B55F4                 mov     edx, [ebp-$0C]
005D0F13   58                     pop     eax

|
005D0F14   E89B4DE3FF             call    00405CB4
005D0F19   0F85A6000000           jnz     005D0FC5
005D0F1F   8BD7                   mov     edx, edi
005D0F21   8BC3                   mov     eax, ebx

|
005D0F23   E8DCB4E5FF             call    0042C404
005D0F28   33D2                   xor     edx, edx
005D0F2A   8B08                   mov     ecx, [eax]

* Possible reference to virtual method TfrmTabChaveAcesso.OFFS_68
|
005D0F2C   FF5168                 call    dword ptr [ecx+$68]
005D0F2F   E991000000             jmp     005D0FC5
005D0F34   807DFF02               cmp     byte ptr [ebp-$01], $02
005D0F38   0F8587000000           jnz     005D0FC5
005D0F3E   8BD7                   mov     edx, edi
005D0F40   8BC3                   mov     eax, ebx

|
005D0F42   E8BDB4E5FF             call    0042C404

* Reference to field TfrmTabChaveAcesso.OFFS_0008
|
005D0F47   8B4008                 mov     eax, [eax+$08]
005D0F4A   50                     push    eax
005D0F4B   BA10105D00             mov     edx, $005D1010

* Reference to field TfrmTabChaveAcesso.OFFS_03A0
|
005D0F50   8B83A0030000           mov     eax, [ebx+$03A0]

|
005D0F56   E8DDE8ECFF             call    0049F838
005D0F5B   8D55E8                 lea     edx, [ebp-$18]
005D0F5E   8B08                   mov     ecx, [eax]
005D0F60   FF5160                 call    dword ptr [ecx+$60]
005D0F63   8B4DE8                 mov     ecx, [ebp-$18]
005D0F66   8D45EC                 lea     eax, [ebp-$14]

* Possible String Reference to: 'CB'
|
005D0F69   BA24105D00             mov     edx, $005D1024

|
005D0F6E   E8414CE3FF             call    00405BB4
005D0F73   8B55EC                 mov     edx, [ebp-$14]
005D0F76   58                     pop     eax

|
005D0F77   E8384DE3FF             call    00405CB4
005D0F7C   7547                   jnz     005D0FC5
005D0F7E   8BD7                   mov     edx, edi
005D0F80   8BC3                   mov     eax, ebx

|
005D0F82   E87DB4E5FF             call    0042C404
005D0F87   B201                   mov     dl, $01
005D0F89   8B08                   mov     ecx, [eax]

* Possible reference to virtual method TfrmTabChaveAcesso.OFFS_68
|
005D0F8B   FF5168                 call    dword ptr [ecx+$68]

* Reference to control TfrmTabChaveAcesso.chbTotal : TCheckBox
|
005D0F8E   8B8318040000           mov     eax, [ebx+$0418]
005D0F94   8B10                   mov     edx, [eax]

* Possible reference to virtual method TCheckBox.OFFS_00D8
|
005D0F96   FF92D8000000           call    dword ptr [edx+$00D8]
005D0F9C   84C0                   test    al, al
005D0F9E   7425                   jz      005D0FC5
005D0FA0   8BD7                   mov     edx, edi
005D0FA2   8BC3                   mov     eax, ebx

|
005D0FA4   E85BB4E5FF             call    0042C404
005D0FA9   8B10                   mov     edx, [eax]

* Possible reference to virtual method TfrmTabChaveAcesso.OFFS_00D8
|
005D0FAB   FF92D8000000           call    dword ptr [edx+$00D8]
005D0FB1   84C0                   test    al, al
005D0FB3   7510                   jnz     005D0FC5
005D0FB5   33D2                   xor     edx, edx

* Reference to control TfrmTabChaveAcesso.chbTotal : TCheckBox
|
005D0FB7   8B8318040000           mov     eax, [ebx+$0418]
005D0FBD   8B08                   mov     ecx, [eax]

* Possible reference to virtual method TCheckBox.OFFS_00DC
|
005D0FBF   FF91DC000000           call    dword ptr [ecx+$00DC]
005D0FC5   47                     inc     edi
005D0FC6   4E                     dec     esi
005D0FC7   0F8508FFFFFF           jnz     005D0ED5

* Reference to field TfrmTabChaveAcesso.OFFS_03A0
|
005D0FCD   8B83A0030000           mov     eax, [ebx+$03A0]

|
005D0FD3   E84800EDFF             call    004A1020
005D0FD8   FF4DF8                 dec     dword ptr [ebp-$08]
005D0FDB   0F85DFFEFFFF           jnz     005D0EC0
005D0FE1   33C0                   xor     eax, eax
005D0FE3   5A                     pop     edx
005D0FE4   59                     pop     ecx
005D0FE5   59                     pop     ecx
005D0FE6   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: '_^[‹å]Ã'
|
005D0FE9   6803105D00             push    $005D1003
005D0FEE   8D45E8                 lea     eax, [ebp-$18]
005D0FF1   BA04000000             mov     edx, $00000004

|
005D0FF6   E8CD48E3FF             call    004058C8
005D0FFB   C3                     ret


|
005D0FFC   E99340E3FF             jmp     00405094
005D1001   EBEB                   jmp     005D0FEE

****** END
|
005D1003   5F                     pop     edi
005D1004   5E                     pop     esi
005D1005   5B                     pop     ebx
005D1006   8BE5                   mov     esp, ebp
005D1008   5D                     pop     ebp
005D1009   C3                     ret

*)
end;

procedure TfrmTabChaveAcesso._PROC_005D1138(Sender : TObject);
begin
(*
005D1138   180400                 sbb     [eax+eax], al
005D113B   008B08FF91DC           add     [ebx+$DC91FF08], cl
005D1141   0000                   add     [eax], al

*)
end;

procedure TfrmTabChaveAcesso._PROC_005D1151(Sender : TObject);
begin
(*
005D1151   8BEC                   mov     ebp, esp
005D1153   33C9                   xor     ecx, ecx
005D1155   51                     push    ecx
005D1156   51                     push    ecx
005D1157   51                     push    ecx
005D1158   51                     push    ecx
005D1159   51                     push    ecx
005D115A   51                     push    ecx
005D115B   51                     push    ecx
005D115C   53                     push    ebx
005D115D   56                     push    esi
005D115E   8855FF                 mov     [ebp-$01], dl
005D1161   8BD8                   mov     ebx, eax
005D1163   33C0                   xor     eax, eax
005D1165   55                     push    ebp

* Possible String Reference to: 'é‡=ãÿëë‹Ã^[‹å]Ã'
|
005D1166   6808135D00             push    $005D1308

***** TRY
|
005D116B   64FF30                 push    dword ptr fs:[eax]
005D116E   648920                 mov     fs:[eax], esp
005D1171   807DFF00               cmp     byte ptr [ebp-$01], $00
005D1175   7406                   jz      005D117D
005D1177   807DFF03               cmp     byte ptr [ebp-$01], $03
005D117B   7507                   jnz     005D1184
005D117D   B301                   mov     bl, $01
005D117F   E969010000             jmp     005D12ED

* Reference to control Label2 : TLabel [1]
|
005D1184   8B83A0030000           mov     eax, [ebx+$03A0]

|
005D118A   E875FBECFF             call    004A0D04

* Reference to control Label2 : TLabel [1]
|
005D118F   8B83A0030000           mov     eax, [ebx+$03A0]
005D1195   8B10                   mov     edx, [eax]

* Possible reference to virtual method TLabel [1].OFFS_016C
|
005D1197   FF926C010000           call    dword ptr [edx+$016C]
005D119D   48                     dec     eax
005D119E   85C0                   test    eax, eax
005D11A0   0F8C45010000           jl      005D12EB
005D11A6   40                     inc     eax
005D11A7   8945F4                 mov     [ebp-$0C], eax
005D11AA   8BC3                   mov     eax, ebx

|
005D11AC   E87FB2E5FF             call    0042C430
005D11B1   8BF0                   mov     esi, eax
005D11B3   4E                     dec     esi
005D11B4   85F6                   test    esi, esi
005D11B6   0F8C1B010000           jl      005D12D7
005D11BC   46                     inc     esi
005D11BD   C745F800000000         mov     dword ptr [ebp-$08], $00000000
005D11C4   807DFF01               cmp     byte ptr [ebp-$01], $01
005D11C8   7573                   jnz     005D123D
005D11CA   8B55F8                 mov     edx, [ebp-$08]
005D11CD   8BC3                   mov     eax, ebx

|
005D11CF   E830B2E5FF             call    0042C404
005D11D4   8B4008                 mov     eax, [eax+$08]
005D11D7   50                     push    eax
005D11D8   BA1C135D00             mov     edx, $005D131C

* Reference to control Label2 : TLabel [1]
|
005D11DD   8B83A0030000           mov     eax, [ebx+$03A0]

|
005D11E3   E850E6ECFF             call    0049F838
005D11E8   8D55EC                 lea     edx, [ebp-$14]
005D11EB   8B08                   mov     ecx, [eax]

* Possible reference to virtual method TLabel [1].OFFS_60
|
005D11ED   FF5160                 call    dword ptr [ecx+$60]
005D11F0   8B4DEC                 mov     ecx, [ebp-$14]
005D11F3   8D45F0                 lea     eax, [ebp-$10]

* Possible String Reference to: 'CB'
|
005D11F6   BA30135D00             mov     edx, $005D1330

|
005D11FB   E8B449E3FF             call    00405BB4
005D1200   8B55F0                 mov     edx, [ebp-$10]
005D1203   58                     pop     eax

|
005D1204   E8AB4AE3FF             call    00405CB4
005D1209   0F85BE000000           jnz     005D12CD
005D120F   BA38135D00             mov     edx, $005D1338

* Reference to control Label2 : TLabel [1]
|
005D1214   8B83A0030000           mov     eax, [ebx+$03A0]

|
005D121A   E819E6ECFF             call    0049F838
005D121F   8B10                   mov     edx, [eax]

* Possible reference to virtual method TLabel [1].OFFS_44
|
005D1221   FF5244                 call    dword ptr [edx+$44]
005D1224   50                     push    eax
005D1225   8B55F8                 mov     edx, [ebp-$08]
005D1228   8BC3                   mov     eax, ebx

|
005D122A   E8D5B1E5FF             call    0042C404
005D122F   5A                     pop     edx
005D1230   8B08                   mov     ecx, [eax]
005D1232   FF91DC000000           call    dword ptr [ecx+$00DC]
005D1238   E990000000             jmp     005D12CD
005D123D   807DFF02               cmp     byte ptr [ebp-$01], $02
005D1241   0F8586000000           jnz     005D12CD
005D1247   8B55F8                 mov     edx, [ebp-$08]
005D124A   8BC3                   mov     eax, ebx

|
005D124C   E8B3B1E5FF             call    0042C404
005D1251   8B4008                 mov     eax, [eax+$08]
005D1254   50                     push    eax
005D1255   BA1C135D00             mov     edx, $005D131C

* Reference to control Label2 : TLabel [1]
|
005D125A   8B83A0030000           mov     eax, [ebx+$03A0]

|
005D1260   E8D3E5ECFF             call    0049F838
005D1265   8D55E4                 lea     edx, [ebp-$1C]
005D1268   8B08                   mov     ecx, [eax]

* Possible reference to virtual method TLabel [1].OFFS_60
|
005D126A   FF5160                 call    dword ptr [ecx+$60]
005D126D   8B4DE4                 mov     ecx, [ebp-$1C]
005D1270   8D45E8                 lea     eax, [ebp-$18]

* Possible String Reference to: 'CB'
|
005D1273   BA30135D00             mov     edx, $005D1330

|
005D1278   E83749E3FF             call    00405BB4
005D127D   8B55E8                 mov     edx, [ebp-$18]
005D1280   58                     pop     eax

|
005D1281   E82E4AE3FF             call    00405CB4
005D1286   7545                   jnz     005D12CD

* Reference to control Label2 : TLabel [1]
|
005D1288   8B83A0030000           mov     eax, [ebx+$03A0]

|
005D128E   E889FEECFF             call    004A111C
005D1293   8B55F8                 mov     edx, [ebp-$08]
005D1296   8BC3                   mov     eax, ebx

|
005D1298   E867B1E5FF             call    0042C404
005D129D   8B10                   mov     edx, [eax]
005D129F   FF92D8000000           call    dword ptr [edx+$00D8]
005D12A5   50                     push    eax
005D12A6   BA38135D00             mov     edx, $005D1338

* Reference to control Label2 : TLabel [1]
|
005D12AB   8B83A0030000           mov     eax, [ebx+$03A0]

|
005D12B1   E882E5ECFF             call    0049F838
005D12B6   5A                     pop     edx
005D12B7   8B08                   mov     ecx, [eax]

* Possible reference to virtual method TLabel [1].OFFS_009C
|
005D12B9   FF919C000000           call    dword ptr [ecx+$009C]

* Reference to control Label2 : TLabel [1]
|
005D12BF   8B83A0030000           mov     eax, [ebx+$03A0]
005D12C5   8B10                   mov     edx, [eax]

* Possible reference to virtual method TLabel [1].OFFS_0270
|
005D12C7   FF9270020000           call    dword ptr [edx+$0270]
005D12CD   FF45F8                 inc     dword ptr [ebp-$08]
005D12D0   4E                     dec     esi
005D12D1   0F85EDFEFFFF           jnz     005D11C4

* Reference to control Label2 : TLabel [1]
|
005D12D7   8B83A0030000           mov     eax, [ebx+$03A0]

|
005D12DD   E83EFDECFF             call    004A1020
005D12E2   FF4DF4                 dec     dword ptr [ebp-$0C]
005D12E5   0F85BFFEFFFF           jnz     005D11AA
005D12EB   B301                   mov     bl, $01
005D12ED   33C0                   xor     eax, eax
005D12EF   5A                     pop     edx
005D12F0   59                     pop     ecx
005D12F1   59                     pop     ecx
005D12F2   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: '‹Ã^[‹å]Ã'
|
005D12F5   680F135D00             push    $005D130F
005D12FA   8D45E4                 lea     eax, [ebp-$1C]
005D12FD   BA04000000             mov     edx, $00000004

|
005D1302   E8C145E3FF             call    004058C8
005D1307   C3                     ret


|
005D1308   E9873DE3FF             jmp     00405094
005D130D   EBEB                   jmp     005D12FA

****** END
|
005D130F   8BC3                   mov     eax, ebx
005D1311   5E                     pop     esi
005D1312   5B                     pop     ebx
005D1313   8BE5                   mov     esp, ebp
005D1315   5D                     pop     ebp
005D1316   C3                     ret

*)
end;

procedure TfrmTabChaveAcesso._PROC_005D1317(Sender : TObject);
begin
(*
005D1317   000A                   add     [edx], cl
005D1319   0000                   add     [eax], al

*)
end;

procedure TfrmTabChaveAcesso._PROC_005D134D(Sender : TObject);
begin
(*
005D134D   8BEC                   mov     ebp, esp
005D134F   B904000000             mov     ecx, $00000004
005D1354   6A00                   push    $00
005D1356   6A00                   push    $00
005D1358   49                     dec     ecx
005D1359   75F9                   jnz     005D1354
005D135B   51                     push    ecx
005D135C   53                     push    ebx
005D135D   56                     push    esi
005D135E   8BD8                   mov     ebx, eax
005D1360   33C0                   xor     eax, eax
005D1362   55                     push    ebp

* Possible String Reference to: 'éí:ãÿëã‹Ã^[‹å]Ã'
|
005D1363   68A2155D00             push    $005D15A2

***** TRY
|
005D1368   64FF30                 push    dword ptr fs:[eax]
005D136B   648920                 mov     fs:[eax], esp

* Reference to control TfrmTabChaveAcesso.qryAcesso : TQuery
|
005D136E   8B83FC030000           mov     eax, [ebx+$03FC]

|
005D1374   E823D3ECFF             call    0049E69C
005D1379   84C0                   test    al, al
005D137B   740B                   jz      005D1388

* Reference to control TfrmTabChaveAcesso.qryAcesso : TQuery
|
005D137D   8B83FC030000           mov     eax, [ebx+$03FC]

|
005D1383   E888D1ECFF             call    0049E510

* Reference to control TfrmTabChaveAcesso.qryAcesso : TQuery
|
005D1388   8B83FC030000           mov     eax, [ebx+$03FC]

|
005D138E   E869D1ECFF             call    0049E4FC
005D1393   33C0                   xor     eax, eax
005D1395   8945F8                 mov     [ebp-$08], eax
005D1398   C745FC14000000         mov     dword ptr [ebp-$04], $00000014
005D139F   C745F41E000000         mov     dword ptr [ebp-$0C], $0000001E
005D13A6   E9BF010000             jmp     005D156A
005D13AB   BAB8155D00             mov     edx, $005D15B8

* Reference to control TfrmTabChaveAcesso.qryAcesso : TQuery
|
005D13B0   8B83FC030000           mov     eax, [ebx+$03FC]

|
005D13B6   E87DE4ECFF             call    0049F838
005D13BB   8B10                   mov     edx, [eax]

* Possible reference to virtual method TQuery.OFFS_58
|
005D13BD   FF5258                 call    dword ptr [edx+$58]
005D13C0   85C0                   test    eax, eax
005D13C2   754E                   jnz     005D1412
005D13C4   8BCB                   mov     ecx, ebx
005D13C6   B201                   mov     dl, $01

* Reference to class TTabSheet
|
005D13C8   A108084C00             mov     eax, dword ptr [$004C0808]

* Reference to : TTabStrings._PROC_004C6CCC()
|
005D13CD   E8FA58EFFF             call    004C6CCC
005D13D2   8945F8                 mov     [ebp-$08], eax

* Reference to control TfrmTabChaveAcesso.PageControl : TPageControl [8]
|
005D13D5   8B93F8030000           mov     edx, [ebx+$03F8]
005D13DB   8B45F8                 mov     eax, [ebp-$08]

* Reference to : TTabStrings._PROC_004C6EA4()
|
005D13DE   E8C15AEFFF             call    004C6EA4
005D13E3   BAD0155D00             mov     edx, $005D15D0

* Reference to control TfrmTabChaveAcesso.qryAcesso : TQuery
|
005D13E8   8B83FC030000           mov     eax, [ebx+$03FC]

|
005D13EE   E845E4ECFF             call    0049F838
005D13F3   8D55EC                 lea     edx, [ebp-$14]
005D13F6   8B08                   mov     ecx, [eax]

* Possible reference to virtual method TQuery.OFFS_60
|
005D13F8   FF5160                 call    dword ptr [ecx+$60]
005D13FB   8B55EC                 mov     edx, [ebp-$14]
005D13FE   8B45F8                 mov     eax, [ebp-$08]

|
005D1401   E82AE7E8FF             call    0045FB30
005D1406   C745FC14000000         mov     dword ptr [ebp-$04], $00000014
005D140D   E94D010000             jmp     005D155F
005D1412   8BCB                   mov     ecx, ebx
005D1414   B201                   mov     dl, $01

* Reference to class TLabel
|
005D1416   A1E4B54300             mov     eax, dword ptr [$0043B5E4]

* Reference to : TListBoxStrings._PROC_00441884()
|
005D141B   E86404E7FF             call    00441884
005D1420   8945F0                 mov     [ebp-$10], eax
005D1423   8B55F8                 mov     edx, [ebp-$08]
005D1426   8B45F0                 mov     eax, [ebp-$10]
005D1429   8B08                   mov     ecx, [eax]

* Possible reference to virtual method TLabel.OFFS_6C
|
005D142B   FF516C                 call    dword ptr [ecx+$6C]
005D142E   8B55FC                 mov     edx, [ebp-$04]
005D1431   83C202                 add     edx, +$02
005D1434   8B45F0                 mov     eax, [ebp-$10]

|
005D1437   E850DDE8FF             call    0045F18C
005D143C   BAB8155D00             mov     edx, $005D15B8

* Reference to control TfrmTabChaveAcesso.qryAcesso : TQuery
|
005D1441   8B83FC030000           mov     eax, [ebx+$03FC]

|
005D1447   E8ECE3ECFF             call    0049F838
005D144C   8B10                   mov     edx, [eax]

* Possible reference to virtual method TQuery.OFFS_58
|
005D144E   FF5258                 call    dword ptr [edx+$58]
005D1451   8BD0                   mov     edx, eax
005D1453   0FAF55F4               imul    edx, [ebp-$0C]
005D1457   83C216                 add     edx, +$16
005D145A   8B45F0                 mov     eax, [ebp-$10]

|
005D145D   E8F6DCE8FF             call    0045F158
005D1462   B201                   mov     dl, $01
005D1464   8B45F0                 mov     eax, [ebp-$10]
005D1467   8B08                   mov     ecx, [eax]

* Possible reference to virtual method TLabel.OFFS_60
|
005D1469   FF5160                 call    dword ptr [ecx+$60]
005D146C   BAD0155D00             mov     edx, $005D15D0

* Reference to control TfrmTabChaveAcesso.qryAcesso : TQuery
|
005D1471   8B83FC030000           mov     eax, [ebx+$03FC]

|
005D1477   E8BCE3ECFF             call    0049F838
005D147C   8D55E8                 lea     edx, [ebp-$18]
005D147F   8B08                   mov     ecx, [eax]

* Possible reference to virtual method TQuery.OFFS_60
|
005D1481   FF5160                 call    dword ptr [ecx+$60]
005D1484   8B55E8                 mov     edx, [ebp-$18]
005D1487   8B45F0                 mov     eax, [ebp-$10]

|
005D148A   E8A1E6E8FF             call    0045FB30
005D148F   33D2                   xor     edx, edx
005D1491   8B45F0                 mov     eax, [ebp-$10]

|
005D1494   E887E5E8FF             call    0045FA20
005D1499   8BCB                   mov     ecx, ebx
005D149B   B201                   mov     dl, $01

* Reference to class TCheckBox
|
005D149D   A10CF14300             mov     eax, dword ptr [$0043F10C]

|
005D14A2   E85943E7FF             call    00445800
005D14A7   8BF0                   mov     esi, eax
005D14A9   8B55F8                 mov     edx, [ebp-$08]
005D14AC   8BC6                   mov     eax, esi
005D14AE   8B08                   mov     ecx, [eax]

* Possible reference to virtual method TCheckBox.OFFS_6C
|
005D14B0   FF516C                 call    dword ptr [ecx+$6C]
005D14B3   8B55FC                 mov     edx, [ebp-$04]
005D14B6   8BC6                   mov     eax, esi

|
005D14B8   E8CFDCE8FF             call    0045F18C
005D14BD   BAB8155D00             mov     edx, $005D15B8

* Reference to control TfrmTabChaveAcesso.qryAcesso : TQuery
|
005D14C2   8B83FC030000           mov     eax, [ebx+$03FC]

|
005D14C8   E86BE3ECFF             call    0049F838
005D14CD   8B10                   mov     edx, [eax]

* Possible reference to virtual method TQuery.OFFS_58
|
005D14CF   FF5258                 call    dword ptr [edx+$58]
005D14D2   8BD0                   mov     edx, eax
005D14D4   0FAF55F4               imul    edx, [ebp-$0C]
005D14D8   8BC6                   mov     eax, esi

|
005D14DA   E879DCE8FF             call    0045F158
005D14DF   BAEC155D00             mov     edx, $005D15EC

* Reference to control TfrmTabChaveAcesso.qryAcesso : TQuery
|
005D14E4   8B83FC030000           mov     eax, [ebx+$03FC]

|
005D14EA   E849E3ECFF             call    0049F838
005D14EF   8D55E0                 lea     edx, [ebp-$20]
005D14F2   8B08                   mov     ecx, [eax]

* Possible reference to virtual method TQuery.OFFS_60
|
005D14F4   FF5160                 call    dword ptr [ecx+$60]
005D14F7   8B4DE0                 mov     ecx, [ebp-$20]
005D14FA   8D45E4                 lea     eax, [ebp-$1C]

* Possible String Reference to: 'CB'
|
005D14FD   BA00165D00             mov     edx, $005D1600

|
005D1502   E8AD46E3FF             call    00405BB4
005D1507   8B55E4                 mov     edx, [ebp-$1C]
005D150A   8BC6                   mov     eax, esi
005D150C   8B08                   mov     ecx, [eax]

* Possible reference to virtual method TCheckBox.OFFS_18
|
005D150E   FF5118                 call    dword ptr [ecx+$18]
005D1511   8D55DC                 lea     edx, [ebp-$24]
005D1514   8B45F0                 mov     eax, [ebp-$10]

|
005D1517   E8E4E5E8FF             call    0045FB00
005D151C   8B55DC                 mov     edx, [ebp-$24]
005D151F   8BC6                   mov     eax, esi

|
005D1521   E80AE6E8FF             call    0045FB30
005D1526   B201                   mov     dl, $01
005D1528   8BC6                   mov     eax, esi

|
005D152A   E8F1E4E8FF             call    0045FA20
005D152F   BA11000000             mov     edx, $00000011
005D1534   8BC6                   mov     eax, esi

|
005D1536   E8B9DCE8FF             call    0045F1F4
005D153B   8B45F0                 mov     eax, [ebp-$10]

* Reference to field TLabel.OFFS_0048
|
005D153E   8B5048                 mov     edx, [eax+$48]
005D1541   83C211                 add     edx, +$11
005D1544   8BC6                   mov     eax, esi

|
005D1546   E875DCE8FF             call    0045F1C0

* Reference to field TCheckBox.OFFS_0114
|
005D154B   899E14010000           mov     [esi+$0114], ebx

* Reference to field TCheckBox.OFFS_0110
|
005D1551   C7861001000020115D00   mov     dword ptr [esi+$0110], $005D1120
005D155B   8345FC14               add     dword ptr [ebp-$04], +$14

* Reference to control TfrmTabChaveAcesso.qryAcesso : TQuery
|
005D155F   8B83FC030000           mov     eax, [ebx+$03FC]

|
005D1565   E8B6FAECFF             call    004A1020

* Reference to control TfrmTabChaveAcesso.qryAcesso : TQuery
|
005D156A   8B83FC030000           mov     eax, [ebx+$03FC]

* Reference to field TQuery.OFFS_00A1
|
005D1570   80B8A100000000         cmp     byte ptr [eax+$00A1], $00
005D1577   0F842EFEFFFF           jz      005D13AB
005D157D   B301                   mov     bl, $01
005D157F   33C0                   xor     eax, eax
005D1581   5A                     pop     edx
005D1582   59                     pop     ecx
005D1583   59                     pop     ecx
005D1584   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: '‹Ã^[‹å]Ã'
|
005D1587   68A9155D00             push    $005D15A9
005D158C   8D45DC                 lea     eax, [ebp-$24]

|
005D158F   E81043E3FF             call    004058A4
005D1594   8D45E0                 lea     eax, [ebp-$20]
005D1597   BA04000000             mov     edx, $00000004

|
005D159C   E82743E3FF             call    004058C8
005D15A1   C3                     ret


|
005D15A2   E9ED3AE3FF             jmp     00405094
005D15A7   EBE3                   jmp     005D158C

****** END
|
005D15A9   8BC3                   mov     eax, ebx
005D15AB   5E                     pop     esi
005D15AC   5B                     pop     ebx
005D15AD   8BE5                   mov     esp, ebp
005D15AF   5D                     pop     ebp
005D15B0   C3                     ret

*)
end;

procedure TfrmTabChaveAcesso._PROC_005D163A(Sender : TObject);
begin
(*
005D163A   47                     inc     edi
005D163B   001C4B                 add     [ebx+ecx*2], bl
005D163E   40                     inc     eax
005D163F   000C8547005848         add     [$48580047+eax*4], cl
005D1646   40                     inc     eax
005D1647   00744840               add     [eax+ecx*2+$40], dh
005D164B   00905547008C           add     [eax+$8C004755], dl
005D1651   844600                 test    [esi+$00], al
005D1654   845B47                 test    [ebx+$47], bl
005D1657   000C31                 add     [ecx+esi], cl
005D165A   42                     inc     edx
005D165B   006C5747               add     [edi+edx*2+$47], ch
005D165F   00B8574700F4           add     [eax+$F4004757], bh
005D1665   58                     pop     eax
005D1666   47                     inc     edi
005D1667   00E8                   add     al, ch
005D1669   F8                     clc
005D166A   45                     inc     ebp
005D166B   0094C542008462         add     [ebp+eax*8+$62840042], dl
005D1672   47                     inc     edi
005D1673   0070C2                 add     [eax-$3E], dh
005D1676   42                     inc     edx
005D1677   0070AB                 add     [eax-$55], dh
005D167A   47                     inc     edi
005D167B   00E0                   add     al, ah
005D167D   51                     push    ecx
005D167E   47                     inc     edi
005D167F   00B07E4600BC           add     [eax+$BC00467E], dh
005D1685   844600                 test    [esi+$00], al
005D1688   08844600B0EB45         or      [esi+eax*2+$45EBB000], al
005D168F   002C79                 add     [ecx+edi*2], ch
005D1692   46                     inc     esi
005D1693   00B85E4700B8           add     [eax+$B800475E], bh
005D1699   7546                   jnz     005D16E1
005D169B   00F0                   add     al, dh
005D169D   EA4500F4EA             jmp     $EAF40045
005D16A2   45                     inc     ebp
005D16A3   00AC5F47006C24         add     [edi+ebx*2+$246C0047], ch
005D16AA   46                     inc     esi
005D16AB   003CA8                 add     [eax+ebp*4], bh
005D16AE   47                     inc     edi
005D16AF   00CC                   add     ah, cl
005D16B1   F8                     clc
005D16B2   45                     inc     ebp
005D16B3   002CED450058FA         add     [$FA580045+ebp*8], ch
005D16BA   45                     inc     ebp
005D16BB   00C8                   add     al, cl
005D16BD   61                     popa
005D16BE   47                     inc     edi
005D16BF   008460470094FB         add     [eax+$FB940047], al
005D16C6   45                     inc     ebp
005D16C7   00C4                   add     ah, al
005D16C9   624700                 bound   eax, qword ptr [edi+$00]
005D16CC   F0                     lock
005D16CD   2446                   and     al, $46
005D16CF   000C76                 add     [esi+esi*2], cl
005D16D2   46                     inc     esi
005D16D3   00CC                   add     ah, cl
005D16D5   7646                   jbe     005D171D
005D16D7   00C0                   add     al, al
005D16D9   7146                   jno     005D1721
005D16DB   00B0764600C8           add     [eax+$C8004676], dh
005D16E1   4F                     dec     edi
005D16E2   47                     inc     edi
005D16E3   0008                   add     [eax], cl
005D16E5   6A47                   push    $47
005D16E7   00A042460034           add     [eax+$34004642], ah
005D16ED   7D47                   jnl     005D1736
005D16EF   004882                 add     [eax-$7E], cl
005D16F2   47                     inc     edi
005D16F3   00748047               add     [eax+eax*4+$47], dh
005D16F7   0038                   add     [eax], bh
005D16F9   43                     inc     ebx
005D16FA   46                     inc     esi
005D16FB   005C4346               add     [ebx+eax*2+$46], bl
005D16FF   00C4                   add     ah, al
005D1701   834700C8               add     dword ptr [edi+$00], -$38
005D1705   844700                 test    [edi+$00], al
005D1708   94                     xchg    eax, esp
005D1709   41                     inc     ecx
005D170A   46                     inc     esi
005D170B   00A08C4600F8           add     [eax+$F800468C], ah
005D1711   7746                   jnbe    005D1759
005D1713   0000                   add     [eax], al

005D1715   8C4700                 mov     word ptr [edi+$00], es
005D1718   148C                   adc     al, $8C
005D171A   46                     inc     esi
005D171B   006874                 add     [eax+$74], ch
005D171E   46                     inc     esi
005D171F   00648D46               add     [ebp+ecx*4+$46], ah
005D1723   0088A34700A8           add     [eax+$A80047A3], cl
005D1729   49                     dec     ecx
005D172A   47                     inc     edi
005D172B   00584C                 add     [eax+$4C], bl
005D172E   47                     inc     edi
005D172F   004093                 add     [eax-$6D], al
005D1732   47                     inc     edi
005D1733   00905647000C           add     [eax+$C004756], dl
005D1739   57                     push    edi
005D173A   47                     inc     edi
005D173B   00D4                   add     ah, dl
005D173D   A7                     cmpsd
005D173E   47                     inc     edi
005D173F   00A45347006CA2         add     [ebx+edx*2+$A26C0047], ah
005D1746   47                     inc     edi
005D1747   009C86470060A4         add     [esi+eax*4+$A4600047], bl
005D174E   47                     inc     edi
005D174F   00C4                   add     ah, al
005D1751   61                     popa
005D1752   47                     inc     edi
005D1753   00AC175D00B891         add     [edi+edx+$91B8005D], ch
005D175A   5C                     pop     esp
005D175B   00A4915C001154         add     [ecx+edx*4+$5411005C], ah
005D1762   66726D                 jb      005D17D2
005D1765   54                     push    esp
005D1766   61                     popa
005D1767   624361                 bound   eax, qword ptr [ebx+$61]
005D176A   7465                   jz      005D17D1
005D176C   676F                   outsd
005D176E   7269                   jb      005D17D9
005D1770   61                     popa
005D1771   738B                   jnb     005D16FE
005D1773   C078175D               sar     byte ptr [eax+$17], $5D
005D1777   0007                   add     [edi], al
005D1779   11546672               adc     [esi+$72], edx
005D177D   6D                     insd
005D177E   54                     push    esp
005D177F   61                     popa
005D1780   624361                 bound   eax, qword ptr [ebx+$61]
005D1783   7465                   jz      005D17EA
005D1785   676F                   outsd
005D1787   7269                   jb      005D17F2
005D1789   61                     popa
005D178A   7350                   jnb     005D17DC
005D178C   16                     push    ss
005D178D   5D                     pop     ebp
005D178E   005C905C               add     [eax+edx*4+$5C], bl
005D1792   006F00                 add     [edi+$00], ch
005D1795   117546                 adc     [ebp+$46], esi
005D1798   726D                   jb      005D1807
005D179A   54                     push    esp
005D179B   61                     popa
005D179C   624361                 bound   eax, qword ptr [ebx+$61]
005D179F   7465                   jz      005D1806
005D17A1   676F                   outsd
005D17A3   7269                   jb      005D180E
005D17A5   61                     popa
005D17A6   7300                   jnb     005D17A8
005D17A8   008D4000558B           add     [ebp+$8B550040], cl
005D17AE   EC                     in      al, dx
005D17AF   6A00                   push    $00
005D17B1   6A00                   push    $00
005D17B3   53                     push    ebx
005D17B4   56                     push    esi
005D17B5   57                     push    edi
005D17B6   8BD8                   mov     ebx, eax
005D17B8   33C0                   xor     eax, eax
005D17BA   55                     push    ebp

* Possible String Reference to: 'é´7ãÿëë‹Ã_^[YY]Ã'
|
005D17BB   68DB185D00             push    $005D18DB

***** TRY
|
005D17C0   64FF30                 push    dword ptr fs:[eax]
005D17C3   648920                 mov     fs:[eax], esp
005D17C6   8D8378030000           lea     eax, [ebx+$0378]

* Possible String Reference to: 'Versão 8.0'
|
005D17CC   BAF4185D00             mov     edx, $005D18F4

|
005D17D1   E82241E3FF             call    004058F8
005D17D6   8D83B4030000           lea     eax, [ebx+$03B4]

* Possible String Reference to: 'categorias'
|
005D17DC   BA08195D00             mov     edx, $005D1908

|
005D17E1   E81241E3FF             call    004058F8
005D17E6   8D83B8030000           lea     eax, [ebx+$03B8]

* Possible String Reference to: 'Categorias'
|
005D17EC   BA1C195D00             mov     edx, $005D191C

|
005D17F1   E80241E3FF             call    004058F8
005D17F6   8BC3                   mov     eax, ebx

* Reference to : TfrmBaseClientTabela._PROC_005C9154()
|
005D17F8   E85779FFFF             call    005C9154
005D17FD   8B83A8030000           mov     eax, [ebx+$03A8]
005D1803   8B802C030000           mov     eax, [eax+$032C]

|
005D1809   E84A20E5FF             call    00423858
005D180E   8BF8                   mov     edi, eax
005D1810   4F                     dec     edi
005D1811   85FF                   test    edi, edi
005D1813   0F8CA5000000           jl      005D18BE
005D1819   47                     inc     edi
005D181A   33F6                   xor     esi, esi
005D181C   8B83A8030000           mov     eax, [ebx+$03A8]
005D1822   8B802C030000           mov     eax, [eax+$032C]
005D1828   8BD6                   mov     edx, esi

* Reference to : TDBGridInplaceEdit._PROC_005C2D18()
|
005D182A   E8E914FFFF             call    005C2D18
005D182F   8B401C                 mov     eax, [eax+$1C]
005D1832   8D55FC                 lea     edx, [ebp-$04]

* Reference to : TDBGridInplaceEdit._PROC_005C1838()
|
005D1835   E8FEFFFEFF             call    005C1838
005D183A   8B45FC                 mov     eax, [ebp-$04]

* Possible String Reference to: 'ct_codigo'
|
005D183D   BA30195D00             mov     edx, $005D1930

|
005D1842   E86D44E3FF             call    00405CB4
005D1847   7520                   jnz     005D1869
005D1849   8B83A8030000           mov     eax, [ebx+$03A8]
005D184F   8B802C030000           mov     eax, [eax+$032C]
005D1855   8BD6                   mov     edx, esi

* Reference to : TDBGridInplaceEdit._PROC_005C2D18()
|
005D1857   E8BC14FFFF             call    005C2D18
005D185C   8B401C                 mov     eax, [eax+$1C]

* Possible String Reference to: 'Código'
|
005D185F   BA44195D00             mov     edx, $005D1944
005D1864   8B08                   mov     ecx, [eax]
005D1866   FF510C                 call    dword ptr [ecx+$0C]
005D1869   8B83A8030000           mov     eax, [ebx+$03A8]
005D186F   8B802C030000           mov     eax, [eax+$032C]
005D1875   8BD6                   mov     edx, esi

* Reference to : TDBGridInplaceEdit._PROC_005C2D18()
|
005D1877   E89C14FFFF             call    005C2D18
005D187C   8B401C                 mov     eax, [eax+$1C]
005D187F   8D55F8                 lea     edx, [ebp-$08]

* Reference to : TDBGridInplaceEdit._PROC_005C1838()
|
005D1882   E8B1FFFEFF             call    005C1838
005D1887   8B45F8                 mov     eax, [ebp-$08]

* Possible String Reference to: 'ct_descricao'
|
005D188A   BA54195D00             mov     edx, $005D1954

|
005D188F   E82044E3FF             call    00405CB4
005D1894   7520                   jnz     005D18B6
005D1896   8B83A8030000           mov     eax, [ebx+$03A8]
005D189C   8B802C030000           mov     eax, [eax+$032C]
005D18A2   8BD6                   mov     edx, esi

* Reference to : TDBGridInplaceEdit._PROC_005C2D18()
|
005D18A4   E86F14FFFF             call    005C2D18
005D18A9   8B401C                 mov     eax, [eax+$1C]

* Possible String Reference to: 'Descrição'
|
005D18AC   BA6C195D00             mov     edx, $005D196C
005D18B1   8B08                   mov     ecx, [eax]
005D18B3   FF510C                 call    dword ptr [ecx+$0C]
005D18B6   46                     inc     esi
005D18B7   4F                     dec     edi
005D18B8   0F855EFFFFFF           jnz     005D181C
005D18BE   B301                   mov     bl, $01
005D18C0   33C0                   xor     eax, eax
005D18C2   5A                     pop     edx
005D18C3   59                     pop     ecx
005D18C4   59                     pop     ecx
005D18C5   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: '‹Ã_^[YY]Ã'
|
005D18C8   68E2185D00             push    $005D18E2
005D18CD   8D45F8                 lea     eax, [ebp-$08]
005D18D0   BA02000000             mov     edx, $00000002

|
005D18D5   E8EE3FE3FF             call    004058C8
005D18DA   C3                     ret

*)
end;

end.