unit uFrmRelatorioMedicao;

interface

uses
  Windows, Messages, SysUtils, Classes, Graphics,
  Controls, Forms, Dialogs, StdCtrls
type
  TfrmRelatorioMedicao=class(TForm)
    GroupBox1: TGroupBox;
    LGrupo: TLabel;
    cmbReferencia: TComboBox;
    sbtnImprimir: TSpeedButton;
    qryReferencia: TQuery;
    procedure sbtnImprimirClick(Sender : TObject);
    procedure cmbReferenciaDropDown(Sender : TObject);
    procedure _PROC_005DF717(Sender : TObject);
  private
    { Private declarations }
  public
    { Public declarations }
  end ;

var
  frmRelatorioMedicao: TfrmRelatorioMedicao;

{This file is generated by DeDe Ver 3.50.04 Copyright (c) 1999-2002 DaFixer}

implementation

{$R *.DFM}

procedure TfrmRelatorioMedicao.sbtnImprimirClick(Sender : TObject);
begin
(*
005DF600   55                     push    ebp
005DF601   8BEC                   mov     ebp, esp
005DF603   33C9                   xor     ecx, ecx
005DF605   51                     push    ecx
005DF606   51                     push    ecx
005DF607   51                     push    ecx
005DF608   51                     push    ecx
005DF609   51                     push    ecx
005DF60A   51                     push    ecx
005DF60B   51                     push    ecx
005DF60C   51                     push    ecx
005DF60D   53                     push    ebx
005DF60E   56                     push    esi
005DF60F   8BD8                   mov     ebx, eax
005DF611   33C0                   xor     eax, eax
005DF613   55                     push    ebp

* Possible String Reference to: 'é…Yâÿëã^[‹å]Ã'
|
005DF614   680AF75D00             push    $005DF70A

***** TRY
|
005DF619   64FF30                 push    dword ptr fs:[eax]
005DF61C   648920                 mov     fs:[eax], esp
005DF61F   8D55F0                 lea     edx, [ebp-$10]

* Reference to control TfrmRelatorioMedicao.cmbReferencia : TComboBox
|
005DF622   8B8388030000           mov     eax, [ebx+$0388]

|
005DF628   E8D304E8FF             call    0045FB00
005DF62D   8B45F0                 mov     eax, [ebp-$10]
005DF630   8D55F4                 lea     edx, [ebp-$0C]

|
005DF633   E81CB3E2FF             call    0040A954
005DF638   837DF400               cmp     dword ptr [ebp-$0C], +$00
005DF63C   7528                   jnz     005DF666
005DF63E   6A00                   push    $00
005DF640   0FB70D18F75D00         movzx   ecx, word ptr [$005DF718]
005DF647   B202                   mov     dl, $02

* Possible String Reference to: 'Selecionar a referência.'
|
005DF649   B824F75D00             mov     eax, $005DF724

|
005DF64E   E85515E7FF             call    00450BA8

* Reference to control TfrmRelatorioMedicao.cmbReferencia : TComboBox
|
005DF653   8B8388030000           mov     eax, [ebx+$0388]
005DF659   8B10                   mov     edx, [eax]

* Possible reference to virtual method TComboBox.OFFS_00D4
|
005DF65B   FF92D4000000           call    dword ptr [edx+$00D4]
005DF661   E981000000             jmp     005DF6E7
005DF666   8D45EC                 lea     eax, [ebp-$14]
005DF669   50                     push    eax
005DF66A   8D55E8                 lea     edx, [ebp-$18]

* Reference to control TfrmRelatorioMedicao.cmbReferencia : TComboBox
|
005DF66D   8B8388030000           mov     eax, [ebx+$0388]

|
005DF673   E88804E8FF             call    0045FB00
005DF678   8B45E8                 mov     eax, [ebp-$18]
005DF67B   B904000000             mov     ecx, $00000004
005DF680   BA04000000             mov     edx, $00000004

|
005DF685   E83E67E2FF             call    00405DC8
005DF68A   8B45EC                 mov     eax, [ebp-$14]
005DF68D   33D2                   xor     edx, edx

|
005DF68F   E8ECBBE2FF             call    0040B280
005DF694   8BF0                   mov     esi, eax
005DF696   8D45E4                 lea     eax, [ebp-$1C]
005DF699   50                     push    eax
005DF69A   8D55E0                 lea     edx, [ebp-$20]

* Reference to control TfrmRelatorioMedicao.cmbReferencia : TComboBox
|
005DF69D   8B8388030000           mov     eax, [ebx+$0388]

|
005DF6A3   E85804E8FF             call    0045FB00
005DF6A8   8B45E0                 mov     eax, [ebp-$20]
005DF6AB   B902000000             mov     ecx, $00000002
005DF6B0   BA01000000             mov     edx, $00000001

|
005DF6B5   E80E67E2FF             call    00405DC8
005DF6BA   8B45E4                 mov     eax, [ebp-$1C]
005DF6BD   33D2                   xor     edx, edx

|
005DF6BF   E8BCBBE2FF             call    0040B280
005DF6C4   66B90100               mov     cx, $0001
005DF6C8   8BD0                   mov     edx, eax
005DF6CA   8BC6                   mov     eax, esi

|
005DF6CC   E88FE9E2FF             call    0040E060
005DF6D1   DD5DF8                 fstp    qword ptr [ebp-$08]
005DF6D4   9B                     wait
005DF6D5   FF75FC                 push    dword ptr [ebp-$04]
005DF6D8   FF75F8                 push    dword ptr [ebp-$08]
005DF6DB   A1C8FC6300             mov     eax, dword ptr [$0063FCC8]
005DF6E0   8B00                   mov     eax, [eax]

|
005DF6E2   E8FDA5F9FF             call    00579CE4
005DF6E7   33C0                   xor     eax, eax
005DF6E9   5A                     pop     edx
005DF6EA   59                     pop     ecx
005DF6EB   59                     pop     ecx
005DF6EC   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: '^[‹å]Ã'
|
005DF6EF   6811F75D00             push    $005DF711
005DF6F4   8D45E0                 lea     eax, [ebp-$20]
005DF6F7   BA05000000             mov     edx, $00000005

|
005DF6FC   E8C761E2FF             call    004058C8
005DF701   8D45F4                 lea     eax, [ebp-$0C]

|
005DF704   E89B61E2FF             call    004058A4
005DF709   C3                     ret


|
005DF70A   E98559E2FF             jmp     00405094
005DF70F   EBE3                   jmp     005DF6F4

****** END
|
005DF711   5E                     pop     esi
005DF712   5B                     pop     ebx
005DF713   8BE5                   mov     esp, ebp
005DF715   5D                     pop     ebp
005DF716   C3                     ret

*)
end;

procedure TfrmRelatorioMedicao.cmbReferenciaDropDown(Sender : TObject);
begin
(*
005DF4AC   55                     push    ebp
005DF4AD   8BEC                   mov     ebp, esp
005DF4AF   83C4F0                 add     esp, -$10
005DF4B2   53                     push    ebx
005DF4B3   56                     push    esi
005DF4B4   33C9                   xor     ecx, ecx
005DF4B6   894DFC                 mov     [ebp-$04], ecx
005DF4B9   8BD8                   mov     ebx, eax
005DF4BB   33C0                   xor     eax, eax
005DF4BD   55                     push    ebp

* Possible String Reference to: 'é#[âÿëð^[‹å]Ã'
|
005DF4BE   686CF55D00             push    $005DF56C

***** TRY
|
005DF4C3   64FF30                 push    dword ptr fs:[eax]
005DF4C6   648920                 mov     fs:[eax], esp

* Reference to control TfrmRelatorioMedicao.cmbReferencia : TComboBox
|
005DF4C9   8B8388030000           mov     eax, [ebx+$0388]
005DF4CF   8B10                   mov     edx, [eax]

* Possible reference to virtual method TComboBox.OFFS_00E8
|
005DF4D1   FF92E8000000           call    dword ptr [edx+$00E8]

* Reference to control TfrmRelatorioMedicao.cmbReferencia : TComboBox
|
005DF4D7   8B8388030000           mov     eax, [ebx+$0388]

* Reference to field TComboBox.OFFS_0284
|
005DF4DD   8B8084020000           mov     eax, [eax+$0284]
005DF4E3   8B10                   mov     edx, [eax]
005DF4E5   FF5244                 call    dword ptr [edx+$44]

* Reference to control TfrmRelatorioMedicao.qryReferencia : TQuery
|
005DF4E8   8B8390030000           mov     eax, [ebx+$0390]

|
005DF4EE   E81DF0EBFF             call    0049E510

* Reference to control TfrmRelatorioMedicao.qryReferencia : TQuery
|
005DF4F3   8B8390030000           mov     eax, [ebx+$0390]

|
005DF4F9   E8FEEFEBFF             call    0049E4FC
005DF4FE   EB47                   jmp     005DF547
005DF500   BA80F55D00             mov     edx, $005DF580
005DF505   8BC6                   mov     eax, esi

|
005DF507   E82C03ECFF             call    0049F838
005DF50C   8B10                   mov     edx, [eax]
005DF50E   FF5250                 call    dword ptr [edx+$50]
005DF511   DD5DF0                 fstp    qword ptr [ebp-$10]
005DF514   9B                     wait
005DF515   FF75F4                 push    dword ptr [ebp-$0C]
005DF518   FF75F0                 push    dword ptr [ebp-$10]
005DF51B   8D45FC                 lea     eax, [ebp-$04]

* Possible String Reference to: 'MM/yyyy'
|
005DF51E   BAA0F55D00             mov     edx, $005DF5A0

|
005DF523   E85CF9E2FF             call    0040EE84

* Reference to control TfrmRelatorioMedicao.cmbReferencia : TComboBox
|
005DF528   8B8388030000           mov     eax, [ebx+$0388]

* Reference to field TComboBox.OFFS_0284
|
005DF52E   8B8084020000           mov     eax, [eax+$0284]
005DF534   8B55FC                 mov     edx, [ebp-$04]
005DF537   8B08                   mov     ecx, [eax]
005DF539   FF5138                 call    dword ptr [ecx+$38]

* Reference to control TfrmRelatorioMedicao.qryReferencia : TQuery
|
005DF53C   8B8390030000           mov     eax, [ebx+$0390]

|
005DF542   E8D91AECFF             call    004A1020

* Reference to control TfrmRelatorioMedicao.qryReferencia : TQuery
|
005DF547   8BB390030000           mov     esi, [ebx+$0390]

* Reference to field TQuery.OFFS_00A1
|
005DF54D   80BEA100000000         cmp     byte ptr [esi+$00A1], $00
005DF554   74AA                   jz      005DF500
005DF556   33C0                   xor     eax, eax
005DF558   5A                     pop     edx
005DF559   59                     pop     ecx
005DF55A   59                     pop     ecx
005DF55B   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: '^[‹å]Ã'
|
005DF55E   6873F55D00             push    $005DF573
005DF563   8D45FC                 lea     eax, [ebp-$04]

|
005DF566   E83963E2FF             call    004058A4
005DF56B   C3                     ret


|
005DF56C   E9235BE2FF             jmp     00405094
005DF571   EBF0                   jmp     005DF563

****** END
|
005DF573   5E                     pop     esi
005DF574   5B                     pop     ebx
005DF575   8BE5                   mov     esp, ebp
005DF577   5D                     pop     ebp
005DF578   C3                     ret

*)
end;

procedure TfrmRelatorioMedicao._PROC_005DF717(Sender : TObject);
begin
(*
005DF717   000400                 add     [eax+eax], al
005DF71A   0000                   add     [eax], al

*)
end;

end.