unit uSelecionarPasta;

interface

uses
  Windows, Messages, SysUtils, Classes, Graphics,
  Controls, Forms, Dialogs, StdCtrls
type
  TSelecionarPasta=class(TForm)
    DirectoryListBox1: TDirectoryListBox;
    DriveComboBox1: TDriveComboBox;
    Label1: TLabel;
    BitBtOk: TBitBtn;
    BitBtn2: TBitBtn;
    Label2: TLabel;
    Label3: TLabel;
    ESelecionada: TEdit;
    procedure DirectoryListBox1Change(Sender : TObject);
    procedure BitBtOkClick(Sender : TObject);
    procedure DriveComboBox1Change(Sender : TObject);
    procedure _PROC_0046A7D8(Sender : TObject);
    procedure _PROC_0046A858(Sender : TObject);
  private
    { Private declarations }
  public
    { Public declarations }
  end ;

var
  SelecionarPasta: TSelecionarPasta;

{This file is generated by DeDe Ver 3.50.04 Copyright (c) 1999-2002 DaFixer}

implementation

{$R *.DFM}

procedure TSelecionarPasta.DirectoryListBox1Change(Sender : TObject);
begin
(*
0046A7FC   53                     push    ebx
0046A7FD   8BD8                   mov     ebx, eax

* Reference to control TSelecionarPasta.DirectoryListBox1 : TDirectoryListBox
|
0046A7FF   8B8360030000           mov     eax, [ebx+$0360]

* Reference to field TDirectoryListBox.OFFS_02E4
|
0046A805   8B90E4020000           mov     edx, [eax+$02E4]

* Reference to control TSelecionarPasta.ESelecionada : TEdit
|
0046A80B   8B837C030000           mov     eax, [ebx+$037C]

|
0046A811   E8F68EFDFF             call    0044370C

* Reference to field TSelecionarPasta.OFFS_0380
|
0046A816   8D8380030000           lea     eax, [ebx+$0380]

* Reference to control TSelecionarPasta.DirectoryListBox1 : TDirectoryListBox
|
0046A81C   8B9360030000           mov     edx, [ebx+$0360]

* Reference to field TDirectoryListBox.OFFS_02E4
|
0046A822   8B92E4020000           mov     edx, [edx+$02E4]

|
0046A828   E8CBA6F9FF             call    00404EF8
0046A82D   5B                     pop     ebx
0046A82E   C3                     ret

*)
end;

procedure TSelecionarPasta.BitBtOkClick(Sender : TObject);
begin
(*
0046A7AC   53                     push    ebx
0046A7AD   8BD8                   mov     ebx, eax

* Reference to control TSelecionarPasta.DirectoryListBox1 : TDirectoryListBox
|
0046A7AF   8B8360030000           mov     eax, [ebx+$0360]
0046A7B5   8B10                   mov     edx, [eax]

* Possible reference to virtual method TDirectoryListBox.OFFS_00DC
|
0046A7B7   FF92DC000000           call    dword ptr [edx+$00DC]
0046A7BD   85C0                   test    eax, eax
0046A7BF   7D15                   jnl     0046A7D6
0046A7C1   6A00                   push    $00
0046A7C3   0FB70DD8A74600         movzx   ecx, word ptr [$0046A7D8]
0046A7CA   B201                   mov     dl, $01

* Possible String Reference to: 'Selecionar uma pasta.'
|
0046A7CC   B8E4A74600             mov     eax, $0046A7E4

|
0046A7D1   E89AABFCFF             call    00435370
0046A7D6   5B                     pop     ebx
0046A7D7   C3                     ret

*)
end;

procedure TSelecionarPasta.DriveComboBox1Change(Sender : TObject);
begin
(*
0046A830   53                     push    ebx
0046A831   8BD8                   mov     ebx, eax

* Reference to control TSelecionarPasta.DriveComboBox1 : TDriveComboBox
|
0046A833   8B8364030000           mov     eax, [ebx+$0364]
0046A839   0FB690E4020000         movzx   edx, byte ptr [eax+$02E4]

* Reference to control TSelecionarPasta.DirectoryListBox1 : TDirectoryListBox
|
0046A840   8B8360030000           mov     eax, [ebx+$0360]

|
0046A846   E859EBFFFF             call    004693A4
0046A84B   8BD3                   mov     edx, ebx
0046A84D   8BC3                   mov     eax, ebx

* Reference to : TSelecionarPasta.DirectoryListBox1Change()
|
0046A84F   E8A8FFFFFF             call    0046A7FC
0046A854   5B                     pop     ebx
0046A855   C3                     ret

*)
end;

procedure TSelecionarPasta._PROC_0046A7D8(Sender : TObject);
begin
(*
0046A7D8   0400                   add     al, +$00
0046A7DA   0000                   add     [eax], al

*)
end;

procedure TSelecionarPasta._PROC_0046A858(Sender : TObject);
begin
(*
0046A858   A4                     movsb
0046A859   A846                   test    al, $46
0046A85B   0000                   add     [eax], al

*)
end;

end.