<script type="text/javascript"> 
		function end_upload2(data){
			alert('Foto enviada!');
		}
		window.onload=function(){
			var pathFoto = document.getElementById('pathFoto');
			pathFoto.onchange = function(){
				var ext = pathFoto.value.split('.')[1];
				document.getElementById('return_element4').innerHTML = "<b>"+pathFoto.value+"</b>";
				if(ext == 'jpg' || ext == 'png' || ext == 'gif'){
					micoxUpload2(this.form,15,'Carregando',end_upload2)
				}
				else{
					alert('Foto não reconhecida.');
				}
			}
		}
</script> 
<fieldset> 
	<legend>Selecione uma foto</legend>
	<form action='<?=$this->baseUrl."/".$this->modulo?>/foto/avatar'> 
	  <input type="file" name="pathFoto" id='pathFoto' /> 
	  <?php //echo $this->render('foto/_form.phtml'); ?> 
	</form> 
	<div id='return_element4'></div> 
</fieldset> 
